package app.tsuyu.mobile;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.os.*;
import android.view.*;
import android.view.inputmethod.*;
import android.widget.*;
import androidx.recyclerview.widget.*;
import com.google.firebase.database.*;
import org.json.*;
import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root; RecyclerView dialogs,search; EditText query; DialogAdapter dialogAdapter; UserAdapter userAdapter; ValueEventListener chatListener, searchListener; final ArrayList<Row> rows=new ArrayList<>(); final ArrayList<JSONObject> users=new ArrayList<>(); boolean visible;
    @Override protected void onCreate(Bundle b){super.onCreate(b);Notify.init(this);TsuyuApp.app().crypto.active();if(TsuyuApp.app().auth.getCurrentUser()==null)authUi();else homeUi();}
    @Override protected void onResume(){super.onResume();visible=true;Rt.online();if(TsuyuApp.app().auth.getCurrentUser()!=null)startRealtime();}
    @Override protected void onPause(){super.onPause();visible=false;}
    @Override protected void onDestroy(){super.onDestroy();detach();}

    private void authUi(){root=Tui.root(this);TextView logo=Tui.text(this,"Tsuyu",32,true);logo.setTextColor(Tui.ACCENT);root.addView(logo);root.addView(Tui.text(this,"Чёрный быстрый мессенджер с E2EE и Firebase RTDB",14,false));EditText email=Tui.input(this,"Email");EditText pass=Tui.input(this,"Пароль");pass.setInputType(0x00000081);EditText user=Tui.input(this,"@username");EditText name=Tui.input(this,"Имя");EditText bio=Tui.input(this,"Описание");root.addView(email);root.addView(pass);root.addView(user);root.addView(name);root.addView(bio);LinearLayout row=Tui.row(this);Button login=Tui.button(this,"Войти");Button reg=Tui.button(this,"Создать");row.addView(login,new LinearLayout.LayoutParams(0,dp(52),1));row.addView(reg,new LinearLayout.LayoutParams(0,dp(52),1));root.addView(row);TextView hint=Tui.text(this,"Публичные ключи публикуются автоматически. Приватный ключ остаётся на устройстве.",13,false);root.addView(hint);setContentView(root);login.setOnClickListener(v->{hide(email);Rt.login(email.getText().toString(),pass.getText().toString(),new Rt.Done(){public void ok(){homeUi();}public void fail(String e){Tui.toast(MainActivity.this,e);}});});reg.setOnClickListener(v->{hide(email);Rt.register(email.getText().toString(),pass.getText().toString(),user.getText().toString(),name.getText().toString(),bio.getText().toString(),"",new Rt.Done(){public void ok(){homeUi();}public void fail(String e){Tui.toast(MainActivity.this,e);}});});}
    private void homeUi(){askNotify();root=Tui.root(this);LinearLayout top=Tui.row(this);TextView title=Tui.text(this,"Tsuyu",28,true);title.setTextColor(Tui.ACCENT);Button set=Tui.iconButton(this,R.drawable.ic_settings);top.addView(title,new LinearLayout.LayoutParams(0,dp(56),1));top.addView(set,new LinearLayout.LayoutParams(dp(52),dp(52)));root.addView(top);query=Tui.input(this,"Поиск @username");root.addView(query);search=new RecyclerView(this);search.setLayoutManager(new LinearLayoutManager(this));userAdapter=new UserAdapter();search.setAdapter(userAdapter);search.setVisibility(View.GONE);root.addView(search,new LinearLayout.LayoutParams(-1,dp(170)));TextView d=Tui.text(this,"Диалоги",16,true);root.addView(d);dialogs=new RecyclerView(this);dialogs.setLayoutManager(new LinearLayoutManager(this));dialogAdapter=new DialogAdapter();dialogs.setAdapter(dialogAdapter);root.addView(dialogs,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);set.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));query.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){runSearch(s.toString());}public void afterTextChanged(android.text.Editable e){}});listenDialogs();startRealtime();}
    private void askNotify(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},91);}
    private void startRealtime(){try{Intent s=new Intent(this,TsuyuRealtimeService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(s);else startService(s);}catch(Exception ignored){}}
    private void listenDialogs(){detach();String id=Rt.uid();DatabaseReference ref=Rt.db().child("userChats").child(id);chatListener=new ValueEventListener(){@Override public void onDataChange(DataSnapshot root){rows.clear();for(DataSnapshot s:root.getChildren()){String peer=s.getKey();String chat=s.child("chatId").getValue(String.class);String last=s.child("lastId").getValue(String.class);if(peer!=null&&chat!=null){Row r=new Row();r.peer=peer;r.chat=chat;r.last=last;r.name="@"+peer;r.preview="...";rows.add(r);loadRow(r);}}Collections.sort(rows,(a,b)->Long.compare(b.time,a.time));dialogAdapter.notifyDataSetChanged();}@Override public void onCancelled(DatabaseError e){Tui.toast(MainActivity.this,e.getMessage());}};ref.addValueEventListener(chatListener);}
    private void loadRow(Row r){Rt.getProfile(r.peer,new Rt.Got(){public void ok(JSONObject p){r.name=p.optString("name",p.optString("username",r.peer));r.username=p.optString("username","");r.avatar=p.optString("avatar","");TsuyuApp.app().index.profile(p);dialogAdapter.notifyDataSetChanged();listenPresence(r);listenTyping(r);}public void fail(String e){}});if(r.last!=null)Rt.db().child("chats").child(r.chat).child("messages").child(r.last).addListenerForSingleValueEvent(new ValueEventListener(){public void onDataChange(DataSnapshot s){try{JSONObject p=Rt.decrypt(r.chat,r.last,s);r.preview=Rt.preview(p);r.time=longv(s.child("ts"),longv(s.child("clientAt"),0));JSONObject cached=new JSONObject().put("id",r.last).put("chatId",r.chat).put("sender",s.child("sender").getValue(String.class)).put("receiver",s.child("receiver").getValue(String.class)).put("text",p.optString("text","")).put("type",p.optString("type","text")).put("decryptedPreview",r.preview).put("ts",r.time).put("payload",p.toString());TsuyuApp.app().index.message(cached);Collections.sort(rows,(a,b)->Long.compare(b.time,a.time));dialogAdapter.notifyDataSetChanged();}catch(Exception e){r.preview="Не удалось расшифровать";dialogAdapter.notifyDataSetChanged();}}public void onCancelled(DatabaseError e){}});} 
    private void listenPresence(Row r){Rt.db().child("presence").child(r.peer).addValueEventListener(new ValueEventListener(){public void onDataChange(DataSnapshot s){Boolean on=s.child("online").getValue(Boolean.class);r.online=on!=null&&on;r.lastSeen=longv(s.child("lastSeen"),0);dialogAdapter.notifyDataSetChanged();}public void onCancelled(DatabaseError e){}});} 
    private void listenTyping(Row r){Rt.db().child("typing").child(r.chat).child(r.peer).addValueEventListener(new ValueEventListener(){public void onDataChange(DataSnapshot s){long at=longv(s.child("at"),0);r.typing=System.currentTimeMillis()-at<3500;s.getRef().getParent();dialogAdapter.notifyDataSetChanged();}public void onCancelled(DatabaseError e){}});} 
    private void runSearch(String q){String c=Rt.cleanUser(q);if(searchListener!=null){Rt.db().child("profiles").removeEventListener(searchListener);searchListener=null;}if(c.length()<1){users.clear();userAdapter.notifyDataSetChanged();search.setVisibility(View.GONE);return;}search.setVisibility(View.VISIBLE);Query query=Rt.db().child("profiles").orderByChild("usernameLower").startAt(c).endAt(c+"\uf8ff").limitToFirst(20);searchListener=new ValueEventListener(){public void onDataChange(DataSnapshot ds){users.clear();for(DataSnapshot s:ds.getChildren()){if(!s.getKey().equals(Rt.uid()))users.add(Rt.json(s));}userAdapter.notifyDataSetChanged();search.animate().alpha(users.isEmpty()?0.35f:1f).setDuration(160).start();}public void onCancelled(DatabaseError e){}};query.addValueEventListener(searchListener);} 
    private void detach(){String id=Rt.uid();if(chatListener!=null&&!id.isEmpty()){Rt.db().child("userChats").child(id).removeEventListener(chatListener);chatListener=null;}if(searchListener!=null){Rt.db().child("profiles").removeEventListener(searchListener);searchListener=null;}}
    private void open(String peer){startActivity(new Intent(this,ChatActivity.class).putExtra("peerUid",peer));}
    private long longv(DataSnapshot s,long d){Object v=s.getValue();if(v instanceof Number)return ((Number)v).longValue();try{return Long.parseLong(String.valueOf(v));}catch(Exception e){return d;}}
    private int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}private void hide(View v){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);} 
    static class Row{String peer,chat,last,name,username,avatar,preview="",typingText="";boolean online,typing;long time,lastSeen;}
    class DialogAdapter extends RecyclerView.Adapter<DialogAdapter.H>{class H extends RecyclerView.ViewHolder{LinearLayout box;TextView name,sub,time;ImageView av;H(View v){super(v);box=(LinearLayout)v;av=(ImageView)box.getChildAt(0);LinearLayout col=(LinearLayout)box.getChildAt(1);name=(TextView)col.getChildAt(0);sub=(TextView)col.getChildAt(1);time=(TextView)box.getChildAt(2);}}@Override public H onCreateViewHolder(android.view.ViewGroup p,int vt){LinearLayout b=Tui.row(MainActivity.this);b.setPadding(dp(10),dp(8),dp(10),dp(8));ImageView av=new ImageView(MainActivity.this);av.setBackground(Tui.oval(0xff1c1c20));b.addView(av,new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout col=new LinearLayout(MainActivity.this);col.setOrientation(LinearLayout.VERTICAL);col.setPadding(dp(12),0,0,0);col.addView(Tui.text(MainActivity.this,"",16,true));col.addView(Tui.text(MainActivity.this,"",13,false));b.addView(col,new LinearLayout.LayoutParams(0,dp(58),1));b.addView(Tui.text(MainActivity.this,"",12,false),new LinearLayout.LayoutParams(dp(70),dp(58)));return new H(b);}@Override public void onBindViewHolder(H h,int pos){Row r=rows.get(pos);Bitmap bm=Tui.bitmap(r.avatar);if(bm!=null)h.av.setImageBitmap(bm);else h.av.setImageDrawable(Tui.oval(r.online?Tui.ACCENT:0xff24242a));h.name.setText((r.online?"● ":"")+r.name+(r.username.isEmpty()?"":" @"+r.username));h.name.setTextColor(r.online?Tui.ACCENT:Tui.FG);h.sub.setText(r.typing?"печатает...":r.preview);h.time.setText(r.time>0?Tui.time(r.time):"");h.box.setOnClickListener(v->open(r.peer));Tui.press(h.box);}@Override public int getItemCount(){return rows.size();}}
    class UserAdapter extends RecyclerView.Adapter<UserAdapter.H>{class H extends RecyclerView.ViewHolder{LinearLayout b;TextView n,s;ImageView a;H(View v){super(v);b=(LinearLayout)v;a=(ImageView)b.getChildAt(0);LinearLayout c=(LinearLayout)b.getChildAt(1);n=(TextView)c.getChildAt(0);s=(TextView)c.getChildAt(1);}}@Override public H onCreateViewHolder(android.view.ViewGroup p,int vt){LinearLayout b=Tui.row(MainActivity.this);b.setPadding(dp(10),dp(6),dp(10),dp(6));ImageView av=new ImageView(MainActivity.this);b.addView(av,new LinearLayout.LayoutParams(dp(42),dp(42)));LinearLayout c=new LinearLayout(MainActivity.this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(10),0,0,0);c.addView(Tui.text(MainActivity.this,"",15,true));c.addView(Tui.text(MainActivity.this,"",12,false));b.addView(c,new LinearLayout.LayoutParams(0,dp(46),1));return new H(b);}@Override public void onBindViewHolder(H h,int p){JSONObject o=users.get(p);Bitmap bm=Tui.bitmap(o.optString("avatar",""));if(bm!=null)h.a.setImageBitmap(bm);else h.a.setImageDrawable(Tui.oval(0xff24242a));h.n.setText(o.optString("name","Tsuyu"));h.s.setText("@"+o.optString("username","")+" · "+o.optString("bio",""));h.b.setOnClickListener(v->open(o.optString("uid","")));Tui.press(h.b);}@Override public int getItemCount(){return users.size();}}
}
