package app.tsuyu.mobile;

import android.net.Uri;
import com.google.firebase.auth.*;
import com.google.firebase.database.*;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;

public final class Rt {
    public interface Done {void ok();void fail(String e);} 
    public interface Got {void ok(JSONObject o);void fail(String e);} 
    private Rt(){}
    public static String uid(){return TsuyuApp.app().uid();}
    public static String cleanUser(String s){String v=s==null?"":s.trim().toLowerCase(Locale.ROOT);if(v.startsWith("@"))v=v.substring(1);v=v.replaceAll("[^a-z0-9_\\.]","");if(v.length()>24)v=v.substring(0,24);return v;}
    public static String chatId(String a,String b){return a.compareTo(b)<0?a+"_"+b:b+"_"+a;}
    public static DatabaseReference db(){return TsuyuApp.app().db;}

    public static void register(String email,String pass,String username,String name,String bio,String avatar,Done done){String u=cleanUser(username);if(u.length()<3){done.fail("Юз минимум 3 символа");return;}TsuyuApp app=TsuyuApp.app();app.auth.createUserWithEmailAndPassword(email,pass).addOnSuccessListener(r->{String id=app.uid();db().child("usernames").child(u).runTransaction(new Transaction.Handler(){@Override public Transaction.Result doTransaction(MutableData data){Object cur=data.getValue();if(cur==null||String.valueOf(cur).equals(id)){data.setValue(id);return Transaction.success(data);}return Transaction.abort();}@Override public void onComplete(com.google.firebase.database.DatabaseError e,boolean committed,DataSnapshot snap){if(e!=null||!committed){try{FirebaseUser fu=app.auth.getCurrentUser();if(fu!=null)fu.delete();}catch(Exception ignored){}done.fail("Этот @ уже занят");return;}publishProfile(email,u,name,bio,avatar,done);}});}).addOnFailureListener(e->done.fail(e.getMessage()==null?"Не удалось создать аккаунт":e.getMessage()));}
    public static void login(String email,String pass,Done done){TsuyuApp app=TsuyuApp.app();app.auth.signInWithEmailAndPassword(email,pass).addOnSuccessListener(r->{app.crypto.active();db().child("profiles").child(app.uid()).child("publicKey").setValue(app.crypto.publicKey());db().child("profiles").child(app.uid()).child("keyId").setValue(app.crypto.keyId());online();done.ok();}).addOnFailureListener(e->done.fail(e.getMessage()==null?"Не удалось войти":e.getMessage()));}
    public static void publishProfile(String email,String username,String name,String bio,String avatar,Done done){TsuyuApp app=TsuyuApp.app();app.crypto.active();String id=app.uid();HashMap<String,Object> m=new HashMap<>();m.put("uid",id);m.put("username",username);m.put("usernameLower",cleanUser(username));m.put("name",clip(name,80));m.put("bio",clip(bio,280));m.put("avatar",clip(avatar,220000));m.put("publicKey",app.crypto.publicKey());m.put("keyId",app.crypto.keyId());m.put("keyRing",app.crypto.publicRing().toString());m.put("emailHash",sha(email));m.put("updatedAt",ServerValue.TIMESTAMP);HashMap<String,Object> privacy=new HashMap<>();privacy.put("canWrite","all");privacy.put("lastSeen","all");privacy.put("photos","all");privacy.put("about","all");m.put("privacy",privacy);db().child("profiles").child(id).updateChildren(m).addOnSuccessListener(x->{online();done.ok();}).addOnFailureListener(e->done.fail(msg(e)));}
    public static void updateProfile(Map<String,Object> m,Done done){String id=uid();if(id.isEmpty()){done.fail("Нет входа");return;}m.put("updatedAt",ServerValue.TIMESTAMP);db().child("profiles").child(id).updateChildren(m).addOnSuccessListener(x->done.ok()).addOnFailureListener(e->done.fail(msg(e)));}
    public static void changeUsername(String oldName,String newName,Done done){String id=uid();String n=cleanUser(newName);String old=cleanUser(oldName);if(id.isEmpty()){done.fail("Нет входа");return;}if(n.length()<3){done.fail("Юз минимум 3 символа");return;}if(n.equals(old)){HashMap<String,Object> m=new HashMap<>();m.put("username",n);m.put("usernameLower",n);updateProfile(m,done);return;}db().child("usernames").child(n).runTransaction(new Transaction.Handler(){@Override public Transaction.Result doTransaction(MutableData data){Object cur=data.getValue();if(cur==null||String.valueOf(cur).equals(id)){data.setValue(id);return Transaction.success(data);}return Transaction.abort();}@Override public void onComplete(DatabaseError e,boolean committed,DataSnapshot snap){if(e!=null||!committed){done.fail("Этот @ уже занят");return;}HashMap<String,Object> m=new HashMap<>();m.put("username",n);m.put("usernameLower",n);db().child("profiles").child(id).updateChildren(m).addOnSuccessListener(x->{if(!old.isEmpty())db().child("usernames").child(old).removeValue();done.ok();}).addOnFailureListener(er->done.fail(msg(er)));}});}

    public static void online(){String id=uid();if(id.isEmpty())return;DatabaseReference p=db().child("presence").child(id);HashMap<String,Object> on=new HashMap<>();on.put("online",true);on.put("lastSeen",ServerValue.TIMESTAMP);p.updateChildren(on);HashMap<String,Object> off=new HashMap<>();off.put("online",false);off.put("lastSeen",ServerValue.TIMESTAMP);p.onDisconnect().updateChildren(off);} 
    public static void offline(){String id=uid();if(id.isEmpty())return;HashMap<String,Object> off=new HashMap<>();off.put("online",false);off.put("lastSeen",ServerValue.TIMESTAMP);db().child("presence").child(id).updateChildren(off);} 
    public static void typing(String chatId,String text){String id=uid();if(id.isEmpty()||chatId==null||chatId.isEmpty())return;DatabaseReference t=db().child("typing").child(chatId).child(id);HashMap<String,Object> m=new HashMap<>();m.put("at",ServerValue.TIMESTAMP);m.put("status",clip(text,40));t.setValue(m);t.onDisconnect().removeValue();}
    public static void stopTyping(String chatId){String id=uid();if(!id.isEmpty()&&chatId!=null&&!chatId.isEmpty())db().child("typing").child(chatId).child(id).removeValue();}

    public static void sendText(String peer,String text,String reply,Done done){try{JSONObject p=new JSONObject().put("type","text").put("text",text==null?"":text).put("replyTo",reply==null?"":reply);send(peer,p,done);}catch(Exception e){done.fail(e.getMessage());}}
    public static void sendMedia(String peer,String text,ArrayList<MediaTools.Pack> media,String reply,Done done){try{JSONArray arr=new JSONArray();String type="media";for(MediaTools.Pack p:media){arr.put(MediaTools.json(p));type=p.kind;}if(media.size()>1)type="collage";JSONObject payload=new JSONObject().put("type",type).put("text",text==null?"":text).put("media",arr).put("replyTo",reply==null?"":reply);send(peer,payload,done);}catch(Exception e){done.fail(e.getMessage());}}
    public static void send(String peer,JSONObject payload,Done done){String me=uid();if(me.isEmpty()){done.fail("Нет входа");return;}String c=chatId(me,peer);String msg=db().child("chats").child(c).child("messages").push().getKey();if(msg==null){done.fail("Нет ключа сообщения");return;}db().child("profiles").child(peer).addListenerForSingleValueEvent(new ValueEventListener(){@Override public void onDataChange(DataSnapshot s){try{String peerPub=s.child("publicKey").getValue(String.class);if(peerPub==null||peerPub.isEmpty()){done.fail("У пользователя нет публичного ключа");return;}JSONObject enc=TsuyuApp.app().crypto.encrypt(c,msg,peerPub,payload);HashMap<String,Object> row=new HashMap<>();row.put("id",msg);row.put("chatId",c);row.put("sender",me);row.put("receiver",peer);row.put("type",payload.optString("type","text"));row.put("senderPub",enc.optString("senderPub"));row.put("recipientPub",enc.optString("recipientPub"));row.put("keyId",enc.optString("keyId"));row.put("iv",enc.optString("iv"));row.put("cipher",enc.optString("cipher"));row.put("alg",enc.optString("alg"));row.put("clientAt",System.currentTimeMillis());row.put("ts",ServerValue.TIMESTAMP);row.put("edited",false);row.put("deletedForAll",false);HashMap<String,Object> up=new HashMap<>();up.put("/chats/"+c+"/messages/"+msg,row);up.put("/chats/"+c+"/participants/"+me,true);up.put("/chats/"+c+"/participants/"+peer,true);up.put("/userChats/"+me+"/"+peer,chatIndex(c,peer,msg));up.put("/userChats/"+peer+"/"+me,chatIndex(c,me,msg));db().updateChildren(up).addOnSuccessListener(x->{stopTyping(c);done.ok();}).addOnFailureListener(e->done.fail(msg(e)));}catch(Exception e){done.fail(e.getMessage()==null?"Ошибка шифрования":e.getMessage());}}@Override public void onCancelled(DatabaseError e){done.fail(e.getMessage());}});}
    private static HashMap<String,Object> chatIndex(String c,String peer,String last){HashMap<String,Object> m=new HashMap<>();m.put("chatId",c);m.put("peerUid",peer);m.put("lastId",last);m.put("updatedAt",ServerValue.TIMESTAMP);return m;}
    public static JSONObject decrypt(String chat,String id,DataSnapshot row)throws Exception{return TsuyuApp.app().crypto.decrypt(chat,id,new JSONObject((Map)row.getValue()),uid());}
    public static void edit(String chat,String msg,String peer,String newText,JSONObject oldPayload,Done done){try{JSONObject p=new JSONObject(oldPayload.toString());p.put("text",newText);p.put("editedAt",System.currentTimeMillis());String other=peer;String me=uid();db().child("profiles").child(other).addListenerForSingleValueEvent(new ValueEventListener(){@Override public void onDataChange(DataSnapshot s){try{String peerPub=s.child("publicKey").getValue(String.class);JSONObject enc=TsuyuApp.app().crypto.encrypt(chat,msg,peerPub,p);HashMap<String,Object> m=new HashMap<>();m.put("cipher",enc.optString("cipher"));m.put("iv",enc.optString("iv"));m.put("senderPub",enc.optString("senderPub"));m.put("recipientPub",enc.optString("recipientPub"));m.put("edited",true);m.put("editedAt",ServerValue.TIMESTAMP);db().child("chats").child(chat).child("messages").child(msg).updateChildren(m).addOnSuccessListener(x->done.ok()).addOnFailureListener(e->done.fail(msg(e)));}catch(Exception e){done.fail(e.getMessage());}}@Override public void onCancelled(DatabaseError e){done.fail(e.getMessage());}});}catch(Exception e){done.fail(e.getMessage());}}
    public static void deleteForAll(String chat,String msg,Done done){db().child("chats").child(chat).child("messages").child(msg).removeValue().addOnSuccessListener(x->done.ok()).addOnFailureListener(e->done.fail(msg(e)));}
    public static void heart(String chat,String msg,boolean on){react(chat,msg,"heart",on);} 
    public static void react(String chat,String msg,String emoji,boolean on){String id=uid();if(id.isEmpty())return;String key=emoji==null?"heart":emoji.replaceAll("[^a-zA-Z0-9_\\-]","");if(key.isEmpty())key="heart";DatabaseReference r=db().child("chats").child(chat).child("messages").child(msg).child("reactions").child(key).child(id);if(on)r.setValue(ServerValue.TIMESTAMP);else r.removeValue();}
    public static void getProfile(String id,Got got){db().child("profiles").child(id).addListenerForSingleValueEvent(new ValueEventListener(){@Override public void onDataChange(DataSnapshot s){got.ok(json(s));}@Override public void onCancelled(DatabaseError e){got.fail(e.getMessage());}});} 
    public static JSONObject json(DataSnapshot s){JSONObject o=new JSONObject();try{Object v=s.getValue();if(v instanceof Map)o=new JSONObject((Map)v);}catch(Exception ignored){}return o;}
    public static String preview(JSONObject p){String type=p.optString("type","text"),text=p.optString("text","").trim();if(!text.isEmpty())return text;return MediaTools.preview(type,p.optJSONArray("media"));}
    private static String clip(String s,int max){if(s==null)return "";s=s.trim();return s.length()>max?s.substring(0,max):s;}
    private static String sha(String s){try{byte[] d=MessageDigest.getInstance("SHA-256").digest((s==null?"":s.toLowerCase(Locale.ROOT)).getBytes(StandardCharsets.UTF_8));StringBuilder b=new StringBuilder();for(byte x:d)b.append(String.format(Locale.ROOT,"%02x",x&255));return b.toString();}catch(Exception e){return "";}}
    private static String msg(Exception e){return e==null||e.getMessage()==null?"Ошибка RTDB":e.getMessage();}
}
