package app.yoru.mobile;

import android.content.Context;
import android.net.Uri;
import android.text.Html;
import org.jsoup.Jsoup;
import org.jsoup.nodes.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;
import java.time.*;

public final class ApiRepository {
    private static final String CHROME="Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Mobile Safari/537.36";
    public static final LinkedHashMap<String,String> sourceNames=new LinkedHashMap<>();
    private static final String[] REAL_SOURCES={"yummy","anilibria","animevost","animelib","animedia","shikimori"};
    static {sourceNames.put("all","YORU Auto");sourceNames.put("yoru","YORU Source");sourceNames.put("yummy","YORU Max");sourceNames.put("anilibria","AniLiberty");sourceNames.put("animevost","AnimeVost");sourceNames.put("animelib","AniLib");sourceNames.put("animelib4k","AniLib Ultra");sourceNames.put("animedia","AniMedia");sourceNames.put("animetka","Animetka");sourceNames.put("anidub","AniDub");sourceNames.put("shikimori","Shikimori");sourceNames.put("kodik","YORU Prime");}
    public static final String[] VOICE_PREF_VALUES={"","anidub","anilibria","animaunt","animevost","anistar-deep","beyond-studio","dreamcast","animedia","studio-band","jam","shiza","subtitles"};
    public static final String[] VOICE_PREF_NAMES={"Авто","AniDUB","AniLibria.TV","AniMaunt","AnimeVost","AniStar & DEEP","Beyond:Studio","Dream Cast","AniMedia","StudioBand","JAM","SHIZA Project","Субтитры"};
    private static boolean routeLabel(String value){String v=value==null?"":value.toLowerCase(Locale.ROOT).replace('ё','е');return v.contains("yoru")||v.contains("yummy")||v.contains("yani")||v.contains("kodik")||v.contains("aniqit")||v.contains("cdnvideohub")||v.equals("player")||v.equals("iframe")||v.equals("плеер")||v.equals("вариант")||v.equals("оригинал");}
    public static String sourceVoice(String source){String s=sourceId(source);if(s.equals("anilibria"))return "AniLibria.TV";if(s.equals("animevost"))return "AnimeVost";if(s.equals("anidub"))return "AniDUB";if(s.equals("animedia"))return "AniMedia";if(s.equals("animetka"))return "AniLibria.TV";return "";}
    public static String voiceKey(String value){String v=value==null?"":value.toLowerCase(Locale.ROOT).replace('ё','е');v=v.replace("анилибрия","anilibria").replace("анилиберт","aniliberty").replace("анимаунт","animaunt").replace("анимевост","animevost").replace("анимедиа","animedia").replace("субтитры","subtitles").replace("сабы","subtitles");if(v.contains("anilibria")||v.contains("aniliberty")||v.contains("cdnlibs"))return "anilibria";if(v.contains("animaunt")||v.contains("ani maunt"))return "animaunt";if(v.contains("animevost")||v.contains("anime vost"))return "animevost";if(v.contains("anistar")&&v.contains("deep"))return "anistar-deep";if(v.contains("beyond")&&v.contains("studio"))return "beyond-studio";if(v.contains("dream")&&v.contains("cast"))return "dreamcast";if(v.contains("anidub")||v.contains("ani dub"))return "anidub";if(v.contains("animedia")||v.contains("ani media"))return "animedia";if(v.contains("studioband")||v.contains("studio band"))return "studio-band";if(v.matches(".*\bjam\b.*"))return "jam";if(v.contains("shiza"))return "shiza";if(v.contains("subtitles")||v.contains("subtitle")||v.contains("sub ")||v.contains(" subs")||v.contains("суб"))return "subtitles";if(routeLabel(v))return "";String plain=plainName(v);if(plain.isEmpty()||plain.equals("auto")||plain.equals("avto")||plain.equals("ozvuchka")||plain.equals("perevod"))return "";return plain.replaceAll("\\s+","");}
    public static String voiceTitle(String value){String key=voiceKey(value);if(key.equals("anilibria"))return "AniLibria.TV";if(key.equals("animaunt"))return "AniMaunt";if(key.equals("animevost"))return "AnimeVost";if(key.equals("anistar-deep"))return "AniStar & DEEP";if(key.equals("beyond-studio"))return "Beyond:Studio";if(key.equals("dreamcast"))return "Dream Cast";if(key.equals("anidub"))return "AniDUB";if(key.equals("animedia"))return "AniMedia";if(key.equals("studio-band"))return "StudioBand";if(key.equals("jam"))return "JAM";if(key.equals("shiza"))return "SHIZA Project";if(key.equals("subtitles"))return "Субтитры";String label=cleanLabel(value);if(label.isEmpty()||routeLabel(label)||label.equalsIgnoreCase("Озвучка")||label.equalsIgnoreCase("Перевод")||label.equalsIgnoreCase("Дубляж"))return "";label=label.replaceAll("(?i)\\b(player|iframe|hls|dash|mp4|kodik|yummy|yani|aniqit|cdnvideohub|yoru)\\b","").replaceAll("\\s+"," ").trim();return label.isEmpty()?"":label;}
    public static boolean voiceMatches(String wanted,String actual){String w=voiceKey(wanted);if(w.isEmpty())return true;String a=voiceKey(actual);if(w.equals(a))return true;String wt=plainName(wanted),at=plainName(actual);return !wt.isEmpty()&&!at.isEmpty()&&!routeLabel(actual)&&(at.contains(wt)||wt.contains(at));}
    private static final String SH_FIELDS="id malId name russian english kind rating score status episodes episodesAired airedOn{year date} poster{mainUrl originalUrl} genres{id russian name} studios{name}";
    private static final long DAY_MS=24L*60*60*1000;
    private final Context context;
    private final Map<String,Cache> cache=Collections.synchronizedMap(new LinkedHashMap<String,Cache>(32,.75f,true){protected boolean removeEldestEntry(Map.Entry<String,Cache> e){return size()>32;}});
    private final Map<String,StreamCache> streamCache=Collections.synchronizedMap(new LinkedHashMap<String,StreamCache>(64,.75f,true){protected boolean removeEldestEntry(Map.Entry<String,StreamCache> e){return size()>64;}});
    private final Map<String,Anime> known=Collections.synchronizedMap(new LinkedHashMap<>());
    private final YoruShield shield;
    private final ArrayList<Anime> seed=new ArrayList<>();
    private final java.util.concurrent.ConcurrentHashMap<String,Long> counts=new java.util.concurrent.ConcurrentHashMap<>();
    private String publicToken="";
    private long tokenAt;
    private static final class Cache {String text;long at;Cache(String t){text=t;at=System.currentTimeMillis();}}
    private static final class StreamCache {TreeMap<Integer,String> streams;long at;StreamCache(TreeMap<Integer,String> s){streams=new TreeMap<>(s);at=System.currentTimeMillis();}}
    private static final class YoruChoice {Anime.Variant variant;int quality;TreeMap<Integer,String> streams;YoruChoice(Anime.Variant v,int q,TreeMap<Integer,String> s){variant=v;quality=q;streams=new TreeMap<>(s);}}
    public static final class Filter {public String year="",genre="",type="",status="",sort="RATING_DESC",season="";}
    public static final class AiringItem {public Anime anime;public long time;public int episode;public String kind="",precision="",source="";}
    public ApiRepository(Context c){context=c.getApplicationContext();shield=new YoruShield(context);try{JSONObject boot=new JSONObject(readStream(context.getAssets().open("boot.json"),3*1024*1024));JSONArray rows=boot.optJSONArray("releases");for(int i=0;rows!=null&&i<rows.length();i++){Anime a=Anime.from(rows.getJSONObject(i));a.cached=true;if(a.id.equals("9542"))a.malId=52991;if(a.id.equals("9600"))a.malId=52299;if(a.id.equals("9555"))a.malId=54492;seed.add(a);known.put(a.key(),a);}}catch(Exception ignored){}try{JSONObject cs=new JSONObject(readStream(context.getAssets().open("counts.json"),100000));Iterator<String> it=cs.keys();while(it.hasNext()){String key=it.next();JSONObject row=cs.optJSONObject(key);long n=row==null?-1:row.optLong("value",-1);if(n>=0)counts.put(key,n);}}catch(Exception ignored){}}
    public long countOf(String source){if("yoru".equals(source))return countOf("all");if("all".equals(source)){long sum=0;for(String s:REAL_SOURCES){Long n=counts.get(s);if(n!=null&&n>0)sum+=n;}return sum>0?sum:-1;}Long n=counts.get(source);return n==null?-1:n;}
    public void clearMemory(){cache.clear();streamCache.clear();}
    public List<Anime> seed(){return new ArrayList<>(seed);}
    public Anime remember(Anime a){if(Anime.valid(a)){known.put(a.key(),a);if(known.size()>1800){synchronized(known){String first=known.keySet().iterator().next();known.remove(first);}}}return a;}
    public Anime known(String key){return known.get(key);}
    public TreeMap<Integer,String> resolveStreams(String input)throws Exception{String key=embed(input);if(key.isEmpty())key=safeUrl(input);if(key.isEmpty())throw new IOException("Просмотр не передал данные");StreamCache hit=streamCache.get(key);if(hit!=null&&System.currentTimeMillis()-hit.at<20*60*1000)return new TreeMap<>(hit.streams);TreeMap<Integer,String> streams=VideoResolver.resolve(this,key);if(!streams.isEmpty())streamCache.put(key,new StreamCache(streams));return new TreeMap<>(streams);}
    static String readStream(InputStream in,int max)throws IOException{try(InputStream input=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=input.read(b))!=-1){if(out.size()+n>max)throw new IOException("Слишком большой ответ каталога");out.write(b,0,n);}return out.toString("UTF-8");}}
    public static String safeUrl(String value){if(value==null||value.trim().isEmpty())return "";value=value.trim().replace(" ","%20").replace("\\/","/").replace("&amp;","&");if(value.startsWith("//"))value="https:"+value;try{Uri u=Uri.parse(value);String h=u.getHost();if(h==null)return "";h=h.toLowerCase(Locale.ROOT);if("http".equals(u.getScheme())&&(h.equals("video.animetop.info")||h.equals("media.animetop.info")||h.equals("static.openni.ru")))u=u.buildUpon().scheme("https").build();String scheme=u.getScheme();if(!("https".equals(scheme)||"http".equals(scheme))||u.getUserInfo()!=null||(!h.contains("."))||h.equals("localhost")||h.endsWith(".local")||h.matches("^(127|10|0|192\\.168|169\\.254)\\..*")||h.matches("^172\\.(1[6-9]|2[0-9]|3[01])\\..*"))return "";return u.toString();}catch(Exception e){return "";}}
    String request(String url,String method,String body,boolean form)throws Exception{return request(url,method,body,form,null);}
    String request(String url,String method,String body,boolean form,Map<String,String> headers)throws Exception{
        String ck=method+" "+url+" "+(body==null?"":body)+" "+(headers==null?"":headers.toString());Cache hit=cache.get(ck);if(hit!=null&&System.currentTimeMillis()-hit.at<90000)return hit.text;
        Exception last=null;ArrayList<String> attempts=shield.routes(url);for(String start:attempts){try{String text=requestNetwork(start,method,body,form,headers);if(text.length()<450000)cache.put(ck,new Cache(text));shield.ok(start);return text;}catch(Exception e){last=e;shield.fail(start);}}
        if(last!=null)throw last;throw new IOException("Каталог не ответил");
    }
    private String requestNetwork(String url,String method,String body,boolean form,Map<String,String> headers)throws Exception{
        String current=url;String currentMethod=method,currentBody=body;
        for(int redirect=0;redirect<5;redirect++){
            if(Thread.currentThread().isInterrupted())throw new InterruptedIOException();if(safeUrl(current).isEmpty())throw new IOException("Недопустимый адрес");
            URL target=new URL(current);HttpURLConnection c=(HttpURLConnection)target.openConnection();c.setConnectTimeout(6500);c.setReadTimeout(9500);c.setInstanceFollowRedirects(false);c.setRequestMethod(currentMethod);c.setRequestProperty("Accept","application/json,text/html;q=0.9,*/*;q=0.6");c.setRequestProperty("Accept-Language","ru-RU,ru;q=0.9,en;q=0.5");c.setRequestProperty("User-Agent",CHROME);
            if(headers!=null)for(Map.Entry<String,String> e:headers.entrySet())if(e.getKey()!=null&&e.getValue()!=null)c.setRequestProperty(e.getKey(),e.getValue());
            try{if(currentBody!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type",form?"application/x-www-form-urlencoded; charset=UTF-8":"application/json; charset=UTF-8");try(OutputStream out=c.getOutputStream()){out.write(currentBody.getBytes(StandardCharsets.UTF_8));}}
                int code=c.getResponseCode();if(code>=300&&code<400){String loc=c.getHeaderField("Location");if(loc==null)throw new IOException("Каталог не ответил");current=new URL(new URL(current),loc).toString();if(code!=307&&code!=308){currentMethod="GET";currentBody=null;}continue;}
                if(code==429)throw new IOException("Каталог временно занят. Попробуйте позже.");if(code<200||code>=300)throw new IOException("Каталог сейчас недоступен. Попробуйте другой вариант.");return readStream(c.getInputStream(),12*1024*1024);
            }finally{c.disconnect();}
        }
        throw new IOException("Каталог не ответил");
    }
    public void refreshProtection(boolean force){shield.refresh(force);}
    String document(String u)throws Exception{return request(u,"GET",null,false);}
    String formPage(String u,String body)throws Exception{return request(u,"POST",body,true);}
    private JSONObject get(String u)throws Exception{return new JSONObject(request(u,"GET",null,false));}
    private JSONObject postJson(String u,JSONObject j)throws Exception{return new JSONObject(request(u,"POST",j.toString(),false));}
    private JSONObject postForm(String u,String key,String value)throws Exception{return new JSONObject(request(u,"POST",enc(key)+"="+enc(value),true));}
    private static String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){return "";}}
    public static String query(String base,Map<String,String> params){StringBuilder s=new StringBuilder(base);for(Map.Entry<String,String> e:params.entrySet()){if(e.getValue()==null||e.getValue().isEmpty())continue;s.append(s.indexOf("?")>=0?'&':'?').append(enc(e.getKey())).append('=').append(enc(e.getValue()));}return s.toString();}
    private static LinkedHashMap<String,String> params(String...kv){LinkedHashMap<String,String> p=new LinkedHashMap<>();for(int i=0;i+1<kv.length;i+=2)p.put(kv[i],kv[i+1]);return p;}
    private JSONObject shiki(String q)throws Exception{JSONObject j=postJson("https://shikimori.io/api/graphql",new JSONObject().put("query",q));if(j.has("errors"))throw new IOException("Каталог не ответил на запрос");return j.getJSONObject("data");}
    private static boolean nativeFilters(String source){return source.equals("yoru")||source.equals("shikimori")||source.equals("yummy")||source.equals("anilibria");}
    private static boolean filterActive(Filter f){return f!=null&&(!f.year.isEmpty()||!f.genre.isEmpty()||!f.type.isEmpty()||!f.status.isEmpty()||!f.season.isEmpty()||!"RATING_DESC".equals(f.sort));}
    public Anime.Page catalog(String source,String search,int page,Filter f)throws Exception{
        if(f==null)f=new Filter();if(source==null||source.isEmpty())source="all";if(!source.equals("all")&&!nativeFilters(source)&&filterActive(f)){Anime.Page smart=catalog("shikimori",search,page,f);smart.note="Умная подборка";return smart;}if(source.equals("all"))return allCatalog(search,page,f);if(source.equals("yoru"))return yoruCatalog(search,page,f);if(source.equals("animedia"))return new NativeSources(this).catalog(source,search,page);if(source.equals("kodik"))return kodikCatalog(search,page,f);if(source.equals("animelib4k"))return animelib4kCatalog(search,page,f);if(source.equals("animetka"))return animetkaCatalog(search,page,f);if(source.equals("anidub"))return anidubCatalog(search,page);
        Anime.Page out=new Anime.Page();out.page=page;JSONArray rows;String q=search==null?"":search.trim();int limit=24;
        if(source.equals("shikimori")){
            String args="limit:24,page:"+page+",order:"+(f.sort.equals("POPULARITY")?"popularity":"ranked")+",rating:\"!rx\"";
            if(!q.isEmpty())args+=",search:"+JSONObject.quote(q);if(!f.year.isEmpty())args+=",season:"+JSONObject.quote((f.season.isEmpty()?"":f.season+"_")+f.year);if(!f.genre.isEmpty())args+=",genre:"+JSONObject.quote(f.genre);if(!f.type.isEmpty())args+=",kind:"+JSONObject.quote(f.type.toLowerCase(Locale.ROOT));if(!f.status.isEmpty())args+=",status:"+JSONObject.quote(f.status);
            rows=shiki("{animes("+args+"){"+SH_FIELDS+"}}").optJSONArray("animes");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(shikiAnime(rows.getJSONObject(i))));out.more=rows!=null&&rows.length()==limit;
        }else if(source.equals("animevost")){
            JSONObject data=q.isEmpty()?get("https://api.animevost.org/v1/last?quantity=24&page="+page):postForm("https://api.animevost.org/v1/search","name",q);rows=data.optJSONArray("data");if(rows==null)rows=new JSONArray();if(q.isEmpty()){JSONObject st=data.optJSONObject("state");out.total=st==null?-1:st.optLong("count",-1);for(int i=0;i<rows.length();i++)out.items.add(remember(vostAnime(rows.getJSONObject(i))));out.more=out.total>page*24;}else{out.total=rows.length();for(int i=(page-1)*24;i<Math.min(rows.length(),page*24);i++)out.items.add(remember(vostAnime(rows.getJSONObject(i))));out.more=rows.length()>page*24;}
        }else if(source.equals("yummy")){
            Map<String,String> p=params("limit","24","offset",String.valueOf((page-1)*24),"q",q,"sort",f.sort.equals("YEAR_DESC")?"year":"rating","sort_forward","false","genres",f.genre,"from_year",f.year,"to_year",f.year,"types",f.type.toLowerCase(Locale.ROOT),"status",f.status.equals("anons")?"announcement":f.status);JSONObject data=get(query("https://api.yani.tv/anime",p));if(data.has("error"))throw new IOException("Каталог сейчас недоступен");rows=data.optJSONArray("response");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(yummyAnime(rows.getJSONObject(i))));out.more=rows!=null&&rows.length()==24;
        }else if(source.equals("animelib")){
            Map<String,String> p=params("page",String.valueOf(page),"q",q,"sort_by",f.sort.equals("FRESH_AT_DESC")?"last_episode_at":"rate_avg");String u=query("https://api.cdnlibs.org/api/anime",p)+"&fields%5B%5D=rate&fields%5B%5D=rate_avg&fields%5B%5D=releaseDate";if(!f.status.isEmpty())u+="&status%5B%5D="+(f.status.equals("ongoing")?"1":"2");JSONObject data=get(u);rows=data.optJSONArray("data");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(amAnime(rows.getJSONObject(i))));JSONObject links=data.optJSONObject("links");out.more=links!=null&&!links.isNull("next")&&!links.optString("next","").isEmpty();
        }else if(source.equals("anilibria")){
            Map<String,String> p=params("limit","24","page",String.valueOf(page),"f[search]",q,"f[sorting]",f.sort.equals("POPULARITY")?"RATING_DESC":f.sort,"f[genres]",f.genre,"f[types]",f.type,"f[years][from_year]",f.year,"f[years][to_year]",f.year,"f[publish_statuses]",f.status.isEmpty()?"":f.status.equals("ongoing")?"IS_ONGOING":"IS_NOT_ONGOING");JSONObject data=get(query("https://anilibria.top/api/v1/anime/catalog/releases",p));rows=data.optJSONArray("data");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(libriaAnime(rows.getJSONObject(i))));JSONObject meta=data.optJSONObject("meta"),pg=meta==null?null:meta.optJSONObject("pagination");if(pg!=null){out.total=pg.optLong("total",-1);out.more=page<pg.optInt("total_pages");}
        }else throw new IOException("Неизвестный каталог");
        if(out.total>=0&&q.isEmpty()&&f.genre.isEmpty()&&f.year.isEmpty()&&f.type.isEmpty()&&f.status.isEmpty())counts.put(source,out.total);return out;
    }


    private Anime.Page allCatalog(String search,int page,Filter f)throws Exception{if(filterActive(f)){Anime.Page smart=catalog("shikimori",search,page,f);smart.note="Умная подборка";return smart;}Anime.Page out=new Anime.Page();out.page=page;LinkedHashMap<String,Anime> items=new LinkedHashMap<>();boolean more=false;int ok=0;ExecutorService pool=Executors.newFixedThreadPool(REAL_SOURCES.length);CompletionService<Anime.Page> done=new ExecutorCompletionService<>(pool);for(String source:REAL_SOURCES){final String src=source;done.submit(()->catalog(src,search,page,f));}long deadline=System.currentTimeMillis()+((search==null||search.trim().isEmpty())?5200:6500);try{for(int i=0;i<REAL_SOURCES.length;i++){long left=deadline-System.currentTimeMillis();if(left<=0)break;Future<Anime.Page> future=done.poll(left,TimeUnit.MILLISECONDS);if(future==null)break;try{Anime.Page p=future.get();ok++;more|=p.more;for(Anime a:p.items)items.put(a.key(),a);if(items.size()>=24&&ok>=2)break;}catch(Exception ignored){}}}finally{pool.shutdownNow();}out.items.addAll(SourceEngine.mergeCatalog(items.values(),24));out.more=more;if((search==null||search.trim().isEmpty())&&countOf("all")>0)out.total=countOf("all");if(out.items.isEmpty()&&ok==0)throw new IOException("YORU сейчас не получил подборку");return out;}
    public Anime details(Anime base,boolean episodes)throws Exception{
        if(base.source.equals("animedia"))return new NativeSources(this).details(base,episodes);
        Anime a;String id=base.id;
        switch(base.source){
            case "yoru":{a=yoruDetails(base,episodes);break;}
            case "shikimori":{JSONArray rows=shiki("{animes(ids:"+JSONObject.quote(id)+",limit:1){"+SH_FIELDS+" descriptionHtml related{relationKind anime{"+SH_FIELDS+"}}}}").optJSONArray("animes");if(rows==null||rows.length()==0)throw new IOException("Аниме не найдено");JSONObject j=rows.getJSONObject(0);a=shikiAnime(j);a.description=plain(j.optString("descriptionHtml"));JSONArray rel=j.optJSONArray("related");for(int i=0;rel!=null&&i<rel.length();i++){JSONObject r=rel.getJSONObject(i).optJSONObject("anime");if(r!=null)a.related.add(remember(shikiAnime(r)));}break;}
            case "animevost":{JSONArray rows=postForm("https://api.animevost.org/v1/info","id",id).optJSONArray("data");if(rows==null||rows.length()==0)throw new IOException("Аниме не найдено");a=vostAnime(rows.getJSONObject(0));if(episodes){JSONArray list=new JSONArray(request("https://api.animevost.org/v1/playlist","POST","id="+enc(id),true));for(int i=0;i<list.length();i++){JSONObject e=list.getJSONObject(i);Anime.Episode ep=new Anime.Episode();ep.id=id+"-"+i;ep.name=e.optString("name","");ep.number=numberIn(ep.name,i+1);putStream(ep,480,e.optString("std"));putStream(ep,720,e.optString("hd"));a.episodeList.add(ep);}a.episodes=Math.max(a.episodes,a.episodeList.size());}break;}
            case "yummy":{JSONObject d=get("https://api.yani.tv/anime/"+enc(id)).optJSONObject("response");if(d==null)throw new IOException("YORU не открыл карточку");a=yummyAnime(d);if(episodes){a.episodeList.addAll(YummyParser.episodes(id));a.episodes=Math.max(a.episodes,a.episodeList.size());}break;}
            case "anidub":{a=anidubDetails(base,episodes);break;}
            case "animelib":{String slug=base.alias.isEmpty()?id:base.alias;JSONObject d=animelibDetail(slug,base).getJSONObject("data");a=amAnime(d);if(episodes){JSONArray rows=get("https://api.cdnlibs.org/api/episodes?anime_id="+enc(a.alias)).optJSONArray("data");for(int i=0;rows!=null&&i<rows.length();i++){JSONObject e=rows.getJSONObject(i);double n=e.optDouble("number",-1);if(n<0||!Double.isFinite(n))continue;Anime.Episode ep=new Anime.Episode();ep.id=e.optString("id");ep.number=n;ep.name=e.optString("name","");ep.lazy="animelib";a.episodeList.add(ep);}a.episodeList.sort(Comparator.comparingDouble(e->e.number));a.episodes=a.episodeList.size();}break;}
            case "animelib4k":{Anime copy=Anime.from(base.json());copy.source="animelib";a=details(copy,episodes);a.source="animelib4k";break;}
            case "anilibria":{a=libriaAnime(get("https://anilibria.top/api/v1/anime/releases/"+enc(id)));break;}
            case "animetka":{a=animetkaDetails(base,episodes);break;}

            case "kodik":{a=kodikDetails(base,episodes);break;}
            default:throw new IOException("Неизвестный каталог");
        }
        if(a.year==0)a.year=base.year;if(a.malId==0)a.malId=base.malId;if(a.kpId==0)a.kpId=base.kpId;if(a.description.isEmpty())a.description=base.description;if(a.poster.isEmpty())a.poster=base.poster;return remember(a);
    }
    public Anime.Playback playback(Anime input,String selectedMode)throws Exception{
        normalizeIds(input);
        String selected=selectedMode==null||selectedMode.trim().isEmpty()?"auto":selectedMode.trim();
        if(selected.equals("all"))selected="auto";
        if(!selected.equals("auto")){
            Anime video=findPlayableSource(input,selected);
            if(video==null)throw new IOException("Просмотр сейчас не вернул серии");
            return playbackResult(input,video,selected);
        }
        ArrayList<String> order=SourceEngine.playbackOrder(input);
        ExecutorService pool=Executors.newFixedThreadPool(Math.max(1,Math.min(4,order.size())));
        CompletionService<Anime.Playback> done=new ExecutorCompletionService<>(pool);
        for(String source:order){final String src=source;done.submit(()->{Anime video=findPlayableSource(input,src);return video==null?null:playbackResult(input,video,src);});}
        long deadline=System.currentTimeMillis()+9500;
        try{for(int i=0;i<order.size();i++){long left=deadline-System.currentTimeMillis();if(left<=0)break;Future<Anime.Playback> f=done.poll(left,TimeUnit.MILLISECONDS);if(f==null)break;try{Anime.Playback r=f.get();if(r!=null)return r;}catch(Exception ignored){}}}finally{pool.shutdownNow();}
        throw new IOException("YORU сейчас не нашёл серии");
    }
    private Anime.Playback playbackResult(Anime catalog,Anime video,String provider){Anime.Playback r=new Anime.Playback();r.catalog=catalog;r.video=video;r.provider=provider==null||provider.isEmpty()?video.source:provider;return r;}
    private Anime findPlayableSource(Anime input,String source){long started=System.currentTimeMillis();try{Anime candidate=findSourceCandidate(input,source);if(candidate==null){SourceEngine.record(source,false,System.currentTimeMillis()-started,0,0,0);return null;}Anime full=candidate.episodeList.isEmpty()?details(candidate,true):candidate;if(!full.blocked&&!full.episodeList.isEmpty()){SourceEngine.record(source,true,System.currentTimeMillis()-started,full.episodeList.size(),SourceEngine.optionCount(full),SourceEngine.maxQuality(full));return full;}SourceEngine.record(source,false,System.currentTimeMillis()-started,0,0,0);}catch(Exception ignored){SourceEngine.record(source,false,System.currentTimeMillis()-started,0,0,0);}return null;}
    private Anime findSourceCandidate(Anime input,String source)throws Exception{
        if(source.equals(input.source)&&Arrays.asList("yoru","animevost","anilibria","animedia","animelib","animelib4k","yummy","animetka","anidub","kodik").contains(source))return input;
        if(source.equals("yoru"))return yoruShell(input);
        if(source.equals("yummy"))return findYummy(input);
        if(source.equals("anilibria")){Anime v=findAniLiberty(input);if(v!=null)return v;}
        if(source.equals("animelib")){Anime v=findAniLib(input);if(v!=null)return v;}
        if(source.equals("kodik"))return kodikShell(input);
        if(source.equals("animetka")||source.equals("anidub"))return searchSource(input,source);
        if(source.equals("animelib4k")){Anime v=findAniLib(input);if(v!=null){v.source="animelib4k";return v;}}
        if(Arrays.asList("animevost","animedia").contains(source))return searchSource(input,source);
        return null;
    }
    public synchronized void loadEpisode(Anime.Episode ep)throws Exception{if(ep.lazy.equals("yoru")){loadYoruEpisode(ep);return;}if(ep.lazy.equals("animedia")){new NativeSources(this).loadEpisode(ep);return;}if(ep.lazy.equals("anidub")){if(ep.variants.isEmpty()&&!ep.resolverUrl.isEmpty())ep.variants.add(new Anime.Variant("AniDub",hostName(ep.resolverUrl),ep.resolverUrl));return;}if(ep.lazy.equals("kodik")){if(ep.variants.isEmpty())ep.variants.add(new Anime.Variant("","YORU Prime",ep.resolverUrl));return;}if(!"animelib".equals(ep.lazy)||!ep.variants.isEmpty())return;JSONObject d=get("https://api.cdnlibs.org/api/episodes/"+enc(ep.id)).getJSONObject("data");JSONArray rows=d.optJSONArray("players");for(int i=0;rows!=null&&i<rows.length();i++){JSONObject v=rows.getJSONObject(i);String u=embed(v.optString("src"));if(u.isEmpty())continue;JSONObject team=v.optJSONObject("team"),t=v.optJSONObject("translation_type");String teamName=team==null?"":team.optString("name",team.optString("title",""));String type=t==null?"Озвучка":t.optString("label",t.optString("title","Озвучка"));String name=(type+" "+teamName).trim();String player=cleanLabel(v.optString("player","Вариант"));Anime.Variant row=new Anime.Variant(name.isEmpty()?"Озвучка":cleanLabel(name),player.isEmpty()?"Вариант":player,u);row.displayName=(row.name.isEmpty()?"Озвучка":row.name)+(row.player.isEmpty()?"":" · "+row.player);addVariant(ep,row);}if(ep.variants.isEmpty())throw new IOException("У серии пока нет доступного просмотра");ep.variants.sort(Comparator.comparingInt(v->SourceEngine.variantRank(v)));}
    public static final class DownloadOption {public Anime source;public Anime.Episode episode;public int quality;public String voice,player;DownloadOption(Anime s,Anime.Episode e,int q,String v,String p){source=s;episode=e;quality=q;voice=v;player=p;}public String label(){String q=quality>0?quality+"p":"Оригинал";String v=voiceTitle(voice==null||voice.isEmpty()?episode==null?"":episode.name:voice);return q+(v.isEmpty()?"":" · "+v);}}
    private List<DownloadOption> options(Anime source,double number)throws Exception{SecureStore store=YoruApp.app().store;return options(source,number,store.voicePreference(),store.downloadResolution(),store.onlyPreferredVoice());}
    private List<DownloadOption> options(Anime source,double number,String voice,int maxQuality,boolean strictVoice)throws Exception{ArrayList<DownloadOption> out=new ArrayList<>();if(!Anime.valid(source))return out;Anime a=source.episodeList.isEmpty()?details(source,true):source;Anime.Episode e=findEpisode(a,number);if(e==null)return out;if(!"yoru".equals(e.lazy))loadEpisode(e);for(Map.Entry<Integer,String> stream:e.streams.entrySet()){String u=safeUrl(stream.getValue());if(u.isEmpty())continue;String streamVoice=sourceVoice(a.source);if(streamVoice.isEmpty())streamVoice=voiceTitle(e.name);DownloadOption option=new DownloadOption(a,e,stream.getKey(),streamVoice,downloadSourceName(a.source));if(optionAllowed(option,voice,maxQuality,strictVoice))out.add(option);}if(!e.variants.isEmpty())out.addAll(variantOptions(a,e,voice,maxQuality,strictVoice));return uniqueOptions(out);}
    private List<DownloadOption> variantOptions(Anime source,Anime.Episode episode,String voice,int maxQuality,boolean strictVoice){ArrayList<DownloadOption> out=new ArrayList<>();ArrayList<Anime.Variant> variants=SourceEngine.sortVariants(episode.variants);ArrayList<Anime.Variant> chosen=new ArrayList<>();for(Anime.Variant v:variants){String label=v==null?"":v.name+" "+v.displayName+" "+v.player;if(strictVoice&&!voiceMatches(voice,label))continue;chosen.add(v);if(chosen.size()>=(strictVoice?12:7))break;}if(chosen.isEmpty())return out;ExecutorService pool=Executors.newFixedThreadPool(Math.max(1,Math.min(4,chosen.size())));CompletionService<List<DownloadOption>> done=new ExecutorCompletionService<>(pool);for(Anime.Variant variant:chosen)done.submit(()->{ArrayList<DownloadOption> rows=new ArrayList<>();try{TreeMap<Integer,String> streams=resolveStreams(variant.url);String vName=voiceTitle(variant.name.isEmpty()?variant.label():variant.name);for(Map.Entry<Integer,String> stream:streams.entrySet()){if(safeUrl(stream.getValue()).isEmpty())continue;Anime.Episode ep=new Anime.Episode();ep.id=episode.id+"-"+Integer.toHexString((variant.url+"|"+stream.getKey()).hashCode());ep.number=episode.number;ep.name=vName;ep.duration=episode.duration;ep.openingStart=episode.openingStart;ep.openingEnd=episode.openingEnd;ep.streams.put(stream.getKey(),stream.getValue());DownloadOption option=new DownloadOption(source,ep,stream.getKey(),vName,variant.player);if(optionAllowed(option,voice,maxQuality,strictVoice))rows.add(option);}SourceEngine.recordVariant(variant,!rows.isEmpty(),0,streams.isEmpty()?0:streams.lastKey());}catch(Exception ignored){SourceEngine.recordVariant(variant,false,0,0);}return rows;});long deadline=System.currentTimeMillis()+(strictVoice?16000:9500);try{for(int i=0;i<chosen.size();i++){long left=deadline-System.currentTimeMillis();if(left<=0||out.size()>=8)break;Future<List<DownloadOption>> future;try{future=done.poll(left,TimeUnit.MILLISECONDS);}catch(InterruptedException e){Thread.currentThread().interrupt();break;}if(future==null)break;try{out.addAll(future.get());out=uniqueOptions(out);}catch(Exception ignored){}}}finally{pool.shutdownNow();}return uniqueOptions(out);}
    private boolean optionAllowed(DownloadOption option,String voice,int maxQuality,boolean strictVoice){if(option==null||option.episode==null)return false;if(strictVoice&&!voiceMatches(voice,option.voice+" "+option.episode.name))return false;if(maxQuality>0&&maxQuality<9999&&option.quality>0&&option.quality>maxQuality)return false;return option.quality>=0;}
    private static ArrayList<DownloadOption> uniqueOptions(Collection<DownloadOption> rows){LinkedHashMap<String,DownloadOption> map=new LinkedHashMap<>();if(rows!=null)for(DownloadOption option:rows){if(option==null||option.episode==null)continue;String url=safeUrl(option.episode.streams.get(option.quality));if(url.isEmpty())continue;String voice=voiceKey(option.voice+" "+option.episode.name);String urlKey=Integer.toHexString(url.hashCode());String key=episodeParam(option.episode.number)+"|"+option.quality+"|"+(voice.isEmpty()?"unknown:"+urlKey:voice);if(!map.containsKey(key))map.put(key,option);}ArrayList<DownloadOption> out=new ArrayList<>(map.values());out.sort((a,b)->{int sa=SourceEngine.score(a.source==null?"":a.source.source,a.source),sb=SourceEngine.score(b.source==null?"":b.source.source,b.source);int p=sb-sa;if(p!=0)return p;return Integer.compare(b.quality,a.quality);});return out;}
    private boolean enoughDownloadOptions(ArrayList<DownloadOption> rows,String voice,int maxQuality,boolean strictVoice){ArrayList<DownloadOption> unique=uniqueOptions(rows);if(unique.size()>=6)return true;HashSet<Integer> q=new HashSet<>();for(DownloadOption option:unique)if(optionAllowed(option,voice,maxQuality,strictVoice))q.add(option.quality);return q.size()>=3&&unique.size()>=3;}
    private void collectOptions(ArrayList<DownloadOption> out,Anime source,double number,String voice,int maxQuality,boolean strictVoice){if(!Anime.valid(source))return;try{out.addAll(options(source,number,voice,maxQuality,strictVoice));}catch(Exception ignored){}}
    private void collectDetailsOptions(ArrayList<DownloadOption> out,Anime base,double number,String voice,int maxQuality,boolean strictVoice){if(!Anime.valid(base))return;try{collectOptions(out,details(base,true),number,voice,maxQuality,strictVoice);}catch(Exception ignored){}}
    private void collectCatalogOptions(ArrayList<DownloadOption> out,Anime base,double number,String voice,int maxQuality,boolean strictVoice){if(!Anime.valid(base))return;ArrayList<Anime> matches=new ArrayList<>();for(String s:SourceEngine.discoveryOrder(base,null)){try{for(Anime candidate:catalog(s,base.original.isEmpty()?base.title:base.original,1,new Filter()).items)if(candidate!=null&&SourceEngine.identity(candidate).equals(SourceEngine.identity(base)))matches.add(candidate);}catch(Exception ignored){}if(matches.size()>=4)break;}matches.sort((a,b)->SourceEngine.score(b.source,b)-SourceEngine.score(a.source,a));for(Anime candidate:matches){collectOptions(out,candidate,number,voice,maxQuality,strictVoice);if(enoughDownloadOptions(out,voice,maxQuality,strictVoice))break;}}
    private void collectIframeOptions(ArrayList<DownloadOption> out,Anime base,double number){try{Anime.Playback ready=playback(base,"kodik");String url=ready==null?"":embed(ready.directUrl);if(url.isEmpty()&&ready!=null&&ready.video!=null){Anime.Episode ep=findEpisode(ready.video,number);if(ep!=null){loadEpisode(ep);if(!ep.variants.isEmpty())url=embed(ep.variants.get(0).url);}}if(url.isEmpty())return;TreeMap<Integer,String> streams=resolveStreams(url);for(Map.Entry<Integer,String> stream:streams.entrySet()){String safe=safeUrl(stream.getValue());if(safe.isEmpty())continue;Anime source=Anime.from(base.json());source.source="kodik";source.id=base.id.isEmpty()?String.valueOf(Math.abs(base.key().hashCode())):base.id;Anime.Episode ep=new Anime.Episode();ep.id=source.id+"-"+episodeParam(number)+"-"+stream.getKey();ep.number=number;ep.name="";ep.streams.put(stream.getKey(),safe);out.add(new DownloadOption(source,ep,stream.getKey(),"","YORU Prime"));}}catch(Exception ignored){}}
    private static Anime.Episode findEpisode(Anime anime,double number){if(anime==null)return null;Anime.Episode fallback=null;double best=Double.MAX_VALUE;for(Anime.Episode ep:anime.episodeList){if(ep==null)continue;if(sameEpisode(ep.number,number))return ep;double diff=Math.abs(ep.number-number);if(diff<best){best=diff;fallback=ep;}}return fallback;}
    public List<DownloadOption> downloadOptions(Anime a,Anime.Playback current,double number)throws Exception{SecureStore store=YoruApp.app().store;return downloadOptions(a,current,number,store.voicePreference(),store.downloadResolution(),store.onlyPreferredVoice());}
    public List<DownloadOption> downloadOptions(Anime a,Anime.Playback current,double number,String voice,int maxQuality,boolean strictVoice)throws Exception{ArrayList<DownloadOption> out=new ArrayList<>();if(current!=null&&current.video!=null)collectOptions(out,current.video,number,voice,maxQuality,strictVoice);if(enoughDownloadOptions(out,voice,maxQuality,strictVoice))return uniqueOptions(out);collectDetailsOptions(out,a,number,voice,maxQuality,strictVoice);if(enoughDownloadOptions(out,voice,maxQuality,strictVoice))return uniqueOptions(out);Anime yoru=yoruShell(a);if(Anime.valid(yoru))collectOptions(out,yoru,number,voice,maxQuality,strictVoice);if(enoughDownloadOptions(out,voice,maxQuality,strictVoice))return uniqueOptions(out);Anime max=findYummy(a);if(Anime.valid(max))collectOptions(out,max,number,voice,maxQuality,strictVoice);if(enoughDownloadOptions(out,voice,maxQuality,strictVoice))return uniqueOptions(out);if(!strictVoice)collectIframeOptions(out,a,number);if(!out.isEmpty()||strictVoice)return uniqueOptions(out);collectCatalogOptions(out,a,number,voice,maxQuality,false);return uniqueOptions(out);}

    private Anime.Page yoruCatalog(String search,int page,Filter f)throws Exception{String q=search==null?"":search.trim();Anime.Page base;try{base=q.isEmpty()&&!filterActive(f)?catalog("yummy",q,page,f):catalog("shikimori",q,page,f);}catch(Exception first){base=catalog("shikimori",q,page,f);}Anime.Page out=new Anime.Page();out.page=base.page;out.total=base.total;out.more=base.more;out.note="YORU Source";for(Anime item:base.items)out.items.add(remember(yoruShell(item)));return out;}
    private Anime yoruShell(Anime base){Anime a=Anime.from(base==null?new JSONObject():base.json());String originalSource=base==null?"":base.source;a.source="yoru";int id=a.malId>0?a.malId:("shikimori".equals(originalSource)?parseInt(base.id):0);if(id>0&&a.malId==0)a.malId=id;if(id<=0)id=(int)(1L+Integer.toUnsignedLong((base==null?"yoru":base.key()).hashCode())%999999999L);a.id=String.valueOf(id);a.blocked=false;return a;}
    private Anime yoruDetails(Anime base,boolean episodes)throws Exception{Anime a=yoruShell(base);Anime y=null;try{y=findYummy(base);if(y!=null)fillYoruMeta(a,y);}catch(Exception ignored){}try{int mal=a.malId>0?a.malId:(y==null?0:y.malId);if(mal>0){Anime sh=new Anime();sh.source="shikimori";sh.id=String.valueOf(mal);Anime meta=details(sh,false);fillYoruMeta(a,meta);for(Anime r:meta.related)a.related.add(r);}}catch(Exception ignored){}if(episodes){ArrayList<Anime> found=yoruFoundSources(base,a,y);LinkedHashMap<String,Anime.Episode> map=new LinkedHashMap<>();for(Anime source:found)mergeYoruEpisodes(map,source);a.episodeList.clear();a.episodeList.addAll(map.values());a.episodeList.sort(Comparator.comparingDouble(e->e.number));a.episodes=Math.max(a.episodes,a.episodeList.size());}return remember(a);}

    private void fillYoruMeta(Anime target,Anime source){if(target==null||source==null)return;if(target.title.isEmpty())target.title=source.title;if(target.original.isEmpty())target.original=source.original;if(target.alias.isEmpty())target.alias=source.alias;if(target.poster.isEmpty())target.poster=source.poster;if(target.description.isEmpty())target.description=source.description;if(target.year==0)target.year=source.year;if(target.type.isEmpty()||target.type.equals("Аниме"))target.type=source.type;if(target.status.isEmpty())target.status=source.status;if(target.age.isEmpty())target.age=source.age;if(target.studio.isEmpty())target.studio=source.studio;if(target.episodes==0)target.episodes=source.episodes;if(target.malId==0)target.malId=source.malId;if(target.anilistId==0)target.anilistId=source.anilistId;if(target.kpId==0)target.kpId=source.kpId;if(target.libriaAlias.isEmpty())target.libriaAlias=source.libriaAlias;if(target.score==0)target.score=source.score;for(String g:source.genres)if(!target.genres.contains(g))target.genres.add(g);}
    private ArrayList<Anime> yoruFoundSources(Anime original,Anime shell,Anime yummy){ArrayList<Anime> out=new ArrayList<>();LinkedHashSet<String> seen=new LinkedHashSet<>();ArrayList<String> sources=SourceEngine.discoveryOrder(original,shell);ExecutorService pool=Executors.newFixedThreadPool(Math.max(1,Math.min(5,sources.size()+1)));CompletionService<Anime> done=new ExecutorCompletionService<>(pool);int jobs=0;if(yummy!=null){Anime y=yummy;done.submit(()->details(y,true));jobs++;}for(String source:sources){done.submit(()->yoruFindSource(original,shell,source));jobs++;}long deadline=System.currentTimeMillis()+11500;try{for(int i=0;i<jobs;i++){long left=deadline-System.currentTimeMillis();if(left<=0)break;Future<Anime> f;try{f=done.poll(left,TimeUnit.MILLISECONDS);}catch(InterruptedException e){Thread.currentThread().interrupt();break;}if(f==null)break;try{Anime a=f.get();if(a!=null&&!a.episodeList.isEmpty()&&seen.add(a.source+":"+a.id))out.add(a);}catch(Exception ignored){}}}finally{pool.shutdownNow();}out.sort(Comparator.comparingInt(a->1000-SourceEngine.score(a.source,a)));return out;}
    private Anime yoruFindSource(Anime original,Anime shell,String source){long started=System.currentTimeMillis();try{Anime candidate;if(source.equals("kodik"))candidate=kodikShell(shell);else if(source.equals("anilibria"))candidate=findAniLiberty(shell);else if(source.equals("animetka")||source.equals("anidub")||source.equals("animevost")||source.equals("animedia"))candidate=searchSource(shell,source);else candidate=searchSource(shell,source);if(candidate==null&&original!=null&&!original.source.equals("yoru")&&original.source.equals(source))candidate=original;if(candidate==null){SourceEngine.record(source,false,System.currentTimeMillis()-started,0,0,0);return null;}Anime full=details(candidate,true);if(full.blocked||full.episodeList.isEmpty()){SourceEngine.record(source,false,System.currentTimeMillis()-started,0,0,0);return null;}SourceEngine.record(source,true,System.currentTimeMillis()-started,full.episodeList.size(),SourceEngine.optionCount(full),SourceEngine.maxQuality(full));return full;}catch(Exception e){SourceEngine.record(source,false,System.currentTimeMillis()-started,0,0,0);return null;}}
    private void mergeYoruEpisodes(LinkedHashMap<String,Anime.Episode> map,Anime source){String route=downloadSourceName(source.source);for(Anime.Episode e:source.episodeList){if(e==null||e.number<0||!Double.isFinite(e.number))continue;ArrayList<Anime.Variant> variants=new ArrayList<>();String baseVoice=sourceVoice(source.source);if(baseVoice.isEmpty())baseVoice=voiceTitle(e.name);for(Map.Entry<Integer,String> stream:e.streams.entrySet()){String url=safeUrl(stream.getValue());if(url.isEmpty())continue;Anime.Variant v=new Anime.Variant(baseVoice,route,url);v.duration=e.duration;v.openingStart=e.openingStart;v.openingEnd=e.openingEnd;v.displayName=baseVoice;variants.add(v);}for(Anime.Variant row:e.variants){String url=embed(row.url);if(url.isEmpty())continue;String rowLabel=cleanLabel(row.name.isEmpty()?row.label():row.name),rowPlayer=cleanLabel(row.player);String voice=voiceTitle(rowLabel);if(voice.isEmpty())voice=sourceVoice(source.source);Anime.Variant v=new Anime.Variant(voice,rowPlayer.isEmpty()?route:route+" · "+rowPlayer,url);v.duration=row.duration;v.openingStart=row.openingStart;v.openingEnd=row.openingEnd;v.displayName=voice;variants.add(v);}if(variants.isEmpty())continue;String key=episodeParam(e.number);Anime.Episode ep=map.get(key);if(ep==null){ep=new Anime.Episode();ep.id="yoru-"+key;ep.number=e.number;ep.name="";ep.lazy="yoru";map.put(key,ep);}ep.duration=Math.max(ep.duration,e.duration);if(ep.openingEnd<=0&&e.openingEnd>0){ep.openingStart=e.openingStart;ep.openingEnd=e.openingEnd;}for(Anime.Variant v:variants)addVariant(ep,v);ep.variants.sort(Comparator.comparingInt(v->SourceEngine.variantRank(v)));}}
    private void loadYoruEpisode(Anime.Episode ep)throws Exception{if("yoru-ready".equals(ep.resolverUrl))return;if(ep.variants.isEmpty()&&!ep.streams.isEmpty()){ep.resolverUrl="yoru-ready";return;}ArrayList<Anime.Variant> sorted=SourceEngine.sortVariants(ep.variants);ArrayList<Anime.Variant> input=new ArrayList<>();String preferred="";boolean strict=false;try{preferred=YoruApp.app().store.voicePreference();strict=YoruApp.app().store.onlyPreferredVoice();}catch(Exception ignored){}for(Anime.Variant v:sorted){if(strict&&!voiceMatches(preferred,v.name+" "+v.displayName+" "+v.player))continue;input.add(v);if(input.size()>=18)break;}if(input.isEmpty())throw new IOException(strict?"Выбранная озвучка пока недоступна":"YORU Source не нашёл вариантов");ep.variants.clear();ExecutorService pool=Executors.newFixedThreadPool(Math.max(1,Math.min(6,input.size())));CompletionService<YoruChoice> done=new ExecutorCompletionService<>(pool);for(Anime.Variant v:input)done.submit(()->{long started=System.currentTimeMillis();try{TreeMap<Integer,String> streams=resolveStreams(v.url);if(streams.isEmpty()){SourceEngine.recordVariant(v,false,System.currentTimeMillis()-started,0);return null;}int q=streams.lastKey();Anime.Variant copy=copyVariant(v);String voice=voiceTitle(copy.name.isEmpty()?copy.label():copy.name);copy.name=voice;copy.displayName=voice;SourceEngine.recordVariant(v,true,System.currentTimeMillis()-started,q);return new YoruChoice(copy,q,streams);}catch(Exception e){SourceEngine.recordVariant(v,false,System.currentTimeMillis()-started,0);return null;}});long deadline=System.currentTimeMillis()+16000;try{for(int i=0;i<input.size();i++){long left=deadline-System.currentTimeMillis();if(left<=0)break;Future<YoruChoice> f;try{f=done.poll(left,TimeUnit.MILLISECONDS);}catch(InterruptedException e){Thread.currentThread().interrupt();break;}if(f==null)break;try{YoruChoice c=f.get();if(c!=null)addVariant(ep,c.variant);}catch(Exception ignored){}}}finally{pool.shutdownNow();}if(ep.variants.isEmpty()){int keep=0;for(Anime.Variant raw:input){addVariant(ep,copyVariant(raw));if(++keep>=5)break;}}ep.variants.sort(Comparator.comparingInt(v->SourceEngine.variantRank(v)));ep.resolverUrl="yoru-ready";if(ep.variants.isEmpty())throw new IOException("YORU Source не нашёл подходящий вариант");}
    private static Anime.Variant copyVariant(Anime.Variant v){Anime.Variant copy=new Anime.Variant(cleanLabel(v.name),cleanLabel(v.player),v.url);copy.displayName=cleanLabel(v.displayName);copy.duration=v.duration;copy.openingStart=v.openingStart;copy.openingEnd=v.openingEnd;return copy;}
    private static int yoruSourceRank(String source){if("yummy".equals(source))return 0;if("anilibria".equals(source))return 1;if("animevost".equals(source))return 2;if("animetka".equals(source))return 3;if("kodik".equals(source))return 4;if("anidub".equals(source))return 5;if("animedia".equals(source))return 6;return 20;}
    private static int yoruVariantRank(Anime.Variant v){String p=((v==null?"":v.player)+" "+(v==null?"":v.name)+" "+(v==null?"":v.displayName)).toLowerCase(Locale.ROOT);int source=p.contains("yummyanime")?0:p.contains("anilibria")||p.contains("aniliberty")?1:p.contains("animevost")?2:p.contains("animetka")?3:p.contains("kodik")?4:p.contains("anidub")?5:10;int player=p.contains("cvh")||p.contains("cdnvideohub")?0:p.contains("aksor")?1:p.contains("vk")||p.contains("вконт")?2:p.contains("rutube")?3:p.contains("zedfilm")||p.contains("hlamer")?4:p.contains("alloha")?5:p.contains("sibnet")?6:10;return source*100+player;}
    public ArrayList<AiringItem> airingSchedule(int days)throws Exception{days=Math.max(7,Math.min(28,days));long now=System.currentTimeMillis(),start=startOfDay(now),end=start+days*DAY_MS;LinkedHashMap<String,AiringItem> map=new LinkedHashMap<>();Exception fail=null;try{for(int page=1;page<=2;page++)airingPage(map,"ongoing","popularity",page,now,start,end,false);}catch(Exception e){fail=e;}try{airingPage(map,"anons","aired_on",1,now,start,end,true);}catch(Exception ignored){}ArrayList<AiringItem> list=new ArrayList<>(map.values());if(list.isEmpty()){try{Filter f=new Filter();f.status="ongoing";Anime.Page p=catalog("shikimori","",1,f);int i=0;for(Anime a:p.items){AiringItem row=new AiringItem();row.anime=a;row.time=start+((i++)%7)*DAY_MS+20*60*60*1000;row.episode=Math.max(1,a.episodes);row.kind="Онгоинг";row.precision="Скоро";row.source="YORU";list.add(row);if(list.size()>=24)break;}}catch(Exception ignored){}}list.sort((a,b)->{int t=Long.compare(a.time,b.time);if(t!=0)return t;double bs=b.anime==null?0:b.anime.score,as=a.anime==null?0:a.anime.score;return Double.compare(bs,as);});if(list.isEmpty()&&fail!=null)throw fail;return list;}
    private void airingPage(LinkedHashMap<String,AiringItem> map,String status,String order,int page,long now,long start,long end,boolean premiere)throws Exception{String fields="id malId name russian english kind rating score status episodes episodesAired airedOn{year date} poster{mainUrl originalUrl} genres{id russian name} nextEpisodeAt";JSONArray rows=shiki("{animes(limit:50,page:"+page+",status:"+JSONObject.quote(status)+",order:"+order+"){"+fields+"}}").optJSONArray("animes");for(int i=0;rows!=null&&i<rows.length();i++)putAiring(map,rows.getJSONObject(i),now,start,end,premiere);}
    private void putAiring(LinkedHashMap<String,AiringItem> map,JSONObject j,long now,long start,long end,boolean premiere){Anime a=remember(shikiAnime(j));int aired=j.optInt("episodesAired",0),total=j.optInt("episodes",a.episodes),next=Math.max(1,aired+1);long at=premiere?dateAt(j.optJSONObject("airedOn"),20):parseInstant(j.optString("nextEpisodeAt",""));String precision=premiere?"Премьера":"Точная дата";if(!premiere&&at<=0){at=estimateWeekly(j,now,end);precision="Расчёт";}if(total>0&&next>total&&!premiere)return;if(at<=0||at<start-DAY_MS/2||at>end)return;AiringItem item=new AiringItem();item.anime=a;item.time=at;item.episode=premiere?1:next;item.kind=premiere?"Премьера":"Новая серия";item.precision=precision;item.source="YORU";String key=a.key()+"|"+item.episode+"|"+startOfDay(at);AiringItem old=map.get(key);if(old==null||("Точная дата".equals(item.precision)&&!"Точная дата".equals(old.precision)))map.put(key,item);}
    private static long estimateWeekly(JSONObject j,long now,long end){long first=dateAt(j.optJSONObject("airedOn"),20);if(first<=0)return 0;int aired=Math.max(0,j.optInt("episodesAired",0));long at=first+aired*7L*DAY_MS;while(at<now-6*60*60*1000)at+=7L*DAY_MS;return at<=end?at:0;}
    private static long parseInstant(String value){String v=value==null?"":value.trim();if(v.isEmpty()||v.equals("null"))return 0;try{return OffsetDateTime.parse(v).toInstant().toEpochMilli();}catch(Exception ignored){}try{return Instant.parse(v).toEpochMilli();}catch(Exception ignored){}try{return LocalDateTime.parse(v).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();}catch(Exception ignored){}return 0;}
    private static long dateAt(JSONObject value,int hour){if(value==null)return 0;String d=value.optString("date","");if(d.isEmpty()&&value.optInt("year",0)>0)d=String.format(Locale.US,"%04d-%02d-%02d",value.optInt("year"),Math.max(1,value.optInt("month",1)),Math.max(1,value.optInt("day",1)));try{return LocalDate.parse(d).atTime(hour,0).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();}catch(Exception e){return 0;}}
    private static long startOfDay(long time){return Instant.ofEpochMilli(time).atZone(ZoneId.systemDefault()).toLocalDate().atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli();}

    private Anime.Page animetkaCatalog(String search,int page,Filter f)throws Exception{Anime.Page out=new Anime.Page();out.page=page;String q=search==null?"":search.trim();int limit=24,offset=Math.max(0,(page-1)*limit);String url=q.isEmpty()?query("https://animetka.com/api/anime/top",params("limit",String.valueOf(limit),"offset",String.valueOf(offset))):query("https://animetka.com/api/anime/search",params("name",q,"limit",String.valueOf(limit),"offset",String.valueOf(offset)));JSONArray rows=new JSONArray(request(url,"GET",null,false,animetkaHeaders()));if(rows.length()==0&&!q.isEmpty())rows=new JSONArray(request(query("https://animetka.com/api/anime/search",params("q",q,"limit",String.valueOf(limit),"offset",String.valueOf(offset))),"GET",null,false,animetkaHeaders()));int end=Math.min(rows.length(),limit);for(int i=0;i<end;i++){Anime a=animetkaAnime(rows.getJSONObject(i));if(Anime.valid(a))out.items.add(remember(a));}out.more=!q.isEmpty()&&rows.length()==limit;return out;}
    private Anime animetkaDetails(Anime base,boolean episodes)throws Exception{JSONObject d=new JSONObject(request("https://animetka.com/api/anime/"+enc(base.id),"GET",null,false,animetkaHeaders()));Anime a=animetkaAnime(d);if(!Anime.valid(a)){a=Anime.from(base.json());a.source="animetka";}JSONArray rel=d.optJSONArray("franchise");for(int i=0;rel!=null&&i<rel.length();i++){JSONObject r=rel.optJSONObject(i);if(r!=null){Anime item=animetkaAnime(r);if(Anime.valid(item)&&!item.id.equals(a.id))a.related.add(remember(item));}}if(episodes){LinkedHashMap<String,Anime.Episode> map=new LinkedHashMap<>();JSONObject lm=d.optJSONObject("AnilibriaMapping");JSONArray le=lm==null?null:lm.optJSONArray("episodes");for(int i=0;le!=null&&i<le.length();i++){JSONObject e=le.optJSONObject(i);if(e==null)continue;double n=e.optDouble("ordinal",i+1);String key=episodeParam(n);Anime.Episode ep=map.get(key);if(ep==null){ep=new Anime.Episode();ep.id=a.id+"-"+key;ep.number=n;ep.name=e.optString("name","");map.put(key,ep);}if(ep.name.isEmpty())ep.name="AniLibria";ep.duration=e.optInt("duration",ep.duration);putStream(ep,480,e.optString("hls_480"));putStream(ep,720,e.optString("hls_720"));putStream(ep,1080,e.optString("hls_1080"));JSONObject op=e.optJSONObject("opening");if(op!=null){ep.openingStart=op.optInt("start",ep.openingStart);ep.openingEnd=op.optInt("stop",ep.openingEnd);}}JSONArray rows=d.optJSONArray("Animes");HashMap<Integer,String> names=animetkaTranslationNames(d,rows);for(int i=0;rows!=null&&i<rows.length();i++){JSONObject row=rows.optJSONObject(i);if(row==null)continue;String link=embed(row.optString("link"));if(link.isEmpty())continue;int tid=row.optInt("translation",0),count=Math.max(row.optInt("episodes_total",0),row.optInt("episodes_aired",0));if(count<=0)count=a.episodes>0?a.episodes:1;if(row.optString("kodik_id").startsWith("movie-")||Uri.parse(link).getPath()!=null&&Uri.parse(link).getPath().startsWith("/video/"))count=1;count=Math.max(1,Math.min(250,count));String voice=names.get(tid);if(voice==null||voice.isEmpty())voice=tid>0?"Перевод "+tid:"";String q=row.optString("quality","").replace("WEB-DLRip ","").trim();for(int n=1;n<=count;n++){String key=episodeParam(n);Anime.Episode ep=map.get(key);if(ep==null){ep=new Anime.Episode();ep.id=a.id+"-"+key;ep.number=n;map.put(key,ep);}String url=animetkaEpisodeUrl(link,n);Anime.Variant v=new Anime.Variant(voice,"YORU Prime",url);v.displayName=voice+(q.isEmpty()?"":" · "+q);addVariant(ep,v);}}a.episodeList.clear();a.episodeList.addAll(map.values());a.episodeList.sort(Comparator.comparingDouble(e->e.number));a.episodes=Math.max(a.episodes,a.episodeList.size());}return remember(a);}
    private HashMap<Integer,String> animetkaTranslationNames(JSONObject detail,JSONArray rows){HashMap<Integer,String> out=new HashMap<>();int material=detail.optInt("id",detail.optInt("animetka_id",0)),tid=0;for(int i=0;rows!=null&&i<rows.length();i++){JSONObject row=rows.optJSONObject(i);if(row!=null&&row.optInt("translation",0)>0){tid=row.optInt("translation");break;}}if(material<=0||tid<=0)return out;try{JSONObject p=new JSONObject(request(query("https://animetka.com/api/anime/playlist",params("material",String.valueOf(material),"tid",String.valueOf(tid))),"GET",null,false,animetkaHeaders()));JSONArray list=p.optJSONArray("translations");for(int i=0;list!=null&&i<list.length();i++){JSONObject t=list.optJSONObject(i);if(t!=null)out.put(t.optInt("value",t.optInt("id",0)),t.optString("name",t.optString("title","")));}}catch(Exception ignored){}return out;}
    private static String animetkaEpisodeUrl(String link,int episode){try{Uri u=Uri.parse(link);String path=u.getPath();if(path!=null&&path.startsWith("/video/"))return link;return u.buildUpon().appendQueryParameter("episode",String.valueOf(episode)).build().toString();}catch(Exception e){return link;}}
    private static void addVariant(Anime.Episode ep,Anime.Variant v){for(Anime.Variant old:ep.variants)if(old.url.equals(v.url)&&old.name.equals(v.name)&&old.player.equals(v.player))return;ep.variants.add(v);}
    private static HashMap<String,String> animetkaHeaders(){HashMap<String,String> h=new HashMap<>();h.put("Accept","application/json,text/plain,*/*");h.put("Accept-Language","ru-RU,ru;q=0.9,en;q=0.5");h.put("Origin","https://animetka.com");h.put("Referer","https://animetka.com/");h.put("User-Agent","Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Mobile Safari/537.36");return h;}

    private Anime.Page anidubCatalog(String search,int page)throws Exception{Anime.Page out=new Anime.Page();out.page=page;String q=search==null?"":search.trim();String url=q.isEmpty()?(page<=1?"https://online.anidub.com/":"https://online.anidub.com/page/"+page+"/"):query("https://online.anidub.com/index.php",params("do","search","subaction","search","story",q));Document doc=Jsoup.parse(document(url),url);LinkedHashMap<String,Anime> map=new LinkedHashMap<>();for(Element a:doc.select("a[href]")){String href=absolute(url,a.attr("href"));if(href.isEmpty()||href.contains("/user/")||href.contains("/anidub_news/")||!Pattern.compile("/(\\d+)-[^/]+\\.html(?:$|[?#])").matcher(href).find())continue;Element scope=cardScope(a);String title=anchorTitle(a);if(title.isEmpty()||title.length()<2||title.matches("[+\\-]?[0-9.]+"))continue;Anime item=anidubShell(href,title,posterFrom(url,scope),scope==null?title:scope.text());if(q.isEmpty()||matchesQuery(item,q))putBetter(map,item);if(map.size()>=24)break;}out.items.addAll(map.values());out.more=q.isEmpty()&&out.items.size()>=18;return out;}
    private Anime anidubDetails(Anime base,boolean episodes)throws Exception{String url=sourceUrl(base);String html=document(url);Document doc=Jsoup.parse(html,url);Anime a=anidubShell(url,heading(doc,base.title),posterFrom(url,doc),doc.text());String desc=descriptionFrom(doc);if(!desc.isEmpty())a.description=desc;for(Element g:doc.select("a[href*=/xfsearch/genre/],a[href*=/genre/]") ){String t=cleanText(g.text());if(!t.isEmpty()&&!a.genres.contains(t))a.genres.add(t);}if(episodes){LinkedHashMap<String,Anime.Episode> map=new LinkedHashMap<>();anidubOptions(doc,html,url,"sel","Sibnet",map,a.id);anidubOptions(doc,html,url,"sel2","AniDub",map,a.id);anidubOptions(doc,html,url,"sel3","Stormo",map,a.id);if(map.isEmpty())anidubDirectFallback(a,html,url);else{a.episodeList.clear();a.episodeList.addAll(map.values());a.episodeList.sort(Comparator.comparingDouble(e->e.number));a.episodes=Math.max(a.episodes,a.episodeList.size());}}return remember(a);}



    private void anidubOptions(Document doc,String html,String page,String id,String player,LinkedHashMap<String,Anime.Episode> map,String baseId){for(Element o:doc.select("#"+id+" option"))anidubOption(page,player,o.attr("value"),o.text(),map,baseId);Matcher box=Pattern.compile("<select[^>]+id=[\\\"']"+Pattern.quote(id)+"[\\\"'][^>]*>(.*?)</select>",Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(html);while(box.find()){Matcher m=Pattern.compile("<option[^>]+value=[\\\"']([^\\\"']+)[\\\"'][^>]*>(.*?)</option>",Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(box.group(1));while(m.find())anidubOption(page,player,unescape(m.group(1)),plain(m.group(2)),map,baseId);}}
    private void anidubOption(String page,String suggested,String value,String label,LinkedHashMap<String,Anime.Episode> map,String baseId){String v=unescape(value);if(v.isEmpty())return;int cut=v.lastIndexOf('|');String raw=cut>0?v.substring(0,cut):v,num=cut>0?v.substring(cut+1):label;String provider=absolute(page,raw);if(provider.isEmpty())return;double n=numberIn(num+" "+label,map.size()+1);if(n<=0||!Double.isFinite(n))n=map.size()+1;String key=episodeParam(n);Anime.Episode ep=map.get(key);if(ep==null){ep=new Anime.Episode();ep.id=baseId+"-"+key;ep.number=n;ep.name="AniDub";ep.lazy="anidub";map.put(key,ep);}String h=hostName(provider).toLowerCase(Locale.ROOT),p=suggested;if(h.contains("sibnet"))p="Sibnet";else if(h.contains("stormo"))p="Stormo";else if(h.contains("ladony")||provider.contains("vid.php"))p="AniDub";Anime.Variant variant=new Anime.Variant("AniDub",p,provider);variant.displayName="AniDub · "+p;addVariant(ep,variant);}
    private void anidubDirectFallback(Anime a,String html,String page){Matcher m=Pattern.compile("https?:\\\\?/\\\\?/[^\\\"'<>\\s]+?(?:\\.m3u8|\\.mp4)[^\\\"'<>\\s]*",Pattern.CASE_INSENSITIVE).matcher(html);Anime.Episode ep=null;while(m.find()){String safe=safeUrl(m.group().replace("\\/","/"));if(safe.isEmpty())continue;if(ep==null){ep=new Anime.Episode();ep.id=a.id+"-1";ep.number=1;ep.name="AniDub";a.episodeList.add(ep);}putStream(ep,VideoResolver.qualityOf(safe),safe);}if(ep!=null){a.episodes=Math.max(a.episodes,1);return;}Matcher iframe=Pattern.compile("<(?:iframe|embed)[^>]+src=[\\\"']([^\\\"']+)[\\\"']",Pattern.CASE_INSENSITIVE).matcher(html);while(iframe.find()){String u=embed(absolute(page,iframe.group(1)));if(u.isEmpty())continue;if(ep==null){ep=new Anime.Episode();ep.id=a.id+"-1";ep.number=1;ep.name="AniDub";ep.lazy="anidub";a.episodeList.add(ep);}Anime.Variant v=new Anime.Variant("AniDub",hostName(u),u);v.displayName="AniDub · "+hostName(u);addVariant(ep,v);}if(ep!=null)a.episodes=Math.max(a.episodes,1);}
    private static boolean badTitle(String title){String t=title==null?"":title.trim();if(t.length()<2||t.length()>120)return true;if(!Pattern.compile("[\\p{L}]").matcher(t).find())return true;String compact=t.replaceAll("[\\s_.-]","");boolean cyr=Pattern.compile("[А-Яа-яЁё]").matcher(t).find();boolean token=compact.length()>18&&compact.matches("[A-Za-z0-9+/=_]+")&&compact.matches(".*[0-9+/=_].*");return token&&!cyr;}
    private static Anime anidubShell(String url,String title,String poster,String meta){Anime a=new Anime();a.source="anidub";Matcher m=Pattern.compile("/(\\d+)-[^/]+\\.html").matcher(url);a.id=m.find()?m.group(1):stableId(url);a.alias=safeUrl(url);fillNames(a,title);a.poster=safeUrl(poster);a.year=yearIn(meta);a.episodes=episodesIn(meta+" "+title);a.status=meta!=null&&meta.toLowerCase(Locale.ROOT).contains("онгоинг")?"ongoing":"released";return a;}
    private static void fillNames(Anime a,String title){String t=cleanTitle(title);if(t.isEmpty())t="Аниме";String[] parts=t.split("\\s*/\\s*",2);a.title=parts[0].trim();if(parts.length>1)a.original=parts[1].replaceAll("\\s*\\[[^\\]]*\\]\\s*$","").trim();}
    private static String cleanTitle(String raw){String t=plain(raw).replace('\u00a0',' ').trim();if(t.contains("\n"))for(String row:t.split("\\r?\\n")){row=row.trim();if(row.length()>1){t=row;break;}}t=t.replaceAll("\\s+"," ").trim();t=t.replaceFirst("(?iu)^смотреть\\s+","").replaceFirst("(?iu)^постер\\s+аниме\\s+","");t=t.replaceAll("(?iu)\\s+все\\s+серии(?:\\s+и\\s+сезоны)?$","");t=t.replaceAll("\\s*\\[[^\\]]*\\]\\s*$","");return t.trim();}
    private static String cleanText(String raw){return plain(raw).replace('\u00a0',' ').replaceAll("\\s+"," ").trim();}
    private static String anchorTitle(Element a){String[] values={a.attr("title"),a.select("img[alt]").attr("alt"),a.ownText(),a.text()};for(String v:values){String t=cleanTitle(v);if(!t.isEmpty()&&!t.equalsIgnoreCase("смотреть")&&!t.matches("[+\\-]?[0-9.]+"))return t;}return "";}
    private static Element cardScope(Element a){Element s=a;for(int i=0;i<5&&s!=null;i++){String cls=s.className().toLowerCase(Locale.ROOT);if(cls.contains("short")||cls.contains("th-")||cls.contains("item")||cls.contains("movie")||cls.contains("anime")||cls.contains("story")||!s.select("img[src]").isEmpty())return s;s=s.parent();}return a.parent()==null?a:a.parent();}
    private static String posterFrom(String base,Element scope){if(scope==null)return "";String best="";for(Element img:scope.select("img[src],img[data-src],img[data-original]")){String src=first(first(img.attr("data-src"),img.attr("data-original")),img.attr("src"));String safe=absolute(base,src);String low=safe.toLowerCase(Locale.ROOT);if(safe.isEmpty()||low.contains("logo")||low.contains("banner")||low.contains("avatar")||low.contains("transparent"))continue;best=safe;if(low.contains("poster")||low.contains("uploads/posts")||low.contains("previews"))break;}if(!best.isEmpty())return best;Matcher bg=Pattern.compile("url\\(['\\\"]?([^)'\\\"]+)",Pattern.CASE_INSENSITIVE).matcher(scope.attr("style"));return bg.find()?absolute(base,bg.group(1)):"";}
    private static String heading(Document doc,String fallback){for(Element h:doc.select("h1,h2,h3")){String t=cleanTitle(h.text());String l=t.toLowerCase(Locale.ROOT);if(t.length()>2&&!l.startsWith("описание")&&!l.contains("комментар")&&!l.contains("смотреть онлайн"))return t;}String title=cleanTitle(doc.title());return title.isEmpty()?fallback:title.replaceAll("(?iu)\\s+смотреть.*$","").trim();}
    private static String descriptionFrom(Document doc){for(String sel:new String[]{"[itemprop=description]",".description",".full-text",".story",".quote",".entry","p"})for(Element e:doc.select(sel)){String t=cleanText(e.text());String l=t.toLowerCase(Locale.ROOT);if(t.length()>80&&!l.contains("зарегистриру")&&!l.contains("комментар")&&!l.contains("донат"))return t.length()>1200?t.substring(0,1200):t;}return "";}
    private void putBetter(LinkedHashMap<String,Anime> map,Anime a){if(!Anime.valid(a))return;Anime old=map.get(a.id);if(old==null||a.title.length()<old.title.length()||old.poster.isEmpty()&&!a.poster.isEmpty())map.put(a.id,remember(a));}
    private static boolean matchesQuery(Anime a,String q){String n=plainName(q);if(n.isEmpty())return true;String title=plainName(a.title+" "+a.original+" "+a.alias);return title.contains(n)||n.contains(plainName(a.title))||(!a.original.isEmpty()&&n.contains(plainName(a.original)));}
    private static String sourceUrl(Anime base)throws Exception{String u=safeUrl(base.alias);if(!u.isEmpty())return u;throw new IOException("У каталога нет адреса страницы");}
    private static String stableId(String value){long h=Integer.toUnsignedLong((value==null?"":value).hashCode());return String.valueOf(1000000000L+h%8999999999L);}
    private static int yearIn(String text){Matcher m=Pattern.compile("(?:^|[^0-9])((?:19|20)[0-9]{2})(?:[^0-9]|$)").matcher(text==null?"":text);try{return m.find()?Integer.parseInt(m.group(1)):0;}catch(Exception e){return 0;}}
    private static int episodesIn(String text){String s=text==null?"":text;String[] patterns={"из\\s*(\\d{1,4})","(\\d{1,4})\\s*сер(?:ия|ии|ий)","Серии?:\\s*[^0-9]*(\\d{1,4})"};for(String p:patterns){Matcher m=Pattern.compile(p,Pattern.CASE_INSENSITIVE|Pattern.UNICODE_CASE).matcher(s);if(m.find())try{return Integer.parseInt(m.group(1));}catch(Exception ignored){}}return 0;}
    private static String episodeTitle(String text,int fallback){String t=cleanText(text);if(t.isEmpty())return "Серия "+fallback;t=t.replaceFirst("(?iu)^смотреть\\s+","");return t.length()>120?t.substring(0,120):t;}
    private static String latinSlug(String text){String s=(text==null?"":text).toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-").replaceAll("^-+|-+$","");return s.matches(".*[a-z].*")?s:"";}
    private static String findText(String input,String regex){Matcher m=Pattern.compile(regex,Pattern.CASE_INSENSITIVE|Pattern.UNICODE_CASE|Pattern.DOTALL).matcher(input==null?"":input);return m.find()?cleanText(unescape(m.group(1))):"";}
    private static String unescape(String s){return s==null?"":s.replace("&quot;","\"").replace("&#34;","\"").replace("&#039;","'").replace("&amp;","&").replace("\\/","/");}

    private Anime.Page animelib4kCatalog(String search,int page,Filter f)throws Exception{Anime.Page base=catalog("animelib",search,page,f);Anime.Page out=new Anime.Page();out.page=base.page;out.total=base.total;out.more=base.more;for(Anime a:base.items){Anime copy=Anime.from(a.json());copy.source="animelib4k";out.items.add(remember(copy));}return out;}
    private Anime.Page kodikCatalog(String search,int page,Filter f)throws Exception{Anime.Page base=catalog("shikimori",search,page,f);Anime.Page out=new Anime.Page();out.page=base.page;out.total=base.total;out.more=base.more;for(Anime a:base.items)out.items.add(remember(kodikShell(a)));return out;}
    private Anime kodikShell(Anime base){Anime a=new Anime();a.source="kodik";a.id=String.valueOf(base.malId>0?base.malId:base.id.matches("\\d+")?Integer.parseInt(base.id):(int)(1L+(Integer.toUnsignedLong(base.key().hashCode())%999999999L)));a.title=base.title;a.original=base.original;a.alias=base.alias;a.poster=base.poster;a.description=base.description;a.year=base.year;a.type=base.type;a.status=base.status;a.age=base.age;a.episodes=base.episodes;a.malId=base.malId>0?base.malId:parseInt(base.id);a.anilistId=base.anilistId;a.kpId=base.kpId;a.libriaAlias=base.libriaAlias;a.score=base.score;a.genres.addAll(base.genres);return a;}
    private Anime kodikDetails(Anime base,boolean episodes)throws Exception{Anime shell=kodikShell(base);if(shell.description.isEmpty()||shell.poster.isEmpty()){try{Anime sh=new Anime();sh.source="shikimori";sh.id=String.valueOf(shell.malId>0?shell.malId:parseInt(shell.id));sh.title=shell.title;sh.original=shell.original;Anime full=details(sh,false);shell=kodikShell(full);}catch(Exception ignored){}}if(episodes){int mal=shell.malId>0?shell.malId:parseInt(shell.id);String url=directKodik(mal);int count=Math.max(1,Math.min(250,shell.episodes>0?shell.episodes:1));for(int i=1;i<=count;i++){Anime.Episode ep=new Anime.Episode();ep.id=shell.id+"-"+i;ep.number=i;ep.name="";ep.lazy="kodik";ep.resolverUrl=Uri.parse(url).buildUpon().appendQueryParameter("episode",String.valueOf(i)).build().toString();ep.variants.add(new Anime.Variant("","YORU Prime",ep.resolverUrl));shell.episodeList.add(ep);}}return remember(shell);}
    private static int parseInt(String s){try{return Integer.parseInt(s==null?"0":s.replaceAll("\\D+",""));}catch(Exception e){return 0;}}
    private Anime findAniLiberty(Anime a)throws Exception{normalizeIds(a);Anime y=null;try{y=findYummy(a);}catch(Exception ignored){}String alias=a.libriaAlias.isEmpty()?(y==null?"":y.libriaAlias):a.libriaAlias;if(!alias.isEmpty())return libriaAnime(get("https://anilibria.top/api/v1/anime/releases/"+enc(alias)));return searchSource(a,"anilibria");}
    private Anime searchSource(Anime a,String source)throws Exception{for(String term:searchTerms(a)){Anime.Page page=catalog(source,term,1,new Filter());for(Anime item:page.items)if(matchesAnime(item,a))return item;}return null;}
    private static boolean matchesAnime(Anime candidate,Anime base){if(candidate==null||base==null)return false;if(candidate.malId>0&&base.malId>0&&candidate.malId==base.malId)return true;if(candidate.anilistId>0&&base.anilistId>0&&candidate.anilistId==base.anilistId)return true;String bt=plainName(base.title),bo=plainName(base.original),ct=plainName(candidate.title),co=plainName(candidate.original);boolean title=(!bt.isEmpty()&&(bt.equals(ct)||bt.equals(co)))||(!bo.isEmpty()&&(bo.equals(ct)||bo.equals(co)));if(!title&&("anidub".equals(candidate.source)))title=(!bt.isEmpty()&&(ct.contains(bt)||bt.contains(ct)))||(!bo.isEmpty()&&(co.contains(bo)||bo.contains(co)||ct.contains(bo)));return title&&(base.year==0||candidate.year==0||Math.abs(base.year-candidate.year)<=1);}
    private static LinkedHashSet<String> searchTerms(Anime a){LinkedHashSet<String> terms=new LinkedHashSet<>();ArrayList<String> raw=new ArrayList<>();if(a!=null){raw.add(a.title);raw.add(a.original);raw.add(a.alias);}for(String value:raw){if(value==null)continue;String v=value.trim();if(v.isEmpty()||v.length()>160||v.contains("/")&&v.startsWith("http"))continue;addSearchTerm(terms,v);addSearchTerm(terms,trimSearchNoise(v));int cut=v.indexOf('/');if(cut>1)addSearchTerm(terms,v.substring(0,cut));Matcher m=Pattern.compile("(.+?)(?:\\s+[-–—:]\\s+.+)$").matcher(v);if(m.find())addSearchTerm(terms,m.group(1));}if(terms.isEmpty()&&a!=null)addSearchTerm(terms,YoruBrain.title(a));LinkedHashSet<String> limited=new LinkedHashSet<>();for(String t:terms){limited.add(t);if(limited.size()>=8)break;}return limited;}
    private static void addSearchTerm(LinkedHashSet<String> terms,String value){String v=cleanTitle(value);v=v.replaceAll("(?iu)\\b(смотреть|онлайн|аниме|все серии|озвучка|субтитры)\\b","").replaceAll("\\s+"," ").trim();if(v.length()>=2&&v.length()<=120&&Pattern.compile("[\\p{L}]").matcher(v).find())terms.add(v);}
    private static String trimSearchNoise(String value){String v=cleanTitle(value);v=v.replaceAll("\\s*\\([^)]*\\)\\s*"," ").replaceAll("\\s*\\[[^]]*]\\s*"," ");v=v.replaceAll("(?iu)\\b(tv|ova|ona|movie|special|season|фильм|спешл|сезон)\\b"," ");v=v.replaceAll("(?iu)\\b[0-9]+(?:st|nd|rd|th)?\\s*(season|сезон)\\b"," ").replaceAll("\\s+"," ").trim();return v;}
    private static boolean sameEpisode(double a,double b){return Math.abs(a-b)<0.001;}
    private static String episodeParam(double n){return sameEpisode(n,Math.floor(n))?String.valueOf((int)Math.floor(n)):String.valueOf(n);}
    public static String downloadSourceName(String id){String name=sourceNames.get(id);if(name!=null)return name;if("kodik".equals(id))return "YORU Prime";if("animelib4k".equals(id))return "AniLib Ultra";if("player".equals(id))return "Вариант";return id==null||id.isEmpty()?"YORU":"YORU Link";}
    public static String cleanLabel(String value){String v=value==null?"":value.trim();if(v.isEmpty())return "";String l=v.toLowerCase(Locale.ROOT);if(l.contains("kodik")||l.contains("aniqit"))return "YORU Prime";if(l.contains("yummy")||l.contains("yani")||l.contains("cvh")||l.contains("cdnvideohub"))return "YORU Max";if(l.equals("player")||l.equals("плеер"))return "Вариант";return v.replace("Kodik","YORU Prime").replace("kodik","YORU Prime");}
    private static int downloadSourceRank(String id){if("yoru".equals(id))return -1;if("yummy".equals(id))return 0;if("animevost".equals(id))return 1;if("anidub".equals(id))return 2;if("animelib4k".equals(id))return 3;if("anilibria".equals(id))return 4;if("animelib".equals(id))return 5;if("animedia".equals(id))return 6;if("animetka".equals(id))return 7;if("kodik".equals(id))return 8;return 20;}
    private static void normalizeIds(Anime a){if(a!=null&&a.malId==0&&"shikimori".equals(a.source))try{a.malId=Integer.parseInt(a.id);}catch(Exception ignored){}}
    private Anime findYummy(Anime a)throws Exception{normalizeIds(a);String url=a.malId>0?"https://api.yani.tv/anime?shikimori_ids="+a.malId+"&limit=20":"https://api.yani.tv/anime?q="+enc(a.title)+"&limit=20";JSONArray rows=get(url).optJSONArray("response");Anime found=null;for(int i=0;rows!=null&&i<rows.length();i++){Anime y=yummyAnime(rows.getJSONObject(i));if(a.malId>0){JSONObject remote=rows.getJSONObject(i).optJSONObject("remote_ids");if(remote!=null&&(remote.optInt("myanimelist_id")==a.malId||remote.optInt("shikimori_id")==a.malId))return remember(y);}if(a.malId==0&&plainName(y.title).equals(plainName(a.title))&&(a.year==0||a.year==y.year)){if(found!=null&&found.malId!=y.malId)return null;found=y;}}return found==null?null:remember(found);}
    private Anime findAniLib(Anime a)throws Exception{normalizeIds(a);Anime best=null;for(String q:searchTerms(a)){Anime.Page page=catalog("animelib",q,1,new Filter());for(Anime item:page.items){if(!matchesAnime(item,a))continue;Anime full=details(item,false);if(a.malId>0&&full.malId==a.malId)return item;if(a.anilistId>0&&full.anilistId==a.anilistId)return item;if(best==null)best=item;}}return best;}
    private JSONObject animelibDetail(String slug,Anime base)throws Exception{String fields="?fields[]=genres&fields[]=releaseDate&fields[]=shiki_id&fields[]=anilist_id&fields[]=rate&fields[]=rate_avg";String resolved=slug;if(parseInt(slug)>0&&!slug.contains("--")){String found=animelibSlug(base);if(!found.isEmpty())resolved=found;}try{return get("https://api.cdnlibs.org/api/anime/"+enc(resolved)+fields);}catch(Exception first){String found=animelibSlug(base);if(!found.isEmpty()&&!found.equals(resolved))return get("https://api.cdnlibs.org/api/anime/"+enc(found)+fields);throw first;}}
    private String animelibSlug(Anime base){try{if(base==null)return "";if(base.alias!=null&&!base.alias.isEmpty()&&base.alias.contains("--"))return base.alias;for(String q:searchTerms(base)){Anime.Page page=catalog("animelib",q,1,new Filter());for(Anime item:page.items){if(item.id.equals(base.id)||matchesAnime(item,base))return item.alias;}}}catch(Exception ignored){}return "";}
    private int resolveMal(Anime a)throws Exception{if(a.malId>0)return a.malId;Anime y=findYummy(a);if(y!=null&&y.malId>0){a.malId=y.malId;a.kpId=y.kpId;return y.malId;}throw new IOException("Не удалось найти просмотр. Попробуйте открыть карточку позже.");}
    private int resolveKp(Anime a)throws Exception{if(a.kpId>0)return a.kpId;Anime y=findYummy(a);if(y!=null&&y.kpId>0){a.kpId=y.kpId;return y.kpId;}throw new IOException("У этого просмотра пока нет подходящего варианта.");}
    private synchronized String token()throws Exception{if(!publicToken.isEmpty()&&System.currentTimeMillis()-tokenAt<300000)return publicToken;String script=request("https://kodik-add.com/add-players.min.js?v=2","GET",null,false);String[] patterns={"token\\s*=\\s*[\"\\\']([A-Za-z0-9]{16,120})[\"\\\']","[\"\\\']token[\"\\\']\\s*:\\s*[\"\\\']([A-Za-z0-9]{16,120})[\"\\\']","token=\\\\?[\"\\\']([A-Za-z0-9]{16,120})[\"\\\']"};for(String pattern:patterns){Matcher m=Pattern.compile(pattern).matcher(script);if(m.find()){publicToken=m.group(1);tokenAt=System.currentTimeMillis();return publicToken;}}throw new IOException("Просмотр временно недоступен");}
    public String directKodik(int mal)throws Exception{if(mal<=0)throw new IOException("Не удалось найти аниме в этом каталоге");String q=query("https://kodik-api.com/get-player",params("title","Player","hasPlayer","false","url","https://kodikdb.com/find-player?shikimoriID="+mal,"token",token(),"shikimoriID",String.valueOf(mal)));JSONObject j=get(q);if(j.has("error")||!j.optBoolean("found"))throw new IOException("У этого каталога пока нет просмотра");if(j.has("allowed")&&j.optInt("allowed",1)==0)throw new IOException("Просмотр временно ограничен");String u=embed(j.optString("link"));if(u.isEmpty())throw new IOException("Просмотр временно недоступен");return u;}
    private String regional(String source,int kp)throws Exception{if(source.equals("flixcdn"))return "https://tarantino.factorios.live/show/kinopoisk/"+kp;if(source.equals("gendit"))return "https://horsez.org/lat/"+kp;JSONObject root=get("https://fbphdplay.top/api/players?kinopoisk="+kp);JSONArray list=root.optJSONArray("data");for(int i=0;list!=null&&i<list.length();i++){JSONObject j=list.getJSONObject(i);if(j.optString("type").equalsIgnoreCase(source)){String url=safeUrl(j.optString("iframeUrl"));if(!url.isEmpty())return url;}}throw new IOException("Просмотр пока недоступен для этого аниме");}
    public static String embed(String input){if(input==null)return "";String s=input.trim().replace("&amp;","&");Matcher html=Pattern.compile("src=[\"']([^\"']+)",Pattern.CASE_INSENSITIVE).matcher(s);if(html.find())s=html.group(1);if(s.startsWith("//"))s="https:"+s;try{Uri u=Uri.parse(s);String host=u.getHost();if(host!=null&&Arrays.asList("aniqit.com","kodik.info","kodik.cc","kodik.biz").contains(host))s=u.buildUpon().scheme("https").authority("kodikplayer.com").build().toString();return safeUrl(s);}catch(Exception e){return "";}}
    private static String absolute(String base,String value){try{if(value==null||value.trim().isEmpty())return "";value=value.trim().replace(" ","%20").replace("&amp;","&");if(value.startsWith("//"))value="https:"+value;return safeUrl(new URL(new URL(base),value).toString());}catch(Exception e){return "";}}
    private static String hostName(String link){try{String h=Uri.parse(link.startsWith("//")?"https:"+link:link).getHost();return h==null?"Вариант":h.replace("www.","");}catch(Exception e){return "Вариант";}}
    static String plain(String text){return Html.fromHtml(text==null?"":text,Html.FROM_HTML_MODE_LEGACY).toString().replaceAll("\\[/?[^\\]]+\\]","").trim();}
    static String plainName(String text){return (text==null?"":text).toLowerCase(Locale.ROOT).replaceAll("[^\\p{L}\\p{N}]+"," ").trim();}
    private static double numberIn(String text,double fallback){Matcher m=Pattern.compile("[0-9]+(?:\\.[0-9]+)?").matcher(text);try{return m.find()?Double.parseDouble(m.group()):fallback;}catch(Exception e){return fallback;}}
    private static void putStream(Anime.Episode ep,int q,String url){String s=safeUrl(url);if(!s.isEmpty())ep.streams.put(q,s);}
    private static void genres(Anime a,JSONArray rows,String name){for(int i=0;rows!=null&&i<rows.length();i++){Object g=rows.opt(i);if(g instanceof JSONObject){String value=((JSONObject)g).optString(name,((JSONObject)g).optString("name",""));if(!value.isEmpty()&&!a.genres.contains(value))a.genres.add(value);}else if(g instanceof String&&!a.genres.contains((String)g))a.genres.add((String)g);}}





    private static Anime animetkaAnime(JSONObject j){Anime a=new Anime();a.source="animetka";a.id=j.optString("animetka_id",j.optString("id"));a.title=j.optString("anime_title",j.optString("title","Аниме"));if(a.title.isEmpty())a.title=j.optString("title","Аниме");a.original=j.optString("title_orig",j.optString("title_en",""));a.alias=j.optString("title_en","");a.description=plain(j.optString("anime_description",j.optString("description","")));String poster=j.optString("anime_poster_url",j.optString("poster_url",""));a.poster=safeUrl(poster);a.year=j.optInt("year");a.type=kind(j.optString("anime_kind",j.optString("kind","")));a.status=j.optString("all_status",j.optString("anime_status",""));int age=j.optInt("minimal_age",0);a.age=age>0?age+"+":j.optString("rating_mpaa","");a.episodes=j.optInt("episodes_total",j.optInt("episodes",0));a.score=j.optDouble("shikimori_rating",j.optDouble("rating",0));if(!Double.isFinite(a.score))a.score=0;a.malId=j.optInt("shikimori_id",j.optInt("malId",0));a.kpId=j.optInt("kinopoisk_id",j.optInt("kp_id",0));genres(a,j.optJSONArray("anime_genres"),"name");genres(a,j.optJSONArray("all_genres"),"name");genres(a,j.optJSONArray("Genres"),"name");return a;}

    private static Anime shikiAnime(JSONObject j){Anime a=new Anime();a.source="shikimori";a.id=j.optString("id");a.malId=j.optInt("malId",0);if(a.malId==0)try{a.malId=Integer.parseInt(a.id);}catch(Exception ignored){}a.title=j.optString("russian","");if(a.title.isEmpty())a.title=j.optString("name","Аниме");a.original=j.optString("name","");a.type=kind(j.optString("kind"));a.status=j.optString("status");a.episodes=j.optInt("episodes");a.score=j.optDouble("score",0);JSONObject date=j.optJSONObject("airedOn"),poster=j.optJSONObject("poster");a.year=date==null?0:date.optInt("year");a.poster=poster==null?"":safeUrl(poster.optString("mainUrl",poster.optString("originalUrl")));a.age=j.optString("rating").equals("pg_13")?"13+":j.optString("rating").startsWith("r")?"18+":"";JSONArray studios=j.optJSONArray("studios");if(studios!=null&&studios.length()>0)a.studio=studios.optJSONObject(0)==null?"":studios.optJSONObject(0).optString("name","");genres(a,j.optJSONArray("genres"),"russian");return a;}
    private static Anime vostAnime(JSONObject j){Anime a=new Anime();a.source="animevost";a.id=j.optString("id");String raw=j.optString("title","Аниме"),clean=raw.replaceAll("\\s*\\[[^\\]]*\\]\\s*$","");String[] names=clean.split(" / ",2);a.title=names[0];a.original=names.length>1?names[1]:"";a.description=plain(j.optString("description"));a.poster=safeUrl(j.optString("urlImagePreview"));a.year=j.optInt("year");a.type=j.optString("type","Аниме");Matcher m=Pattern.compile("из\\s*(\\d+)").matcher(raw);if(m.find())a.episodes=Integer.parseInt(m.group(1));a.status="published";for(String g:j.optString("genre","").split(","))if(!g.trim().isEmpty()&&!a.genres.contains(g.trim()))a.genres.add(g.trim());return a;}
    private static Anime yummyAnime(JSONObject j){Anime a=new Anime();a.source="yummy";a.id=j.optString("anime_id");a.title=j.optString("title","Аниме");a.alias=j.optString("anime_url");a.year=j.optInt("year");a.description=plain(j.optString("description"));JSONObject p=j.optJSONObject("poster"),type=j.optJSONObject("type"),age=j.optJSONObject("min_age"),rat=j.optJSONObject("rating"),ids=j.optJSONObject("remote_ids"),eps=j.optJSONObject("episodes"),status=j.optJSONObject("anime_status");a.poster=p==null?"":safeUrl(p.optString("medium",p.optString("fullsize")));a.type=type==null?"Аниме":type.optString("shortname","Аниме");a.age=age==null?"":age.optString("title");a.score=rat==null?0:rat.optDouble("average",0);a.status=status==null?"":status.optString("alias");a.episodes=eps==null?j.optInt("ep_count"):eps.optInt("count");a.malId=ids==null?0:ids.optInt("myanimelist_id");if(a.malId<=0&&ids!=null)a.malId=ids.optInt("shikimori_id");a.kpId=ids==null?0:ids.optInt("kp_id");a.libriaAlias=ids==null?"":ids.optString("anilibria_alias","");a.blocked=j.optBoolean("blocked",false);genres(a,j.optJSONArray("genres"),"title");return a;}
    private static String animelibCover(JSONObject cover,String id){if(cover==null)return "";String[] keys={"default","md","thumbnail","filename","url","src"};for(String key:keys){String u=animelibCoverUrl(cover.optString(key,""));if(!u.isEmpty())return u;}JSONObject optimized=cover.optJSONObject("optimized");if(optimized!=null)for(String key:keys){String u=animelibCoverUrl(optimized.optString(key,""));if(!u.isEmpty())return u;}JSONObject images=cover.optJSONObject("images");if(images!=null)for(String key:keys){String u=animelibCoverUrl(images.optString(key,""));if(!u.isEmpty())return u;}return animelibCoverUrl(id==null?"":cover.optString("path",id));}
    private static String animelibCoverUrl(String raw){String s=raw==null?"":raw.trim().replace("\\/","/").replace(" ","%20");if(s.isEmpty()||s.equalsIgnoreCase("null"))return "";if(s.startsWith("http://")||s.startsWith("https://"))return safeUrl(s);if(s.startsWith("//"))return safeUrl("https:"+s);if(s.startsWith("/"))return safeUrl("https://cover.cdnlibs.org"+s);return safeUrl("https://cover.cdnlibs.org/"+s.replaceAll("^/+",""));}
    private static Anime amAnime(JSONObject j){Anime a=new Anime();a.source="animelib";a.id=j.optString("id");a.title=j.optString("rus_name",j.optString("name","Аниме"));a.original=j.optString("name",j.optString("eng_name",""));a.alias=j.optString("slug_url",a.id);JSONObject p=j.optJSONObject("cover"),type=j.optJSONObject("type"),age=j.optJSONObject("ageRestriction"),rating=j.optJSONObject("rating"),status=j.optJSONObject("status"),episodes=j.optJSONObject("episodes");a.poster=animelibCover(p,j.optString("id"));try{a.year=Integer.parseInt(j.optString("releaseDate","").substring(0,4));}catch(Exception ignored){}a.type=type==null?"Аниме":type.optString("label");a.age=age==null?"":age.optString("label");a.score=rating==null?j.optDouble("shiki_rate",0):rating.optDouble("average",0);JSONObject studio=j.optJSONObject("studio");if(studio!=null)a.studio=studio.optString("name",studio.optString("title",""));a.status=status!=null&&status.optInt("id")==1?"ongoing":"released";a.malId=j.optInt("shiki_id",parseTrailingId(j.optString("shikimori_href",j.optString("shiki_href",""))));a.anilistId=j.optInt("anilist_id",parseTrailingId(j.optString("anilist_href","")));a.blocked=j.optBoolean("is_licensed",false);a.description=plain(first(j.optString("description",""),prose(j.opt("summary"),0)));a.episodes=episodes==null?j.optInt("episodes_count",0):episodes.optInt("count",0);genres(a,j.optJSONArray("genres"),"name");return a;}
    private static String first(String a,String b){return a!=null&&!a.isEmpty()?a:b==null?"":b;}
    private static String prose(Object value,int depth){if(value==null||depth>12)return "";if(value instanceof String)return plain((String)value);if(!(value instanceof JSONObject))return "";JSONObject j=(JSONObject)value;if(j.has("text"))return j.optString("text");StringBuilder s=new StringBuilder();JSONArray a=j.optJSONArray("content");for(int i=0;a!=null&&i<a.length();i++){s.append(prose(a.opt(i),depth+1));if(j.optString("type").equals("doc"))s.append("\n\n");}return s.toString().trim();}
    private static int parseTrailingId(String value){try{Matcher m=Pattern.compile("(\\d+)(?:/)?$").matcher(value==null?"":value);return m.find()?Integer.parseInt(m.group(1)):0;}catch(Exception e){return 0;}}
    private static Anime libriaAnime(JSONObject j){Anime a=new Anime();a.source="anilibria";a.id=j.optString("id");JSONObject name=j.optJSONObject("name"),poster=j.optJSONObject("poster"),type=j.optJSONObject("type"),age=j.optJSONObject("age_rating");a.title=name==null?"Аниме":name.optString("main","Аниме");a.original=name==null?"":name.optString("english");a.alias=j.optString("alias");a.year=j.optInt("year");a.type=type==null?"Аниме":type.optString("description","Аниме");JSONObject opt=poster==null?null:poster.optJSONObject("optimized");String path=opt==null?(poster==null?"":poster.optString("preview")):opt.optString("preview");a.poster=path.startsWith("/")?"https://anilibria.top"+path:safeUrl(path);a.age=age==null?"":age.optString("label");a.description=plain(j.optString("description"));a.episodes=j.optInt("episodes_total");a.status=j.optBoolean("is_ongoing")?"ongoing":"released";a.blocked=j.optBoolean("is_blocked_by_geo")||j.optBoolean("is_blocked_by_copyrights");genres(a,j.optJSONArray("genres"),"name");JSONArray eps=j.optJSONArray("episodes");for(int i=0;eps!=null&&i<eps.length();i++){JSONObject e=eps.optJSONObject(i);if(e==null)continue;Anime.Episode ep=new Anime.Episode();ep.id=e.optString("id");ep.number=e.optDouble("ordinal");ep.name=e.optString("name");ep.duration=e.optInt("duration");putStream(ep,480,e.optString("hls_480"));putStream(ep,720,e.optString("hls_720"));putStream(ep,1080,e.optString("hls_1080"));JSONObject op=e.optJSONObject("opening");if(op!=null){ep.openingStart=op.optInt("start");ep.openingEnd=op.optInt("stop");}a.episodeList.add(ep);}a.episodeList.sort(Comparator.comparingDouble(e->e.number));return a;}
    private static String kind(String value){switch(value.toLowerCase(Locale.ROOT)){case "tv":case "tv_short":return "ТВ";case "movie":return "Фильм";case "ona":return "ONA";case "ova":return "OVA";case "special":case "tv_special":return "Спешл";case "music":return "Клип";default:return "Аниме";}}
}
