package app.yoru.mobile;

import android.content.Context;
import android.net.Uri;
import android.text.Html;
import org.jsoup.Jsoup;
import org.jsoup.nodes.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;

public final class ApiRepository {
    private static final String CHROME="Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Mobile Safari/537.36";
    public static final LinkedHashMap<String,String> sourceNames=new LinkedHashMap<>();
    private static final String[] REAL_SOURCES={"yummy","anilibria","animevost","animelib","animedia","shikimori"};
    static {sourceNames.put("all","Все источники");sourceNames.put("yummy","YummyAnime");sourceNames.put("anilibria","AniLiberty");sourceNames.put("animevost","AnimeVost");sourceNames.put("animelib","AniLib");sourceNames.put("animelib4k","AniLib 4K probe");sourceNames.put("animedia","AniMedia");sourceNames.put("animetka","Animetka");sourceNames.put("anidub","AniDub");sourceNames.put("jutsu","JutSu");sourceNames.put("shikimori","Shikimori");sourceNames.put("kodik","Kodik 2026");}
    public static final String[] PLAYER_IDS={"auto","yummy","anilibria","animevost","animelib","animelib4k","animedia","animetka","anidub","jutsu","kodik"};
    public static final String[] PLAYER_NAMES={"Все источники","YummyAnime","AniLiberty","AnimeVost","AniLib","AniLib 4K probe","AniMedia","Animetka","AniDub","JutSu","Kodik 2026"};
    private static final String SH_FIELDS="id malId name russian english kind rating score status episodes episodesAired airedOn{year date} poster{mainUrl originalUrl} genres{id russian name}";
    private final Context context;
    private final Map<String,Cache> cache=Collections.synchronizedMap(new LinkedHashMap<String,Cache>(32,.75f,true){protected boolean removeEldestEntry(Map.Entry<String,Cache> e){return size()>32;}});
    private final Map<String,Anime> known=Collections.synchronizedMap(new LinkedHashMap<>());
    private final ArrayList<Anime> seed=new ArrayList<>();
    private final java.util.concurrent.ConcurrentHashMap<String,Long> counts=new java.util.concurrent.ConcurrentHashMap<>();
    private String publicToken="";
    private long tokenAt;
    private static final class Cache {String text;long at;Cache(String t){text=t;at=System.currentTimeMillis();}}
    public static final class Filter {public String year="",genre="",type="",status="",sort="RATING_DESC",season="";}
    public ApiRepository(Context c){context=c.getApplicationContext();try{JSONObject boot=new JSONObject(readStream(context.getAssets().open("boot.json"),3*1024*1024));JSONArray rows=boot.optJSONArray("releases");for(int i=0;rows!=null&&i<rows.length();i++){Anime a=Anime.from(rows.getJSONObject(i));a.cached=true;if(a.id.equals("9542"))a.malId=52991;if(a.id.equals("9600"))a.malId=52299;if(a.id.equals("9555"))a.malId=54492;seed.add(a);known.put(a.key(),a);}}catch(Exception ignored){}try{JSONObject cs=new JSONObject(readStream(context.getAssets().open("counts.json"),100000));Iterator<String> it=cs.keys();while(it.hasNext()){String key=it.next();JSONObject row=cs.optJSONObject(key);long n=row==null?-1:row.optLong("value",-1);if(n>=0)counts.put(key,n);}}catch(Exception ignored){}}
    public long countOf(String source){if("all".equals(source)){long sum=0;for(String s:REAL_SOURCES){Long n=counts.get(s);if(n!=null&&n>0)sum+=n;}return sum>0?sum:-1;}Long n=counts.get(source);return n==null?-1:n;}
    public void clearMemory(){cache.clear();}
    public List<Anime> seed(){return new ArrayList<>(seed);}
    public Anime remember(Anime a){if(Anime.valid(a)){known.put(a.key(),a);if(known.size()>1800){synchronized(known){String first=known.keySet().iterator().next();known.remove(first);}}}return a;}
    public Anime known(String key){return known.get(key);}
    static String readStream(InputStream in,int max)throws IOException{try(InputStream input=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=input.read(b))!=-1){if(out.size()+n>max)throw new IOException("Слишком большой ответ источника");out.write(b,0,n);}return out.toString("UTF-8");}}
    public static String safeUrl(String value){if(value==null||value.trim().isEmpty())return "";value=value.trim().replace(" ","%20").replace("\\/","/").replace("&amp;","&");if(value.startsWith("//"))value="https:"+value;try{Uri u=Uri.parse(value);String h=u.getHost();if(h==null)return "";h=h.toLowerCase(Locale.ROOT);if("http".equals(u.getScheme())&&(h.equals("video.animetop.info")||h.equals("media.animetop.info")||h.equals("static.openni.ru")))u=u.buildUpon().scheme("https").build();String scheme=u.getScheme();if(!("https".equals(scheme)||"http".equals(scheme))||u.getUserInfo()!=null||(!h.contains("."))||h.equals("localhost")||h.endsWith(".local")||h.matches("^(127|10|0|192\\.168|169\\.254)\\..*")||h.matches("^172\\.(1[6-9]|2[0-9]|3[01])\\..*"))return "";return u.toString();}catch(Exception e){return "";}}
    String request(String url,String method,String body,boolean form)throws Exception{return request(url,method,body,form,null);}
    String request(String url,String method,String body,boolean form,Map<String,String> headers)throws Exception{
        String ck=method+" "+url+" "+(body==null?"":body)+" "+(headers==null?"":headers.toString());Cache hit=cache.get(ck);if(hit!=null&&System.currentTimeMillis()-hit.at<45000)return hit.text;
        String current=url;String currentMethod=method,currentBody=body;
        for(int redirect=0;redirect<5;redirect++){
            if(Thread.currentThread().isInterrupted())throw new InterruptedIOException();if(safeUrl(current).isEmpty())throw new IOException("Недопустимый адрес");
            URL target=new URL(current);String host=target.getHost()==null?"":target.getHost().toLowerCase(Locale.ROOT);HttpURLConnection c=(HttpURLConnection)target.openConnection();c.setConnectTimeout(6500);c.setReadTimeout(9500);c.setInstanceFollowRedirects(false);c.setRequestMethod(currentMethod);c.setRequestProperty("Accept","application/json,text/html;q=0.9,*/*;q=0.6");c.setRequestProperty("Accept-Language","ru-RU,ru;q=0.9,en;q=0.5");c.setRequestProperty("User-Agent",CHROME);
            if(headers!=null)for(Map.Entry<String,String> e:headers.entrySet())if(e.getKey()!=null&&e.getValue()!=null)c.setRequestProperty(e.getKey(),e.getValue());
            try{if(currentBody!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type",form?"application/x-www-form-urlencoded; charset=UTF-8":"application/json; charset=UTF-8");try(OutputStream out=c.getOutputStream()){out.write(currentBody.getBytes(StandardCharsets.UTF_8));}}
                int code=c.getResponseCode();if(code>=300&&code<400){String loc=c.getHeaderField("Location");if(loc==null)throw new IOException("Источник не ответил");current=new URL(new URL(current),loc).toString();if(code!=307&&code!=308){currentMethod="GET";currentBody=null;}continue;}
                if(code==429)throw new IOException("Источник временно ограничил частоту запросов. Попробуйте позже.");if(code<200||code>=300)throw new IOException("Источник сейчас недоступен. Попробуйте другой вариант.");String text=readStream(c.getInputStream(),12*1024*1024);if(text.length()<450000)cache.put(ck,new Cache(text));return text;
            }finally{c.disconnect();}
        }
        throw new IOException("Источник не ответил");
    }
    String document(String u)throws Exception{return request(u,"GET",null,false);}
    String formPage(String u,String body)throws Exception{return request(u,"POST",body,true);}
    private JSONObject get(String u)throws Exception{return new JSONObject(request(u,"GET",null,false));}
    private JSONObject postJson(String u,JSONObject j)throws Exception{return new JSONObject(request(u,"POST",j.toString(),false));}
    private JSONObject postForm(String u,String key,String value)throws Exception{return new JSONObject(request(u,"POST",enc(key)+"="+enc(value),true));}
    private static String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){return "";}}
    public static String query(String base,Map<String,String> params){StringBuilder s=new StringBuilder(base);for(Map.Entry<String,String> e:params.entrySet()){if(e.getValue()==null||e.getValue().isEmpty())continue;s.append(s.indexOf("?")>=0?'&':'?').append(enc(e.getKey())).append('=').append(enc(e.getValue()));}return s.toString();}
    private static LinkedHashMap<String,String> params(String...kv){LinkedHashMap<String,String> p=new LinkedHashMap<>();for(int i=0;i+1<kv.length;i+=2)p.put(kv[i],kv[i+1]);return p;}
    private JSONObject shiki(String q)throws Exception{JSONObject j=postJson("https://shikimori.io/api/graphql",new JSONObject().put("query",q));if(j.has("errors"))throw new IOException("Источник не ответил на запрос");return j.getJSONObject("data");}
    public Anime.Page catalog(String source,String search,int page,Filter f)throws Exception{
        if(f==null)f=new Filter();if(source==null||source.isEmpty())source="all";if(source.equals("all"))return allCatalog(search,page,f);if(source.equals("animedia"))return new NativeSources(this).catalog(source,search,page);if(source.equals("kodik"))return kodikCatalog(search,page,f);if(source.equals("animelib4k"))return animelib4kCatalog(search,page,f);if(source.equals("animetka"))return animetkaCatalog(search,page,f);if(source.equals("anidub"))return anidubCatalog(search,page);if(source.equals("jutsu"))return jutsuCatalog(search,page);
        Anime.Page out=new Anime.Page();out.page=page;JSONArray rows;String q=search==null?"":search.trim();int limit=24;
        if(source.equals("shikimori")){
            String args="limit:24,page:"+page+",order:"+(f.sort.equals("POPULARITY")?"popularity":"ranked")+",rating:\"!rx\"";
            if(!q.isEmpty())args+=",search:"+JSONObject.quote(q);if(!f.year.isEmpty())args+=",season:"+JSONObject.quote((f.season.isEmpty()?"":f.season+"_")+f.year);if(!f.genre.isEmpty())args+=",genre:"+JSONObject.quote(f.genre);if(!f.type.isEmpty())args+=",kind:"+JSONObject.quote(f.type.toLowerCase(Locale.ROOT));if(!f.status.isEmpty())args+=",status:"+JSONObject.quote(f.status);
            rows=shiki("{animes("+args+"){"+SH_FIELDS+"}}").optJSONArray("animes");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(shikiAnime(rows.getJSONObject(i))));out.more=rows!=null&&rows.length()==limit;
        }else if(source.equals("animevost")){
            JSONObject data=q.isEmpty()?get("https://api.animevost.org/v1/last?quantity=24&page="+page):postForm("https://api.animevost.org/v1/search","name",q);rows=data.optJSONArray("data");if(rows==null)rows=new JSONArray();if(q.isEmpty()){JSONObject st=data.optJSONObject("state");out.total=st==null?-1:st.optLong("count",-1);for(int i=0;i<rows.length();i++)out.items.add(remember(vostAnime(rows.getJSONObject(i))));out.more=out.total>page*24;}else{out.total=rows.length();for(int i=(page-1)*24;i<Math.min(rows.length(),page*24);i++)out.items.add(remember(vostAnime(rows.getJSONObject(i))));out.more=rows.length()>page*24;}
        }else if(source.equals("yummy")){
            Map<String,String> p=params("limit","24","offset",String.valueOf((page-1)*24),"q",q,"sort",f.sort.equals("YEAR_DESC")?"year":"rating","sort_forward","false","genres",f.genre,"from_year",f.year,"to_year",f.year,"types",f.type.toLowerCase(Locale.ROOT),"status",f.status.equals("anons")?"announcement":f.status);JSONObject data=get(query("https://api.yani.tv/anime",p));if(data.has("error"))throw new IOException("Источник сейчас недоступен");rows=data.optJSONArray("response");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(yummyAnime(rows.getJSONObject(i))));out.more=rows!=null&&rows.length()==24;
        }else if(source.equals("animelib")){
            Map<String,String> p=params("page",String.valueOf(page),"q",q,"sort_by",f.sort.equals("FRESH_AT_DESC")?"last_episode_at":"rate_avg");String u=query("https://api.cdnlibs.org/api/anime",p)+"&fields%5B%5D=rate&fields%5B%5D=rate_avg&fields%5B%5D=releaseDate";if(!f.status.isEmpty())u+="&status%5B%5D="+(f.status.equals("ongoing")?"1":"2");JSONObject data=get(u);rows=data.optJSONArray("data");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(amAnime(rows.getJSONObject(i))));JSONObject links=data.optJSONObject("links");out.more=links!=null&&!links.isNull("next")&&!links.optString("next","").isEmpty();
        }else if(source.equals("anilibria")){
            Map<String,String> p=params("limit","24","page",String.valueOf(page),"f[search]",q,"f[sorting]",f.sort.equals("POPULARITY")?"RATING_DESC":f.sort,"f[genres]",f.genre,"f[types]",f.type,"f[years][from_year]",f.year,"f[years][to_year]",f.year,"f[publish_statuses]",f.status.isEmpty()?"":f.status.equals("ongoing")?"IS_ONGOING":"IS_NOT_ONGOING");JSONObject data=get(query("https://anilibria.top/api/v1/anime/catalog/releases",p));rows=data.optJSONArray("data");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(libriaAnime(rows.getJSONObject(i))));JSONObject meta=data.optJSONObject("meta"),pg=meta==null?null:meta.optJSONObject("pagination");if(pg!=null){out.total=pg.optLong("total",-1);out.more=page<pg.optInt("total_pages");}
        }else throw new IOException("Неизвестный источник");
        if(out.total>=0&&q.isEmpty()&&f.genre.isEmpty()&&f.year.isEmpty()&&f.type.isEmpty()&&f.status.isEmpty())counts.put(source,out.total);return out;
    }
    private Anime.Page allCatalog(String search,int page,Filter f)throws Exception{Anime.Page out=new Anime.Page();out.page=page;LinkedHashMap<String,Anime> items=new LinkedHashMap<>();boolean more=false;int ok=0;ExecutorService pool=Executors.newFixedThreadPool(REAL_SOURCES.length);CompletionService<Anime.Page> done=new ExecutorCompletionService<>(pool);for(String source:REAL_SOURCES){final String src=source;done.submit(()->catalog(src,search,page,f));}long deadline=System.currentTimeMillis()+((search==null||search.trim().isEmpty())?5200:6500);try{for(int i=0;i<REAL_SOURCES.length;i++){long left=deadline-System.currentTimeMillis();if(left<=0)break;Future<Anime.Page> future=done.poll(left,TimeUnit.MILLISECONDS);if(future==null)break;try{Anime.Page p=future.get();ok++;more|=p.more;for(Anime a:p.items)items.put(a.key(),a);if(items.size()>=24&&ok>=2)break;}catch(Exception ignored){}}}finally{pool.shutdownNow();}out.items.addAll(items.values());out.more=more;if((search==null||search.trim().isEmpty())&&countOf("all")>0)out.total=countOf("all");if(out.items.isEmpty()&&ok==0)throw new IOException("Источники сейчас недоступны");return out;}
    public Anime details(Anime base,boolean episodes)throws Exception{
        if(base.source.equals("animedia"))return new NativeSources(this).details(base,episodes);
        Anime a;String id=base.id;
        switch(base.source){
            case "shikimori":{JSONArray rows=shiki("{animes(ids:"+JSONObject.quote(id)+",limit:1){"+SH_FIELDS+" descriptionHtml related{relationKind anime{"+SH_FIELDS+"}}}}").optJSONArray("animes");if(rows==null||rows.length()==0)throw new IOException("Аниме не найдено");JSONObject j=rows.getJSONObject(0);a=shikiAnime(j);a.description=plain(j.optString("descriptionHtml"));JSONArray rel=j.optJSONArray("related");for(int i=0;rel!=null&&i<rel.length();i++){JSONObject r=rel.getJSONObject(i).optJSONObject("anime");if(r!=null)a.related.add(remember(shikiAnime(r)));}break;}
            case "animevost":{JSONArray rows=postForm("https://api.animevost.org/v1/info","id",id).optJSONArray("data");if(rows==null||rows.length()==0)throw new IOException("Аниме не найдено");a=vostAnime(rows.getJSONObject(0));if(episodes){JSONArray list=new JSONArray(request("https://api.animevost.org/v1/playlist","POST","id="+enc(id),true));for(int i=0;i<list.length();i++){JSONObject e=list.getJSONObject(i);Anime.Episode ep=new Anime.Episode();ep.id=id+"-"+i;ep.name=e.optString("name","");ep.number=numberIn(ep.name,i+1);putStream(ep,480,e.optString("std"));putStream(ep,720,e.optString("hd"));a.episodeList.add(ep);}a.episodes=Math.max(a.episodes,a.episodeList.size());}break;}
            case "yummy":{JSONObject d=get("https://api.yani.tv/anime/"+enc(id)).optJSONObject("response");if(d==null)throw new IOException("YummyAnime не вернул карточку");a=yummyAnime(d);if(episodes){a.episodeList.addAll(YummyParser.episodes(id));a.episodes=Math.max(a.episodes,a.episodeList.size());}break;}
            case "anidub":{a=anidubDetails(base,episodes);break;}
            case "jutsu":{a=jutsuDetails(base,episodes);break;}
            case "animelib":{String slug=base.alias.isEmpty()?id:base.alias;JSONObject d=animelibDetail(slug,base).getJSONObject("data");a=amAnime(d);if(episodes){JSONArray rows=get("https://api.cdnlibs.org/api/episodes?anime_id="+enc(a.alias)).optJSONArray("data");for(int i=0;rows!=null&&i<rows.length();i++){JSONObject e=rows.getJSONObject(i);double n=e.optDouble("number",-1);if(n<0||!Double.isFinite(n))continue;Anime.Episode ep=new Anime.Episode();ep.id=e.optString("id");ep.number=n;ep.name=e.optString("name","");ep.lazy="animelib";a.episodeList.add(ep);}a.episodeList.sort(Comparator.comparingDouble(e->e.number));a.episodes=a.episodeList.size();}break;}
            case "animelib4k":{Anime copy=Anime.from(base.json());copy.source="animelib";a=details(copy,episodes);a.source="animelib4k";break;}
            case "anilibria":{a=libriaAnime(get("https://anilibria.top/api/v1/anime/releases/"+enc(id)));break;}
            case "animetka":{a=animetkaDetails(base,episodes);break;}
            case "kodik":{a=kodikDetails(base,episodes);break;}
            default:throw new IOException("Неизвестный источник");
        }
        if(a.year==0)a.year=base.year;if(a.malId==0)a.malId=base.malId;if(a.kpId==0)a.kpId=base.kpId;if(a.description.isEmpty())a.description=base.description;if(a.poster.isEmpty())a.poster=base.poster;return remember(a);
    }
    public Anime.Playback playback(Anime input,String selectedMode)throws Exception{
        normalizeIds(input);
        String selected=selectedMode==null||selectedMode.trim().isEmpty()?"auto":selectedMode.trim();
        if(selected.equals("all"))selected="auto";
        if(!selected.equals("auto")){
            Anime video=findPlayableSource(input,selected);
            if(video==null)throw new IOException("Источник сейчас не вернул серии");
            return playbackResult(input,video,selected);
        }
        ArrayList<String> order=new ArrayList<>();
        if(Arrays.asList("animevost","anilibria","animedia","animelib","animelib4k","yummy","animetka","anidub","jutsu","kodik").contains(input.source))order.add(input.source);
        for(String source:new String[]{"yummy","anilibria","animevost","animelib","animedia"})if(!order.contains(source))order.add(source);
        ExecutorService pool=Executors.newFixedThreadPool(Math.max(1,Math.min(4,order.size())));
        CompletionService<Anime.Playback> done=new ExecutorCompletionService<>(pool);
        for(String source:order){final String src=source;done.submit(()->{Anime video=findPlayableSource(input,src);return video==null?null:playbackResult(input,video,src);});}
        long deadline=System.currentTimeMillis()+9500;
        try{for(int i=0;i<order.size();i++){long left=deadline-System.currentTimeMillis();if(left<=0)break;Future<Anime.Playback> f=done.poll(left,TimeUnit.MILLISECONDS);if(f==null)break;try{Anime.Playback r=f.get();if(r!=null)return r;}catch(Exception ignored){}}}finally{pool.shutdownNow();}
        throw new IOException("Источники сейчас не вернули серии");
    }
    private Anime.Playback playbackResult(Anime catalog,Anime video,String provider){Anime.Playback r=new Anime.Playback();r.catalog=catalog;r.video=video;r.provider=provider==null||provider.isEmpty()?video.source:provider;return r;}
    private Anime findPlayableSource(Anime input,String source){try{Anime candidate=findSourceCandidate(input,source);if(candidate==null)return null;Anime full=candidate.episodeList.isEmpty()?details(candidate,true):candidate;if(!full.blocked&&!full.episodeList.isEmpty())return full;}catch(Exception ignored){}return null;}
    private Anime findSourceCandidate(Anime input,String source)throws Exception{
        if(source.equals(input.source)&&Arrays.asList("animevost","anilibria","animedia","animelib","animelib4k","yummy","animetka","anidub","jutsu","kodik").contains(source))return input;
        if(source.equals("yummy"))return findYummy(input);
        if(source.equals("anilibria")){Anime v=findAniLiberty(input);if(v!=null)return v;}
        if(source.equals("animelib")){Anime v=findAniLib(input);if(v!=null)return v;}
        if(source.equals("kodik"))return kodikShell(input);
        if(source.equals("animetka")||source.equals("anidub")||source.equals("jutsu"))return searchSource(input,source);
        if(source.equals("animelib4k")){Anime v=findAniLib(input);if(v!=null){v.source="animelib4k";return v;}}
        if(Arrays.asList("animevost","animedia").contains(source))return searchSource(input,source);
        return null;
    }
    public synchronized void loadEpisode(Anime.Episode ep)throws Exception{if(ep.lazy.equals("animedia")){new NativeSources(this).loadEpisode(ep);return;}if(ep.lazy.equals("jutsu")){loadJutsuEpisode(ep);return;}if(ep.lazy.equals("anidub")){if(ep.variants.isEmpty()&&!ep.resolverUrl.isEmpty())ep.variants.add(new Anime.Variant("AniDub",hostName(ep.resolverUrl),ep.resolverUrl));return;}if(ep.lazy.equals("kodik")){if(ep.variants.isEmpty())ep.variants.add(new Anime.Variant("Kodik 2026","Kodik",ep.resolverUrl));return;}if(!"animelib".equals(ep.lazy)||!ep.variants.isEmpty())return;JSONObject d=get("https://api.cdnlibs.org/api/episodes/"+enc(ep.id)).getJSONObject("data");JSONArray rows=d.optJSONArray("players");for(int i=0;rows!=null&&i<rows.length();i++){JSONObject v=rows.getJSONObject(i);if(!v.optString("player").equalsIgnoreCase("kodik"))continue;String u=embed(v.optString("src"));if(u.isEmpty())continue;JSONObject team=v.optJSONObject("team"),t=v.optJSONObject("translation_type");String name=(t==null?"Озвучка":t.optString("label","Озвучка"))+" "+(team==null?"":team.optString("name",""));ep.variants.add(new Anime.Variant(name.trim(),"Kodik",u));}if(ep.variants.isEmpty())throw new IOException("У серии нет доступного плеера");}
    public static final class DownloadOption {public Anime source;public Anime.Episode episode;public int quality;public String voice="",player="";public DownloadOption(Anime a,Anime.Episode e,int q){source=a;episode=e;quality=q;}public DownloadOption(Anime a,Anime.Episode e,int q,String v,String p){source=a;episode=e;quality=q;voice=v==null?"":v;player=p==null?"":p;}public String label(){String sourceName=downloadSourceName(source.source);String extra=voice.isEmpty()?"":voice;String p=player.isEmpty()?"":" · "+player;return (quality>0?quality+"p":"Оригинал")+" · "+sourceName+(extra.isEmpty()?"":" · "+extra)+p;}}
    private List<DownloadOption> options(Anime source,double number)throws Exception{ArrayList<DownloadOption> out=new ArrayList<>();if(source==null||source.blocked)return out;for(Anime.Episode e:source.episodeList)if(sameEpisode(e.number,number)){try{loadEpisode(e);}catch(Exception ignored){}for(int q:e.streams.keySet())out.add(new DownloadOption(source,e,q));if(!e.variants.isEmpty())out.addAll(variantOptions(source,e));break;}return uniqueOptions(out);}
    private List<DownloadOption> variantOptions(Anime source,Anime.Episode episode){ArrayList<DownloadOption> out=new ArrayList<>();if(episode.variants.isEmpty())return out;ExecutorService pool=Executors.newFixedThreadPool(Math.max(1,Math.min(6,episode.variants.size())));ArrayList<Future<List<DownloadOption>>> jobs=new ArrayList<>();for(Anime.Variant v:episode.variants)jobs.add(pool.submit(()->{ArrayList<DownloadOption> rows=new ArrayList<>();try{TreeMap<Integer,String> streams=VideoResolver.resolve(this,v.url);if(streams.isEmpty())return rows;Anime.Episode copy=new Anime.Episode();copy.id=episode.id+"-"+Integer.toHexString((v.name+"|"+v.player+"|"+v.url).hashCode());copy.number=episode.number;copy.name=v.label();copy.duration=v.duration;copy.openingStart=v.openingStart;copy.openingEnd=v.openingEnd;copy.streams.putAll(streams);for(int q:copy.streams.keySet())rows.add(new DownloadOption(source,copy,q,v.label(),v.player));}catch(Exception ignored){}return rows;}));long deadline=System.currentTimeMillis()+65000;for(Future<List<DownloadOption>> job:jobs){long left=deadline-System.currentTimeMillis();if(left<=0){job.cancel(true);continue;}try{out.addAll(job.get(left,TimeUnit.MILLISECONDS));}catch(Exception ignored){job.cancel(true);}}pool.shutdownNow();return out;}
    private void collectOptions(ArrayList<DownloadOption> out,LinkedHashSet<String> tried,Anime source,double number){if(source==null)return;String key="options|"+source.key()+"|"+number;if(!tried.add(key))return;try{out.addAll(options(source,number));}catch(Exception ignored){}}
    private void collectDetailsOptions(ArrayList<DownloadOption> out,LinkedHashSet<String> tried,Anime source,double number){if(source==null)return;String key="details|"+source.key()+"|"+number;if(!tried.add(key))return;try{collectOptions(out,tried,details(source,true),number);}catch(Exception ignored){}}
    private void collectCatalogMatches(ArrayList<DownloadOption> out,LinkedHashSet<String> tried,Anime base,String source,double number){int found=0;for(String term:searchTerms(base)){try{Anime.Page page=catalog(source,term,1,new Filter());for(Anime item:page.items){if(!matchesAnime(item,base))continue;collectDetailsOptions(out,tried,item,number);found++;if(found>=3)return;}}catch(Exception ignored){}}}
    private void collectDirectKodik(ArrayList<DownloadOption> out,LinkedHashSet<String> tried,Anime base,double number){try{int mal=base.malId>0?base.malId:resolveMal(base);String url=directKodik(mal);if(url.isEmpty())return;Uri u=Uri.parse(url);String path=u.getPath();if(path==null||!path.startsWith("/video/"))url=u.buildUpon().appendQueryParameter("episode",episodeParam(number)).build().toString();collectIframeOptions(out,tried,base,"kodik","Kodik","Kodik",url,number);}catch(Exception ignored){}}
    private void collectIframeOptions(ArrayList<DownloadOption> out,LinkedHashSet<String> tried,Anime base,String sourceId,String sourceTitle,String player,String iframe,double number){String url=embed(iframe);if(url.isEmpty())return;String key="iframe|"+sourceId+"|"+number+"|"+url;if(!tried.add(key))return;try{TreeMap<Integer,String> streams=VideoResolver.resolve(this,url);if(streams.isEmpty())return;Anime source=new Anime();source.source=sourceId;source.id=(base.key()+"|"+sourceId+"|"+Integer.toHexString(url.hashCode())).replace(':','_');source.title=sourceTitle;source.original=base.original;source.poster=base.poster;source.description=base.description;source.year=base.year;source.type=base.type;source.status=base.status;source.episodes=base.episodes;source.malId=base.malId;source.anilistId=base.anilistId;source.kpId=base.kpId;Anime.Episode ep=new Anime.Episode();ep.id=source.id+"-"+episodeParam(number);ep.number=number;ep.name=sourceTitle;ep.streams.putAll(streams);for(int q:streams.keySet())out.add(new DownloadOption(source,ep,q,sourceTitle,player));}catch(Exception ignored){}}
    private static ArrayList<DownloadOption> uniqueOptions(List<DownloadOption> options){LinkedHashMap<String,DownloadOption> unique=new LinkedHashMap<>();for(DownloadOption d:options){if(d==null||d.episode==null)continue;String url=d.episode.streams.get(d.quality);String safe=safeUrl(url);if(safe.isEmpty())continue;unique.put((d.source==null?"":d.source.source)+"|"+d.quality+"|"+d.voice+"|"+d.player+"|"+safe,d);}ArrayList<DownloadOption> list=new ArrayList<>(unique.values());list.sort((a,b)->{int s=downloadSourceRank(a.source.source)-downloadSourceRank(b.source.source);if(s!=0)return s;int q=Integer.compare(b.quality,a.quality);if(q!=0)return q;return a.label().compareToIgnoreCase(b.label());});return list;}
    public List<DownloadOption> downloadOptions(Anime a,Anime.Playback current,double number)throws Exception{
        ArrayList<DownloadOption> out=new ArrayList<>();if(a==null||a.blocked)return out;normalizeIds(a);LinkedHashSet<String> tried=new LinkedHashSet<>();
        if(current!=null){collectOptions(out,tried,current.video,number);if(!current.directUrl.isEmpty())collectIframeOptions(out,tried,a,current.provider.isEmpty()?"player":current.provider,current.provider.isEmpty()?"Плеер":current.provider,current.directKodik?"Kodik":"Iframe",current.directUrl,number);}
        if(Arrays.asList("animevost","anilibria","animedia","animelib","animelib4k","yummy","animetka","anidub","jutsu","kodik").contains(a.source))collectDetailsOptions(out,tried,a,number);
        Anime y=null;try{y=findYummy(a);if(y!=null)collectDetailsOptions(out,tried,y,number);}catch(Exception ignored){}
        collectDirectKodik(out,tried,a,number);
        try{String alias=a.libriaAlias.isEmpty()?(y==null?"":y.libriaAlias):a.libriaAlias;if(!alias.isEmpty())collectOptions(out,tried,libriaAnime(get("https://anilibria.top/api/v1/anime/releases/"+enc(alias))),number);}catch(Exception ignored){}
        for(String source:new String[]{"anilibria","animevost","animelib","animedia","animetka","anidub"})collectCatalogMatches(out,tried,a,source,number);
        return uniqueOptions(out);
    }

    private Anime.Page animetkaCatalog(String search,int page,Filter f)throws Exception{Anime.Page out=new Anime.Page();out.page=page;String q=search==null?"":search.trim();int limit=24,offset=Math.max(0,(page-1)*limit);String url=q.isEmpty()?query("https://animetka.com/api/anime/top",params("limit",String.valueOf(limit),"offset",String.valueOf(offset))):query("https://animetka.com/api/anime/search",params("name",q,"limit",String.valueOf(limit),"offset",String.valueOf(offset)));JSONArray rows=new JSONArray(request(url,"GET",null,false,animetkaHeaders()));if(rows.length()==0&&!q.isEmpty())rows=new JSONArray(request(query("https://animetka.com/api/anime/search",params("q",q,"limit",String.valueOf(limit),"offset",String.valueOf(offset))),"GET",null,false,animetkaHeaders()));int end=Math.min(rows.length(),limit);for(int i=0;i<end;i++){Anime a=animetkaAnime(rows.getJSONObject(i));if(Anime.valid(a))out.items.add(remember(a));}out.more=!q.isEmpty()&&rows.length()==limit;return out;}
    private Anime animetkaDetails(Anime base,boolean episodes)throws Exception{JSONObject d=new JSONObject(request("https://animetka.com/api/anime/"+enc(base.id),"GET",null,false,animetkaHeaders()));Anime a=animetkaAnime(d);if(!Anime.valid(a)){a=Anime.from(base.json());a.source="animetka";}JSONArray rel=d.optJSONArray("franchise");for(int i=0;rel!=null&&i<rel.length();i++){JSONObject r=rel.optJSONObject(i);if(r!=null){Anime item=animetkaAnime(r);if(Anime.valid(item)&&!item.id.equals(a.id))a.related.add(remember(item));}}if(episodes){LinkedHashMap<String,Anime.Episode> map=new LinkedHashMap<>();JSONObject lm=d.optJSONObject("AnilibriaMapping");JSONArray le=lm==null?null:lm.optJSONArray("episodes");for(int i=0;le!=null&&i<le.length();i++){JSONObject e=le.optJSONObject(i);if(e==null)continue;double n=e.optDouble("ordinal",i+1);String key=episodeParam(n);Anime.Episode ep=map.get(key);if(ep==null){ep=new Anime.Episode();ep.id=a.id+"-"+key;ep.number=n;ep.name=e.optString("name","");map.put(key,ep);}if(ep.name.isEmpty())ep.name="AniLibria";ep.duration=e.optInt("duration",ep.duration);putStream(ep,480,e.optString("hls_480"));putStream(ep,720,e.optString("hls_720"));putStream(ep,1080,e.optString("hls_1080"));JSONObject op=e.optJSONObject("opening");if(op!=null){ep.openingStart=op.optInt("start",ep.openingStart);ep.openingEnd=op.optInt("stop",ep.openingEnd);}}JSONArray rows=d.optJSONArray("Animes");HashMap<Integer,String> names=animetkaTranslationNames(d,rows);for(int i=0;rows!=null&&i<rows.length();i++){JSONObject row=rows.optJSONObject(i);if(row==null)continue;String link=embed(row.optString("link"));if(link.isEmpty())continue;int tid=row.optInt("translation",0),count=Math.max(row.optInt("episodes_total",0),row.optInt("episodes_aired",0));if(count<=0)count=a.episodes>0?a.episodes:1;if(row.optString("kodik_id").startsWith("movie-")||Uri.parse(link).getPath()!=null&&Uri.parse(link).getPath().startsWith("/video/"))count=1;count=Math.max(1,Math.min(250,count));String voice=names.get(tid);if(voice==null||voice.isEmpty())voice=tid>0?"Перевод "+tid:"Kodik";String q=row.optString("quality","").replace("WEB-DLRip ","").trim();for(int n=1;n<=count;n++){String key=episodeParam(n);Anime.Episode ep=map.get(key);if(ep==null){ep=new Anime.Episode();ep.id=a.id+"-"+key;ep.number=n;map.put(key,ep);}String url=animetkaEpisodeUrl(link,n);Anime.Variant v=new Anime.Variant(voice,"Kodik",url);v.displayName=voice+(q.isEmpty()?"":" · "+q);addVariant(ep,v);}}a.episodeList.clear();a.episodeList.addAll(map.values());a.episodeList.sort(Comparator.comparingDouble(e->e.number));a.episodes=Math.max(a.episodes,a.episodeList.size());}return remember(a);}
    private HashMap<Integer,String> animetkaTranslationNames(JSONObject detail,JSONArray rows){HashMap<Integer,String> out=new HashMap<>();int material=detail.optInt("id",detail.optInt("animetka_id",0)),tid=0;for(int i=0;rows!=null&&i<rows.length();i++){JSONObject row=rows.optJSONObject(i);if(row!=null&&row.optInt("translation",0)>0){tid=row.optInt("translation");break;}}if(material<=0||tid<=0)return out;try{JSONObject p=new JSONObject(request(query("https://animetka.com/api/anime/playlist",params("material",String.valueOf(material),"tid",String.valueOf(tid))),"GET",null,false,animetkaHeaders()));JSONArray list=p.optJSONArray("translations");for(int i=0;list!=null&&i<list.length();i++){JSONObject t=list.optJSONObject(i);if(t!=null)out.put(t.optInt("value",t.optInt("id",0)),t.optString("name",t.optString("title","")));}}catch(Exception ignored){}return out;}
    private static String animetkaEpisodeUrl(String link,int episode){try{Uri u=Uri.parse(link);String path=u.getPath();if(path!=null&&path.startsWith("/video/"))return link;return u.buildUpon().appendQueryParameter("episode",String.valueOf(episode)).build().toString();}catch(Exception e){return link;}}
    private static void addVariant(Anime.Episode ep,Anime.Variant v){for(Anime.Variant old:ep.variants)if(old.url.equals(v.url)&&old.name.equals(v.name)&&old.player.equals(v.player))return;ep.variants.add(v);}
    private static HashMap<String,String> animetkaHeaders(){HashMap<String,String> h=new HashMap<>();h.put("Accept","application/json,text/plain,*/*");h.put("Accept-Language","ru-RU,ru;q=0.9,en;q=0.5");h.put("Origin","https://animetka.com");h.put("Referer","https://animetka.com/");h.put("User-Agent","Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Mobile Safari/537.36");return h;}


    private Anime.Page anidubCatalog(String search,int page)throws Exception{Anime.Page out=new Anime.Page();out.page=page;String q=search==null?"":search.trim();String url=q.isEmpty()?(page<=1?"https://online.anidub.com/":"https://online.anidub.com/page/"+page+"/"):query("https://online.anidub.com/index.php",params("do","search","subaction","search","story",q));Document doc=Jsoup.parse(document(url),url);LinkedHashMap<String,Anime> map=new LinkedHashMap<>();for(Element a:doc.select("a[href]")){String href=absolute(url,a.attr("href"));if(href.isEmpty()||href.contains("/user/")||href.contains("/anidub_news/")||!Pattern.compile("/(\\d+)-[^/]+\\.html(?:$|[?#])").matcher(href).find())continue;Element scope=cardScope(a);String title=anchorTitle(a);if(title.isEmpty()||title.length()<2||title.matches("[+\\-]?[0-9.]+"))continue;Anime item=anidubShell(href,title,posterFrom(url,scope),scope==null?title:scope.text());if(q.isEmpty()||matchesQuery(item,q))putBetter(map,item);if(map.size()>=24)break;}out.items.addAll(map.values());out.more=q.isEmpty()&&out.items.size()>=18;return out;}
    private Anime anidubDetails(Anime base,boolean episodes)throws Exception{String url=sourceUrl(base);String html=document(url);Document doc=Jsoup.parse(html,url);Anime a=anidubShell(url,heading(doc,base.title),posterFrom(url,doc),doc.text());String desc=descriptionFrom(doc);if(!desc.isEmpty())a.description=desc;for(Element g:doc.select("a[href*=/xfsearch/genre/],a[href*=/genre/]") ){String t=cleanText(g.text());if(!t.isEmpty()&&!a.genres.contains(t))a.genres.add(t);}if(episodes){LinkedHashMap<String,Anime.Episode> map=new LinkedHashMap<>();anidubOptions(doc,html,url,"sel","Sibnet",map,a.id);anidubOptions(doc,html,url,"sel2","AniDub",map,a.id);anidubOptions(doc,html,url,"sel3","Stormo",map,a.id);if(map.isEmpty())anidubDirectFallback(a,html,url);else{a.episodeList.clear();a.episodeList.addAll(map.values());a.episodeList.sort(Comparator.comparingDouble(e->e.number));a.episodes=Math.max(a.episodes,a.episodeList.size());}}return remember(a);}
    private void anidubOptions(Document doc,String html,String page,String id,String player,LinkedHashMap<String,Anime.Episode> map,String baseId){for(Element o:doc.select("#"+id+" option"))anidubOption(page,player,o.attr("value"),o.text(),map,baseId);Matcher box=Pattern.compile("<select[^>]+id=[\\\"']"+Pattern.quote(id)+"[\\\"'][^>]*>(.*?)</select>",Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(html);while(box.find()){Matcher m=Pattern.compile("<option[^>]+value=[\\\"']([^\\\"']+)[\\\"'][^>]*>(.*?)</option>",Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(box.group(1));while(m.find())anidubOption(page,player,unescape(m.group(1)),plain(m.group(2)),map,baseId);}}
    private void anidubOption(String page,String suggested,String value,String label,LinkedHashMap<String,Anime.Episode> map,String baseId){String v=unescape(value);if(v.isEmpty())return;int cut=v.lastIndexOf('|');String raw=cut>0?v.substring(0,cut):v,num=cut>0?v.substring(cut+1):label;String provider=absolute(page,raw);if(provider.isEmpty())return;double n=numberIn(num+" "+label,map.size()+1);if(n<=0||!Double.isFinite(n))n=map.size()+1;String key=episodeParam(n);Anime.Episode ep=map.get(key);if(ep==null){ep=new Anime.Episode();ep.id=baseId+"-"+key;ep.number=n;ep.name="AniDub";ep.lazy="anidub";map.put(key,ep);}String h=hostName(provider).toLowerCase(Locale.ROOT),p=suggested;if(h.contains("sibnet"))p="Sibnet";else if(h.contains("stormo"))p="Stormo";else if(h.contains("ladony")||provider.contains("vid.php"))p="AniDub HLS";Anime.Variant variant=new Anime.Variant("AniDub",p,provider);variant.displayName="AniDub · "+p;addVariant(ep,variant);}
    private void anidubDirectFallback(Anime a,String html,String page){Matcher m=Pattern.compile("https?:\\\\?/\\\\?/[^\\\"'<>\\s]+?(?:\\.m3u8|\\.mp4)[^\\\"'<>\\s]*",Pattern.CASE_INSENSITIVE).matcher(html);Anime.Episode ep=null;while(m.find()){String safe=safeUrl(m.group().replace("\\/","/"));if(safe.isEmpty())continue;if(ep==null){ep=new Anime.Episode();ep.id=a.id+"-1";ep.number=1;ep.name="AniDub";a.episodeList.add(ep);}putStream(ep,VideoResolver.qualityOf(safe),safe);}if(ep!=null){a.episodes=Math.max(a.episodes,1);return;}Matcher iframe=Pattern.compile("<(?:iframe|embed)[^>]+src=[\\\"']([^\\\"']+)[\\\"']",Pattern.CASE_INSENSITIVE).matcher(html);while(iframe.find()){String u=embed(absolute(page,iframe.group(1)));if(u.isEmpty())continue;if(ep==null){ep=new Anime.Episode();ep.id=a.id+"-1";ep.number=1;ep.name="AniDub";ep.lazy="anidub";a.episodeList.add(ep);}Anime.Variant v=new Anime.Variant("AniDub",hostName(u),u);v.displayName="AniDub · "+hostName(u);addVariant(ep,v);}if(ep!=null)a.episodes=Math.max(a.episodes,1);}
    private Anime.Page jutsuCatalog(String search,int page)throws Exception{Anime.Page out=new Anime.Page();out.page=page;String q=search==null?"":search.trim();LinkedHashMap<String,Anime> map=new LinkedHashMap<>();ArrayList<String> urls=new ArrayList<>();if(q.isEmpty())urls.add(page<=1?"https://jut.su/anime/":"https://jut.su/anime/page-"+page+"/");else{urls.add("https://jut.su/anime/");urls.add("https://jut.su/anime/page-2/");urls.add("https://jut.su/anime/ongoing/");urls.add("https://jut.su/anime/order-by-name/");}for(String url:urls){try{Document doc=Jsoup.parse(document(url),url);for(Element a:doc.select("a[href]")){String href=absolute(url,a.attr("href"));if(!jutsuTitleUrl(href))continue;Anime item=jutsuShell(href,anchorTitle(a),posterFrom(url,cardScope(a)),cardScope(a)==null?a.text():cardScope(a).text());if(item.title.length()<2)continue;if(q.isEmpty()||matchesQuery(item,q))putBetter(map,item);if(map.size()>=24)break;}}catch(Exception ignored){}if(map.size()>=24)break;}if(map.isEmpty()&&!q.isEmpty()){String slug=latinSlug(q);if(!slug.isEmpty())try{String url="https://jut.su/"+slug+"/";Anime seed=jutsuShell(url,q,"",q);Anime item=jutsuDetails(seed,false);if(matchesQuery(item,q))putBetter(map,item);}catch(Exception ignored){}}out.items.addAll(map.values());out.more=q.isEmpty()&&out.items.size()>=18;return out;}
    private Anime jutsuDetails(Anime base,boolean episodes)throws Exception{String url=sourceUrl(base);String html=document(url);Document doc=Jsoup.parse(html,url);Anime a=jutsuShell(url,heading(doc,base.title),posterFrom(url,doc),doc.text());String original=findText(html,"Оригинальное название:\\s*</?[^>]*>\\s*([^<\\n]+)");if(!original.isEmpty())a.original=cleanText(original);String desc=descriptionFrom(doc);if(!desc.isEmpty())a.description=desc;for(Element g:doc.select("a[href*=/anime/]") ){String href=g.attr("href"),t=cleanText(g.text());if(t.isEmpty()||href.matches(".*/anime/(?:page|order|ongoing|before2000|20[0-9]{2}|[0-9-]+)/?.*"))continue;if(!a.genres.contains(t))a.genres.add(t);}if(episodes){LinkedHashSet<String> seen=new LinkedHashSet<>();int seq=1;for(Element link:doc.select("a[href*=episode-][href$=.html],a.video[href]")){String href=absolute(url,link.attr("href"));if(href.isEmpty()||!href.contains("episode-")||!seen.add(href))continue;Anime.Episode ep=new Anime.Episode();ep.id=a.id+"-"+seq;ep.number=seq;ep.name=episodeTitle(link.text(),seq);ep.lazy="jutsu";ep.resolverUrl=href;a.episodeList.add(ep);seq++;}for(Element link:doc.select("a[href*=film][href]")){String href=absolute(url,link.attr("href"));if(href.isEmpty()||!jutsuTitleUrl(href)||!seen.add(href))continue;Anime.Episode ep=new Anime.Episode();ep.id=a.id+"-"+seq;ep.number=seq;ep.name=episodeTitle(link.text(),seq);ep.lazy="jutsu";ep.resolverUrl=href;a.episodeList.add(ep);seq++;}a.episodes=Math.max(a.episodes,a.episodeList.size());}return remember(a);}
    private void loadJutsuEpisode(Anime.Episode ep)throws Exception{if(!ep.streams.isEmpty())return;String url=safeUrl(ep.resolverUrl);if(url.isEmpty())throw new IOException("Серия недоступна");String html=document(url);Document doc=Jsoup.parse(html,url);for(Element s:doc.select("video#my-player source[src],video source[src],source[src]")){String src=absolute(url,s.attr("src"));if(src.isEmpty())continue;int q=parseInt(first(first(s.attr("res"),s.attr("label")),first(s.attr("data-res"),s.attr("data-quality"))));if(q<=0)q=VideoResolver.qualityOf(src);putStream(ep,q,src);}if(ep.streams.isEmpty()){Matcher m=Pattern.compile("https?:\\\\?/\\\\?/[^\\\"'<>\\s]+?(?:\\.m3u8|\\.mp4)[^\\\"'<>\\s]*",Pattern.CASE_INSENSITIVE).matcher(html);while(m.find()){String safe=safeUrl(m.group().replace("\\/","/"));if(safe.isEmpty())continue;TreeMap<Integer,String> found=VideoResolver.probe(this,safe);if(found.isEmpty())putStream(ep,VideoResolver.qualityOf(safe),safe);else for(Map.Entry<Integer,String> e:found.entrySet())putStream(ep,e.getKey(),e.getValue());}}if(ep.streams.isEmpty())throw new IOException("JutSu не вернул прямое видео");}
    private static boolean jutsuTitleUrl(String href){try{Uri u=Uri.parse(href);String h=u.getHost(),path=u.getPath();if(h==null||path==null||!(h.equals("jut.su")||h.endsWith(".jut.su")))return false;if(path.startsWith("/anime/")||path.startsWith("/technique/")||path.contains("episode-")||path.contains("season-")||path.endsWith(".html"))return false;return path.matches("/[a-z0-9][a-z0-9-]+/");}catch(Exception e){return false;}}
    private static Anime anidubShell(String url,String title,String poster,String meta){Anime a=new Anime();a.source="anidub";Matcher m=Pattern.compile("/(\\d+)-[^/]+\\.html").matcher(url);a.id=m.find()?m.group(1):stableId(url);a.alias=safeUrl(url);fillNames(a,title);a.poster=safeUrl(poster);a.year=yearIn(meta);a.episodes=episodesIn(meta+" "+title);a.status=meta!=null&&meta.toLowerCase(Locale.ROOT).contains("онгоинг")?"ongoing":"released";return a;}
    private static Anime jutsuShell(String url,String title,String poster,String meta){Anime a=new Anime();a.source="jutsu";a.id=stableId(url);a.alias=safeUrl(url);fillNames(a,title);a.poster=safeUrl(poster);a.year=yearIn(meta);a.episodes=episodesIn(meta);a.status=meta!=null&&meta.toLowerCase(Locale.ROOT).contains("онгоинг")?"ongoing":"released";return a;}
    private static void fillNames(Anime a,String title){String t=cleanTitle(title);if(t.isEmpty())t="Аниме";String[] parts=t.split("\\s*/\\s*",2);a.title=parts[0].trim();if(parts.length>1)a.original=parts[1].replaceAll("\\s*\\[[^\\]]*\\]\\s*$","").trim();}
    private static String cleanTitle(String raw){String t=plain(raw).replace('\u00a0',' ').trim();if(t.contains("\n"))for(String row:t.split("\\r?\\n")){row=row.trim();if(row.length()>1){t=row;break;}}t=t.replaceAll("\\s+"," ").trim();t=t.replaceFirst("(?iu)^смотреть\\s+","").replaceFirst("(?iu)^постер\\s+аниме\\s+","");t=t.replaceAll("(?iu)\\s+все\\s+серии(?:\\s+и\\s+сезоны)?$","");t=t.replaceAll("\\s*\\[[^\\]]*\\]\\s*$","");return t.trim();}
    private static String cleanText(String raw){return plain(raw).replace('\u00a0',' ').replaceAll("\\s+"," ").trim();}
    private static String anchorTitle(Element a){String[] values={a.attr("title"),a.select("img[alt]").attr("alt"),a.ownText(),a.text()};for(String v:values){String t=cleanTitle(v);if(!t.isEmpty()&&!t.equalsIgnoreCase("смотреть")&&!t.matches("[+\\-]?[0-9.]+"))return t;}return "";}
    private static Element cardScope(Element a){Element s=a;for(int i=0;i<5&&s!=null;i++){String cls=s.className().toLowerCase(Locale.ROOT);if(cls.contains("short")||cls.contains("th-")||cls.contains("item")||cls.contains("movie")||cls.contains("anime")||cls.contains("story")||!s.select("img[src]").isEmpty())return s;s=s.parent();}return a.parent()==null?a:a.parent();}
    private static String posterFrom(String base,Element scope){if(scope==null)return "";String best="";for(Element img:scope.select("img[src],img[data-src],img[data-original]")){String src=first(first(img.attr("data-src"),img.attr("data-original")),img.attr("src"));String safe=absolute(base,src);String low=safe.toLowerCase(Locale.ROOT);if(safe.isEmpty()||low.contains("logo")||low.contains("banner")||low.contains("avatar")||low.contains("transparent"))continue;best=safe;if(low.contains("poster")||low.contains("uploads/posts")||low.contains("previews"))break;}if(!best.isEmpty())return best;Matcher bg=Pattern.compile("url\\(['\\\"]?([^)'\\\"]+)",Pattern.CASE_INSENSITIVE).matcher(scope.attr("style"));return bg.find()?absolute(base,bg.group(1)):"";}
    private static String heading(Document doc,String fallback){for(Element h:doc.select("h1,h2,h3")){String t=cleanTitle(h.text());String l=t.toLowerCase(Locale.ROOT);if(t.length()>2&&!l.startsWith("описание")&&!l.contains("комментар")&&!l.contains("смотреть онлайн"))return t;}String title=cleanTitle(doc.title());return title.isEmpty()?fallback:title.replaceAll("(?iu)\\s+смотреть.*$","").trim();}
    private static String descriptionFrom(Document doc){for(String sel:new String[]{"[itemprop=description]",".description",".full-text",".story",".quote",".entry","p"})for(Element e:doc.select(sel)){String t=cleanText(e.text());String l=t.toLowerCase(Locale.ROOT);if(t.length()>80&&!l.contains("зарегистриру")&&!l.contains("комментар")&&!l.contains("донат"))return t.length()>1200?t.substring(0,1200):t;}return "";}
    private void putBetter(LinkedHashMap<String,Anime> map,Anime a){if(!Anime.valid(a))return;Anime old=map.get(a.id);if(old==null||a.title.length()<old.title.length()||old.poster.isEmpty()&&!a.poster.isEmpty())map.put(a.id,remember(a));}
    private static boolean matchesQuery(Anime a,String q){String n=plainName(q);if(n.isEmpty())return true;String title=plainName(a.title+" "+a.original+" "+a.alias);return title.contains(n)||n.contains(plainName(a.title))||(!a.original.isEmpty()&&n.contains(plainName(a.original)));}
    private static String sourceUrl(Anime base)throws Exception{String u=safeUrl(base.alias);if(!u.isEmpty())return u;throw new IOException("У источника нет адреса страницы");}
    private static String stableId(String value){long h=Integer.toUnsignedLong((value==null?"":value).hashCode());return String.valueOf(1000000000L+h%8999999999L);}
    private static int yearIn(String text){Matcher m=Pattern.compile("(?:^|[^0-9])((?:19|20)[0-9]{2})(?:[^0-9]|$)").matcher(text==null?"":text);try{return m.find()?Integer.parseInt(m.group(1)):0;}catch(Exception e){return 0;}}
    private static int episodesIn(String text){String s=text==null?"":text;String[] patterns={"из\\s*(\\d{1,4})","(\\d{1,4})\\s*сер(?:ия|ии|ий)","Серии?:\\s*[^0-9]*(\\d{1,4})"};for(String p:patterns){Matcher m=Pattern.compile(p,Pattern.CASE_INSENSITIVE|Pattern.UNICODE_CASE).matcher(s);if(m.find())try{return Integer.parseInt(m.group(1));}catch(Exception ignored){}}return 0;}
    private static String episodeTitle(String text,int fallback){String t=cleanText(text);if(t.isEmpty())return "Серия "+fallback;t=t.replaceFirst("(?iu)^смотреть\\s+","");return t.length()>120?t.substring(0,120):t;}
    private static String latinSlug(String text){String s=(text==null?"":text).toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-").replaceAll("^-+|-+$","");return s.matches(".*[a-z].*")?s:"";}
    private static String findText(String input,String regex){Matcher m=Pattern.compile(regex,Pattern.CASE_INSENSITIVE|Pattern.UNICODE_CASE|Pattern.DOTALL).matcher(input==null?"":input);return m.find()?cleanText(unescape(m.group(1))):"";}

    private Anime.Page animelib4kCatalog(String search,int page,Filter f)throws Exception{Anime.Page base=catalog("animelib",search,page,f);Anime.Page out=new Anime.Page();out.page=base.page;out.total=base.total;out.more=base.more;for(Anime a:base.items){Anime copy=Anime.from(a.json());copy.source="animelib4k";out.items.add(remember(copy));}return out;}
    private Anime.Page kodikCatalog(String search,int page,Filter f)throws Exception{Anime.Page base=catalog("shikimori",search,page,f);Anime.Page out=new Anime.Page();out.page=base.page;out.total=base.total;out.more=base.more;for(Anime a:base.items)out.items.add(remember(kodikShell(a)));return out;}
    private Anime kodikShell(Anime base){Anime a=new Anime();a.source="kodik";a.id=String.valueOf(base.malId>0?base.malId:base.id.matches("\\d+")?Integer.parseInt(base.id):(int)(1L+(Integer.toUnsignedLong(base.key().hashCode())%999999999L)));a.title=base.title;a.original=base.original;a.alias=base.alias;a.poster=base.poster;a.description=base.description;a.year=base.year;a.type=base.type;a.status=base.status;a.age=base.age;a.episodes=base.episodes;a.malId=base.malId>0?base.malId:parseInt(base.id);a.anilistId=base.anilistId;a.kpId=base.kpId;a.libriaAlias=base.libriaAlias;a.score=base.score;a.genres.addAll(base.genres);return a;}
    private Anime kodikDetails(Anime base,boolean episodes)throws Exception{Anime shell=kodikShell(base);if(shell.description.isEmpty()||shell.poster.isEmpty()){try{Anime sh=new Anime();sh.source="shikimori";sh.id=String.valueOf(shell.malId>0?shell.malId:parseInt(shell.id));sh.title=shell.title;sh.original=shell.original;Anime full=details(sh,false);shell=kodikShell(full);}catch(Exception ignored){}}if(episodes){int mal=shell.malId>0?shell.malId:parseInt(shell.id);String url=directKodik(mal);int count=Math.max(1,Math.min(250,shell.episodes>0?shell.episodes:1));for(int i=1;i<=count;i++){Anime.Episode ep=new Anime.Episode();ep.id=shell.id+"-"+i;ep.number=i;ep.name="Kodik 2026";ep.lazy="kodik";ep.resolverUrl=Uri.parse(url).buildUpon().appendQueryParameter("episode",String.valueOf(i)).build().toString();ep.variants.add(new Anime.Variant("Kodik 2026","Kodik",ep.resolverUrl));shell.episodeList.add(ep);}}return remember(shell);}
    private static int parseInt(String s){try{return Integer.parseInt(s==null?"0":s.replaceAll("\\D+",""));}catch(Exception e){return 0;}}
    private Anime findAniLiberty(Anime a)throws Exception{normalizeIds(a);Anime y=null;try{y=findYummy(a);}catch(Exception ignored){}String alias=a.libriaAlias.isEmpty()?(y==null?"":y.libriaAlias):a.libriaAlias;if(!alias.isEmpty())return libriaAnime(get("https://anilibria.top/api/v1/anime/releases/"+enc(alias)));return searchSource(a,"anilibria");}
    private Anime searchSource(Anime a,String source)throws Exception{for(String term:searchTerms(a)){Anime.Page page=catalog(source,term,1,new Filter());for(Anime item:page.items)if(matchesAnime(item,a))return item;}return null;}
    private static boolean matchesAnime(Anime candidate,Anime base){if(candidate==null||base==null)return false;if(candidate.malId>0&&base.malId>0&&candidate.malId==base.malId)return true;if(candidate.anilistId>0&&base.anilistId>0&&candidate.anilistId==base.anilistId)return true;String bt=plainName(base.title),bo=plainName(base.original),ct=plainName(candidate.title),co=plainName(candidate.original);boolean title=(!bt.isEmpty()&&(bt.equals(ct)||bt.equals(co)))||(!bo.isEmpty()&&(bo.equals(ct)||bo.equals(co)));if(!title&&("anidub".equals(candidate.source)||"jutsu".equals(candidate.source)))title=(!bt.isEmpty()&&(ct.contains(bt)||bt.contains(ct)))||(!bo.isEmpty()&&(co.contains(bo)||bo.contains(co)||ct.contains(bo)));return title&&(base.year==0||candidate.year==0||Math.abs(base.year-candidate.year)<=1);}
    private static LinkedHashSet<String> searchTerms(Anime a){LinkedHashSet<String> terms=new LinkedHashSet<>();if(a!=null){if(!a.title.trim().isEmpty())terms.add(a.title.trim());if(!a.original.trim().isEmpty())terms.add(a.original.trim());String alias=plain(a.alias);if(!alias.isEmpty()&&alias.length()<120&&!alias.contains("/"))terms.add(alias);}return terms;}
    private static boolean sameEpisode(double a,double b){return Math.abs(a-b)<0.001;}
    private static String episodeParam(double n){return sameEpisode(n,Math.floor(n))?String.valueOf((int)Math.floor(n)):String.valueOf(n);}
    public static String downloadSourceName(String id){String name=sourceNames.get(id);if(name!=null)return name;if("kodik".equals(id))return "Kodik 2026";if("animelib4k".equals(id))return "AniLib 4K probe";if("player".equals(id))return "Плеер";return id==null||id.isEmpty()?"Источник":id;}
    private static int downloadSourceRank(String id){if("yummy".equals(id))return 0;if("animevost".equals(id))return 1;if("anidub".equals(id))return 2;if("jutsu".equals(id))return 3;if("animelib4k".equals(id))return 4;if("anilibria".equals(id))return 5;if("animelib".equals(id))return 6;if("animedia".equals(id))return 7;if("animetka".equals(id))return 8;if("kodik".equals(id))return 9;return 20;}
    private static void normalizeIds(Anime a){if(a!=null&&a.malId==0&&"shikimori".equals(a.source))try{a.malId=Integer.parseInt(a.id);}catch(Exception ignored){}}
    private Anime findYummy(Anime a)throws Exception{normalizeIds(a);String url=a.malId>0?"https://api.yani.tv/anime?shikimori_ids="+a.malId+"&limit=20":"https://api.yani.tv/anime?q="+enc(a.title)+"&limit=20";JSONArray rows=get(url).optJSONArray("response");Anime found=null;for(int i=0;rows!=null&&i<rows.length();i++){Anime y=yummyAnime(rows.getJSONObject(i));if(a.malId>0){JSONObject remote=rows.getJSONObject(i).optJSONObject("remote_ids");if(remote!=null&&(remote.optInt("myanimelist_id")==a.malId||remote.optInt("shikimori_id")==a.malId))return remember(y);}if(a.malId==0&&plainName(y.title).equals(plainName(a.title))&&(a.year==0||a.year==y.year)){if(found!=null&&found.malId!=y.malId)return null;found=y;}}return found==null?null:remember(found);}
    private Anime findAniLib(Anime a)throws Exception{normalizeIds(a);Anime best=null;for(String q:searchTerms(a)){Anime.Page page=catalog("animelib",q,1,new Filter());for(Anime item:page.items){if(!matchesAnime(item,a))continue;Anime full=details(item,false);if(a.malId>0&&full.malId==a.malId)return item;if(a.anilistId>0&&full.anilistId==a.anilistId)return item;if(best==null)best=item;}}return best;}
    private JSONObject animelibDetail(String slug,Anime base)throws Exception{String fields="?fields[]=genres&fields[]=releaseDate&fields[]=shiki_id&fields[]=anilist_id&fields[]=rate&fields[]=rate_avg";String resolved=slug;if(parseInt(slug)>0&&!slug.contains("--")){String found=animelibSlug(base);if(!found.isEmpty())resolved=found;}try{return get("https://api.cdnlibs.org/api/anime/"+enc(resolved)+fields);}catch(Exception first){String found=animelibSlug(base);if(!found.isEmpty()&&!found.equals(resolved))return get("https://api.cdnlibs.org/api/anime/"+enc(found)+fields);throw first;}}
    private String animelibSlug(Anime base){try{if(base==null)return "";if(base.alias!=null&&!base.alias.isEmpty()&&base.alias.contains("--"))return base.alias;for(String q:searchTerms(base)){Anime.Page page=catalog("animelib",q,1,new Filter());for(Anime item:page.items){if(item.id.equals(base.id)||matchesAnime(item,base))return item.alias;}}}catch(Exception ignored){}return "";}
    private int resolveMal(Anime a)throws Exception{if(a.malId>0)return a.malId;Anime y=findYummy(a);if(y!=null&&y.malId>0){a.malId=y.malId;a.kpId=y.kpId;return y.malId;}throw new IOException("Не удалось найти плеер. Попробуйте открыть аниме в другом каталоге.");}
    private int resolveKp(Anime a)throws Exception{if(a.kpId>0)return a.kpId;Anime y=findYummy(a);if(y!=null&&y.kpId>0){a.kpId=y.kpId;return y.kpId;}throw new IOException("У этого плеера пока нет подходящего варианта.");}
    private synchronized String token()throws Exception{if(!publicToken.isEmpty()&&System.currentTimeMillis()-tokenAt<300000)return publicToken;String script=request("https://kodik-add.com/add-players.min.js?v=2","GET",null,false);String[] patterns={"token\\s*=\\s*[\"\\\']([A-Za-z0-9]{16,120})[\"\\\']","[\"\\\']token[\"\\\']\\s*:\\s*[\"\\\']([A-Za-z0-9]{16,120})[\"\\\']","token=\\\\?[\"\\\']([A-Za-z0-9]{16,120})[\"\\\']"};for(String pattern:patterns){Matcher m=Pattern.compile(pattern).matcher(script);if(m.find()){publicToken=m.group(1);tokenAt=System.currentTimeMillis();return publicToken;}}throw new IOException("Плеер временно недоступен");}
    public String directKodik(int mal)throws Exception{if(mal<=0)throw new IOException("Не удалось найти аниме у этого источника");String q=query("https://kodik-api.com/get-player",params("title","Player","hasPlayer","false","url","https://kodikdb.com/find-player?shikimoriID="+mal,"token",token(),"shikimoriID",String.valueOf(mal)));JSONObject j=get(q);if(j.has("error")||!j.optBoolean("found"))throw new IOException("У этого источника пока нет плеера");if(j.has("allowed")&&j.optInt("allowed",1)==0)throw new IOException("Просмотр ограничен источником");String u=embed(j.optString("link"));if(u.isEmpty())throw new IOException("Плеер временно недоступен");return u;}
    private String regional(String source,int kp)throws Exception{if(source.equals("flixcdn"))return "https://tarantino.factorios.live/show/kinopoisk/"+kp;if(source.equals("gendit"))return "https://horsez.org/lat/"+kp;JSONObject root=get("https://fbphdplay.top/api/players?kinopoisk="+kp);JSONArray list=root.optJSONArray("data");for(int i=0;list!=null&&i<list.length();i++){JSONObject j=list.getJSONObject(i);if(j.optString("type").equalsIgnoreCase(source)){String url=safeUrl(j.optString("iframeUrl"));if(!url.isEmpty())return url;}}throw new IOException("Источник не предложил плеер для этого аниме");}
    public static String embed(String input){if(input==null)return "";String s=input.trim().replace("&amp;","&");Matcher html=Pattern.compile("src=[\"']([^\"']+)",Pattern.CASE_INSENSITIVE).matcher(s);if(html.find())s=html.group(1);if(s.startsWith("//"))s="https:"+s;try{Uri u=Uri.parse(s);String host=u.getHost();if(host!=null&&Arrays.asList("aniqit.com","kodik.info","kodik.cc","kodik.biz").contains(host))s=u.buildUpon().scheme("https").authority("kodikplayer.com").build().toString();return safeUrl(s);}catch(Exception e){return "";}}
    private static String absolute(String base,String value){try{if(value==null||value.trim().isEmpty())return "";value=value.trim().replace(" ","%20").replace("&amp;","&");if(value.startsWith("//"))value="https:"+value;return safeUrl(new URL(new URL(base),value).toString());}catch(Exception e){return "";}}
    private static String hostName(String link){try{String h=Uri.parse(link.startsWith("//")?"https:"+link:link).getHost();return h==null?"Плеер":h.replace("www.","");}catch(Exception e){return "Плеер";}}
    static String plain(String text){return Html.fromHtml(text==null?"":text,Html.FROM_HTML_MODE_LEGACY).toString().replaceAll("\\[/?[^\\]]+\\]","").trim();}
    static String plainName(String text){return (text==null?"":text).toLowerCase(Locale.ROOT).replaceAll("[^\\p{L}\\p{N}]+"," ").trim();}
    private static double numberIn(String text,double fallback){Matcher m=Pattern.compile("[0-9]+(?:\\.[0-9]+)?").matcher(text);try{return m.find()?Double.parseDouble(m.group()):fallback;}catch(Exception e){return fallback;}}
    private static void putStream(Anime.Episode ep,int q,String url){String s=safeUrl(url);if(!s.isEmpty())ep.streams.put(q,s);}
    private static void genres(Anime a,JSONArray rows,String name){for(int i=0;rows!=null&&i<rows.length();i++){Object g=rows.opt(i);if(g instanceof JSONObject){String value=((JSONObject)g).optString(name,((JSONObject)g).optString("name",""));if(!value.isEmpty()&&!a.genres.contains(value))a.genres.add(value);}else if(g instanceof String&&!a.genres.contains((String)g))a.genres.add((String)g);}}
    private static Anime animetkaAnime(JSONObject j){Anime a=new Anime();a.source="animetka";a.id=j.optString("animetka_id",j.optString("id"));a.title=j.optString("anime_title",j.optString("title","Аниме"));if(a.title.isEmpty())a.title=j.optString("title","Аниме");a.original=j.optString("title_orig",j.optString("title_en",""));a.alias=j.optString("title_en","");a.description=plain(j.optString("anime_description",j.optString("description","")));String poster=j.optString("anime_poster_url",j.optString("poster_url",""));a.poster=safeUrl(poster);a.year=j.optInt("year");a.type=kind(j.optString("anime_kind",j.optString("kind","")));a.status=j.optString("all_status",j.optString("anime_status",""));int age=j.optInt("minimal_age",0);a.age=age>0?age+"+":j.optString("rating_mpaa","");a.episodes=j.optInt("episodes_total",j.optInt("episodes",0));a.score=j.optDouble("shikimori_rating",j.optDouble("rating",0));if(!Double.isFinite(a.score))a.score=0;a.malId=j.optInt("shikimori_id",j.optInt("malId",0));a.kpId=j.optInt("kinopoisk_id",j.optInt("kp_id",0));genres(a,j.optJSONArray("anime_genres"),"name");genres(a,j.optJSONArray("all_genres"),"name");genres(a,j.optJSONArray("Genres"),"name");return a;}

    private static Anime shikiAnime(JSONObject j){Anime a=new Anime();a.source="shikimori";a.id=j.optString("id");a.malId=j.optInt("malId",0);if(a.malId==0)try{a.malId=Integer.parseInt(a.id);}catch(Exception ignored){}a.title=j.optString("russian","");if(a.title.isEmpty())a.title=j.optString("name","Аниме");a.original=j.optString("name","");a.type=kind(j.optString("kind"));a.status=j.optString("status");a.episodes=j.optInt("episodes");a.score=j.optDouble("score",0);JSONObject date=j.optJSONObject("airedOn"),poster=j.optJSONObject("poster");a.year=date==null?0:date.optInt("year");a.poster=poster==null?"":safeUrl(poster.optString("mainUrl",poster.optString("originalUrl")));a.age=j.optString("rating").equals("pg_13")?"13+":j.optString("rating").startsWith("r")?"18+":"";genres(a,j.optJSONArray("genres"),"russian");return a;}
    private static Anime vostAnime(JSONObject j){Anime a=new Anime();a.source="animevost";a.id=j.optString("id");String raw=j.optString("title","Аниме"),clean=raw.replaceAll("\\s*\\[[^\\]]*\\]\\s*$","");String[] names=clean.split(" / ",2);a.title=names[0];a.original=names.length>1?names[1]:"";a.description=plain(j.optString("description"));a.poster=safeUrl(j.optString("urlImagePreview"));a.year=j.optInt("year");a.type=j.optString("type","Аниме");Matcher m=Pattern.compile("из\\s*(\\d+)").matcher(raw);if(m.find())a.episodes=Integer.parseInt(m.group(1));a.status="published";for(String g:j.optString("genre","").split(","))if(!g.trim().isEmpty()&&!a.genres.contains(g.trim()))a.genres.add(g.trim());return a;}
    private static Anime yummyAnime(JSONObject j){Anime a=new Anime();a.source="yummy";a.id=j.optString("anime_id");a.title=j.optString("title","Аниме");a.alias=j.optString("anime_url");a.year=j.optInt("year");a.description=plain(j.optString("description"));JSONObject p=j.optJSONObject("poster"),type=j.optJSONObject("type"),age=j.optJSONObject("min_age"),rat=j.optJSONObject("rating"),ids=j.optJSONObject("remote_ids"),eps=j.optJSONObject("episodes"),status=j.optJSONObject("anime_status");a.poster=p==null?"":safeUrl(p.optString("medium",p.optString("fullsize")));a.type=type==null?"Аниме":type.optString("shortname","Аниме");a.age=age==null?"":age.optString("title");a.score=rat==null?0:rat.optDouble("average",0);a.status=status==null?"":status.optString("alias");a.episodes=eps==null?j.optInt("ep_count"):eps.optInt("count");a.malId=ids==null?0:ids.optInt("myanimelist_id");if(a.malId<=0&&ids!=null)a.malId=ids.optInt("shikimori_id");a.kpId=ids==null?0:ids.optInt("kp_id");a.libriaAlias=ids==null?"":ids.optString("anilibria_alias","");a.blocked=j.optBoolean("blocked",false);genres(a,j.optJSONArray("genres"),"title");return a;}
    private static Anime amAnime(JSONObject j){Anime a=new Anime();a.source="animelib";a.id=j.optString("id");a.title=j.optString("rus_name",j.optString("name","Аниме"));a.original=j.optString("name",j.optString("eng_name",""));a.alias=j.optString("slug_url",a.id);JSONObject p=j.optJSONObject("cover"),type=j.optJSONObject("type"),age=j.optJSONObject("ageRestriction"),rating=j.optJSONObject("rating"),status=j.optJSONObject("status"),episodes=j.optJSONObject("episodes");a.poster=p==null?"":safeUrl(p.optString("default"));try{a.year=Integer.parseInt(j.optString("releaseDate","").substring(0,4));}catch(Exception ignored){}a.type=type==null?"Аниме":type.optString("label");a.age=age==null?"":age.optString("label");a.score=rating==null?j.optDouble("shiki_rate",0):rating.optDouble("average",0);a.status=status!=null&&status.optInt("id")==1?"ongoing":"released";a.malId=j.optInt("shiki_id",parseTrailingId(j.optString("shikimori_href",j.optString("shiki_href",""))));a.anilistId=j.optInt("anilist_id",parseTrailingId(j.optString("anilist_href","")));a.blocked=j.optBoolean("is_licensed",false);a.description=plain(first(j.optString("description",""),prose(j.opt("summary"),0)));a.episodes=episodes==null?j.optInt("episodes_count",0):episodes.optInt("count",0);genres(a,j.optJSONArray("genres"),"name");return a;}
    private static String first(String a,String b){return a!=null&&!a.isEmpty()?a:b==null?"":b;}
    private static String prose(Object value,int depth){if(value==null||depth>12)return "";if(value instanceof String)return plain((String)value);if(!(value instanceof JSONObject))return "";JSONObject j=(JSONObject)value;if(j.has("text"))return j.optString("text");StringBuilder s=new StringBuilder();JSONArray a=j.optJSONArray("content");for(int i=0;a!=null&&i<a.length();i++){s.append(prose(a.opt(i),depth+1));if(j.optString("type").equals("doc"))s.append("\n\n");}return s.toString().trim();}
    private static int parseTrailingId(String value){try{Matcher m=Pattern.compile("(\\d+)(?:/)?$").matcher(value==null?"":value);return m.find()?Integer.parseInt(m.group(1)):0;}catch(Exception e){return 0;}}
    private static Anime libriaAnime(JSONObject j){Anime a=new Anime();a.source="anilibria";a.id=j.optString("id");JSONObject name=j.optJSONObject("name"),poster=j.optJSONObject("poster"),type=j.optJSONObject("type"),age=j.optJSONObject("age_rating");a.title=name==null?"Аниме":name.optString("main","Аниме");a.original=name==null?"":name.optString("english");a.alias=j.optString("alias");a.year=j.optInt("year");a.type=type==null?"Аниме":type.optString("description","Аниме");JSONObject opt=poster==null?null:poster.optJSONObject("optimized");String path=opt==null?(poster==null?"":poster.optString("preview")):opt.optString("preview");a.poster=path.startsWith("/")?"https://anilibria.top"+path:safeUrl(path);a.age=age==null?"":age.optString("label");a.description=plain(j.optString("description"));a.episodes=j.optInt("episodes_total");a.status=j.optBoolean("is_ongoing")?"ongoing":"released";a.blocked=j.optBoolean("is_blocked_by_geo")||j.optBoolean("is_blocked_by_copyrights");genres(a,j.optJSONArray("genres"),"name");JSONArray eps=j.optJSONArray("episodes");for(int i=0;eps!=null&&i<eps.length();i++){JSONObject e=eps.optJSONObject(i);if(e==null)continue;Anime.Episode ep=new Anime.Episode();ep.id=e.optString("id");ep.number=e.optDouble("ordinal");ep.name=e.optString("name");ep.duration=e.optInt("duration");putStream(ep,480,e.optString("hls_480"));putStream(ep,720,e.optString("hls_720"));putStream(ep,1080,e.optString("hls_1080"));JSONObject op=e.optJSONObject("opening");if(op!=null){ep.openingStart=op.optInt("start");ep.openingEnd=op.optInt("stop");}a.episodeList.add(ep);}a.episodeList.sort(Comparator.comparingDouble(e->e.number));return a;}
    private static String kind(String value){switch(value.toLowerCase(Locale.ROOT)){case "tv":case "tv_short":return "ТВ";case "movie":return "Фильм";case "ona":return "ONA";case "ova":return "OVA";case "special":case "tv_special":return "Спешл";case "music":return "Клип";default:return "Аниме";}}
}
