package app.yoru.mobile;

import android.content.Context;
import android.net.Uri;
import android.text.Html;
import org.jsoup.Jsoup;
import org.jsoup.nodes.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;

public final class ApiRepository {
    public static final LinkedHashMap<String,String> sourceNames=new LinkedHashMap<>();
    private static final String[] REAL_SOURCES={"yummy","anilibria","animevost","animelib","animego","animedia","shikimori"};
    private static final String[] ANIMEGO_BASES={"https://animego.me","https://animego.org","https://animego.one"};
    static {sourceNames.put("all","Все источники");sourceNames.put("yummy","YummyAnime");sourceNames.put("anilibria","AniLiberty");sourceNames.put("animevost","AnimeVost");sourceNames.put("animelib","AniLib");sourceNames.put("animego","AnimeGO");sourceNames.put("animedia","AniMedia");sourceNames.put("shikimori","Shikimori");}
    public static final String[] PLAYER_IDS={"auto","yummy","anilibria","animevost","animelib","animego","animedia"};
    public static final String[] PLAYER_NAMES={"Все источники","YummyAnime","AniLiberty","AnimeVost","AniLib","AnimeGO","AniMedia"};
    private static final String SH_FIELDS="id malId name russian english kind rating score status episodes episodesAired airedOn{year date} poster{mainUrl originalUrl} genres{id russian name}";
    private final Context context;
    private final Map<String,Cache> cache=Collections.synchronizedMap(new LinkedHashMap<String,Cache>(32,.75f,true){protected boolean removeEldestEntry(Map.Entry<String,Cache> e){return size()>32;}});
    private final Map<String,Anime> known=Collections.synchronizedMap(new LinkedHashMap<>());
    private final ArrayList<Anime> seed=new ArrayList<>();
    private final java.util.concurrent.ConcurrentHashMap<String,Long> counts=new java.util.concurrent.ConcurrentHashMap<>();
    private String publicToken="";
    private long tokenAt;
    private static final class Cache {String text;long at;Cache(String t){text=t;at=System.currentTimeMillis();}}
    public static final class Filter {public String year="",genre="",type="",status="",sort="RATING_DESC",season="";}
    public ApiRepository(Context c){context=c.getApplicationContext();try{JSONObject boot=new JSONObject(readStream(context.getAssets().open("boot.json"),3*1024*1024));JSONArray rows=boot.optJSONArray("releases");for(int i=0;rows!=null&&i<rows.length();i++){Anime a=Anime.from(rows.getJSONObject(i));a.cached=true;if(a.id.equals("9542"))a.malId=52991;if(a.id.equals("9600"))a.malId=52299;if(a.id.equals("9555"))a.malId=54492;seed.add(a);known.put(a.key(),a);}}catch(Exception ignored){}try{JSONObject cs=new JSONObject(readStream(context.getAssets().open("counts.json"),100000));Iterator<String> it=cs.keys();while(it.hasNext()){String key=it.next();JSONObject row=cs.optJSONObject(key);long n=row==null?-1:row.optLong("value",-1);if(n>=0)counts.put(key,n);}}catch(Exception ignored){}}
    public long countOf(String source){if("all".equals(source)){long sum=0;for(String s:REAL_SOURCES){Long n=counts.get(s);if(n!=null&&n>0)sum+=n;}return sum>0?sum:-1;}Long n=counts.get(source);return n==null?-1:n;}
    public void clearMemory(){cache.clear();}
    public List<Anime> seed(){return new ArrayList<>(seed);}
    public Anime remember(Anime a){if(Anime.valid(a)){known.put(a.key(),a);if(known.size()>1800){synchronized(known){String first=known.keySet().iterator().next();known.remove(first);}}}return a;}
    public Anime known(String key){return known.get(key);}
    static String readStream(InputStream in,int max)throws IOException{try(InputStream input=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=input.read(b))!=-1){if(out.size()+n>max)throw new IOException("Слишком большой ответ источника");out.write(b,0,n);}return out.toString("UTF-8");}}
    public static String safeUrl(String value){if(value==null||value.trim().isEmpty())return "";value=value.trim().replace(" ","%20").replace("\\/","/").replace("&amp;","&");if(value.startsWith("//"))value="https:"+value;try{Uri u=Uri.parse(value);String h=u.getHost();if(h==null)return "";h=h.toLowerCase(Locale.ROOT);if("http".equals(u.getScheme())&&(h.equals("video.animetop.info")||h.equals("media.animetop.info")||h.equals("static.openni.ru")))u=u.buildUpon().scheme("https").build();String scheme=u.getScheme();if(!("https".equals(scheme)||"http".equals(scheme))||u.getUserInfo()!=null||(!h.contains("."))||h.equals("localhost")||h.endsWith(".local")||h.matches("^(127|10|0|192\\.168|169\\.254)\\..*")||h.matches("^172\\.(1[6-9]|2[0-9]|3[01])\\..*"))return "";return u.toString();}catch(Exception e){return "";}}
    String request(String url,String method,String body,boolean form)throws Exception{return request(url,method,body,form,null);}
    String request(String url,String method,String body,boolean form,Map<String,String> headers)throws Exception{
        String ck=method+" "+url+" "+(body==null?"":body)+" "+(headers==null?"":headers.toString());Cache hit=cache.get(ck);if(hit!=null&&System.currentTimeMillis()-hit.at<45000)return hit.text;
        String current=url;String currentMethod=method,currentBody=body;
        for(int redirect=0;redirect<5;redirect++){
            if(Thread.currentThread().isInterrupted())throw new InterruptedIOException();if(safeUrl(current).isEmpty())throw new IOException("Недопустимый адрес");
            URL target=new URL(current);String host=target.getHost()==null?"":target.getHost().toLowerCase(Locale.ROOT);HttpURLConnection c=(HttpURLConnection)target.openConnection();c.setConnectTimeout(13000);c.setReadTimeout(22000);c.setInstanceFollowRedirects(false);c.setRequestMethod(currentMethod);c.setRequestProperty("Accept","application/json,text/html;q=0.9,*/*;q=0.6");c.setRequestProperty("Accept-Language","ru-RU,ru;q=0.9,en;q=0.5");c.setRequestProperty("User-Agent",host.contains("animego.")?"Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/126 Mobile Safari/537.36":"YORU-Android/2.1");if(host.contains("animego.")){c.setRequestProperty("X-Requested-With","XMLHttpRequest");c.setRequestProperty("Referer",target.getProtocol()+"://"+target.getHost()+"/");}
            if(headers!=null)for(Map.Entry<String,String> e:headers.entrySet())if(e.getKey()!=null&&e.getValue()!=null)c.setRequestProperty(e.getKey(),e.getValue());
            try{if(currentBody!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type",form?"application/x-www-form-urlencoded; charset=UTF-8":"application/json; charset=UTF-8");try(OutputStream out=c.getOutputStream()){out.write(currentBody.getBytes(StandardCharsets.UTF_8));}}
                int code=c.getResponseCode();if(code>=300&&code<400){String loc=c.getHeaderField("Location");if(loc==null)throw new IOException("Источник не ответил");current=new URL(new URL(current),loc).toString();if(code!=307&&code!=308){currentMethod="GET";currentBody=null;}continue;}
                if(code==429)throw new IOException("Источник временно ограничил частоту запросов. Попробуйте позже.");if(code<200||code>=300)throw new IOException("Источник сейчас недоступен. Попробуйте другой вариант.");String text=readStream(c.getInputStream(),12*1024*1024);if(text.length()<450000)cache.put(ck,new Cache(text));return text;
            }finally{c.disconnect();}
        }
        throw new IOException("Источник не ответил");
    }
    String document(String u)throws Exception{return request(u,"GET",null,false);}
    String formPage(String u,String body)throws Exception{return request(u,"POST",body,true);}
    private JSONObject get(String u)throws Exception{return new JSONObject(request(u,"GET",null,false));}
    private JSONObject postJson(String u,JSONObject j)throws Exception{return new JSONObject(request(u,"POST",j.toString(),false));}
    private JSONObject postForm(String u,String key,String value)throws Exception{return new JSONObject(request(u,"POST",enc(key)+"="+enc(value),true));}
    private static String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){return "";}}
    public static String query(String base,Map<String,String> params){StringBuilder s=new StringBuilder(base);for(Map.Entry<String,String> e:params.entrySet()){if(e.getValue()==null||e.getValue().isEmpty())continue;s.append(s.indexOf("?")>=0?'&':'?').append(enc(e.getKey())).append('=').append(enc(e.getValue()));}return s.toString();}
    private static LinkedHashMap<String,String> params(String...kv){LinkedHashMap<String,String> p=new LinkedHashMap<>();for(int i=0;i+1<kv.length;i+=2)p.put(kv[i],kv[i+1]);return p;}
    private JSONObject shiki(String q)throws Exception{JSONObject j=postJson("https://shikimori.io/api/graphql",new JSONObject().put("query",q));if(j.has("errors"))throw new IOException("Источник не ответил на запрос");return j.getJSONObject("data");}
    public Anime.Page catalog(String source,String search,int page,Filter f)throws Exception{
        if(f==null)f=new Filter();if(source==null||source.isEmpty())source="all";if(source.equals("all"))return allCatalog(search,page,f);if(source.equals("animedia"))return new NativeSources(this).catalog(source,search,page);if(source.equals("animego"))return animeGoCatalog(search,page);
        Anime.Page out=new Anime.Page();out.page=page;JSONArray rows;String q=search==null?"":search.trim();int limit=24;
        if(source.equals("shikimori")){
            String args="limit:24,page:"+page+",order:"+(f.sort.equals("POPULARITY")?"popularity":"ranked")+",rating:\"!rx\"";
            if(!q.isEmpty())args+=",search:"+JSONObject.quote(q);if(!f.year.isEmpty())args+=",season:"+JSONObject.quote((f.season.isEmpty()?"":f.season+"_")+f.year);if(!f.genre.isEmpty())args+=",genre:"+JSONObject.quote(f.genre);if(!f.type.isEmpty())args+=",kind:"+JSONObject.quote(f.type.toLowerCase(Locale.ROOT));if(!f.status.isEmpty())args+=",status:"+JSONObject.quote(f.status);
            rows=shiki("{animes("+args+"){"+SH_FIELDS+"}}").optJSONArray("animes");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(shikiAnime(rows.getJSONObject(i))));out.more=rows!=null&&rows.length()==limit;
        }else if(source.equals("animevost")){
            JSONObject data=q.isEmpty()?get("https://api.animevost.org/v1/last?quantity=24&page="+page):postForm("https://api.animevost.org/v1/search","name",q);rows=data.optJSONArray("data");if(rows==null)rows=new JSONArray();if(q.isEmpty()){JSONObject st=data.optJSONObject("state");out.total=st==null?-1:st.optLong("count",-1);for(int i=0;i<rows.length();i++)out.items.add(remember(vostAnime(rows.getJSONObject(i))));out.more=out.total>page*24;}else{out.total=rows.length();for(int i=(page-1)*24;i<Math.min(rows.length(),page*24);i++)out.items.add(remember(vostAnime(rows.getJSONObject(i))));out.more=rows.length()>page*24;}
        }else if(source.equals("yummy")){
            Map<String,String> p=params("limit","24","offset",String.valueOf((page-1)*24),"q",q,"sort",f.sort.equals("YEAR_DESC")?"year":"rating","sort_forward","false","genres",f.genre,"from_year",f.year,"to_year",f.year,"types",f.type.toLowerCase(Locale.ROOT),"status",f.status.equals("anons")?"announcement":f.status);JSONObject data=get(query("https://api.yani.tv/anime",p));if(data.has("error"))throw new IOException("Источник сейчас недоступен");rows=data.optJSONArray("response");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(yummyAnime(rows.getJSONObject(i))));out.more=rows!=null&&rows.length()==24;
        }else if(source.equals("animelib")){
            Map<String,String> p=params("page",String.valueOf(page),"q",q,"sort_by",f.sort.equals("FRESH_AT_DESC")?"last_episode_at":"rate_avg");String u=query("https://api.cdnlibs.org/api/anime",p)+"&fields%5B%5D=rate&fields%5B%5D=rate_avg&fields%5B%5D=releaseDate&fields%5B%5D=summary";if(!f.status.isEmpty())u+="&status%5B%5D="+(f.status.equals("ongoing")?"1":"2");JSONObject data=get(u);rows=data.optJSONArray("data");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(amAnime(rows.getJSONObject(i))));JSONObject links=data.optJSONObject("links");out.more=links!=null&&!links.isNull("next")&&!links.optString("next","").isEmpty();
        }else if(source.equals("anilibria")){
            Map<String,String> p=params("limit","24","page",String.valueOf(page),"f[search]",q,"f[sorting]",f.sort.equals("POPULARITY")?"RATING_DESC":f.sort,"f[genres]",f.genre,"f[types]",f.type,"f[years][from_year]",f.year,"f[years][to_year]",f.year,"f[publish_statuses]",f.status.isEmpty()?"":f.status.equals("ongoing")?"IS_ONGOING":"IS_NOT_ONGOING");JSONObject data=get(query("https://anilibria.top/api/v1/anime/catalog/releases",p));rows=data.optJSONArray("data");for(int i=0;rows!=null&&i<rows.length();i++)out.items.add(remember(libriaAnime(rows.getJSONObject(i))));JSONObject meta=data.optJSONObject("meta"),pg=meta==null?null:meta.optJSONObject("pagination");if(pg!=null){out.total=pg.optLong("total",-1);out.more=page<pg.optInt("total_pages");}
        }else throw new IOException("Неизвестный источник");
        if(out.total>=0&&q.isEmpty()&&f.genre.isEmpty()&&f.year.isEmpty()&&f.type.isEmpty()&&f.status.isEmpty())counts.put(source,out.total);return out;
    }
    private Anime.Page allCatalog(String search,int page,Filter f)throws Exception{Anime.Page out=new Anime.Page();out.page=page;LinkedHashMap<String,Anime> items=new LinkedHashMap<>();boolean more=false;int ok=0;for(String s:REAL_SOURCES){try{Anime.Page p=catalog(s,search,page,f);ok++;more|=p.more;for(Anime a:p.items)items.put(a.key(),a);}catch(Exception ignored){}}out.items.addAll(items.values());out.more=more;if((search==null||search.trim().isEmpty())&&countOf("all")>0)out.total=countOf("all");if(out.items.isEmpty()&&ok==0)throw new IOException("Источники сейчас недоступны");return out;}
    public Anime details(Anime base,boolean episodes)throws Exception{
        if(base.source.equals("animedia"))return new NativeSources(this).details(base,episodes);
        Anime a;String id=base.id;
        switch(base.source){
            case "shikimori":{JSONArray rows=shiki("{animes(ids:"+JSONObject.quote(id)+",limit:1){"+SH_FIELDS+" descriptionHtml related{relationKind anime{"+SH_FIELDS+"}}}}").optJSONArray("animes");if(rows==null||rows.length()==0)throw new IOException("Аниме не найдено");JSONObject j=rows.getJSONObject(0);a=shikiAnime(j);a.description=plain(j.optString("descriptionHtml"));JSONArray rel=j.optJSONArray("related");for(int i=0;rel!=null&&i<rel.length();i++){JSONObject r=rel.getJSONObject(i).optJSONObject("anime");if(r!=null)a.related.add(remember(shikiAnime(r)));}break;}
            case "animevost":{JSONArray rows=postForm("https://api.animevost.org/v1/info","id",id).optJSONArray("data");if(rows==null||rows.length()==0)throw new IOException("Аниме не найдено");a=vostAnime(rows.getJSONObject(0));if(episodes){JSONArray list=new JSONArray(request("https://api.animevost.org/v1/playlist","POST","id="+enc(id),true));for(int i=0;i<list.length();i++){JSONObject e=list.getJSONObject(i);Anime.Episode ep=new Anime.Episode();ep.id=id+"-"+i;ep.name=e.optString("name","");ep.number=numberIn(ep.name,i+1);putStream(ep,480,e.optString("std"));putStream(ep,720,e.optString("hd"));a.episodeList.add(ep);}a.episodes=Math.max(a.episodes,a.episodeList.size());}break;}
            case "yummy":{JSONObject d=get("https://api.yani.tv/anime/"+enc(id)).optJSONObject("response");if(d==null)throw new IOException("YummyAnime не вернул карточку");a=yummyAnime(d);if(episodes){a.episodeList.addAll(YummyParser.episodes(id));a.episodes=Math.max(a.episodes,a.episodeList.size());}break;}
            case "animelib":{String slug=base.alias.isEmpty()?id:base.alias;JSONObject d=get("https://api.cdnlibs.org/api/anime/"+enc(slug)+"?fields[]=summary&fields[]=genres&fields[]=releaseDate&fields[]=shiki_id&fields[]=anilist_id&fields[]=rate&fields[]=rate_avg").getJSONObject("data");a=amAnime(d);if(episodes){JSONArray rows=get("https://api.cdnlibs.org/api/episodes?anime_id="+enc(a.alias)).optJSONArray("data");for(int i=0;rows!=null&&i<rows.length();i++){JSONObject e=rows.getJSONObject(i);double n=e.optDouble("number",-1);if(n<0||!Double.isFinite(n))continue;Anime.Episode ep=new Anime.Episode();ep.id=e.optString("id");ep.number=n;ep.name=e.optString("name","");ep.lazy="animelib";a.episodeList.add(ep);}a.episodeList.sort(Comparator.comparingDouble(e->e.number));a.episodes=a.episodeList.size();}break;}
            case "anilibria":{a=libriaAnime(get("https://anilibria.top/api/v1/anime/releases/"+enc(id)));break;}
            case "animego":{a=animeGoDetails(base,episodes);break;}
            default:throw new IOException("Неизвестный источник");
        }
        if(a.year==0)a.year=base.year;if(a.malId==0)a.malId=base.malId;if(a.kpId==0)a.kpId=base.kpId;if(a.description.isEmpty())a.description=base.description;if(a.poster.isEmpty())a.poster=base.poster;return remember(a);
    }
    public Anime.Playback playback(Anime input,String selectedMode)throws Exception{
        normalizeIds(input);
        String selected=selectedMode==null||selectedMode.trim().isEmpty()?"auto":selectedMode.trim();
        if(selected.equals("all"))selected="auto";
        if(!selected.equals("auto")){
            Anime video=findPlayableSource(input,selected);
            if(video==null)throw new IOException("Источник сейчас не вернул серии");
            return playbackResult(input,video,selected);
        }
        ArrayList<String> order=new ArrayList<>();
        if(Arrays.asList("animevost","anilibria","animedia","animelib","animego","yummy").contains(input.source))order.add(input.source);
        for(String source:new String[]{"yummy","anilibria","animevost","animelib","animego","animedia"})if(!order.contains(source))order.add(source);
        for(String source:order){Anime video=findPlayableSource(input,source);if(video!=null)return playbackResult(input,video,source);}
        throw new IOException("Источники сейчас не вернули серии");
    }
    private Anime.Playback playbackResult(Anime catalog,Anime video,String provider){Anime.Playback r=new Anime.Playback();r.catalog=catalog;r.video=video;r.provider=provider==null||provider.isEmpty()?video.source:provider;return r;}
    private Anime findPlayableSource(Anime input,String source){try{Anime candidate=findSourceCandidate(input,source);if(candidate==null)return null;Anime full=candidate.episodeList.isEmpty()?details(candidate,true):candidate;if(!full.blocked&&!full.episodeList.isEmpty())return full;}catch(Exception ignored){}return null;}
    private Anime findSourceCandidate(Anime input,String source)throws Exception{
        if(source.equals(input.source)&&Arrays.asList("animevost","anilibria","animedia","animelib","animego","yummy").contains(source))return input;
        if(source.equals("yummy"))return findYummy(input);
        if(source.equals("anilibria")){Anime v=findAniLiberty(input);if(v!=null)return v;}
        if(source.equals("animelib")){Anime v=findAniLib(input);if(v!=null)return v;}
        if(Arrays.asList("animevost","animego","animedia").contains(source))return searchSource(input,source);
        return null;
    }
    public synchronized void loadEpisode(Anime.Episode ep)throws Exception{if(ep.lazy.equals("animedia")){new NativeSources(this).loadEpisode(ep);return;}if(ep.lazy.equals("animego")){loadAnimeGoEpisode(ep);return;}if(!"animelib".equals(ep.lazy)||!ep.variants.isEmpty())return;JSONObject d=get("https://api.cdnlibs.org/api/episodes/"+enc(ep.id)).getJSONObject("data");JSONArray rows=d.optJSONArray("players");for(int i=0;rows!=null&&i<rows.length();i++){JSONObject v=rows.getJSONObject(i);if(!v.optString("player").equalsIgnoreCase("kodik"))continue;String u=embed(v.optString("src"));if(u.isEmpty())continue;JSONObject team=v.optJSONObject("team"),t=v.optJSONObject("translation_type");String name=(t==null?"Озвучка":t.optString("label","Озвучка"))+" "+(team==null?"":team.optString("name",""));ep.variants.add(new Anime.Variant(name.trim(),"Kodik",u));}if(ep.variants.isEmpty())throw new IOException("У серии нет доступного плеера");}
    public static final class DownloadOption {public Anime source;public Anime.Episode episode;public int quality;public String voice="",player="";public DownloadOption(Anime a,Anime.Episode e,int q){source=a;episode=e;quality=q;}public DownloadOption(Anime a,Anime.Episode e,int q,String v,String p){source=a;episode=e;quality=q;voice=v==null?"":v;player=p==null?"":p;}public String label(){String sourceName=downloadSourceName(source.source);String extra=voice.isEmpty()?"":voice;String p=player.isEmpty()?"":" · "+player;return (quality>0?quality+"p":"Оригинал")+" · "+sourceName+(extra.isEmpty()?"":" · "+extra)+p;}}
    private List<DownloadOption> options(Anime source,double number)throws Exception{ArrayList<DownloadOption> out=new ArrayList<>();if(source==null||source.blocked)return out;for(Anime.Episode e:source.episodeList)if(sameEpisode(e.number,number)){try{loadEpisode(e);}catch(Exception ignored){}for(int q:e.streams.keySet())out.add(new DownloadOption(source,e,q));if(!e.variants.isEmpty())out.addAll(variantOptions(source,e));break;}return uniqueOptions(out);}
    private List<DownloadOption> variantOptions(Anime source,Anime.Episode episode){ArrayList<DownloadOption> out=new ArrayList<>();if(episode.variants.isEmpty())return out;ExecutorService pool=Executors.newFixedThreadPool(Math.max(1,Math.min(6,episode.variants.size())));ArrayList<Future<List<DownloadOption>>> jobs=new ArrayList<>();for(Anime.Variant v:episode.variants)jobs.add(pool.submit(()->{ArrayList<DownloadOption> rows=new ArrayList<>();try{TreeMap<Integer,String> streams=VideoResolver.resolve(this,v.url);if(streams.isEmpty())return rows;Anime.Episode copy=new Anime.Episode();copy.id=episode.id+"-"+Integer.toHexString((v.name+"|"+v.player+"|"+v.url).hashCode());copy.number=episode.number;copy.name=v.label();copy.duration=v.duration;copy.openingStart=v.openingStart;copy.openingEnd=v.openingEnd;copy.streams.putAll(streams);for(int q:copy.streams.keySet())rows.add(new DownloadOption(source,copy,q,v.label(),v.player));}catch(Exception ignored){}return rows;}));long deadline=System.currentTimeMillis()+65000;for(Future<List<DownloadOption>> job:jobs){long left=deadline-System.currentTimeMillis();if(left<=0){job.cancel(true);continue;}try{out.addAll(job.get(left,TimeUnit.MILLISECONDS));}catch(Exception ignored){job.cancel(true);}}pool.shutdownNow();return out;}
    private void collectOptions(ArrayList<DownloadOption> out,LinkedHashSet<String> tried,Anime source,double number){if(source==null)return;String key="options|"+source.key()+"|"+number;if(!tried.add(key))return;try{out.addAll(options(source,number));}catch(Exception ignored){}}
    private void collectDetailsOptions(ArrayList<DownloadOption> out,LinkedHashSet<String> tried,Anime source,double number){if(source==null)return;String key="details|"+source.key()+"|"+number;if(!tried.add(key))return;try{collectOptions(out,tried,details(source,true),number);}catch(Exception ignored){}}
    private void collectCatalogMatches(ArrayList<DownloadOption> out,LinkedHashSet<String> tried,Anime base,String source,double number){int found=0;for(String term:searchTerms(base)){try{Anime.Page page=catalog(source,term,1,new Filter());for(Anime item:page.items){if(!matchesAnime(item,base))continue;collectDetailsOptions(out,tried,item,number);found++;if(found>=3)return;}}catch(Exception ignored){}}}
    private void collectDirectKodik(ArrayList<DownloadOption> out,LinkedHashSet<String> tried,Anime base,double number){try{int mal=base.malId>0?base.malId:resolveMal(base);String url=directKodik(mal);if(url.isEmpty())return;Uri u=Uri.parse(url);String path=u.getPath();if(path==null||!path.startsWith("/video/"))url=u.buildUpon().appendQueryParameter("episode",episodeParam(number)).build().toString();collectIframeOptions(out,tried,base,"kodik","Kodik","Kodik",url,number);}catch(Exception ignored){}}
    private void collectIframeOptions(ArrayList<DownloadOption> out,LinkedHashSet<String> tried,Anime base,String sourceId,String sourceTitle,String player,String iframe,double number){String url=embed(iframe);if(url.isEmpty())return;String key="iframe|"+sourceId+"|"+number+"|"+url;if(!tried.add(key))return;try{TreeMap<Integer,String> streams=VideoResolver.resolve(this,url);if(streams.isEmpty())return;Anime source=new Anime();source.source=sourceId;source.id=(base.key()+"|"+sourceId+"|"+Integer.toHexString(url.hashCode())).replace(':','_');source.title=sourceTitle;source.original=base.original;source.poster=base.poster;source.description=base.description;source.year=base.year;source.type=base.type;source.status=base.status;source.episodes=base.episodes;source.malId=base.malId;source.anilistId=base.anilistId;source.kpId=base.kpId;Anime.Episode ep=new Anime.Episode();ep.id=source.id+"-"+episodeParam(number);ep.number=number;ep.name=sourceTitle;ep.streams.putAll(streams);for(int q:streams.keySet())out.add(new DownloadOption(source,ep,q,sourceTitle,player));}catch(Exception ignored){}}
    private static ArrayList<DownloadOption> uniqueOptions(List<DownloadOption> options){LinkedHashMap<String,DownloadOption> unique=new LinkedHashMap<>();for(DownloadOption d:options){if(d==null||d.episode==null)continue;String url=d.episode.streams.get(d.quality);String safe=safeUrl(url);if(safe.isEmpty())continue;unique.put((d.source==null?"":d.source.source)+"|"+d.quality+"|"+d.voice+"|"+d.player+"|"+safe,d);}ArrayList<DownloadOption> list=new ArrayList<>(unique.values());list.sort((a,b)->{int s=downloadSourceRank(a.source.source)-downloadSourceRank(b.source.source);if(s!=0)return s;int q=Integer.compare(b.quality,a.quality);if(q!=0)return q;return a.label().compareToIgnoreCase(b.label());});return list;}
    public List<DownloadOption> downloadOptions(Anime a,Anime.Playback current,double number)throws Exception{
        ArrayList<DownloadOption> out=new ArrayList<>();if(a==null||a.blocked)return out;normalizeIds(a);LinkedHashSet<String> tried=new LinkedHashSet<>();
        if(current!=null){collectOptions(out,tried,current.video,number);if(!current.directUrl.isEmpty())collectIframeOptions(out,tried,a,current.provider.isEmpty()?"player":current.provider,current.provider.isEmpty()?"Плеер":current.provider,current.directKodik?"Kodik":"Iframe",current.directUrl,number);}
        if(Arrays.asList("animevost","anilibria","animedia","animelib","animego","yummy").contains(a.source))collectDetailsOptions(out,tried,a,number);
        Anime y=null;try{y=findYummy(a);if(y!=null)collectDetailsOptions(out,tried,y,number);}catch(Exception ignored){}
        collectDirectKodik(out,tried,a,number);
        try{String alias=a.libriaAlias.isEmpty()?(y==null?"":y.libriaAlias):a.libriaAlias;if(!alias.isEmpty())collectOptions(out,tried,libriaAnime(get("https://anilibria.top/api/v1/anime/releases/"+enc(alias))),number);}catch(Exception ignored){}
        for(String source:new String[]{"anilibria","animevost","animelib","animego","animedia"})collectCatalogMatches(out,tried,a,source,number);
        return uniqueOptions(out);
    }
    private Anime findAniLiberty(Anime a)throws Exception{normalizeIds(a);Anime y=null;try{y=findYummy(a);}catch(Exception ignored){}String alias=a.libriaAlias.isEmpty()?(y==null?"":y.libriaAlias):a.libriaAlias;if(!alias.isEmpty())return libriaAnime(get("https://anilibria.top/api/v1/anime/releases/"+enc(alias)));return searchSource(a,"anilibria");}
    private Anime searchSource(Anime a,String source)throws Exception{for(String term:searchTerms(a)){Anime.Page page=catalog(source,term,1,new Filter());for(Anime item:page.items)if(matchesAnime(item,a))return item;}return null;}
    private static boolean matchesAnime(Anime candidate,Anime base){if(candidate==null||base==null)return false;if(candidate.malId>0&&base.malId>0&&candidate.malId==base.malId)return true;if(candidate.anilistId>0&&base.anilistId>0&&candidate.anilistId==base.anilistId)return true;String bt=plainName(base.title),bo=plainName(base.original),ct=plainName(candidate.title),co=plainName(candidate.original);boolean title=(!bt.isEmpty()&&(bt.equals(ct)||bt.equals(co)))||(!bo.isEmpty()&&(bo.equals(ct)||bo.equals(co)));return title&&(base.year==0||candidate.year==0||Math.abs(base.year-candidate.year)<=1);}
    private static LinkedHashSet<String> searchTerms(Anime a){LinkedHashSet<String> terms=new LinkedHashSet<>();if(a!=null){if(!a.title.trim().isEmpty())terms.add(a.title.trim());if(!a.original.trim().isEmpty())terms.add(a.original.trim());String alias=plain(a.alias);if(!alias.isEmpty()&&alias.length()<120&&!alias.contains("/"))terms.add(alias);}return terms;}
    private static boolean sameEpisode(double a,double b){return Math.abs(a-b)<0.001;}
    private static String episodeParam(double n){return sameEpisode(n,Math.floor(n))?String.valueOf((int)Math.floor(n)):String.valueOf(n);}
    public static String downloadSourceName(String id){String name=sourceNames.get(id);if(name!=null)return name;if("kodik".equals(id))return "Kodik";if("player".equals(id))return "Плеер";return id==null||id.isEmpty()?"Источник":id;}
    private static int downloadSourceRank(String id){if("yummy".equals(id))return 0;if("anilibria".equals(id))return 1;if("animevost".equals(id))return 2;if("animelib".equals(id))return 3;if("animego".equals(id))return 4;if("animedia".equals(id))return 5;if("kodik".equals(id))return 6;return 20;}
    private static void normalizeIds(Anime a){if(a!=null&&a.malId==0&&"shikimori".equals(a.source))try{a.malId=Integer.parseInt(a.id);}catch(Exception ignored){}}
    private Anime findYummy(Anime a)throws Exception{normalizeIds(a);String url=a.malId>0?"https://api.yani.tv/anime?shikimori_ids="+a.malId+"&limit=20":"https://api.yani.tv/anime?q="+enc(a.title)+"&limit=20";JSONArray rows=get(url).optJSONArray("response");Anime found=null;for(int i=0;rows!=null&&i<rows.length();i++){Anime y=yummyAnime(rows.getJSONObject(i));if(a.malId>0){JSONObject remote=rows.getJSONObject(i).optJSONObject("remote_ids");if(remote!=null&&(remote.optInt("myanimelist_id")==a.malId||remote.optInt("shikimori_id")==a.malId))return remember(y);}if(a.malId==0&&plainName(y.title).equals(plainName(a.title))&&(a.year==0||a.year==y.year)){if(found!=null&&found.malId!=y.malId)return null;found=y;}}return found==null?null:remember(found);}
    private Anime findAniLib(Anime a)throws Exception{normalizeIds(a);Anime best=null;for(String q:searchTerms(a)){Anime.Page page=catalog("animelib",q,1,new Filter());for(Anime item:page.items){if(!matchesAnime(item,a))continue;Anime full=details(item,false);if(a.malId>0&&full.malId==a.malId)return item;if(a.anilistId>0&&full.anilistId==a.anilistId)return item;if(best==null)best=item;}}return best;}
    private int resolveMal(Anime a)throws Exception{if(a.malId>0)return a.malId;Anime y=findYummy(a);if(y!=null&&y.malId>0){a.malId=y.malId;a.kpId=y.kpId;return y.malId;}throw new IOException("Не удалось найти плеер. Попробуйте открыть аниме в другом каталоге.");}
    private int resolveKp(Anime a)throws Exception{if(a.kpId>0)return a.kpId;Anime y=findYummy(a);if(y!=null&&y.kpId>0){a.kpId=y.kpId;return y.kpId;}throw new IOException("У этого плеера пока нет подходящего варианта.");}
    private synchronized String token()throws Exception{if(!publicToken.isEmpty()&&System.currentTimeMillis()-tokenAt<300000)return publicToken;String script=request("https://kodik-add.com/add-players.min.js?v=2","GET",null,false);Matcher m=Pattern.compile("token\\s*=\\s*[\"']([A-Za-z0-9]{20,80})[\"']").matcher(script);if(!m.find())throw new IOException("Плеер временно недоступен");publicToken=m.group(1);tokenAt=System.currentTimeMillis();return publicToken;}
    public String directKodik(int mal)throws Exception{if(mal<=0)throw new IOException("Не удалось найти аниме у этого источника");String q=query("https://kodik-api.com/get-player",params("title","Player","hasPlayer","false","url","https://kodikdb.com/find-player?shikimoriID="+mal,"token",token(),"shikimoriID",String.valueOf(mal)));JSONObject j=get(q);if(j.has("error")||!j.optBoolean("found"))throw new IOException("У этого источника пока нет плеера");if(j.has("allowed")&&j.optInt("allowed",1)==0)throw new IOException("Просмотр ограничен источником");String u=embed(j.optString("link"));if(u.isEmpty())throw new IOException("Плеер временно недоступен");return u;}
    private String regional(String source,int kp)throws Exception{if(source.equals("flixcdn"))return "https://tarantino.factorios.live/show/kinopoisk/"+kp;if(source.equals("gendit"))return "https://horsez.org/lat/"+kp;JSONObject root=get("https://fbphdplay.top/api/players?kinopoisk="+kp);JSONArray list=root.optJSONArray("data");for(int i=0;list!=null&&i<list.length();i++){JSONObject j=list.getJSONObject(i);if(j.optString("type").equalsIgnoreCase(source)){String url=safeUrl(j.optString("iframeUrl"));if(!url.isEmpty())return url;}}throw new IOException("Источник не предложил плеер для этого аниме");}
    public static String embed(String input){if(input==null)return "";String s=input.trim().replace("&amp;","&");Matcher html=Pattern.compile("src=[\"']([^\"']+)",Pattern.CASE_INSENSITIVE).matcher(s);if(html.find())s=html.group(1);if(s.startsWith("//"))s="https:"+s;try{Uri u=Uri.parse(s);String host=u.getHost();if(host!=null&&Arrays.asList("aniqit.com","kodik.info","kodik.cc","kodik.biz").contains(host))s=u.buildUpon().scheme("https").authority("kodikplayer.com").build().toString();return safeUrl(s);}catch(Exception e){return "";}}
    private Anime.Page animeGoCatalog(String search,int page)throws Exception{Exception last=null;for(String base:ANIMEGO_BASES){try{return animeGoCatalog(base,search,page);}catch(Exception e){last=e;}}if(last!=null)throw last;throw new IOException("AnimeGO недоступен");}
    private Anime.Page animeGoCatalog(String base,String search,int page)throws Exception{String q=search==null?"":search.trim();String raw;if(q.isEmpty()){raw=animeGoAjax(base,page<=1?"/anime":"/anime/"+page,"sort=createdAt&direction=asc");if(raw.isEmpty())raw=document(base+"/anime?sort=a.createdAt&direction=desc&page="+page);}else raw=document(base+"/search/all?q="+enc(q));String html=animeGoContent(raw);Document doc=Jsoup.parse(html,base);Anime.Page out=new Anime.Page();out.page=page;LinkedHashMap<String,Anime> rows=new LinkedHashMap<>();for(Element link:doc.select(".ani-grid__item-title a[href^=/anime/],.ani-list__item-title a[href^=/anime/],a[href*=/anime/]")){Anime a=animeGoRow(base,link);if(a!=null&&!rows.containsKey(a.key()))rows.put(a.key(),remember(a));}out.items.addAll(rows.values());for(Element a:doc.select("a[href]")){String href=a.attr("href");if(href.contains("/"+(page+1))||href.contains("page="+(page+1))||a.text().trim().equals(String.valueOf(page+1)))out.more=true;}if(q.isEmpty()&&out.items.size()>=20)out.more=true;if(out.items.isEmpty()&&!doc.text().toLowerCase(Locale.ROOT).contains("ничего"))throw new IOException("AnimeGO изменил выдачу");return out;}
    private Anime animeGoDetails(Anime base,boolean episodes)throws Exception{String url=base.alias.startsWith("http")?base.alias:"";if(url.isEmpty()&&!base.alias.isEmpty())for(String root:ANIMEGO_BASES){url=root+"/anime/"+base.alias;break;}if(url.isEmpty())throw new IOException("Откройте аниме из каталога AnimeGO");String html=animeGoContent(document(url));Document doc=Jsoup.parse(html,url);Anime a=Anime.from(base.json());a.source="animego";a.alias=url;Element h=doc.selectFirst("h1,.entity__title-name,.anime-title,.title");if(h!=null&&!h.text().trim().isEmpty())a.title=h.text().trim();Element original=doc.selectFirst(".entity__title-original,.fw-lighter");if(original!=null&&!original.text().trim().isEmpty())a.original=original.text().trim();Element desc=doc.selectFirst(".description,.entity-description,.anime-description,.anime-synopsis,.text,.description-block");if(desc!=null&&!desc.text().trim().isEmpty())a.description=desc.text().trim();Element poster=doc.selectFirst(".entity__poster img,.anime-detail-picture img,.poster img,.anime-poster img,img[src*=/upload/],img[src*=/poster/]");if(poster!=null)a.poster=absolute(url,poster.hasAttr("data-src")?poster.attr("data-src"):poster.attr("src"));String text=doc.text();Matcher year=Pattern.compile("(?:Год|Дата|Выпуск|Year)[^0-9]{0,20}((?:19|20)\\d{2})",Pattern.CASE_INSENSITIVE).matcher(text);if(year.find())a.year=Integer.parseInt(year.group(1));String lower=text.toLowerCase(Locale.ROOT);if(lower.contains("фильм")||lower.contains("movie"))a.type="Фильм";else if(lower.contains("ova"))a.type="OVA";else if(lower.contains("ona"))a.type="ONA";else if(lower.contains("спешл")||lower.contains("special"))a.type="Спешл";else a.type="ТВ";Matcher ep=Pattern.compile("(?:Эпизоды|Episodes)\\D+(\\d+)(?:\\D{0,10}/\\D{0,10}(\\d+))?",Pattern.CASE_INSENSITIVE).matcher(text);if(ep.find())a.episodes=Integer.parseInt(ep.group(2)!=null&&!ep.group(2).isEmpty()?ep.group(2):ep.group(1));for(Element g:doc.select("a[href*=/genre/],a[href*=/genres/],.entity__genres a")){String name=g.text().trim();if(!name.isEmpty()&&!a.genres.contains(name)&&a.genres.size()<30)a.genres.add(name);}a.status=lower.contains("онгоинг")||lower.contains("выходит")||lower.contains("ongoing")?"ongoing":lower.contains("анонс")||lower.contains("announce")?"anons":"published";if(episodes)animeGoEpisodes(a,url);return a;}
    private void animeGoEpisodes(Anime a,String pageUrl)throws Exception{String base=new URL(pageUrl).getProtocol()+"://"+new URL(pageUrl).getHost();TreeMap<Double,Anime.Episode> rows=new TreeMap<>();String content=animeGoAjax(base,"/player/"+a.id,"");Document doc=Jsoup.parse(content,base);for(Element e:doc.select(".player-video-bar__item[data-episode]")){try{String id=e.attr("data-episode");double number=e.hasAttr("data-episode-number")?Double.parseDouble(e.attr("data-episode-number")):numberIn(e.text(),rows.size()+1);if(id.isEmpty()||rows.containsKey(number))continue;Anime.Episode ep=new Anime.Episode();ep.id=id;ep.number=number;ep.name=e.attr("data-episode-title");ep.lazy="animego";ep.resolverUrl=base+"/player/videos/"+enc(id);rows.put(number,ep);}catch(Exception ignored){}}if(rows.isEmpty()){String old=animeGoContent(document(base+"/anime/"+a.id+"/player?_allow=true"));doc=Jsoup.parse(old,base);for(Element e:doc.select("[data-episode][data-id]")){try{double number=Double.parseDouble(e.attr("data-episode"));String id=e.attr("data-id");if(id.isEmpty()||rows.containsKey(number))continue;Anime.Episode ep=new Anime.Episode();ep.id=id;ep.number=number;ep.lazy="animego";ep.resolverUrl=base+"/anime/series?id="+enc(id);rows.put(number,ep);}catch(Exception ignored){}}}if(rows.isEmpty()){Anime.Episode ep=new Anime.Episode();ep.id=a.id+"-film";ep.number=1;ep.lazy="animego";ep.resolverUrl=base+"/player/videos/"+a.id;rows.put(1d,ep);}a.episodeList.addAll(rows.values());a.episodes=Math.max(a.episodes,a.episodeList.size());}
    private void loadAnimeGoEpisode(Anime.Episode ep)throws Exception{if(!ep.variants.isEmpty())return;String content=animeGoContent(document(ep.resolverUrl));Document doc=Jsoup.parse(content,ep.resolverUrl);HashMap<String,String> names=new HashMap<>();for(Element e:doc.select("[data-dubbing]")){String id=e.attr("data-dubbing").trim();if(id.isEmpty())continue;Element name=e.selectFirst(".video-player-toggle-item-name");String text=name==null?e.text():name.text();if(!text.trim().isEmpty())names.put(id,text.trim());}HashSet<String> seen=new HashSet<>();for(Element e:doc.select("[data-player]")){String link=embed(e.attr("data-player"));if(link.isEmpty())continue;String did=e.attr("data-provide-dubbing").trim();String name=e.hasAttr("data-translation-title")?e.attr("data-translation-title").trim():(names.containsKey(did)?names.get(did):"Озвучка");String player=e.hasAttr("data-provider-title")?e.attr("data-provider-title").trim():hostName(link);if(name.isEmpty())name="Озвучка";if(player.isEmpty())player=hostName(link);String key=name+"|"+player+"|"+link;if(seen.add(key))ep.variants.add(new Anime.Variant(name,player,link));}if(ep.variants.isEmpty()){Matcher m=Pattern.compile("data-player=\"([^\"]+)\"",Pattern.CASE_INSENSITIVE).matcher(content);while(m.find()){String link=embed(m.group(1));if(!link.isEmpty()&&seen.add(link))ep.variants.add(new Anime.Variant("Озвучка",hostName(link),link));}}if(ep.variants.isEmpty())throw new IOException("У серии нет доступного плеера");ep.variants.sort(Comparator.comparing(Anime.Variant::label));}
    private String animeGoAjax(String base,String path,String query)throws Exception{String url=base+path+(query==null||query.isEmpty()?"?entities=true":"?entities=true&"+query);HashMap<String,String> h=new HashMap<>();h.put("X-Requested-With","XMLHttpRequest");h.put("Referer",base+"/");String raw=request(url,"GET",null,false,h);try{JSONObject root=new JSONObject(raw);JSONObject data=root.optJSONObject("data");if(data!=null)return data.optString("content",raw);}catch(Exception ignored){}return raw;}
    private static Anime animeGoRow(String base,Element link){String href=link.absUrl("href");if(href.isEmpty())href=absolute(base,link.attr("href"));Matcher m=Pattern.compile("/anime/([^?#]+?)-(\\d+)(?:[/?#].*)?$").matcher(href);if(!m.find())return null;Anime a=new Anime();a.source="animego";a.id=m.group(2);a.alias=href;a.title=link.attr("title").trim();Element box=link;for(int depth=0;depth<5&&box!=null;depth++,box=box.parent()){if(a.title.isEmpty()){Element title=box.selectFirst(".ani-grid__item-title,.ani-list__item-title,.h5,.card-title,.animes-list-item-title,.media-title,.title");if(title!=null)a.title=title.text().trim();}if(a.poster.isEmpty()){Element img=box.selectFirst(".ani-grid__item-picture img[src],.ani-list__item-picture img[src],img[src],img[data-src],img[data-original]");if(img!=null)a.poster=absolute(base,img.hasAttr("data-src")?img.attr("data-src"):img.hasAttr("data-original")?img.attr("data-original"):img.attr("src"));}}if(a.title.isEmpty())a.title=link.text().trim();if(a.title.length()>180)a.title=a.title.substring(0,180);if(a.title.isEmpty())return null;a.type="Аниме";a.status="published";String text=link.parent()==null?"":link.parent().text();Matcher y=Pattern.compile("(19|20)\\d{2}").matcher(text);if(y.find())a.year=Integer.parseInt(y.group());return a;}
    private static String animeGoContent(String raw){try{JSONObject j=new JSONObject(raw);if(j.has("content"))return j.optString("content",raw);JSONObject data=j.optJSONObject("data");if(data!=null&&data.has("content"))return data.optString("content",raw);}catch(Exception ignored){}return raw;}
    private static String absolute(String base,String value){try{if(value==null||value.trim().isEmpty())return "";value=value.trim().replace(" ","%20").replace("&amp;","&");if(value.startsWith("//"))value="https:"+value;return safeUrl(new URL(new URL(base),value).toString());}catch(Exception e){return "";}}
    private static String hostName(String link){try{String h=Uri.parse(link.startsWith("//")?"https:"+link:link).getHost();return h==null?"Плеер":h.replace("www.","");}catch(Exception e){return "Плеер";}}
    static String plain(String text){return Html.fromHtml(text==null?"":text,Html.FROM_HTML_MODE_LEGACY).toString().replaceAll("\\[/?[^\\]]+\\]","").trim();}
    static String plainName(String text){return (text==null?"":text).toLowerCase(Locale.ROOT).replaceAll("[^\\p{L}\\p{N}]+"," ").trim();}
    private static double numberIn(String text,double fallback){Matcher m=Pattern.compile("[0-9]+(?:\\.[0-9]+)?").matcher(text);try{return m.find()?Double.parseDouble(m.group()):fallback;}catch(Exception e){return fallback;}}
    private static void putStream(Anime.Episode ep,int q,String url){String s=safeUrl(url);if(!s.isEmpty())ep.streams.put(q,s);}
    private static void genres(Anime a,JSONArray rows,String name){for(int i=0;rows!=null&&i<rows.length();i++){Object g=rows.opt(i);if(g instanceof JSONObject){String value=((JSONObject)g).optString(name,((JSONObject)g).optString("name",""));if(!value.isEmpty()&&!a.genres.contains(value))a.genres.add(value);}else if(g instanceof String&&!a.genres.contains((String)g))a.genres.add((String)g);}}
    private static Anime shikiAnime(JSONObject j){Anime a=new Anime();a.source="shikimori";a.id=j.optString("id");a.malId=j.optInt("malId",0);if(a.malId==0)try{a.malId=Integer.parseInt(a.id);}catch(Exception ignored){}a.title=j.optString("russian","");if(a.title.isEmpty())a.title=j.optString("name","Аниме");a.original=j.optString("name","");a.type=kind(j.optString("kind"));a.status=j.optString("status");a.episodes=j.optInt("episodes");a.score=j.optDouble("score",0);JSONObject date=j.optJSONObject("airedOn"),poster=j.optJSONObject("poster");a.year=date==null?0:date.optInt("year");a.poster=poster==null?"":safeUrl(poster.optString("mainUrl",poster.optString("originalUrl")));a.age=j.optString("rating").equals("pg_13")?"13+":j.optString("rating").startsWith("r")?"18+":"";genres(a,j.optJSONArray("genres"),"russian");return a;}
    private static Anime vostAnime(JSONObject j){Anime a=new Anime();a.source="animevost";a.id=j.optString("id");String raw=j.optString("title","Аниме"),clean=raw.replaceAll("\\s*\\[[^\\]]*\\]\\s*$","");String[] names=clean.split(" / ",2);a.title=names[0];a.original=names.length>1?names[1]:"";a.description=plain(j.optString("description"));a.poster=safeUrl(j.optString("urlImagePreview"));a.year=j.optInt("year");a.type=j.optString("type","Аниме");Matcher m=Pattern.compile("из\\s*(\\d+)").matcher(raw);if(m.find())a.episodes=Integer.parseInt(m.group(1));a.status="published";for(String g:j.optString("genre","").split(","))if(!g.trim().isEmpty()&&!a.genres.contains(g.trim()))a.genres.add(g.trim());return a;}
    private static Anime yummyAnime(JSONObject j){Anime a=new Anime();a.source="yummy";a.id=j.optString("anime_id");a.title=j.optString("title","Аниме");a.alias=j.optString("anime_url");a.year=j.optInt("year");a.description=plain(j.optString("description"));JSONObject p=j.optJSONObject("poster"),type=j.optJSONObject("type"),age=j.optJSONObject("min_age"),rat=j.optJSONObject("rating"),ids=j.optJSONObject("remote_ids"),eps=j.optJSONObject("episodes"),status=j.optJSONObject("anime_status");a.poster=p==null?"":safeUrl(p.optString("medium",p.optString("fullsize")));a.type=type==null?"Аниме":type.optString("shortname","Аниме");a.age=age==null?"":age.optString("title");a.score=rat==null?0:rat.optDouble("average",0);a.status=status==null?"":status.optString("alias");a.episodes=eps==null?j.optInt("ep_count"):eps.optInt("count");a.malId=ids==null?0:ids.optInt("myanimelist_id");if(a.malId<=0&&ids!=null)a.malId=ids.optInt("shikimori_id");a.kpId=ids==null?0:ids.optInt("kp_id");a.libriaAlias=ids==null?"":ids.optString("anilibria_alias","");a.blocked=j.optBoolean("blocked",false);genres(a,j.optJSONArray("genres"),"title");return a;}
    private static Anime amAnime(JSONObject j){Anime a=new Anime();a.source="animelib";a.id=j.optString("id");a.title=j.optString("rus_name",j.optString("name","Аниме"));a.original=j.optString("name",j.optString("eng_name",""));a.alias=j.optString("slug_url",a.id);JSONObject p=j.optJSONObject("cover"),type=j.optJSONObject("type"),age=j.optJSONObject("ageRestriction"),rating=j.optJSONObject("rating"),status=j.optJSONObject("status"),episodes=j.optJSONObject("episodes");a.poster=p==null?"":safeUrl(p.optString("default"));try{a.year=Integer.parseInt(j.optString("releaseDate","").substring(0,4));}catch(Exception ignored){}a.type=type==null?"Аниме":type.optString("label");a.age=age==null?"":age.optString("label");a.score=rating==null?j.optDouble("shiki_rate",0):rating.optDouble("average",0);a.status=status!=null&&status.optInt("id")==1?"ongoing":"released";a.malId=j.optInt("shiki_id");a.anilistId=j.optInt("anilist_id");a.blocked=j.optBoolean("is_licensed",false);a.description=prose(j.opt("summary"),0);a.episodes=episodes==null?j.optInt("episodes_count",0):episodes.optInt("count",0);genres(a,j.optJSONArray("genres"),"name");return a;}
    private static String prose(Object value,int depth){if(value==null||depth>12)return "";if(value instanceof String)return plain((String)value);if(!(value instanceof JSONObject))return "";JSONObject j=(JSONObject)value;if(j.has("text"))return j.optString("text");StringBuilder s=new StringBuilder();JSONArray a=j.optJSONArray("content");for(int i=0;a!=null&&i<a.length();i++){s.append(prose(a.opt(i),depth+1));if(j.optString("type").equals("doc"))s.append("\n\n");}return s.toString().trim();}
    private static Anime libriaAnime(JSONObject j){Anime a=new Anime();a.source="anilibria";a.id=j.optString("id");JSONObject name=j.optJSONObject("name"),poster=j.optJSONObject("poster"),type=j.optJSONObject("type"),age=j.optJSONObject("age_rating");a.title=name==null?"Аниме":name.optString("main","Аниме");a.original=name==null?"":name.optString("english");a.alias=j.optString("alias");a.year=j.optInt("year");a.type=type==null?"Аниме":type.optString("description","Аниме");JSONObject opt=poster==null?null:poster.optJSONObject("optimized");String path=opt==null?(poster==null?"":poster.optString("preview")):opt.optString("preview");a.poster=path.startsWith("/")?"https://anilibria.top"+path:safeUrl(path);a.age=age==null?"":age.optString("label");a.description=plain(j.optString("description"));a.episodes=j.optInt("episodes_total");a.status=j.optBoolean("is_ongoing")?"ongoing":"released";a.blocked=j.optBoolean("is_blocked_by_geo")||j.optBoolean("is_blocked_by_copyrights");genres(a,j.optJSONArray("genres"),"name");JSONArray eps=j.optJSONArray("episodes");for(int i=0;eps!=null&&i<eps.length();i++){JSONObject e=eps.optJSONObject(i);if(e==null)continue;Anime.Episode ep=new Anime.Episode();ep.id=e.optString("id");ep.number=e.optDouble("ordinal");ep.name=e.optString("name");ep.duration=e.optInt("duration");putStream(ep,480,e.optString("hls_480"));putStream(ep,720,e.optString("hls_720"));putStream(ep,1080,e.optString("hls_1080"));JSONObject op=e.optJSONObject("opening");if(op!=null){ep.openingStart=op.optInt("start");ep.openingEnd=op.optInt("stop");}a.episodeList.add(ep);}a.episodeList.sort(Comparator.comparingDouble(e->e.number));return a;}
    private static String kind(String value){switch(value.toLowerCase(Locale.ROOT)){case "tv":case "tv_short":return "ТВ";case "movie":return "Фильм";case "ona":return "ONA";case "ova":return "OVA";case "special":case "tv_special":return "Спешл";case "music":return "Клип";default:return "Аниме";}}
}
