package app.yoru.mobile;

import android.app.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import androidx.recyclerview.widget.*;
import org.json.*;
import java.text.*;
import java.util.*;
import java.util.concurrent.*;

public final class CalendarScreen extends FrameLayout {
    private static final int DAYS=28,PAGE_SIZE=5;
    private static final String[][] FILTERS={{"all","Все"},{"fav","Избранное"},{"new","Новые"},{"soon","Скоро"},{"premiere","Премьеры"},{"ongoing","Выходит"},{"film","Фильмы"}};
    private final Activity activity;private final RecyclerView recycler;private final LinearLayoutManager layout;private final CalendarAdapter adapter;
    private final ArrayList<ApiRepository.AiringItem> items=new ArrayList<>(),allRows=new ArrayList<>(),visible=new ArrayList<>();
    private final HashMap<String,ArrayList<ArrayList<ApiRepository.AiringItem>>> buckets=new HashMap<>();private final HashMap<String,Integer> filterCounts=new HashMap<>();
    private final Locale ru=new Locale("ru");private final long[] starts=new long[DAYS];private final String[] shortDays=new String[DAYS],longDays=new String[DAYS];
    private int selected=-1,generation,allLimit=PAGE_SIZE;private String filter="all",state="Календарь";private boolean attached=true,refreshing,personalRefreshQueued;private Future<?> loadFuture;
    public CalendarScreen(Activity a){super(a);activity=a;setBackgroundColor(Ui.BG);recycler=new RecyclerView(a);layout=new LinearLayoutManager(a);recycler.setLayoutManager(layout);recycler.setHasFixedSize(false);recycler.setItemViewCacheSize(18);recycler.setClipToPadding(false);recycler.setPadding(0,0,0,Ui.dp(a,16));recycler.setVerticalScrollBarEnabled(false);recycler.setHorizontalScrollBarEnabled(false);recycler.setOverScrollMode(View.OVER_SCROLL_NEVER);DefaultItemAnimator animator=new DefaultItemAnimator();animator.setAddDuration(170);animator.setMoveDuration(150);animator.setChangeDuration(120);recycler.setItemAnimator(animator);adapter=new CalendarAdapter();recycler.setAdapter(adapter);recycler.addOnScrollListener(new RecyclerView.OnScrollListener(){@Override public void onScrolled(RecyclerView rv,int dx,int dy){if(dy>=0)maybeLoadMore();}});addView(recycler,new FrameLayout.LayoutParams(-1,-1));prepareDays();load();}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();attached=true;}
    @Override protected void onDetachedFromWindow(){attached=false;if(loadFuture!=null)loadFuture.cancel(true);super.onDetachedFromWindow();}
    private void load(){int gen=++generation;if(loadFuture!=null)loadFuture.cancel(true);prepareDays();refreshing=true;state="Календарь";rebuildVisible(true);adapter.notifyDataSetChanged();loadFuture=YoruApp.app().discovery.submit(()->{ArrayList<ApiRepository.AiringItem> cached=new ArrayList<>();boolean fresh=false;try{cached=ApiRepository.airingFromJson(YoruApp.app().cache.schedule(6*60*60*1000L));if(cached.isEmpty())cached=ApiRepository.airingFromJson(readLegacyCache());fresh=!cached.isEmpty()&&System.currentTimeMillis()-YoruApp.app().store.calendarCacheAt()<25*60*1000L;}catch(Exception ignored){}final ArrayList<ApiRepository.AiringItem> cacheSnapshot=new ArrayList<>(cached);if(!cacheSnapshot.isEmpty())YoruApp.app().main.post(()->{if(alive()&&gen==generation&&items.isEmpty())setItems(cacheSnapshot,true);});if(fresh){YoruApp.app().main.post(()->{if(alive()&&gen==generation){refreshing=false;if(!cacheSnapshot.isEmpty())setItems(cacheSnapshot,true);}});return;}try{ArrayList<ApiRepository.AiringItem> loaded=YoruApp.app().api.airingSchedule(DAYS,YoruApp.app().store.favorites());JSONArray json=ApiRepository.airingJson(loaded);YoruApp.app().cache.schedule(json);YoruApp.app().store.calendarCache(json);YoruApp.app().calendarTodayCount=ApiRepository.todayCount(loaded);YoruApp.app().main.post(()->{if(!alive()||gen!=generation)return;refreshing=false;setItems(loaded,true);});}catch(Exception e){YoruApp.app().main.post(()->{if(!alive()||gen!=generation)return;refreshing=false;if(items.isEmpty()&&!cacheSnapshot.isEmpty())setItems(cacheSnapshot,true);else{state="Календарь";rebuildVisible(false);adapter.notifyDataSetChanged();}});}});}
    public void quickShow(){prepareDays();if(items.isEmpty()){load();return;}buildBuckets();rebuildVisible(false);adapter.notifyDataSetChanged();}
    private JSONArray readLegacyCache(){try{return new JSONArray(YoruApp.app().store.calendarCache());}catch(Exception e){return new JSONArray();}}
    private boolean alive(){return attached&&!activity.isFinishing();}
    private void setItems(List<ApiRepository.AiringItem> rows,boolean keepPosition){items.clear();if(rows!=null)items.addAll(rows);buildBuckets();if(selected>=DAYS)selected=-1;rebuildVisible(true);adapter.notifyDataSetChanged();if(!keepPosition)recycler.scrollToPosition(0);}
    private void buildBuckets(){buckets.clear();filterCounts.clear();for(String[] f:FILTERS){ArrayList<ArrayList<ApiRepository.AiringItem>> days=new ArrayList<>(DAYS);for(int i=0;i<DAYS;i++)days.add(new ArrayList<>());buckets.put(f[0],days);filterCounts.put(f[0],0);}long now=System.currentTimeMillis();SecureStore store=YoruApp.app().store;boolean personal=store!=null&&store.ready();if(!personal&&store!=null&&!personalRefreshQueued){personalRefreshQueued=true;YoruApp.app().io.execute(()->{try{store.preload();}catch(Exception ignored){}YoruApp.app().main.post(()->{personalRefreshQueued=false;if(!alive())return;buildBuckets();rebuildVisible(false);adapter.notifyDataSetChanged();});});}HashMap<String,Boolean> favMemo=new HashMap<>(),historyMemo=new HashMap<>();HashSet<String> seen=new HashSet<>();for(ApiRepository.AiringItem item:items){if(item==null||item.anime==null)continue;int day=(int)((startOfDay(item.time)-starts[0])/(24L*60*60*1000));if(day<0||day>=DAYS)continue;String eventKey=item.anime.key()+"|"+item.time+"|"+item.episode+"|"+item.kind;if(!seen.add(eventKey))continue;String aKey=item.anime.key();boolean fav=false,history=false;if(personal){Boolean f=favMemo.get(aKey);if(f==null){f=store.favorite(item.anime);favMemo.put(aKey,f);}Boolean h=historyMemo.get(aKey);if(h==null){h=store.progress(item.anime).length()>0;historyMemo.put(aKey,h);}fav=f;history=h;}boolean premiere="Премьера".equals(item.kind);boolean ongoing=item.anime.ongoing()||"Новая серия".equals(item.kind);boolean film=item.anime.type.toLowerCase(Locale.ROOT).contains("фильм");addBucket("all",day,item);if(fav)addBucket("fav",day,item);if(!history&&!fav)addBucket("new",day,item);if(item.time>=now)addBucket("soon",day,item);if(premiere)addBucket("premiere",day,item);if(ongoing)addBucket("ongoing",day,item);if(film)addBucket("film",day,item);}}
    private void addBucket(String key,int day,ApiRepository.AiringItem item){ArrayList<ArrayList<ApiRepository.AiringItem>> days=buckets.get(key);if(days!=null&&day>=0&&day<days.size()){days.get(day).add(item);filterCounts.put(key,filterCounts.getOrDefault(key,0)+1);}}
    private ArrayList<ApiRepository.AiringItem> dayItems(int day){ArrayList<ArrayList<ApiRepository.AiringItem>> days=buckets.get(filter);ArrayList<ApiRepository.AiringItem> out=new ArrayList<>();if(days==null)return out;if(day<0){for(ArrayList<ApiRepository.AiringItem> d:days)out.addAll(d);}else if(day<days.size())out.addAll(days.get(day));out.sort((a,b)->Long.compare(a.time,b.time));return out;}
    private void resetPager(){allLimit=PAGE_SIZE;}
    private boolean pagedAll(){return selected<0&&"all".equals(filter);}
    private boolean showPagerFooter(){return pagedAll()&&allRows.size()>PAGE_SIZE;}
    private boolean canLoadMore(){return pagedAll()&&visible.size()<allRows.size();}
    private void rebuildVisible(boolean reset){if(reset)resetPager();allRows.clear();allRows.addAll(dayItems(selected));visible.clear();int total=allRows.size(),limit=pagedAll()?Math.min(allLimit,total):total;if(limit>0)visible.addAll(allRows.subList(0,limit));if(selected<0){state=pagedAll()&&total>PAGE_SIZE?"Все события · показано "+visible.size()+" из "+total:"Все события · "+total;}else state=longDays[Math.max(0,Math.min(DAYS-1,selected))]+" · "+total;}
    private void maybeLoadMore(){if(!canLoadMore())return;int last=layout.findLastVisibleItemPosition();if(last>=adapter.getItemCount()-3)appendNextPage();}
    private void appendNextPage(){if(!canLoadMore())return;int old=visible.size();allLimit=Math.min(allLimit+PAGE_SIZE,allRows.size());rebuildVisible(false);int inserted=visible.size()-old;if(inserted<=0)return;adapter.notifyItemChanged(0);adapter.notifyItemRangeInserted(1+old,inserted);int footer=adapter.getItemCount()-1;if(showPagerFooter()&&footer>=0)adapter.notifyItemChanged(footer);}
    private View header(){LinearLayout box=Ui.column(activity);box.setPadding(Ui.dp(activity,16),Ui.dp(activity,12),Ui.dp(activity,16),Ui.dp(activity,10));box.addView(Ui.label(activity,"КАЛЕНДАРЬ YORU"));Ui.space(box,9);box.addView(Ui.text(activity,"Выход серий",28,Ui.TEXT,true));Ui.space(box,7);TextView note=Ui.text(activity,"Все ближайшие аниме одним списком.",12,Ui.MUTED,false);note.setLineSpacing(Ui.dp(activity,3),1);box.addView(note);Ui.space(box,12);LinearLayout hero=Ui.column(activity);hero.setPadding(Ui.dp(activity,15),Ui.dp(activity,14),Ui.dp(activity,15),Ui.dp(activity,14));hero.setBackground(Ui.gradient(0xff2e2140,0xff181220,18,activity));TextView title=Ui.text(activity,visible.isEmpty()?"Календарь YORU":nearestTitle(),19,Ui.TEXT,true);title.setMaxLines(3);title.setEllipsize(TextUtils.TruncateAt.END);hero.addView(title);Ui.space(hero,7);TextView info=Ui.text(activity,items.isEmpty()?"События появятся автоматически.":summaryLine(),11,0xffd8c7ea,false);info.setLineSpacing(Ui.dp(activity,3),1);hero.addView(info);Ui.space(hero,10);LinearLayout actions=Ui.row(activity);actions.setGravity(Gravity.RIGHT);actions.addView(new View(activity),new LinearLayout.LayoutParams(0,1,1));actions.addView(Ui.iconButton(activity,"refresh","Обновить",this::load),Ui.lp(activity,42,42));hero.addView(actions);box.addView(hero,Ui.lp(activity,-1,-2));Ui.space(box,13);HorizontalScrollView days=new HorizontalScrollView(activity);days.setHorizontalScrollBarEnabled(false);LinearLayout dayRow=Ui.row(activity);TextView all=Ui.chip(activity,"Все дни · "+filteredCount(),selected<0,()->{if(selected<0)return;selected=-1;rebuildVisible(true);adapter.notifyDataSetChanged();recycler.scrollToPosition(0);});LinearLayout.LayoutParams ap=Ui.lp(activity,-2,-2);ap.rightMargin=Ui.dp(activity,7);dayRow.addView(all,ap);for(int i=0;i<DAYS;i++){final int index=i;TextView chip=Ui.chip(activity,shortDays[i]+" · "+dayCount(filter,i),i==selected,()->{if(selected==index)return;selected=index;rebuildVisible(true);adapter.notifyDataSetChanged();recycler.scrollToPosition(0);});LinearLayout.LayoutParams p=Ui.lp(activity,-2,-2);p.rightMargin=Ui.dp(activity,7);dayRow.addView(chip,p);}days.addView(dayRow);box.addView(days,Ui.lp(activity,-1,-2));Ui.space(box,9);HorizontalScrollView filters=new HorizontalScrollView(activity);filters.setHorizontalScrollBarEnabled(false);LinearLayout filterRow=Ui.row(activity);for(String[] r:FILTERS){final String value=r[0];TextView chip=Ui.chip(activity,r[1]+" · "+countForFilter(value),value.equals(filter),()->{if(value.equals(filter))return;filter=value;selected=-1;rebuildVisible(true);adapter.notifyDataSetChanged();recycler.scrollToPosition(0);});LinearLayout.LayoutParams p=Ui.lp(activity,-2,-2);p.rightMargin=Ui.dp(activity,7);filterRow.addView(chip,p);}filters.addView(filterRow);box.addView(filters,Ui.lp(activity,-1,-2));Ui.space(box,10);box.addView(Ui.text(activity,state,12,Ui.MUTED,false));return box;}
    private View itemCard(ApiRepository.AiringItem item){LinearLayout card=Ui.row(activity);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(Ui.dp(activity,12),Ui.dp(activity,12),Ui.dp(activity,12),Ui.dp(activity,12));card.setBackground(Ui.stroke(Ui.CARD,16,activity));ImageView poster=new ImageView(activity);poster.setScaleType(ImageView.ScaleType.CENTER_CROP);poster.setBackground(Ui.shape(Ui.SURFACE,12,activity));poster.setClipToOutline(true);card.addView(poster,Ui.lp(activity,54,76));if(item.anime!=null)YoruApp.app().images.load(poster,item.anime);LinearLayout text=Ui.column(activity);text.setPadding(Ui.dp(activity,12),0,0,0);TextView name=Ui.text(activity,item.anime==null?"Аниме":YoruBrain.title(item.anime),14,Ui.TEXT,true);name.setMaxLines(2);name.setEllipsize(TextUtils.TruncateAt.END);text.addView(name);Ui.space(text,6);text.addView(Ui.text(activity,item.kind+" · серия "+Ui.number(item.episode)+" · "+time(item.time),11,kindColor(item),true));Ui.space(text,5);String meta=countdown(item.time)+" · "+item.precision+statusSuffix(item);TextView line=Ui.text(activity,meta,10,Ui.MUTED,false);line.setSingleLine();line.setEllipsize(TextUtils.TruncateAt.END);text.addView(line);card.addView(text,new LinearLayout.LayoutParams(0,-2,1));Ui.Icon icon=new Ui.Icon(activity,"play");icon.color=Ui.PURPLE;card.addView(icon,Ui.lp(activity,24,24));Ui.press(card);card.setContentDescription((item.anime==null?"Аниме":YoruBrain.title(item.anime))+". "+item.kind+", серия "+Ui.number(item.episode)+", "+time(item.time)+". Долгое нажатие — в коллекцию.");card.setOnClickListener(v->{if(item.anime!=null)Ui.openDetails(activity,item.anime);});card.setOnLongClickListener(v->{if(item.anime==null)return false;Ui.bucketDialog(activity,item.anime,()->{buildBuckets();rebuildVisible(true);adapter.notifyDataSetChanged();});return true;});return card;}
    private View emptyCard(){LinearLayout c=Ui.column(activity);c.setPadding(Ui.dp(activity,16),Ui.dp(activity,18),Ui.dp(activity,16),Ui.dp(activity,18));c.setBackground(Ui.stroke(Ui.CARD,16,activity));c.addView(Ui.text(activity,items.isEmpty()?"Пока нет событий":"В этом фильтре пока пусто",17,Ui.TEXT,true));Ui.space(c,8);TextView msg=Ui.text(activity,items.isEmpty()?"События появятся автоматически.":"Выберите другой фильтр, другой день или вернитесь к режиму «Все».",12,Ui.MUTED,false);msg.setLineSpacing(Ui.dp(activity,4),1);c.addView(msg);Ui.space(c,12);c.addView(Ui.button(activity,items.isEmpty()?"Обновить":"Показать все",false,()->{if(items.isEmpty())load();else{filter="all";selected=-1;rebuildVisible(true);adapter.notifyDataSetChanged();recycler.scrollToPosition(0);}}));return c;}
    private View moreCard(){LinearLayout c=Ui.column(activity);c.setPadding(Ui.dp(activity,16),Ui.dp(activity,14),Ui.dp(activity,16),Ui.dp(activity,14));c.setBackground(Ui.stroke(0xff1b1624,16,activity));String text=canLoadMore()?"Показано "+visible.size()+" из "+allRows.size():"Показаны все "+allRows.size()+" событий";TextView t=Ui.text(activity,text,12,Ui.MUTED,false);t.setGravity(Gravity.CENTER);c.addView(t);if(canLoadMore()){Ui.space(c,10);c.addView(Ui.button(activity,"Показать ещё",false,this::appendNextPage));}return c;}
    private int filteredCount(){return countForFilter(filter);}
    private int countForFilter(String key){Integer n=filterCounts.get(key);return n==null?0:n;}
    private int dayCount(String key,int day){ArrayList<ArrayList<ApiRepository.AiringItem>> days=buckets.get(key);return days==null||day<0||day>=days.size()?0:days.get(day).size();}
    private int exactCount(){int n=0;ArrayList<ArrayList<ApiRepository.AiringItem>> days=buckets.get(filter);if(days!=null)for(ArrayList<ApiRepository.AiringItem> d:days)for(ApiRepository.AiringItem item:d)if("Точная дата".equals(item.precision)||"Премьера".equals(item.precision))n++;return n;}
    private int premiereCount(){return countForFilter("premiere");}
    private String summaryLine(){String base=filteredCount()+" событий · "+exactCount()+" с точным временем";if(premiereCount()>0)base+=" · премьер: "+premiereCount();return base;}
    private String nearestTitle(){long now=System.currentTimeMillis();ApiRepository.AiringItem best=null,past=null;List<ApiRepository.AiringItem> src=allRows.isEmpty()?visible:allRows;for(ApiRepository.AiringItem item:src){if(item.time>=now&&(best==null||item.time<best.time))best=item;if(item.time<now&&(past==null||item.time>past.time))past=item;}if(best==null)best=past;return best==null?"Календарь YORU":(best.time<System.currentTimeMillis()?"Уже вышло: ":"Ближайшая серия: ")+(best.anime==null?"аниме":YoruBrain.title(best.anime));}
    private int nearestIndex(){long now=System.currentTimeMillis();int best=-1,past=-1;for(int i=0;i<allRows.size();i++){ApiRepository.AiringItem item=allRows.get(i);if(item.time>=now&&(best<0||item.time<allRows.get(best).time))best=i;if(item.time<now&&(past<0||item.time>allRows.get(past).time))past=i;}return best>=0?best:past;}
    private void jumpNearest(){int index=nearestIndex();if(index<0){Ui.toast(activity,"Событий пока нет");return;}if(pagedAll()&&index>=visible.size()){allLimit=Math.min(allRows.size(),((index/PAGE_SIZE)+1)*PAGE_SIZE);rebuildVisible(false);adapter.notifyDataSetChanged();}recycler.smoothScrollToPosition(Math.max(0,index+1));}
    private int kindColor(ApiRepository.AiringItem item){if(item==null)return Ui.PURPLE;if("Премьера".equals(item.kind))return 0xffffcf70;if(item.time<System.currentTimeMillis())return 0xff88e0a0;if(item.anime!=null&&item.anime.ongoing())return Ui.PURPLE;return 0xff9ec7ff;}
    private String statusSuffix(ApiRepository.AiringItem item){try{if(item!=null&&item.anime!=null){if(YoruApp.app().store.ready()&&YoruApp.app().store.favorite(item.anime))return " · в коллекции";if(item.anime.year>0)return " · "+item.anime.year;}}catch(Exception ignored){}return "";}
    private void prepareDays(){long base=todayStart();for(int i=0;i<DAYS;i++){starts[i]=base+i*24L*60*60*1000;shortDays[i]=i==0?"Сегодня":i==1?"Завтра":new SimpleDateFormat("EEE dd.MM",ru).format(new Date(starts[i])).replaceFirst("\\.","");longDays[i]=i==0?"Сегодня":i==1?"Завтра":new SimpleDateFormat("EEEE, dd MMMM",ru).format(new Date(starts[i]));}}
    private long todayStart(){Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}
    private long startOfDay(long t){Calendar c=Calendar.getInstance();c.setTimeInMillis(t);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}
    private String time(long t){return new SimpleDateFormat("HH:mm",ru).format(new Date(t));}
    private String countdown(long t){long diff=t-System.currentTimeMillis();if(diff<=-90*60*1000)return "уже вышло";if(diff<=0)return "выходит сейчас";long min=diff/60000,h=min/60,d=h/24;if(d>0)return "через "+d+" д "+(h%24)+" ч";if(h>0)return "через "+h+" ч "+(min%60)+" мин";return "через "+Math.max(1,min)+" мин";}
    private final class CalendarAdapter extends RecyclerView.Adapter<CalendarHolder>{public int getItemCount(){int count=1+(visible.isEmpty()?1:visible.size());return showPagerFooter()?count+1:count;}public int getItemViewType(int p){if(p==0)return 0;if(visible.isEmpty())return 2;if(p<=visible.size())return 1;return 3;}public CalendarHolder onCreateViewHolder(ViewGroup parent,int viewType){FrameLayout frame=new FrameLayout(activity);frame.setPadding(Ui.dp(activity,16),0,Ui.dp(activity,16),viewType==0?0:Ui.dp(activity,9));frame.setLayoutParams(new RecyclerView.LayoutParams(-1,-2));return new CalendarHolder(frame);}public void onBindViewHolder(CalendarHolder h,int p){h.box.removeAllViews();int type=getItemViewType(p);View v=type==0?header():type==2?emptyCard():type==3?moreCard():itemCard(visible.get(p-1));h.box.addView(v,new FrameLayout.LayoutParams(-1,-2));}}
    private static final class CalendarHolder extends RecyclerView.ViewHolder{final FrameLayout box;CalendarHolder(FrameLayout v){super(v);box=v;}}
}
