package app.yoru.mobile;

import android.app.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import androidx.recyclerview.widget.*;
import org.json.*;
import java.text.*;
import java.util.*;
import java.util.concurrent.*;

public final class CalendarScreen extends FrameLayout {
    private static final int DAYS=28;
    private static final String[][] FILTERS={{"all","Все"},{"fav","Избранное"},{"new","Новые"},{"soon","Скоро"},{"premiere","Премьеры"},{"ongoing","Выходит"},{"film","Фильмы"}};
    private final Activity activity;private final RecyclerView recycler;private final CalendarAdapter adapter;private final ArrayList<ApiRepository.AiringItem> items=new ArrayList<>(),visible=new ArrayList<>();private final HashMap<String,ArrayList<ArrayList<ApiRepository.AiringItem>>> buckets=new HashMap<>();private final Locale ru=new Locale("ru");private final long[] starts=new long[DAYS];private final String[] shortDays=new String[DAYS],longDays=new String[DAYS];private int selected=-1,generation;private String filter="all",state="Календарь";private boolean attached=true;private Future<?> loadFuture;
    public CalendarScreen(Activity a){super(a);activity=a;setBackgroundColor(Ui.BG);recycler=new RecyclerView(a);recycler.setLayoutManager(new LinearLayoutManager(a));recycler.setHasFixedSize(false);recycler.setItemViewCacheSize(24);recycler.setClipToPadding(false);recycler.setPadding(0,0,0,Ui.dp(a,16));recycler.setVerticalScrollBarEnabled(false);recycler.setHorizontalScrollBarEnabled(false);recycler.setOverScrollMode(View.OVER_SCROLL_NEVER);adapter=new CalendarAdapter();recycler.setAdapter(adapter);addView(recycler,new FrameLayout.LayoutParams(-1,-1));prepareDays();load();}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();attached=true;}
    @Override protected void onDetachedFromWindow(){attached=false;if(loadFuture!=null)loadFuture.cancel(true);super.onDetachedFromWindow();}
    private void load(){int gen=++generation;if(loadFuture!=null)loadFuture.cancel(true);prepareDays();ArrayList<ApiRepository.AiringItem> cached=ApiRepository.airingFromJson(YoruApp.app().cache.schedule(6*60*60*1000L));if(cached.isEmpty())cached=ApiRepository.airingFromJson(readLegacyCache());if(!cached.isEmpty())setItems(cached,true);else{rebuildVisible();adapter.notifyDataSetChanged();}final ArrayList<ApiRepository.AiringItem> cacheSnapshot=new ArrayList<>(cached);loadFuture=YoruApp.app().discovery.submit(()->{try{ArrayList<ApiRepository.AiringItem> loaded=YoruApp.app().api.airingSchedule(DAYS,YoruApp.app().store.favorites());JSONArray json=ApiRepository.airingJson(loaded);YoruApp.app().cache.schedule(json);YoruApp.app().store.calendarCache(json);YoruApp.app().calendarTodayCount=ApiRepository.todayCount(loaded);YoruApp.app().main.post(()->{if(!alive()||gen!=generation)return;setItems(loaded,true);});}catch(Exception e){YoruApp.app().main.post(()->{if(!alive()||gen!=generation)return;if(items.isEmpty()&&!cacheSnapshot.isEmpty())setItems(cacheSnapshot,true);else{state="Календарь";rebuildVisible();adapter.notifyDataSetChanged();}});}});}
    public void quickShow(){prepareDays();if(items.isEmpty()){ArrayList<ApiRepository.AiringItem> cached=ApiRepository.airingFromJson(YoruApp.app().cache.schedule(6*60*60*1000L));if(cached.isEmpty())cached=ApiRepository.airingFromJson(readLegacyCache());if(!cached.isEmpty())setItems(cached,false);else{rebuildVisible();adapter.notifyDataSetChanged();}}else{buildBuckets();rebuildVisible();adapter.notifyDataSetChanged();}}
    private JSONArray readLegacyCache(){try{return new JSONArray(YoruApp.app().store.calendarCache());}catch(Exception e){return new JSONArray();}}
    private boolean alive(){return attached&&!activity.isFinishing();}
    private void setItems(List<ApiRepository.AiringItem> rows,boolean keepPosition){items.clear();if(rows!=null)items.addAll(rows);buildBuckets();if(selected>=DAYS)selected=-1;rebuildVisible();adapter.notifyDataSetChanged();if(!keepPosition)recycler.scrollToPosition(0);}
    private void buildBuckets(){buckets.clear();for(String[] f:FILTERS){ArrayList<ArrayList<ApiRepository.AiringItem>> days=new ArrayList<>(DAYS);for(int i=0;i<DAYS;i++)days.add(new ArrayList<>());buckets.put(f[0],days);}long now=System.currentTimeMillis();for(ApiRepository.AiringItem item:items){if(item==null||item.anime==null)continue;int day=(int)((startOfDay(item.time)-starts[0])/(24L*60*60*1000));if(day<0||day>=DAYS)continue;boolean fav=YoruApp.app().store.favorite(item.anime);boolean history=YoruApp.app().store.progress(item.anime).length()>0;boolean premiere="Премьера".equals(item.kind);boolean ongoing=item.anime.ongoing()||"Новая серия".equals(item.kind);boolean film=item.anime.type.toLowerCase(Locale.ROOT).contains("фильм");addBucket("all",day,item);if(fav)addBucket("fav",day,item);if(!history&&!fav)addBucket("new",day,item);if(item.time>=now)addBucket("soon",day,item);if(premiere)addBucket("premiere",day,item);if(ongoing)addBucket("ongoing",day,item);if(film)addBucket("film",day,item);}}
    private void addBucket(String key,int day,ApiRepository.AiringItem item){ArrayList<ArrayList<ApiRepository.AiringItem>> days=buckets.get(key);if(days!=null&&day>=0&&day<days.size())days.get(day).add(item);}
    private ArrayList<ApiRepository.AiringItem> dayItems(int day){ArrayList<ArrayList<ApiRepository.AiringItem>> days=buckets.get(filter);ArrayList<ApiRepository.AiringItem> out=new ArrayList<>();if(days==null)return out;if(day<0){for(ArrayList<ApiRepository.AiringItem> d:days)out.addAll(d);}else if(day<days.size())out.addAll(days.get(day));out.sort((a,b)->Long.compare(a.time,b.time));return out;}
    private void rebuildVisible(){visible.clear();visible.addAll(dayItems(selected));state=selected<0?("Все события · "+visible.size()):(longDays[Math.max(0,Math.min(DAYS-1,selected))]+" · "+visible.size());}
    private View header(){LinearLayout box=Ui.column(activity);box.setPadding(Ui.dp(activity,16),Ui.dp(activity,12),Ui.dp(activity,16),Ui.dp(activity,10));box.addView(Ui.label(activity,"КАЛЕНДАРЬ YORU"));Ui.space(box,9);box.addView(Ui.text(activity,"Выход серий",28,Ui.TEXT,true));Ui.space(box,7);TextView note=Ui.text(activity,"Все ближайшие аниме одним списком. Дни ниже — быстрый фильтр.",12,Ui.MUTED,false);note.setLineSpacing(Ui.dp(activity,3),1);box.addView(note);Ui.space(box,12);LinearLayout hero=Ui.column(activity);hero.setPadding(Ui.dp(activity,15),Ui.dp(activity,14),Ui.dp(activity,15),Ui.dp(activity,14));hero.setBackground(Ui.gradient(0xff2e2140,0xff181220,18,activity));TextView title=Ui.text(activity,visible.isEmpty()?"Календарь YORU":nearestTitle(),19,Ui.TEXT,true);title.setMaxLines(3);title.setEllipsize(TextUtils.TruncateAt.END);hero.addView(title);Ui.space(hero,7);hero.addView(Ui.text(activity,items.isEmpty()?"События появятся здесь автоматически.":filteredCount()+" событий · "+exactCount()+" с точным временем",11,0xffd8c7ea,false));Ui.space(hero,10);hero.addView(Ui.button(activity,"Обновить календарь",false,this::load));box.addView(hero,Ui.lp(activity,-1,-2));Ui.space(box,13);HorizontalScrollView days=new HorizontalScrollView(activity);days.setHorizontalScrollBarEnabled(false);LinearLayout dayRow=Ui.row(activity);TextView all=Ui.chip(activity,"Все · "+filteredCount(),selected<0,()->{if(selected<0)return;selected=-1;rebuildVisible();adapter.notifyDataSetChanged();recycler.scrollToPosition(0);});LinearLayout.LayoutParams ap=Ui.lp(activity,-2,-2);ap.rightMargin=Ui.dp(activity,7);dayRow.addView(all,ap);for(int i=0;i<DAYS;i++){final int index=i;TextView chip=Ui.chip(activity,shortDays[i]+" · "+dayItems(i).size(),i==selected,()->{if(selected==index)return;selected=index;rebuildVisible();adapter.notifyDataSetChanged();recycler.scrollToPosition(0);});LinearLayout.LayoutParams p=Ui.lp(activity,-2,-2);p.rightMargin=Ui.dp(activity,7);dayRow.addView(chip,p);}days.addView(dayRow);box.addView(days,Ui.lp(activity,-1,-2));Ui.space(box,9);HorizontalScrollView filters=new HorizontalScrollView(activity);filters.setHorizontalScrollBarEnabled(false);LinearLayout filterRow=Ui.row(activity);for(String[] r:FILTERS){final String value=r[0];TextView chip=Ui.chip(activity,r[1],value.equals(filter),()->{if(value.equals(filter))return;filter=value;selected=-1;rebuildVisible();adapter.notifyDataSetChanged();recycler.scrollToPosition(0);});LinearLayout.LayoutParams p=Ui.lp(activity,-2,-2);p.rightMargin=Ui.dp(activity,7);filterRow.addView(chip,p);}filters.addView(filterRow);box.addView(filters,Ui.lp(activity,-1,-2));Ui.space(box,10);box.addView(Ui.text(activity,state,12,Ui.MUTED,false));return box;}
    private View itemCard(ApiRepository.AiringItem item){LinearLayout card=Ui.row(activity);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(Ui.dp(activity,12),Ui.dp(activity,12),Ui.dp(activity,12),Ui.dp(activity,12));card.setBackground(Ui.stroke(Ui.CARD,16,activity));ImageView poster=new ImageView(activity);poster.setScaleType(ImageView.ScaleType.CENTER_CROP);poster.setBackground(Ui.shape(Ui.SURFACE,12,activity));poster.setClipToOutline(true);card.addView(poster,Ui.lp(activity,54,76));if(item.anime!=null)YoruApp.app().images.load(poster,item.anime);LinearLayout text=Ui.column(activity);text.setPadding(Ui.dp(activity,12),0,0,0);TextView name=Ui.text(activity,item.anime==null?"Аниме":YoruBrain.title(item.anime),14,Ui.TEXT,true);name.setMaxLines(2);name.setEllipsize(TextUtils.TruncateAt.END);text.addView(name);Ui.space(text,6);text.addView(Ui.text(activity,item.kind+" · серия "+Ui.number(item.episode)+" · "+time(item.time),11,Ui.PURPLE,true));Ui.space(text,5);text.addView(Ui.text(activity,countdown(item.time)+" · "+item.precision,10,Ui.MUTED,false));card.addView(text,new LinearLayout.LayoutParams(0,-2,1));Ui.Icon icon=new Ui.Icon(activity,"play");icon.color=Ui.PURPLE;card.addView(icon,Ui.lp(activity,24,24));Ui.press(card);card.setOnClickListener(v->{if(item.anime!=null)Ui.openDetails(activity,item.anime);});return card;}
    private View emptyCard(){LinearLayout c=Ui.column(activity);c.setPadding(Ui.dp(activity,16),Ui.dp(activity,18),Ui.dp(activity,16),Ui.dp(activity,18));c.setBackground(Ui.stroke(Ui.CARD,16,activity));c.addView(Ui.text(activity,items.isEmpty()?"Пока нет событий":"В этом фильтре пока пусто",17,Ui.TEXT,true));Ui.space(c,8);TextView msg=Ui.text(activity,"Нажмите «Обновить календарь» или выберите другой фильтр.",12,Ui.MUTED,false);msg.setLineSpacing(Ui.dp(activity,4),1);c.addView(msg);return c;}
    private int filteredCount(){int n=0;ArrayList<ArrayList<ApiRepository.AiringItem>> days=buckets.get(filter);if(days!=null)for(ArrayList<ApiRepository.AiringItem> d:days)n+=d.size();return n;}
    private int exactCount(){int n=0;ArrayList<ArrayList<ApiRepository.AiringItem>> days=buckets.get(filter);if(days!=null)for(ArrayList<ApiRepository.AiringItem> d:days)for(ApiRepository.AiringItem item:d)if("Точная дата".equals(item.precision)||"Премьера".equals(item.precision))n++;return n;}
    private String nearestTitle(){long now=System.currentTimeMillis();ApiRepository.AiringItem best=null,past=null;for(ApiRepository.AiringItem item:visible){if(item.time>=now&&(best==null||item.time<best.time))best=item;if(item.time<now&&(past==null||item.time>past.time))past=item;}if(best==null)best=past;return best==null?"Календарь YORU":(best.time<System.currentTimeMillis()?"Уже вышло: ":"Ближайшая серия: ")+(best.anime==null?"аниме":YoruBrain.title(best.anime));}
    private void prepareDays(){long base=todayStart();for(int i=0;i<DAYS;i++){starts[i]=base+i*24L*60*60*1000;shortDays[i]=i==0?"Сегодня":i==1?"Завтра":new SimpleDateFormat("EEE dd.MM",ru).format(new Date(starts[i])).replaceFirst("\\.","");longDays[i]=i==0?"Сегодня":i==1?"Завтра":new SimpleDateFormat("EEEE, dd MMMM",ru).format(new Date(starts[i]));}}
    private long todayStart(){Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}
    private long startOfDay(long t){Calendar c=Calendar.getInstance();c.setTimeInMillis(t);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}
    private String time(long t){return new SimpleDateFormat("HH:mm",ru).format(new Date(t));}
    private String countdown(long t){long diff=t-System.currentTimeMillis();if(diff<=-90*60*1000)return "уже вышло";if(diff<=0)return "выходит сейчас";long min=diff/60000,h=min/60,d=h/24;if(d>0)return "через "+d+" д "+(h%24)+" ч";if(h>0)return "через "+h+" ч "+(min%60)+" мин";return "через "+Math.max(1,min)+" мин";}
    private final class CalendarAdapter extends RecyclerView.Adapter<CalendarHolder>{public int getItemCount(){return 1+(visible.isEmpty()?1:visible.size());}public int getItemViewType(int p){return p==0?0:visible.isEmpty()?2:1;}public CalendarHolder onCreateViewHolder(ViewGroup parent,int viewType){FrameLayout frame=new FrameLayout(activity);frame.setPadding(Ui.dp(activity,16),0,Ui.dp(activity,16),viewType==0?0:Ui.dp(activity,9));frame.setLayoutParams(new RecyclerView.LayoutParams(-1,-2));return new CalendarHolder(frame);}public void onBindViewHolder(CalendarHolder h,int p){h.box.removeAllViews();View v=p==0?header():visible.isEmpty()?emptyCard():itemCard(visible.get(p-1));h.box.addView(v,new FrameLayout.LayoutParams(-1,-2));}}
    private static final class CalendarHolder extends RecyclerView.ViewHolder{final FrameLayout box;CalendarHolder(FrameLayout v){super(v);box=v;}}
}
