package app.yoru.mobile;

import android.app.*;
import android.content.*;
import android.os.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

public final class DetailsActivity extends Activity {
    private Anime anime;private LinearLayout root,body;private TextView state;private int generation;private boolean loaded;
    @Override public void onCreate(Bundle b){super.onCreate(b);if(!Ui.allow(this))return;anime=Ui.intentAnime(this);if(!Anime.valid(anime)){finish();return;}YoruApp.app().api.remember(anime);root=Ui.base(this);LinearLayout bar=Ui.row(this);bar.setPadding(Ui.dp(this,16),Ui.dp(this,9),Ui.dp(this,16),Ui.dp(this,9));bar.addView(Ui.iconButton(this,"back","Назад",this::finish),Ui.lp(this,39,39));TextView label=Ui.text(this,ApiRepository.sourceNames.get(anime.source),13,Ui.MUTED,true);Ui.gap(bar,label,-2,-2,13);root.addView(bar,Ui.lp(this,-1,-2));ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);body=Ui.column(this);body.setPadding(Ui.dp(this,20),Ui.dp(this,12),Ui.dp(this,20),Ui.dp(this,30));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));render();loadFull();}
    @Override protected void onResume(){super.onResume();if(body!=null)render();}
    private void loadFull(){int gen=++generation;YoruApp.app().io.execute(()->{try{Anime full=YoruApp.app().api.details(anime,true);if(full.episodeList.isEmpty())try{Anime.Playback p=YoruApp.app().api.playback(full,"auto");if(p!=null&&p.video!=null&&!p.video.episodeList.isEmpty()){full.episodeList.addAll(p.video.episodeList);full.episodes=Math.max(full.episodes,full.episodeList.size());}}catch(Exception ignored){}YoruApp.app().main.post(()->{if(gen==generation&&!isFinishing()){anime=full;loaded=true;render();}});}catch(Exception e){YoruApp.app().main.post(()->{if(!isFinishing()){loaded=true;if(state!=null)state.setText("Показаны сохранённые сведения. Выберите источник для просмотра.");Ui.toast(this,"Карточка открыта из кэша");}});}});}
    private void render(){body.removeAllViews();LinearLayout hero=Ui.row(this);hero.setGravity(Gravity.TOP);ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackground(Ui.gradient(0xff2a2135,0xff18131f,16,this));image.setClipToOutline(true);hero.addView(image,Ui.lp(this,126,184));YoruApp.app().images.load(image,anime);LinearLayout info=Ui.column(this);info.setPadding(Ui.dp(this,17),Ui.dp(this,3),0,0);TextView source=Ui.label(this,ApiRepository.sourceNames.get(anime.source).toUpperCase(Locale.ROOT));source.setTextColor(Ui.PURPLE);info.addView(source);Ui.space(info,11);TextView title=Ui.text(this,anime.title,23,Ui.TEXT,true);title.setMaxLines(6);info.addView(title);Ui.space(info,12);info.addView(Ui.text(this,anime.meta()+(anime.studio.isEmpty()?"":" · "+anime.studio),11,Ui.MUTED,false));if(anime.score>0){Ui.space(info,9);info.addView(Ui.text(this,String.format(Locale.US,"★ %.2f",anime.score),15,Ui.PURPLE,true));}hero.addView(info,new LinearLayout.LayoutParams(0,-2,1));body.addView(hero);Ui.space(body,18);chips();actions();progress();episodes();about();related();}
    private void chips(){if(!anime.original.isEmpty()&&!anime.original.equals(anime.title)){body.addView(Ui.text(this,anime.original,12,Ui.MUTED,false));Ui.space(body,13);}if(!anime.genres.isEmpty()){HorizontalScrollView h=new HorizontalScrollView(this);h.setHorizontalScrollBarEnabled(false);LinearLayout row=Ui.row(this);for(String g:anime.genres.subList(0,Math.min(10,anime.genres.size()))){TextView chip=Ui.chip(this,g,false,null);LinearLayout.LayoutParams p=Ui.lp(this,-2,-2);p.rightMargin=Ui.dp(this,7);row.addView(chip,p);}h.addView(row);body.addView(h,Ui.lp(this,-1,-2));Ui.space(body,14);}String status=anime.status.equals("ongoing")?"Сейчас выходит":anime.status.equals("anons")?"Анонсирован":anime.status.equals("released")?"Завершён":"Опубликован";body.addView(Ui.text(this,status+(anime.episodes>0?" · "+anime.episodes+" серий":"")+(anime.age.isEmpty()?"":" · "+anime.age),11,Ui.MUTED,false));Ui.space(body,18);}
    private void actions(){JSONObject history=YoruApp.app().store.progress(anime);String play=history.length()>0?"Продолжить просмотр":"Смотреть через YORU Source";String storedMode=history.optString("playerMode","");if(storedMode.trim().isEmpty()||storedMode.equals("auto"))storedMode="yoru";final String playMode=storedMode;TextView start=Ui.button(this,anime.blocked?"Просмотр ограничен":play,true,()->Ui.openPlayer(this,anime,playMode,history.optDouble("episode",1)));start.setEnabled(!anime.blocked);if(anime.blocked)start.setAlpha(.45f);body.addView(start,Ui.lp(this,-1,-2));Ui.space(body,10);LinearLayout actions=Ui.row(this);TextView favorite=Ui.button(this,YoruApp.app().store.favorite(anime)?"В коллекции":"В коллекцию",false,()->Ui.bucketDialog(this,anime,this::render));actions.addView(favorite,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(0,-2,1);ap.leftMargin=Ui.dp(this,9);actions.addView(Ui.button(this,"Источник",false,this::choosePlayer),ap);body.addView(actions);Ui.space(body,10);LinearLayout plan=Ui.row(this);plan.addView(Ui.button(this,"В план",false,()->{YoruApp.app().store.enqueueWatch(anime);Ui.toast(this,"Добавлено в план просмотра");}),new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,-2,1);pp.leftMargin=Ui.dp(this,9);plan.addView(Ui.button(this,"Заметка",false,this::editNote),pp);body.addView(plan);Ui.space(body,10);LinearLayout downloads=Ui.row(this);downloads.addView(Ui.button(this,"Скачать серию",false,()->DownloadActions.chooseEpisode(this,anime,null,history.optDouble("episode",1))),new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(0,-2,1);mp.leftMargin=Ui.dp(this,9);downloads.addView(Ui.button(this,"Массово",false,()->DownloadActions.chooseBatch(this,anime,null,history.optDouble("episode",1))),mp);body.addView(downloads);}
    private void progress(){JSONObject history=YoruApp.app().store.progress(anime);if(history.length()>0){Ui.space(body,10);body.addView(Ui.text(this,"Вы смотрели серию "+Ui.number(history.optDouble("episode",1))+" · "+Ui.time(history.optInt("time")),11,Ui.MUTED,false));}String bucket=YoruApp.app().store.bucket(anime);if(!bucket.isEmpty()){int i=Arrays.asList(SecureStore.BUCKETS).indexOf(bucket);Ui.space(body,7);body.addView(Ui.text(this,"Ваш список: "+(i>=0?SecureStore.BUCKET_LABELS[i]:"В планах"),11,Ui.PURPLE,false));}String note=YoruApp.app().store.note(anime);if(!note.isEmpty()){Ui.space(body,10);TextView nt=Ui.text(this,"Заметка: "+note,12,Ui.TEXT,false);nt.setPadding(Ui.dp(this,13),Ui.dp(this,11),Ui.dp(this,13),Ui.dp(this,11));nt.setBackground(Ui.stroke(Ui.CARD,13,this));body.addView(nt);}
    String hint=anime.episodeList.isEmpty()?(loaded?"Источник не отдал список серий. Попробуйте кнопку “Источник” или откройте просмотр.":"Список серий загружается в фоне…"):"YORU Source проверит рабочие озвучки перед запуском серии.";state=Ui.text(this,hint,11,Ui.MUTED,false);if(!state.getText().toString().isEmpty()){Ui.space(body,12);body.addView(state);}}
    private void episodes(){Ui.space(body,24);LinearLayout row=Ui.row(this);row.addView(Ui.text(this,"Серии",21,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));if(anime.episodes>0)row.addView(Ui.text(this,String.valueOf(anime.episodes),13,Ui.PURPLE,true));body.addView(row);Ui.space(body,12);if(anime.episodeList.isEmpty()){LinearLayout card=card();card.addView(Ui.text(this,"Список серий появится здесь после загрузки источника. Смотреть можно уже сейчас через кнопку выше.",12,Ui.MUTED,false));body.addView(card);return;}int limit=Math.min(80,anime.episodeList.size());for(int i=0;i<limit;i++)episodeRow(anime.episodeList.get(i));if(anime.episodeList.size()>limit){Ui.space(body,8);body.addView(Ui.text(this,"Показано "+limit+" из "+anime.episodeList.size()+" серий. Полный список доступен в плеере и в массовом скачивании.",10,Ui.MUTED,false));}}
    private void episodeRow(Anime.Episode ep){LinearLayout outer=Ui.column(this);outer.setPadding(0,0,0,Ui.dp(this,8));LinearLayout card=Ui.row(this);card.setPadding(Ui.dp(this,13),Ui.dp(this,11),Ui.dp(this,10),Ui.dp(this,11));card.setBackground(Ui.stroke(Ui.CARD,14,this));TextView title=Ui.text(this,"Серия "+Ui.number(ep.number)+(ep.name.isEmpty()?"":" · "+ep.name),12,Ui.TEXT,true);title.setMaxLines(2);title.setEllipsize(android.text.TextUtils.TruncateAt.END);card.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView load=Ui.text(this,"Скачать",10,Ui.PURPLE,true);load.setPadding(Ui.dp(this,8),Ui.dp(this,7),Ui.dp(this,8),Ui.dp(this,7));load.setBackground(Ui.stroke(Ui.SURFACE,10,this));Ui.press(load);load.setOnClickListener(v->DownloadActions.prepare(this,anime,null,ep.number));card.addView(load);card.setOnClickListener(v->Ui.openPlayer(this,anime,"yoru",ep.number));Ui.press(card);outer.addView(card);body.addView(outer);}
    private LinearLayout card(){LinearLayout c=Ui.column(this);c.setPadding(Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14));c.setBackground(Ui.stroke(Ui.CARD,14,this));return c;}
    private void about(){Ui.space(body,24);body.addView(Ui.text(this,"Об истории",21,Ui.TEXT,true));Ui.space(body,13);TextView description=Ui.text(this,anime.description.isEmpty()?"Описание пока недоступно.":anime.description,14,0xffc8b8d6,false);description.setLineSpacing(Ui.dp(this,5),1);body.addView(description);}
    private void related(){if(anime.related.isEmpty())return;Ui.space(body,27);body.addView(Ui.text(this,"Связанные истории",21,Ui.TEXT,true));Ui.space(body,12);for(Anime a:anime.related.subList(0,Math.min(12,anime.related.size()))){LinearLayout row=Ui.row(this);row.setPadding(Ui.dp(this,13),Ui.dp(this,11),Ui.dp(this,13),Ui.dp(this,11));row.setBackground(Ui.stroke(Ui.CARD,14,this));ImageView poster=new ImageView(this);poster.setScaleType(ImageView.ScaleType.CENTER_CROP);poster.setClipToOutline(true);poster.setBackground(Ui.shape(Ui.SURFACE,12,this));row.addView(poster,Ui.lp(this,43,60));YoruApp.app().images.load(poster,a);TextView text=Ui.text(this,a.title+"\n"+a.meta(),12,Ui.TEXT,false);text.setPadding(Ui.dp(this,12),0,0,0);row.addView(text,new LinearLayout.LayoutParams(0,-2,1));Ui.press(row);row.setOnClickListener(v->Ui.openDetails(this,a));body.addView(row);Ui.space(body,9);}}
    private void editNote(){EditText input=new EditText(this);input.setText(YoruApp.app().store.note(anime));input.setTextColor(Ui.TEXT);input.setHintTextColor(Ui.MUTED);input.setHint("Например: смотреть вечером, любимая озвучка, с кем смотреть");input.setMinLines(3);input.setMaxLines(6);input.setFilters(new InputFilter[]{new InputFilter.LengthFilter(800)});input.setBackground(Ui.stroke(Ui.CARD,13,this));input.setPadding(Ui.dp(this,13),Ui.dp(this,10),Ui.dp(this,13),Ui.dp(this,10));Ui.custom(this,"Заметка",input,"Сохранить",()->{YoruApp.app().store.note(anime,input.getText().toString());Ui.toast(this,"Заметка сохранена");render();},"Удалить",()->{YoruApp.app().store.note(anime,"");Ui.toast(this,"Заметка удалена");render();},"Отмена");}
    private void choosePlayer(){Ui.choices(this,"Выберите плеер",ApiRepository.PLAYER_NAMES,index->Ui.openPlayer(this,anime,ApiRepository.PLAYER_IDS[index],YoruApp.app().store.progress(anime).optDouble("episode",1)));}
    @Override protected void onDestroy(){generation++;super.onDestroy();}
}
