package app.yoru.mobile;

import android.app.*;
import android.content.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import androidx.media3.exoplayer.offline.*;
import org.json.*;
import java.util.*;

public final class DownloadsScreen extends LinearLayout {
    private final Activity activity;private final DownloadHub hub;private final ArrayList<Download> rows=new ArrayList<>();private final TextView summary,empty;private final ListView list;private final Adapter adapter;private final Handler handler=new Handler(Looper.getMainLooper());
    private final Runnable update=new Runnable(){public void run(){refresh();handler.postDelayed(this,1800);}};
    public DownloadsScreen(Activity a){super(a);activity=a;hub=YoruApp.app().downloads();setOrientation(VERTICAL);setPadding(Ui.dp(a,17),Ui.dp(a,15),Ui.dp(a,17),Ui.dp(a,8));addView(Ui.label(a,"ВАШИ ИСТОРИИ ВСЕГДА РЯДОМ"));Ui.space(this,10);addView(Ui.text(a,"Загрузки",28,Ui.TEXT,true));Ui.space(this,9);addView(Ui.text(a,"Скачанные серии можно смотреть без интернета.",12,Ui.MUTED,false));Ui.space(this,16);summary=Ui.text(a,"",12,Ui.PURPLE,true);addView(summary);Ui.space(this,12);LinearLayout actions=Ui.row(a);actions.addView(Ui.button(a,"Продолжить загрузки",false,()->{try{DownloadService.sendSetStopReason(a,YoruDownloadService.class,null,0,true);DownloadService.sendResumeDownloads(a,YoruDownloadService.class,true);}catch(Exception e){Ui.toast(a,"Откройте приложение и попробуйте ещё раз");}}),new LinearLayout.LayoutParams(0,-2,1));Ui.space(this,4);addView(actions);Ui.space(this,12);list=new ListView(a);list.setDivider(null);list.setClipToPadding(false);list.setPadding(0,0,0,Ui.dp(a,15));list.setBackgroundColor(Ui.BG);adapter=new Adapter();list.setAdapter(adapter);empty=Ui.text(a,"Здесь появятся скачанные серии.\n\nОткройте аниме и нажмите «Скачать» на экране просмотра. Если текущий вариант доступен только онлайн, приложение предложит источник с прямым видео.",14,Ui.MUTED,false);empty.setPadding(Ui.dp(a,20),Ui.dp(a,40),Ui.dp(a,20),Ui.dp(a,20));empty.setGravity(Gravity.CENTER);FrameLayout frame=new FrameLayout(a);frame.addView(list,new FrameLayout.LayoutParams(-1,-1));frame.addView(empty,new FrameLayout.LayoutParams(-1,-1));addView(frame,new LinearLayout.LayoutParams(-1,0,1));list.setOnItemClickListener((parent,v,pos,id)->actions(rows.get(pos)));}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();handler.post(update);}
    @Override protected void onDetachedFromWindow(){handler.removeCallbacksAndMessages(null);super.onDetachedFromWindow();}
    private void refresh(){rows.clear();rows.addAll(hub.all());int complete=0,active=0;for(Download d:rows){if(d.state==Download.STATE_COMPLETED)complete++;if(d.state==Download.STATE_DOWNLOADING)active++;}summary.setText("Готово: "+complete+" · скачивается: "+active+" · "+Ui.bytes(YoruApp.app().mediaCache.offlineBytes()));empty.setVisibility(rows.isEmpty()?VISIBLE:GONE);adapter.notifyDataSetChanged();}
    private void actions(Download d){JSONObject meta=DownloadHub.metadata(d);Anime a=Anime.from(meta.optJSONObject("anime"));String voice=meta.optString("voice","");String title=a.title+" · серия "+Ui.number(meta.optDouble("episode",1))+(voice.isEmpty()?"":" · "+voice);ArrayList<String> choices=new ArrayList<>();if(d.state==Download.STATE_COMPLETED)choices.add("Смотреть офлайн");else if(d.state==Download.STATE_STOPPED)choices.add("Продолжить");else if(d.state==Download.STATE_FAILED)choices.add("Обновить и повторить");else if(d.state!=Download.STATE_REMOVING)choices.add("Пауза");choices.add("Удалить загрузку");new AlertDialog.Builder(activity).setTitle(title).setItems(choices.toArray(new String[0]),(dialog,which)->{String choice=choices.get(which);if(choice.equals("Смотреть офлайн"))Ui.openOffline(activity,d.request.id,a,meta.optDouble("episode",1));else if(choice.equals("Продолжить"))hub.resume(d.request.id);else if(choice.equals("Пауза"))hub.pause(d.request.id);else if(choice.equals("Обновить и повторить"))hub.retry(d.request.id);else new AlertDialog.Builder(activity).setMessage("Удалить скачанные файлы этой серии? Коллекция и история останутся.").setPositiveButton("Удалить",(x,y)->{hub.remove(d.request.id);refresh();}).setNegativeButton("Отмена",null).show();}).setNegativeButton("Закрыть",null).show();}
    private final class Adapter extends BaseAdapter {public int getCount(){return rows.size();}public Object getItem(int n){return rows.get(n);}public long getItemId(int n){return n;}public View getView(int position,View old,ViewGroup parent){Download d=rows.get(position);JSONObject meta=DownloadHub.metadata(d);Anime a=Anime.from(meta.optJSONObject("anime"));LinearLayout outer=Ui.column(activity);outer.setPadding(0,0,0,Ui.dp(activity,10));LinearLayout card=Ui.column(activity);card.setPadding(Ui.dp(activity,15),Ui.dp(activity,14),Ui.dp(activity,15),Ui.dp(activity,14));card.setBackground(Ui.stroke(Ui.CARD,13,activity));TextView title=Ui.text(activity,a.title,14,Ui.TEXT,true);title.setMaxLines(2);card.addView(title);Ui.space(card,7);int quality=meta.optInt("quality");String voice=meta.optString("voice","");card.addView(Ui.text(activity,"Серия "+Ui.number(meta.optDouble("episode",1))+" · "+(quality>0?quality+"p":"Оригинал")+(voice.isEmpty()?"":" · "+voice),11,Ui.PURPLE,false));Ui.space(card,9);String state=DownloadHub.status(d);if(d.state==Download.STATE_QUEUED&&YoruApp.app().store.wifiDownloads()&&YoruApp.app().traffic.metered())state="Ожидает Wi-Fi / безлимитную сеть";card.addView(Ui.text(activity,state,11,d.state==Download.STATE_FAILED?0xffe0a791:Ui.MUTED,false));if(d.state==Download.STATE_DOWNLOADING||d.state==Download.STATE_QUEUED||d.state==Download.STATE_RESTARTING){ProgressBar progress=new ProgressBar(activity,null,android.R.attr.progressBarStyleHorizontal);float pct=d.getPercentDownloaded();progress.setIndeterminate(pct<0);progress.setMax(100);if(pct>=0)progress.setProgress((int)pct);LinearLayout.LayoutParams pp=Ui.lp(activity,-1,7);pp.topMargin=Ui.dp(activity,11);pp.bottomMargin=Ui.dp(activity,9);card.addView(progress,pp);}
        long bytes=d.getBytesDownloaded();String size=Ui.bytes(bytes);if(d.contentLength>0)size+=" / "+Ui.bytes(d.contentLength);card.addView(Ui.text(activity,size+" · нажмите для действий",10,Ui.MUTED,false));outer.addView(card,Ui.lp(activity,-1,-2));return outer;}}
}
