package app.yoru.mobile;

import android.app.*;
import android.content.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import androidx.media3.exoplayer.offline.*;
import org.json.*;
import java.util.*;

public final class DownloadsScreen extends LinearLayout {
    private final Activity activity;private final DownloadHub hub;private final ArrayList<Download> rows=new ArrayList<>();private final TextView summary,empty;private final ListView list;private final Adapter adapter;private final Handler handler=new Handler(Looper.getMainLooper());private String lastSignature="";
    private final Runnable update=new Runnable(){public void run(){refreshSafe();handler.postDelayed(this,5000);}};
    public DownloadsScreen(Activity a){super(a);activity=a;hub=YoruApp.app().downloads();setOrientation(VERTICAL);setPadding(Ui.dp(a,17),Ui.dp(a,15),Ui.dp(a,17),Ui.dp(a,8));addView(Ui.label(a,"ОФЛАЙН-БИБЛИОТЕКА"));Ui.space(this,10);addView(Ui.text(a,"Загрузки",28,Ui.TEXT,true));Ui.space(this,9);addView(Ui.text(a,"Скачанные серии с превью, качеством и быстрым запуском во встроенном плеере YORU.",12,Ui.MUTED,false));Ui.space(this,16);summary=Ui.text(a,"",12,Ui.PURPLE,true);addView(summary);Ui.space(this,12);list=new ListView(a);list.setDivider(null);list.setClipToPadding(false);list.setVerticalScrollBarEnabled(false);list.setPadding(0,0,0,Ui.dp(a,15));list.setBackgroundColor(Ui.BG);adapter=new Adapter();list.setAdapter(adapter);empty=Ui.text(a,"Здесь появятся скачанные серии.\n\nОткройте аниме и нажмите «Скачать» рядом с нужной серией. Готовые загрузки открываются прямо в YORU.",14,Ui.MUTED,false);empty.setPadding(Ui.dp(a,20),Ui.dp(a,40),Ui.dp(a,20),Ui.dp(a,20));empty.setGravity(Gravity.CENTER);FrameLayout frame=new FrameLayout(a);frame.addView(list,new FrameLayout.LayoutParams(-1,-1));frame.addView(empty,new FrameLayout.LayoutParams(-1,-1));addView(frame,new LinearLayout.LayoutParams(-1,0,1));list.setOnItemClickListener((parent,v,pos,id)->{try{if(pos>=0&&pos<rows.size())actions(rows.get(pos));}catch(Throwable e){Ui.toast(activity,"Не удалось открыть действия загрузки");}});}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();handler.post(update);}
    @Override protected void onDetachedFromWindow(){handler.removeCallbacksAndMessages(null);super.onDetachedFromWindow();}
    private void refreshSafe(){try{refresh();}catch(Throwable e){summary.setText("Загрузки восстановлены после битой записи. Если повторится — удалите старую загрузку.");empty.setVisibility(rows.isEmpty()?VISIBLE:GONE);try{adapter.notifyDataSetChanged();}catch(Throwable ignored){}}}
    private void refresh(){ArrayList<Download> fresh=new ArrayList<>(hub.all());int complete=0,active=0;StringBuilder sig=new StringBuilder();for(Download d:new ArrayList<>(fresh)){if(d==null||d.request==null)continue;if(d.state==Download.STATE_COMPLETED)complete++;if(d.state==Download.STATE_DOWNLOADING)active++;int pct=d.getPercentDownloaded()<0?-1:(int)d.getPercentDownloaded();sig.append(d.request.id).append(':').append(d.state).append(':').append(pct/3).append(':').append(d.getBytesDownloaded()).append('|');}summary.setText("Готово: "+complete+" · скачивается: "+active+" · "+Ui.bytes(YoruApp.app().mediaCache.offlineBytes()));empty.setVisibility(fresh.isEmpty()?VISIBLE:GONE);String next=sig.toString();if(!next.equals(lastSignature)){lastSignature=next;rows.clear();rows.addAll(fresh);adapter.notifyDataSetChanged();}}
    private void actions(Download d){if(d==null||d.request==null){Ui.toast(activity,"Эта запись загрузки повреждена");return;}JSONObject meta=DownloadHub.metadata(d);Anime a=Anime.from(meta.optJSONObject("anime"));String voice=meta.optString("voice","");String title=(a.title==null||a.title.isEmpty()?"Загрузка":a.title)+" · серия "+Ui.number(meta.optDouble("episode",1))+(voice.isEmpty()?"":" · "+voice);ArrayList<String> choices=new ArrayList<>();if(d.state==Download.STATE_COMPLETED){choices.add("Смотреть в YORU");if(OfflineExporter.canExport(d)){choices.add("Открыть в другом плеере");choices.add("Сохранить через проводник");choices.add("Сохранить в Видео / YORU");choices.add("Поделиться файлом");}choices.add("Информация");}else if(d.state==Download.STATE_STOPPED)choices.add("Продолжить");else if(d.state==Download.STATE_FAILED)choices.add("Обновить и повторить");else if(d.state!=Download.STATE_REMOVING)choices.add("Пауза");choices.add("Удалить загрузку");Ui.choices(activity,title,choices.toArray(new String[0]),which->handle(d,a,meta,choices.get(which)));}
    private void handle(Download d,Anime a,JSONObject meta,String choice){try{if(choice.equals("Смотреть в YORU"))Ui.openOffline(activity,d.request.id,a,meta.optDouble("episode",1));else if(choice.equals("Открыть в другом плеере"))OfflineExporter.openExternal(activity,d);else if(choice.equals("Сохранить через проводник"))OfflineExporter.saveWithPicker(activity,d);else if(choice.equals("Сохранить в Видео / YORU"))OfflineExporter.saveToMovies(activity,d);else if(choice.equals("Поделиться файлом"))OfflineExporter.share(activity,d);else if(choice.equals("Информация"))Ui.message(activity,"Информация",OfflineExporter.details(d));else if(choice.equals("Продолжить"))hub.resume(d.request.id);else if(choice.equals("Пауза"))hub.pause(d.request.id);else if(choice.equals("Обновить и повторить"))hub.retry(d.request.id);else confirmDelete(d);}catch(Throwable e){Ui.toast(activity,"Действие загрузки не выполнено");}}
    private void confirmDelete(Download d){Ui.confirm(activity,"Удалить загрузку?","Удалить скачанные файлы этой серии?", "Удалить",()->{hub.remove(d.request.id);refreshSafe();},"Отмена");}
    private final class Adapter extends BaseAdapter {public int getCount(){return rows.size();}public Object getItem(int n){return rows.get(n);}public long getItemId(int n){return n;}public View getView(int position,View old,ViewGroup parent){try{return row(position);}catch(Throwable e){TextView t=Ui.text(activity,"Повреждённая запись загрузки",13,Ui.MUTED,false);t.setPadding(Ui.dp(activity,16),Ui.dp(activity,16),Ui.dp(activity,16),Ui.dp(activity,16));return t;}}
        private View row(int position){Download d=rows.get(position);JSONObject meta=DownloadHub.metadata(d);Anime a=Anime.from(meta.optJSONObject("anime"));LinearLayout outer=Ui.column(activity);outer.setPadding(0,0,0,Ui.dp(activity,10));LinearLayout card=Ui.column(activity);card.setPadding(Ui.dp(activity,12),Ui.dp(activity,12),Ui.dp(activity,12),Ui.dp(activity,12));card.setBackground(Ui.stroke(Ui.CARD,16,activity));card.addView(preview(d,a,meta),Ui.lp(activity,-1,154));Ui.space(card,12);TextView title=Ui.text(activity,a.title==null||a.title.isEmpty()?"Загрузка":YoruBrain.title(a),14,Ui.TEXT,true);title.setMaxLines(2);card.addView(title);Ui.space(card,7);int quality=meta.optInt("quality");String voice=meta.optString("voice","");card.addView(Ui.text(activity,"Серия "+Ui.number(meta.optDouble("episode",1))+" · "+(quality>0?quality+"p":"Оригинал")+(voice.isEmpty()?"":" · "+voice),11,Ui.PURPLE,false));Ui.space(card,7);String format;try{format=OfflineExporter.format(d);}catch(Throwable e){format="проверяется";}boolean export;try{export=OfflineExporter.canExport(d);}catch(Throwable e){export=false;}card.addView(Ui.text(activity,"Тип: "+format,10,export?0xffa9e8c2:Ui.MUTED,false));Ui.space(card,9);String state=DownloadHub.status(d);if(d.state==Download.STATE_QUEUED&&YoruApp.app().store.wifiDownloads()&&YoruApp.app().traffic.metered())state="Ожидает Wi-Fi";card.addView(Ui.text(activity,state,11,d.state==Download.STATE_FAILED?0xffe0a791:Ui.MUTED,false));if(d.state==Download.STATE_DOWNLOADING||d.state==Download.STATE_QUEUED||d.state==Download.STATE_RESTARTING){ProgressBar progress=new ProgressBar(activity,null,android.R.attr.progressBarStyleHorizontal);float pct=d.getPercentDownloaded();progress.setIndeterminate(pct<0);progress.setMax(100);if(pct>=0)progress.setProgress((int)pct);LinearLayout.LayoutParams pp=Ui.lp(activity,-1,7);pp.topMargin=Ui.dp(activity,11);pp.bottomMargin=Ui.dp(activity,9);card.addView(progress,pp);}long bytes=d.getBytesDownloaded();String size=Ui.bytes(bytes);if(d.contentLength>0)size+=" / "+Ui.bytes(d.contentLength);card.addView(Ui.text(activity,size,10,Ui.MUTED,false));Ui.space(card,11);quick(card,d,a,meta);outer.addView(card,Ui.lp(activity,-1,-2));return outer;}
        private View preview(Download d,Anime a,JSONObject meta){FrameLayout frame=new FrameLayout(activity);frame.setBackground(Ui.gradient(0xff2a2135,0xff18131f,18,activity));frame.setClipToOutline(true);ImageView img=new ImageView(activity);img.setScaleType(ImageView.ScaleType.CENTER_CROP);frame.addView(img,new FrameLayout.LayoutParams(-1,-1));String poster=episodePoster(a,meta);if(!poster.isEmpty())YoruApp.app().images.load(img,poster,a.key()+":download:"+Ui.number(meta.optDouble("episode",1)));else if(Anime.valid(a))YoruApp.app().images.load(img,a);View shade=new View(activity);shade.setBackground(Ui.gradient(0x00111111,0xdd110d18,18,activity));frame.addView(shade,new FrameLayout.LayoutParams(-1,-1));LinearLayout caption=Ui.column(activity);caption.setPadding(Ui.dp(activity,14),0,Ui.dp(activity,14),Ui.dp(activity,12));TextView ep=Ui.text(activity,"Серия "+Ui.number(meta.optDouble("episode",1)),18,Ui.TEXT,true);caption.addView(ep);TextView status=Ui.text(activity,d.state==Download.STATE_COMPLETED?"Готово офлайн":"Загрузка в YORU",11,Ui.PURPLE,true);caption.addView(status);FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);frame.addView(caption,cp);if(d.state==Download.STATE_COMPLETED){FrameLayout circle=new FrameLayout(activity);circle.setBackground(Ui.shape(0xcc20162c,42,activity));Ui.Icon play=new Ui.Icon(activity,"play");play.color=Ui.TEXT;circle.addView(play,new FrameLayout.LayoutParams(Ui.dp(activity,30),Ui.dp(activity,30),Gravity.CENTER));frame.addView(circle,new FrameLayout.LayoutParams(Ui.dp(activity,58),Ui.dp(activity,58),Gravity.CENTER));Ui.press(frame);frame.setOnClickListener(v->Ui.openOffline(activity,d.request.id,a,meta.optDouble("episode",1)));}return frame;}
        private void quick(LinearLayout card,Download d,Anime a,JSONObject meta){LinearLayout row=Ui.row(activity);row.setGravity(Gravity.CENTER_VERTICAL);if(d.state==Download.STATE_COMPLETED){row.addView(icon("play","Смотреть",()->Ui.openOffline(activity,d.request.id,a,meta.optDouble("episode",1))),Ui.lp(activity,44,44));addIcon(row,"trash","Удалить",()->confirmDelete(d));if(OfflineExporter.canExport(d))addIcon(row,"download","Сохранить",()->OfflineExporter.saveWithPicker(activity,d));}else if(d.state==Download.STATE_FAILED){row.addView(icon("retry","Повторить",()->{hub.retry(d.request.id);refreshSafe();}),Ui.lp(activity,44,44));addIcon(row,"trash","Удалить",()->{hub.remove(d.request.id);refreshSafe();});}else if(d.state==Download.STATE_STOPPED){row.addView(icon("play","Продолжить",()->{hub.resume(d.request.id);refreshSafe();}),Ui.lp(activity,44,44));addIcon(row,"trash","Удалить",()->confirmDelete(d));}else{row.addView(icon("pause","Пауза",()->{hub.pause(d.request.id);refreshSafe();}),Ui.lp(activity,44,44));addIcon(row,"trash","Удалить",()->confirmDelete(d));}card.addView(row);}
        private void addIcon(LinearLayout row,String kind,String desc,Runnable action){LinearLayout.LayoutParams lp=Ui.lp(activity,44,44);lp.leftMargin=Ui.dp(activity,8);row.addView(icon(kind,desc,action),lp);}
        private View icon(String kind,String desc,Runnable action){return Ui.iconButton(activity,kind,desc,action);}
        private String episodePoster(Anime a,JSONObject meta){String p=ApiRepository.safeUrl(meta.optString("episodePoster",meta.optString("poster","")));if(!p.isEmpty())return p;double ep=meta.optDouble("episode",1);if(Anime.valid(a)&&!a.screenshots.isEmpty())return a.screenshots.get(Math.abs((int)Math.floor(ep)-1)%a.screenshots.size());return "";}
        private TextView small(String text,Runnable action){TextView b=Ui.button(activity,text,false,action);b.setTextSize(11);b.setMinHeight(Ui.dp(activity,38));b.setPadding(Ui.dp(activity,8),Ui.dp(activity,8),Ui.dp(activity,8),Ui.dp(activity,8));return b;}}
}
