package app.yoru.mobile;

import android.content.Context;
import android.net.Uri;
import android.os.Handler;
import android.os.Looper;
import androidx.media3.common.*;
import androidx.media3.exoplayer.DefaultRenderersFactory;
import androidx.media3.exoplayer.offline.*;
import androidx.media3.exoplayer.scheduler.Requirements;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

public final class DownloadHub {
    public static final int USER_PAUSED=1;
    public final DownloadManager manager;
    private final Context context;private final MediaCache caches;private final Handler main=new Handler(Looper.getMainLooper());private final Set<String> preparing=Collections.synchronizedSet(new HashSet<>());private final Map<String,DownloadRequest> replacement=new ConcurrentHashMap<>();
    public DownloadHub(Context c,MediaCache cache){context=c.getApplicationContext();caches=cache;manager=new DownloadManager(context,caches.database(),caches.offline(),caches.http(),Executors.newFixedThreadPool(2));manager.setMaxParallelDownloads(2);applyRequirements();manager.addListener(new DownloadManager.Listener(){@Override public void onDownloadRemoved(DownloadManager dm,Download d){DownloadRequest pending=replacement.remove(d.request.id);if(pending!=null)dm.addDownload(pending);}});}
    public void applyRequirements(){manager.setRequirements(new Requirements(Requirements.NETWORK|(YoruApp.app().store.wifiDownloads()?Requirements.NETWORK_UNMETERED:0)));}
    public List<Download> all(){ArrayList<Download> list=new ArrayList<>();DownloadCursor cursor=null;try{cursor=manager.getDownloadIndex().getDownloads();while(cursor.moveToNext())list.add(cursor.getDownload());}catch(IOException ignored){}finally{if(cursor!=null)cursor.close();}list.sort((a,b)->Long.compare(b.startTimeMs,a.startTimeMs));return list;}
    public Download get(String id){try{return manager.getDownloadIndex().getDownload(id);}catch(IOException e){return null;}}
    public static JSONObject metadata(Download d){try{return new JSONObject(new String(d.request.data,StandardCharsets.UTF_8));}catch(Exception e){return new JSONObject();}}
    public static String status(Download d){switch(d.state){case Download.STATE_COMPLETED:return "Готово к просмотру офлайн";case Download.STATE_DOWNLOADING:return "Скачивается";case Download.STATE_QUEUED:return "В очереди / ожидание сети";case Download.STATE_STOPPED:return "Приостановлено";case Download.STATE_FAILED:return "Не удалось скачать";case Download.STATE_REMOVING:return "Удаляется";case Download.STATE_RESTARTING:return "Перезапускается";default:return "Подготовка";}}
    public static String idFor(Anime source,Anime.Episode ep,int quality){String input=source.key()+"|"+ep.id+"|"+ep.number+"|"+quality+"|"+ep.name;try{byte[] hash=MessageDigest.getInstance("SHA-256").digest(input.getBytes(StandardCharsets.UTF_8));StringBuilder out=new StringBuilder();for(byte b:hash)out.append(String.format(Locale.ROOT,"%02x",b&255));return out.toString();}catch(Exception e){return input.replace(':','_');}}
    public boolean preparing(String id){return preparing.contains(id);}
    public void enqueue(Anime catalog,Anime source,Anime.Episode ep,int quality){String url=ep.streams.get(quality);if(url==null||ApiRepository.safeUrl(url).isEmpty()){Ui.toast(context,"Источник не предоставил прямое видео для загрузки");return;}String id=idFor(source,ep,quality);Download exists=get(id);if(exists!=null&&exists.state==Download.STATE_COMPLETED){Ui.toast(context,"Эта серия уже скачана");return;}if(exists!=null&&exists.state!=Download.STATE_FAILED&&exists.state!=Download.STATE_STOPPED&&exists.state!=Download.STATE_REMOVING){Ui.toast(context,"Эта серия уже в очереди");return;}if(!preparing.add(id)){Ui.toast(context,"Серия уже подготавливается");return;}if(context.getFilesDir().getUsableSpace()<100L*1024*1024){preparing.remove(id);Ui.toast(context,"Недостаточно свободного места");return;}
        Ui.toast(context,"Подготавливаем серию к скачиванию…");try{JSONObject meta=new JSONObject().put("anime",catalog.json()).put("source",source.json()).put("episode",ep.number).put("episodeId",ep.id).put("title",ep.name).put("voice",ep.name).put("quality",quality).put("created",System.currentTimeMillis());MediaItem item=item(url);TrackSelectionParameters.Builder selection=new TrackSelectionParameters.Builder(context).setPreferredAudioLanguage("ru");if(quality>0)selection.setMaxVideoSize(Integer.MAX_VALUE,quality);else selection.setForceLowestBitrate(true);DownloadHelper helper=DownloadHelper.forMediaItem(item,selection.build(),new DefaultRenderersFactory(context),caches.http());helper.prepare(new DownloadHelper.Callback(){@Override public void onPrepared(DownloadHelper h){try{DownloadRequest request=h.getDownloadRequest(id,meta.toString().getBytes(StandardCharsets.UTF_8));Download current=get(id);if(current!=null&&(current.state==Download.STATE_FAILED||current.state==Download.STATE_REMOVING)){replacement.put(id,request);DownloadService.sendRemoveDownload(context,YoruDownloadService.class,id,true);}else DownloadService.sendAddDownload(context,YoruDownloadService.class,request,true);DownloadService.sendResumeDownloads(context,YoruDownloadService.class,true);Ui.toast(context,YoruApp.app().store.wifiDownloads()&&YoruApp.app().traffic.metered()?"Добавлено. Ожидаем Wi-Fi / безлимитную сеть.":"Серия добавлена в загрузки");}catch(Exception e){Ui.toast(context,"Не удалось начать загрузку. Попробуйте другой источник.");}finally{preparing.remove(id);h.release();}}@Override public void onPrepareError(DownloadHelper h,IOException error){preparing.remove(id);h.release();Ui.toast(context,"Поток не удалось подготовить для офлайн. Попробуйте другой источник.");}});}catch(Exception e){preparing.remove(id);Ui.toast(context,"Загрузка этого потока недоступна.");}}
    public static MediaItem item(String uri){MediaItem.Builder b=new MediaItem.Builder().setUri(uri);String path=Uri.parse(uri).getPath();String p=path==null?"":path.toLowerCase(Locale.ROOT);if(p.endsWith(".m3u8"))b.setMimeType(MimeTypes.APPLICATION_M3U8);else if(p.endsWith(".mpd"))b.setMimeType(MimeTypes.APPLICATION_MPD);else if(p.endsWith(".mp4"))b.setMimeType(MimeTypes.VIDEO_MP4);return b.build();}
    public MediaItem offlineItem(Download download){return item(download.request.uri.toString()).buildUpon().setStreamKeys(download.request.streamKeys).setCustomCacheKey(download.request.customCacheKey).build();}
    public void pause(String id){DownloadService.sendSetStopReason(context,YoruDownloadService.class,id,USER_PAUSED,true);}
    public void resume(String id){DownloadService.sendSetStopReason(context,YoruDownloadService.class,id,Download.STOP_REASON_NONE,true);DownloadService.sendResumeDownloads(context,YoruDownloadService.class,true);}
    public void remove(String id){replacement.remove(id);DownloadService.sendRemoveDownload(context,YoruDownloadService.class,id,true);}
    public void retry(String id){Download d=get(id);if(d==null)return;JSONObject meta=metadata(d);Anime catalog=Anime.from(meta.optJSONObject("anime")),source=Anime.from(meta.optJSONObject("source"));double number=meta.optDouble("episode",1);int quality=meta.optInt("quality",720);String voice=meta.optString("voice","");String sourceId=source.source;Ui.toast(context,"Обновляем варианты загрузки…");YoruApp.app().io.execute(()->{try{YoruApp.app().api.clearMemory();List<ApiRepository.DownloadOption> options=YoruApp.app().api.downloadOptions(catalog,null,number);ApiRepository.DownloadOption selected=null;for(ApiRepository.DownloadOption option:options){boolean sameSource=sourceId.equals(option.source.source);boolean sameVoice=voice.isEmpty()||voice.equals(option.voice)||voice.equals(option.episode.name);if(option.quality==quality&&sameSource&&sameVoice){selected=option;break;}}if(selected==null)for(ApiRepository.DownloadOption option:options)if(option.quality==quality){selected=option;break;}if(selected==null&&!options.isEmpty())selected=options.get(0);if(selected==null)throw new IOException();ApiRepository.DownloadOption ready=selected;main.post(()->enqueue(catalog,ready.source,ready.episode,ready.quality));}catch(Exception e){main.post(()->Ui.toast(context,"Источники не смогли обновить видео. Можно удалить загрузку и выбрать другой вариант."));}});}
    public Download neighbour(Download current,int direction){JSONObject own=metadata(current);Anime a=Anime.from(own.optJSONObject("anime"));double number=own.optDouble("episode",1)+direction;Download best=null;for(Download d:all()){if(d.state!=Download.STATE_COMPLETED)continue;JSONObject m=metadata(d);Anime b=Anime.from(m.optJSONObject("anime"));if(a.key().equals(b.key())&&Double.compare(m.optDouble("episode",-1),number)==0){best=d;if(m.optInt("quality")==own.optInt("quality"))break;}}return best;}
    public Download findCompleted(Anime a,double episode){Download best=null;for(Download d:all()){if(d.state!=Download.STATE_COMPLETED)continue;JSONObject m=metadata(d);Anime parent=Anime.from(m.optJSONObject("anime")),source=Anime.from(m.optJSONObject("source"));boolean same=a.key().equals(parent.key())||a.key().equals(source.key())||(a.malId>0&&a.malId==parent.malId);if(same&&Double.compare(m.optDouble("episode",-1),episode)==0){if(best==null||metadata(best).optInt("quality")<m.optInt("quality"))best=d;}}return best;}
}
