package app.yoru.mobile;

import android.Manifest;
import android.app.*;
import android.content.pm.PackageManager;
import android.os.Build;
import android.widget.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;

public final class DownloadActions {
    private DownloadActions(){}
    private interface Loader {List<ApiRepository.DownloadOption> load()throws Exception;}
    public static void askEpisode(Activity activity,Anime anime,Anime.Playback current,double suggested){chooseEpisode(activity,anime,current,suggested);}
    public static void chooseEpisode(Activity activity,Anime anime,Anime.Playback current,double suggested){AtomicBoolean cancelled=new AtomicBoolean(false);ProgressDialog wait=new ProgressDialog(activity);wait.setMessage("Загружаем список серий…");wait.setCancelable(true);wait.setOnCancelListener(d->cancelled.set(true));wait.show();YoruApp.app().io.execute(()->{try{Anime.Playback ready=current;if(ready==null||ready.video==null||ready.video.episodeList.isEmpty())ready=YoruApp.app().api.playback(anime,"auto");Anime.Playback finalReady=ready;ArrayList<Anime.Episode> episodes=new ArrayList<>(ready.video.episodeList);YoruApp.app().main.post(()->{if(dead(activity)||cancelled.get())return;wait.dismiss();if(episodes.isEmpty()){Ui.toast(activity,"У источников пока нет списка серий");return;}String[] labels=new String[episodes.size()];int index=0;double best=Double.MAX_VALUE;for(int i=0;i<episodes.size();i++){Anime.Episode ep=episodes.get(i);labels[i]="Серия "+Ui.number(ep.number)+(ep.name.isEmpty()?"":" · "+ep.name);double diff=Math.abs(ep.number-suggested);if(diff<best){best=diff;index=i;}}final int[] selected={index};new AlertDialog.Builder(activity).setTitle("Выберите серию").setSingleChoiceItems(labels,index,(d,i)->selected[0]=i).setPositiveButton("Выбрать качество",(d,i)->prepare(activity,anime,finalReady,episodes.get(selected[0]).number)).setNegativeButton("Отмена",null).show();});}catch(Exception e){YoruApp.app().main.post(()->{if(!dead(activity)&&!cancelled.get()){wait.dismiss();Ui.toast(activity,"Не удалось загрузить список серий");}});}});}
    public static void prepare(Activity activity,Anime anime,Anime.Playback current,double episode){loadAndShow(activity,anime,episode,"Ищем все варианты для загрузки…","У текущих источников не найден прямой видеопоток этой серии. Откройте серию в YummyAnime и нажмите «Скачать эту серию» после начала воспроизведения.",()->YoruApp.app().api.downloadOptions(anime,current,episode));}
    public static void prepareCurrentFrame(Activity activity,Anime anime,Anime.Playback current,double episode,String iframeUrl,String voice,String player,List<String> captured){loadAndShow(activity,anime,episode,"Готовим текущий YummyAnime iframe…","Не удалось поймать прямой поток текущего iframe. Запустите воспроизведение на пару секунд и нажмите «Скачать эту серию» ещё раз.",()->{ArrayList<ApiRepository.DownloadOption> out=new ArrayList<>();out.addAll(frameOptions(anime,episode,iframeUrl,voice,player,captured));out.addAll(YoruApp.app().api.downloadOptions(anime,current,episode));return merge(out);});}
    private static void loadAndShow(Activity activity,Anime anime,double episode,String message,String empty,Loader loader){AtomicBoolean cancelled=new AtomicBoolean(false);ProgressDialog wait=new ProgressDialog(activity);wait.setMessage(message);wait.setCancelable(true);wait.setOnCancelListener(d->cancelled.set(true));wait.show();YoruApp.app().io.execute(()->{try{List<ApiRepository.DownloadOption> options=merge(loader.load());YoruApp.app().main.post(()->{if(dead(activity)||cancelled.get())return;wait.dismiss();if(options.isEmpty()){new AlertDialog.Builder(activity).setTitle("Нет доступного варианта для скачивания").setMessage(empty).setPositiveButton("Понятно",null).show();return;}showOptions(activity,anime,episode,options);});}catch(Exception e){YoruApp.app().main.post(()->{if(!dead(activity)&&!cancelled.get()){wait.dismiss();Ui.toast(activity,"Не удалось подготовить загрузку. Попробуйте другой источник.");}});}});}
    private static void showOptions(Activity activity,Anime anime,double episode,List<ApiRepository.DownloadOption> options){String[] labels=new String[options.size()];int preferred=YoruApp.app().savingMobile()?480:YoruApp.app().store.quality(),index=0,best=-1;for(int i=0;i<options.size();i++){labels[i]=options.get(i).label();int q=options.get(i).quality;if(q>0&&q<=preferred&&q>best){best=q;index=i;}}final int[] selected={index};new AlertDialog.Builder(activity).setTitle("Серия "+Ui.number(episode)+" · качество").setSingleChoiceItems(labels,index,(d,i)->selected[0]=i).setPositiveButton("Скачать",(d,i)->confirm(activity,anime,options.get(selected[0]))).setNegativeButton("Отмена",null).show();}
    private static List<ApiRepository.DownloadOption> frameOptions(Anime anime,double number,String iframe,String voice,String player,List<String> captured){ArrayList<ApiRepository.DownloadOption> out=new ArrayList<>();LinkedHashSet<String> urls=new LinkedHashSet<>();if(captured!=null)for(String u:captured){String safe=ApiRepository.safeUrl(u);if(!safe.isEmpty()&&VideoResolver.downloadable(safe))urls.add(safe);}String safeFrame=ApiRepository.embed(iframe);if(!safeFrame.isEmpty())try{TreeMap<Integer,String> streams=VideoResolver.resolve(YoruApp.app().api,safeFrame);for(String u:streams.values()){String safe=ApiRepository.safeUrl(u);if(!safe.isEmpty())urls.add(safe);}}catch(Exception ignored){}int n=0;for(String url:urls){int quality=VideoResolver.qualityOf(url);Anime source=new Anime();source.source="yummy";source.id="iframe-"+Integer.toHexString((anime.key()+"|"+url).hashCode());source.title=anime.title;source.original=anime.original;source.poster=anime.poster;source.description=anime.description;source.year=anime.year;source.type=anime.type;source.status=anime.status;source.episodes=anime.episodes;source.malId=anime.malId;source.anilistId=anime.anilistId;source.kpId=anime.kpId;Anime.Episode ep=new Anime.Episode();ep.id=source.id+"-"+Ui.number(number)+"-"+(++n);ep.number=number;ep.name=(voice==null||voice.isEmpty())?"YummyAnime Iframe":voice;ep.streams.put(quality,url);out.add(new ApiRepository.DownloadOption(source,ep,quality,ep.name,(player==null||player.isEmpty())?"YummyAnime":player));}return out;}
    private static ArrayList<ApiRepository.DownloadOption> merge(List<ApiRepository.DownloadOption> options){LinkedHashMap<String,ApiRepository.DownloadOption> map=new LinkedHashMap<>();if(options!=null)for(ApiRepository.DownloadOption option:options){if(option==null||option.source==null||option.episode==null)continue;String url=option.episode.streams.get(option.quality);String safe=ApiRepository.safeUrl(url);if(safe.isEmpty())continue;String key=option.source.source+"|"+option.quality+"|"+option.voice+"|"+option.player+"|"+safe;if(!map.containsKey(key))map.put(key,option);}return new ArrayList<>(map.values());}
    private static void confirm(Activity a,Anime anime,ApiRepository.DownloadOption option){Runnable run=()->{if(Build.VERSION.SDK_INT>=33&&a.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)a.requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},4101);YoruApp.app().downloads().enqueue(anime,option.source,option.episode,option.quality);};if(YoruApp.app().traffic.metered()&&!YoruApp.app().store.wifiDownloads())new AlertDialog.Builder(a).setTitle("Использовать мобильную / платную сеть?").setMessage("Размер серии может составлять сотни мегабайт. Можно включить загрузки только по Wi-Fi в профиле.").setPositiveButton("Скачать",(d,w)->run.run()).setNegativeButton("Отмена",null).show();else run.run();}
    private static boolean dead(Activity activity){return activity.isFinishing()||activity.isDestroyed();}
}
