package app.yoru.mobile;

import android.Manifest;
import android.app.Activity;
import android.content.pm.PackageManager;
import android.os.Build;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;

public final class DownloadActions {
    private DownloadActions(){}
    private interface Loader {List<ApiRepository.DownloadOption> load()throws Exception;}
    public static void askEpisode(Activity activity,Anime anime,Anime.Playback current,double suggested){chooseEpisode(activity,anime,current,suggested);}
    public static void chooseEpisode(Activity activity,Anime anime,Anime.Playback current,double suggested){AtomicBoolean cancelled=new AtomicBoolean(false);Ui.Progress wait=Ui.progress(activity,"Загружаем список серий…",true,()->cancelled.set(true));YoruApp.app().io.execute(()->{try{Anime.Playback ready=current;if(ready==null||ready.video==null||ready.video.episodeList.isEmpty())ready=YoruApp.app().api.playback(anime,"auto");Anime.Playback finalReady=ready;ArrayList<Anime.Episode> episodes=new ArrayList<>(ready.video.episodeList);YoruApp.app().main.post(()->{if(dead(activity)||cancelled.get())return;wait.dismiss();if(episodes.isEmpty()){Ui.toast(activity,"У источников пока нет списка серий");return;}String[] labels=labels(episodes);int index=closest(episodes,suggested);Ui.singleChoice(activity,"Выберите серию",labels,index,"Качество",i->prepare(activity,anime,finalReady,episodes.get(i).number));});}catch(Exception e){YoruApp.app().main.post(()->{if(!dead(activity)&&!cancelled.get()){wait.dismiss();Ui.toast(activity,"Не удалось загрузить список серий");}});}});}
    public static void chooseBatch(Activity activity,Anime anime,Anime.Playback current,double suggested){AtomicBoolean cancelled=new AtomicBoolean(false);Ui.Progress wait=Ui.progress(activity,"Загружаем серии для массового скачивания…",true,()->cancelled.set(true));YoruApp.app().io.execute(()->{try{Anime.Playback ready=current;if(ready==null||ready.video==null||ready.video.episodeList.isEmpty())ready=YoruApp.app().api.playback(anime,"auto");Anime.Playback finalReady=ready;ArrayList<Anime.Episode> episodes=new ArrayList<>(ready.video.episodeList);YoruApp.app().main.post(()->{if(dead(activity)||cancelled.get())return;wait.dismiss();if(episodes.isEmpty()){Ui.toast(activity,"У источников пока нет списка серий");return;}showBatch(activity,anime,finalReady,episodes,suggested);});}catch(Exception e){YoruApp.app().main.post(()->{if(!dead(activity)&&!cancelled.get()){wait.dismiss();Ui.toast(activity,"Не удалось загрузить список серий");}});}});}
    public static void prepare(Activity activity,Anime anime,Anime.Playback current,double episode){loadAndShow(activity,anime,episode,"Ищем все варианты для загрузки…","У текущих источников не найден прямой видеопоток этой серии. Откройте серию в плеере и попробуйте другой источник.",()->YoruApp.app().api.downloadOptions(anime,current,episode));}
    public static void prepareCurrentFrame(Activity activity,Anime anime,Anime.Playback current,double episode,String iframeUrl,String voice,String player,List<String> captured){loadAndShow(activity,anime,episode,"Готовим текущий внешний плеер…","Не удалось получить прямой поток текущего внешнего плеера. Запустите воспроизведение на пару секунд и нажмите «Скачать» ещё раз.",()->merge(frameOptions(anime,episode,iframeUrl,voice,player,captured)));}
    public static void prepareNativeCurrent(Activity activity,Anime anime,Anime.Playback current,double number,Anime.Episode episode,String voice,String player){loadAndShow(activity,anime,number,"Готовим текущую озвучку…","У текущей озвучки нет прямого потока для скачивания.",()->merge(nativeOptions(anime,number,episode,voice,player)));}
    private static void showBatch(Activity activity,Anime anime,Anime.Playback ready,ArrayList<Anime.Episode> episodes,double suggested){String[] presets={"Следующие 3 серии","Следующие 6 серий","Следующие 12 серий","Выбрать серии вручную"};Ui.choices(activity,"Массовое скачивание",presets,which->{if(which==3)multiBatch(activity,anime,ready,episodes,suggested);else{int count=which==0?3:which==1?6:12;int start=closest(episodes,suggested);ArrayList<Anime.Episode> selected=new ArrayList<>();for(int i=start;i<episodes.size()&&selected.size()<count;i++)selected.add(episodes.get(i));qualityBatch(activity,anime,ready,selected);}});}
    private static void multiBatch(Activity activity,Anime anime,Anime.Playback ready,ArrayList<Anime.Episode> episodes,double suggested){String[] labels=labels(episodes);boolean[] checked=new boolean[episodes.size()];int start=closest(episodes,suggested);for(int i=0;i<episodes.size();i++)checked[i]=i>=start&&i<start+3;Ui.multiChoice(activity,"Выберите серии",labels,checked,"Качество",state->{ArrayList<Anime.Episode> selected=new ArrayList<>();for(int n=0;n<episodes.size();n++)if(state[n])selected.add(episodes.get(n));qualityBatch(activity,anime,ready,selected);});}
    private static void qualityBatch(Activity activity,Anime anime,Anime.Playback ready,ArrayList<Anime.Episode> episodes){if(episodes.isEmpty()){Ui.toast(activity,"Серии не выбраны");return;}String[] labels={"Авто как в настройках","480p или ниже","720p или ниже","1080p или ниже","Лучшее доступное"};int[] values={-1,480,720,1080,9999};Ui.choices(activity,"Качество для "+episodes.size()+" серий",labels,which->startBatch(activity,anime,ready,episodes,values[which]));}
    private static void startBatch(Activity activity,Anime anime,Anime.Playback ready,ArrayList<Anime.Episode> episodes,int preferred){AtomicBoolean cancelled=new AtomicBoolean(false);Ui.Progress wait=Ui.progress(activity,"Готовим очередь: 0 / "+episodes.size(),true,()->cancelled.set(true));YoruApp.app().io.execute(()->{int added=0,failed=0;for(int i=0;i<episodes.size()&&!cancelled.get();i++){Anime.Episode ep=episodes.get(i);int done=i+1;YoruApp.app().main.post(()->{if(!dead(activity))wait.setMessage("Готовим очередь: "+done+" / "+episodes.size());});try{List<ApiRepository.DownloadOption> options=YoruApp.app().api.downloadOptions(anime,ready,ep.number);ApiRepository.DownloadOption chosen=choose(options,preferred);if(chosen==null){failed++;continue;}added++;YoruApp.app().main.post(()->{if(!dead(activity))YoruApp.app().downloads().enqueue(anime,chosen.source,chosen.episode,chosen.quality);});Thread.sleep(100);}catch(Exception e){failed++;}}int a=added,f=failed;YoruApp.app().main.post(()->{if(dead(activity))return;wait.dismiss();Ui.toast(activity,"В очередь добавлено: "+a+(f>0?" · не найдено: "+f:""));});});}
    private static ApiRepository.DownloadOption choose(List<ApiRepository.DownloadOption> options,int preferred){if(options==null||options.isEmpty())return null;ApiRepository.DownloadOption best=null;if(preferred==9999){for(ApiRepository.DownloadOption o:options)if(best==null||o.quality>best.quality)best=o;return best==null?options.get(0):best;}int limit=preferred<0?(YoruApp.app().savingMobile()?480:YoruApp.app().store.quality()):preferred;for(ApiRepository.DownloadOption o:options)if(o.quality>0&&o.quality<=limit&&(best==null||o.quality>best.quality))best=o;if(best!=null)return best;for(ApiRepository.DownloadOption o:options)if(best==null||o.quality<best.quality)best=o;return best==null?options.get(0):best;}
    private static void loadAndShow(Activity activity,Anime anime,double episode,String message,String empty,Loader loader){AtomicBoolean cancelled=new AtomicBoolean(false);Ui.Progress wait=Ui.progress(activity,message,true,()->cancelled.set(true));YoruApp.app().io.execute(()->{try{List<ApiRepository.DownloadOption> options=merge(loader.load());YoruApp.app().main.post(()->{if(dead(activity)||cancelled.get())return;wait.dismiss();if(options.isEmpty()){Ui.message(activity,"Нет доступного варианта",empty);return;}showOptions(activity,anime,episode,options);});}catch(Exception e){YoruApp.app().main.post(()->{if(!dead(activity)&&!cancelled.get()){wait.dismiss();Ui.toast(activity,"Не удалось подготовить загрузку. Попробуйте другой источник.");}});}});}
    private static void showOptions(Activity activity,Anime anime,double episode,List<ApiRepository.DownloadOption> options){String[] labels=new String[options.size()];int preferred=YoruApp.app().savingMobile()?480:YoruApp.app().store.quality(),index=0,best=-1;for(int i=0;i<options.size();i++){labels[i]=options.get(i).label()+" · "+streamType(options.get(i));int q=options.get(i).quality;if(q>0&&q<=preferred&&q>best){best=q;index=i;}}Ui.singleChoice(activity,"Серия "+Ui.number(episode)+" · качество",labels,index,"Скачать",i->confirm(activity,anime,options.get(i)));}
    private static List<ApiRepository.DownloadOption> nativeOptions(Anime anime,double number,Anime.Episode current,String voice,String player){ArrayList<ApiRepository.DownloadOption> out=new ArrayList<>();if(current==null||current.streams.isEmpty())return out;int n=0;for(Map.Entry<Integer,String> stream:current.streams.entrySet()){String safe=ApiRepository.safeUrl(stream.getValue());if(safe.isEmpty())continue;Anime source=copyAnime(anime,"yummy","native-"+Integer.toHexString((anime.key()+"|"+safe).hashCode()));Anime.Episode ep=new Anime.Episode();ep.id=source.id+"-"+Ui.number(number)+"-"+(++n);ep.number=number;ep.name=(voice==null||voice.isEmpty())?"Встроенный плеер":voice;ep.streams.put(stream.getKey(),safe);out.add(new ApiRepository.DownloadOption(source,ep,stream.getKey(),ep.name,(player==null||player.isEmpty())?"Встроенный плеер":"Встроенный плеер · "+player));}return out;}
    private static List<ApiRepository.DownloadOption> frameOptions(Anime anime,double number,String iframe,String voice,String player,List<String> captured){ArrayList<ApiRepository.DownloadOption> out=new ArrayList<>();LinkedHashSet<String> urls=new LinkedHashSet<>();if(captured!=null)for(String u:captured){String safe=ApiRepository.safeUrl(u);if(!safe.isEmpty()&&VideoResolver.downloadable(safe))urls.add(safe);}String safeFrame=ApiRepository.embed(iframe);if(!safeFrame.isEmpty())try{TreeMap<Integer,String> streams=VideoResolver.resolve(YoruApp.app().api,safeFrame);for(String u:streams.values()){String safe=ApiRepository.safeUrl(u);if(!safe.isEmpty())urls.add(safe);}}catch(Exception ignored){}int n=0;for(String url:urls){int quality=VideoResolver.qualityOf(url);Anime source=copyAnime(anime,"yummy","iframe-"+Integer.toHexString((anime.key()+"|"+url).hashCode()));Anime.Episode ep=new Anime.Episode();ep.id=source.id+"-"+Ui.number(number)+"-"+(++n);ep.number=number;ep.name=(voice==null||voice.isEmpty())?"Внешний плеер":voice;ep.streams.put(quality,url);out.add(new ApiRepository.DownloadOption(source,ep,quality,ep.name,(player==null||player.isEmpty())?"Внешний плеер":player));}return out;}
    private static String streamType(ApiRepository.DownloadOption option){try{String url=option.episode.streams.get(option.quality);String lower=ApiRepository.safeUrl(url).toLowerCase(Locale.ROOT);if(lower.contains(".m3u8")||lower.contains("hls"))return "HLS";if(lower.contains(".mpd")||lower.contains("dash"))return "DASH";if(lower.contains(".webm"))return "WebM";if(lower.contains(".mkv"))return "MKV";if(lower.contains(".mp4"))return "MP4";}catch(Exception ignored){}return "поток";}
    private static Anime copyAnime(Anime anime,String sourceId,String id){Anime source=new Anime();source.source=sourceId;source.id=id;source.title=anime.title;source.original=anime.original;source.poster=anime.poster;source.description=anime.description;source.year=anime.year;source.type=anime.type;source.status=anime.status;source.episodes=anime.episodes;source.malId=anime.malId;source.anilistId=anime.anilistId;source.kpId=anime.kpId;return source;}
    private static ArrayList<ApiRepository.DownloadOption> merge(List<ApiRepository.DownloadOption> options){LinkedHashMap<String,ApiRepository.DownloadOption> map=new LinkedHashMap<>();if(options!=null)for(ApiRepository.DownloadOption option:options){if(option==null||option.source==null||option.episode==null)continue;String url=option.episode.streams.get(option.quality);String safe=ApiRepository.safeUrl(url);if(safe.isEmpty())continue;String key=option.source.source+"|"+option.quality+"|"+option.voice+"|"+option.player+"|"+safe;if(!map.containsKey(key))map.put(key,option);}return new ArrayList<>(map.values());}
    private static void confirm(Activity a,Anime anime,ApiRepository.DownloadOption option){Runnable run=()->{if(Build.VERSION.SDK_INT>=33&&a.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)a.requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},4101);YoruApp.app().downloads().enqueue(anime,option.source,option.episode,option.quality);};if(YoruApp.app().traffic.metered()&&!YoruApp.app().store.wifiDownloads())Ui.confirm(a,"Использовать мобильную сеть?","Размер серии может составлять сотни мегабайт. Можно включить загрузки только по Wi-Fi в профиле.","Скачать",run,"Отмена");else run.run();}
    private static String[] labels(ArrayList<Anime.Episode> episodes){String[] labels=new String[episodes.size()];for(int i=0;i<episodes.size();i++){Anime.Episode ep=episodes.get(i);labels[i]="Серия "+Ui.number(ep.number)+(ep.name.isEmpty()?"":" · "+ep.name);}return labels;}
    private static int closest(ArrayList<Anime.Episode> episodes,double suggested){int index=0;double best=Double.MAX_VALUE;for(int i=0;i<episodes.size();i++){double diff=Math.abs(episodes.get(i).number-suggested);if(diff<best){best=diff;index=i;}}return index;}
    private static boolean dead(Activity activity){return activity.isFinishing()||activity.isDestroyed();}
}
