package app.yoru.mobile;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.os.*;
import java.util.*;

public final class EpisodeUpdateReceiver extends BroadcastReceiver {
    private static final String ACTION="app.yoru.mobile.UPDATE_CHECK";
    private static final long INTERVAL=6L*60L*60L*1000L;
    public static void schedule(Context context){try{AlarmManager alarm=(AlarmManager)context.getSystemService(Context.ALARM_SERVICE);if(alarm==null)return;Intent intent=new Intent(context,EpisodeUpdateReceiver.class).setAction(ACTION);PendingIntent pending=PendingIntent.getBroadcast(context,2301,intent,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);alarm.setInexactRepeating(AlarmManager.ELAPSED_REALTIME_WAKEUP,SystemClock.elapsedRealtime()+INTERVAL,INTERVAL,pending);}catch(Exception ignored){}}
    public static void checkNow(Context context){try{schedule(context);context.getApplicationContext().sendBroadcast(new Intent(context,EpisodeUpdateReceiver.class).setAction(ACTION));}catch(Exception ignored){}}
    @Override public void onReceive(Context context,Intent intent){schedule(context);BroadcastReceiver.PendingResult pending=goAsync();Runnable work=()->{try{check(context.getApplicationContext());}finally{pending.finish();}};YoruApp app=YoruApp.app();if(app!=null&&app.io!=null)app.io.execute(work);else new Thread(work,"yoru-updates").start();}
    private static void check(Context context){YoruApp app=YoruApp.app();if(app==null||app.store==null||app.api==null)return;List<Anime> rows=app.store.favorites();int done=0;for(Anime base:rows){if(++done>40)break;try{Anime fresh=app.api.details(base,false);int episodes=Math.max(fresh.episodes,base.episodes);if(base.metadataOnly())try{Anime.Playback ready=app.api.playback(base,"auto");if(ready!=null&&ready.video!=null)episodes=Math.max(episodes,ready.video.episodes);}catch(Exception ignored){}if(episodes<=0){fresh=app.api.details(base,true);episodes=Math.max(fresh.episodes,base.episodes);}boolean changed=episodes>0&&app.store.updateFavoriteEpisodes(fresh,episodes);if(changed)notify(context,fresh,episodes);}catch(Exception ignored){}}}
    private static void notify(Context context,Anime anime,int episodes){if(Build.VERSION.SDK_INT>=33&&context.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)return;if(Build.VERSION.SDK_INT>=26){NotificationManager nm=(NotificationManager)context.getSystemService(Context.NOTIFICATION_SERVICE);if(nm!=null)nm.createNotificationChannel(new NotificationChannel("yoru-updates",context.getString(R.string.updates_channel_name),NotificationManager.IMPORTANCE_DEFAULT));}Intent open=new Intent(context,DetailsActivity.class).putExtra("anime",anime.json().toString()).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);int id=anime.key().hashCode()&0x7fffffff;PendingIntent pi=PendingIntent.getActivity(context,id,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder builder=Build.VERSION.SDK_INT>=26?new Notification.Builder(context,"yoru-updates"):new Notification.Builder(context);builder.setSmallIcon(R.drawable.ic_download).setContentTitle("Новая серия в коллекции").setContentText(anime.title+" · доступно "+episodes+" серий").setStyle(new Notification.BigTextStyle().bigText(anime.title+" · появилась новая серия. Откройте карточку и выберите удобную озвучку." )).setContentIntent(pi).setAutoCancel(true).setShowWhen(true).setWhen(System.currentTimeMillis());NotificationManager nm=(NotificationManager)context.getSystemService(Context.NOTIFICATION_SERVICE);if(nm!=null)nm.notify(2400+id%500000,builder.build());}
}
