package app.yoru.mobile;

import android.app.*;
import android.content.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

final class FeaturePanels {
    private FeaturePanels(){}

    static void center(Activity a,Runnable done){ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,500)));TextView intro=Ui.text(a,YoruBrain.commandCenter(),12,Ui.MUTED,false);intro.setLineSpacing(Ui.dp(a,4),1);col.addView(intro);Ui.space(col,12);centerRow(a,col,"YORU Nexus","Главная система автоподбора, единой карточки, обучения вариантов и непрерывного эфира.",()->YoruNexus.showPanel(a));centerRow(a,col,"Эфир YORU","Nexus собирает длинный маршрут просмотра и сам ведёт к следующей истории.",()->YoruNexus.showAir(a));centerRow(a,col,"Приоритеты просмотра","YORU сам поднимает важные тайтлы: план, продолжение, закрепления и онгоинги.",()->priorities(a));centerRow(a,col,"Умные подборки","Все полки, настроение и случайный выбор в одном аккуратном месте.",()->smart(a));centerRow(a,col,"Марафон","Автоматический вечерний маршрут из коротких, начатых и удобных тайтлов.",()->marathon(a));centerRow(a,col,"Карта вкуса","Понимание любимых жанров и текущего стиля просмотра.",()->taste(a));centerRow(a,col,"Диагностика коллекции","YORU ищет долгие паузы, дубли, пустой план и слабые места библиотеки.",()->doctor(a,done));centerRow(a,col,"Статистика и достижения","Итоги просмотра, серия дней, цель дня и личные отметки.",()->stats(a));Ui.custom(a,"Центр YORU",sc,"Готово",null,null,null,null);}
    private static void centerRow(Activity a,LinearLayout col,String title,String text,Runnable action){LinearLayout row=Ui.row(a);row.setPadding(Ui.dp(a,13),Ui.dp(a,12),Ui.dp(a,13),Ui.dp(a,12));row.setBackground(Ui.stroke(Ui.CARD,14,a));LinearLayout words=Ui.column(a);words.addView(Ui.text(a,title,14,Ui.TEXT,true));Ui.space(words,6);TextView sub=Ui.text(a,text,11,Ui.MUTED,false);sub.setLineSpacing(Ui.dp(a,3),1);words.addView(sub);row.addView(words,new LinearLayout.LayoutParams(0,-2,1));Ui.Icon icon=new Ui.Icon(a,"play");icon.color=Ui.PURPLE;row.addView(icon,Ui.lp(a,22,22));Ui.press(row);row.setOnClickListener(v->{if(action!=null)action.run();});col.addView(row,Ui.lp(a,-1,-2));Ui.space(col,8);}

    static void queue(Activity a){List<Anime> rows=YoruApp.app().store.watchQueue();ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,430)));if(rows.isEmpty()){col.addView(Ui.text(a,"План пуст. Добавьте тайтл из карточки кнопкой “В план”.",12,Ui.MUTED,false));}else{for(Anime anime:rows)animeLine(a,col,anime,YoruBrain.nextHint(anime),true);}Ui.custom(a,"План просмотра",sc,"Готово",null,rows.isEmpty()?null:"Очистить",()->{YoruApp.app().store.clearWatchQueue();Ui.toast(a,"План очищен");},null);}
    static void priorities(Activity a){ArrayList<Anime> rows=YoruBrain.priorities(18);ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,470)));if(rows.isEmpty())col.addView(Ui.text(a,"Добавьте тайтлы в коллекцию или историю — YORU построит приоритеты автоматически.",12,Ui.MUTED,false));else for(Anime anime:rows)animeLine(a,col,anime,YoruBrain.nextHint(anime),true);Ui.custom(a,"Приоритеты просмотра",sc,"Готово",null,"План",()->queue(a),null);}
    static void marathon(Activity a){ArrayList<Anime> rows=YoruBrain.marathon(16);ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,470)));col.addView(Ui.text(a,"Маршрут без лишнего выбора: короткое, начатое, закреплённое и удобное для вечера.",12,Ui.MUTED,false));Ui.space(col,12);if(rows.isEmpty())col.addView(Ui.text(a,"Откройте каталог и добавьте пару тайтлов — марафон появится автоматически.",12,Ui.MUTED,false));else for(Anime anime:rows)animeLine(a,col,anime,YoruBrain.nextHint(anime),true);Ui.custom(a,"Марафон",sc,"Готово",null,"Случайный",()->{Anime pick=YoruBrain.surprise();if(pick!=null)Ui.openDetails(a,pick);},null);}
    static void taste(Activity a){TextView body=Ui.text(a,YoruBrain.tasteMap(),13,Ui.MUTED,false);body.setLineSpacing(Ui.dp(a,5),1);Ui.custom(a,"Карта вкуса",body,"Готово",null,"Подборки",()->smart(a),null);}
    static void doctor(Activity a,Runnable done){ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,470)));for(String line:YoruBrain.libraryDoctor()){TextView row=Ui.text(a,line,13,line.startsWith("✓")?0xff8ee6a5:Ui.MUTED,true);row.setPadding(Ui.dp(a,12),Ui.dp(a,10),Ui.dp(a,12),Ui.dp(a,10));row.setBackground(Ui.stroke(Ui.CARD,13,a));col.addView(row,Ui.lp(a,-1,-2));Ui.space(col,8);}Ui.space(col,4);ArrayList<Anime> stale=YoruBrain.restartList(8);if(!stale.isEmpty()){col.addView(Ui.text(a,"Вернуться после паузы",16,Ui.TEXT,true));Ui.space(col,8);for(Anime anime:stale)animeLine(a,col,anime,YoruBrain.nextHint(anime),true);}Ui.custom(a,"Диагностика коллекции",sc,"Готово",null,"Чистка",()->cleanup(a,done),null);}

    static void smart(Activity a){ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,460)));smartBlock(a,col,"Для вас",YoruBrain.shelf("forYou",5));smartBlock(a,col,"Короткий марафон",YoruBrain.shelf("short",5));smartBlock(a,col,"Фильмы на вечер",YoruBrain.shelf("movies",5));smartBlock(a,col,"Сейчас выходит",YoruBrain.shelf("ongoing",5));smartBlock(a,col,"Классика",YoruBrain.shelf("classics",5));smartBlock(a,col,"Пересмотреть",YoruBrain.shelf("rewatch",5));Ui.custom(a,"Умные подборки",sc,"Готово",null,"Случайный выбор",()->{Anime pick=YoruBrain.surprise();if(pick!=null)Ui.openDetails(a,pick);else Ui.toast(a,"Откройте каталог, чтобы YORU собрал подборку");},null);}
    static void achievements(Activity a){ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,460)));col.addView(Ui.text(a,YoruBrain.dashboard(),12,Ui.MUTED,false));Ui.space(col,12);for(String line:YoruBrain.achievements()){TextView row=Ui.text(a,line,13,line.startsWith("✓")?0xff8ee6a5:Ui.MUTED,true);row.setPadding(Ui.dp(a,12),Ui.dp(a,10),Ui.dp(a,12),Ui.dp(a,10));row.setBackground(Ui.stroke(Ui.CARD,13,a));col.addView(row,Ui.lp(a,-1,-2));Ui.space(col,8);}Ui.custom(a,"Достижения",sc,"Готово",null,null,null,null);}
    static void cleanup(Activity a,Runnable done){LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);col.addView(Ui.text(a,"Быстрая чистка помогает держать приложение аккуратным, не удаляя скачанные серии.",12,Ui.MUTED,false));Ui.space(col,12);col.addView(Ui.button(a,"Скрывать просмотренное в подборках",false,()->{YoruApp.app().store.smartSetting("hideSeen",true);Ui.toast(a,"Просмотренное скрывается из подборок");if(done!=null)done.run();}));Ui.space(col,8);col.addView(Ui.button(a,"Очистить план просмотра",false,()->{YoruApp.app().store.clearWatchQueue();Ui.toast(a,"План очищен");if(done!=null)done.run();}));Ui.space(col,8);col.addView(Ui.button(a,"Очистить историю поиска",false,()->{YoruApp.app().store.clearSearchHistory();Ui.toast(a,"История поиска очищена");if(done!=null)done.run();}));Ui.space(col,8);col.addView(Ui.button(a,"Показать скрытые тайтлы",false,()->{YoruApp.app().store.clearHidden();Ui.toast(a,"Скрытые тайтлы снова видны");if(done!=null)done.run();}));Ui.space(col,8);col.addView(Ui.button(a,"Очистить историю просмотра",false,()->Ui.confirm(a,"Очистить историю просмотра?","Коллекция и загрузки останутся.","Очистить",()->{YoruApp.app().store.clearHistory();Ui.toast(a,"История очищена");if(done!=null)done.run();},"Отмена")));Ui.custom(a,"Чистка коллекции",col,"Готово",null,null,null,null);}
    private static void smartBlock(Activity a,LinearLayout col,String title,List<Anime> rows){if(rows==null||rows.isEmpty())return;col.addView(Ui.text(a,title,16,Ui.TEXT,true));Ui.space(col,8);for(Anime anime:rows)animeLine(a,col,anime,YoruBrain.chip(anime),false);Ui.space(col,12);}
    static void stats(Activity a){JSONObject s=YoruApp.app().store.stats();LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);metric(a,col,"Тайтлов в истории",String.valueOf(s.optInt("titles")));metric(a,col,"Серий отмечено",String.valueOf(s.optInt("episodes")));metric(a,col,"Завершено",String.valueOf(s.optInt("finished")));metric(a,col,"В коллекции",String.valueOf(s.optInt("favorites")));metric(a,col,"В плане просмотра",String.valueOf(s.optInt("queue")));metric(a,col,"Серия дней",String.valueOf(s.optInt("streak")));metric(a,col,"Сегодня",s.optInt("today")+" / "+s.optInt("goal"));metric(a,col,"Личные оценки",String.valueOf(s.optInt("ratings")));metric(a,col,"Пересмотры",String.valueOf(s.optInt("rewatches")));long minutes=Math.max(0,s.optLong("seconds")/60);metric(a,col,"Время просмотра",minutes>=60?minutes/60+" ч "+minutes%60+" мин":minutes+" мин");JSONArray genres=s.optJSONArray("genres");StringBuilder g=new StringBuilder();for(int i=0;genres!=null&&i<genres.length();i++){if(g.length()>0)g.append(", ");g.append(genres.optString(i));}Ui.space(col,8);col.addView(Ui.text(a,g.length()>0?"Любимые жанры: "+g:"Любимые жанры появятся после просмотра и добавления в коллекцию.",12,Ui.MUTED,false));Ui.space(col,12);col.addView(Ui.button(a,"Итог года",false,()->year(a)));Ui.custom(a,"Статистика просмотра",col,"Готово",null,"Достижения",()->achievements(a),null);}
    static void year(Activity a){JSONObject s=YoruApp.app().store.stats();int episodes=s.optInt("episodes"),titles=s.optInt("titles"),fav=s.optInt("favorites");long hours=Math.max(0,s.optLong("seconds")/3600);String level=episodes>=300?"легендарный марафон":episodes>=120?"сильный сезон":episodes>=40?"уютный темп":"лёгкий старт";String text="Ваш год в YORU: "+level+".\n\nТайтлов: "+titles+"\nСерий: "+episodes+"\nЧасов просмотра: "+hours+"\nВ коллекции: "+fav+"\n\nПродолжайте собирать свою историю — YORU сохранит прогресс, серию и комфортные настройки.";TextView body=Ui.text(a,text,13,Ui.MUTED,false);body.setLineSpacing(Ui.dp(a,4),1);Ui.custom(a,"Итог года",body,"Красиво",null,"Поделиться",()->{Intent send=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,text);a.startActivity(Intent.createChooser(send,"Поделиться итогом"));},null);}
    private static void animeLine(Activity a,LinearLayout col,Anime anime,String subtitle,boolean play){LinearLayout row=Ui.row(a);row.setPadding(Ui.dp(a,12),Ui.dp(a,10),Ui.dp(a,12),Ui.dp(a,10));row.setBackground(Ui.stroke(Ui.CARD,13,a));LinearLayout words=Ui.column(a);words.addView(Ui.text(a,YoruBrain.title(anime),13,Ui.TEXT,true));if(subtitle!=null&&!subtitle.isEmpty()){Ui.space(words,5);words.addView(Ui.text(a,subtitle,10,Ui.MUTED,false));}row.addView(words,new LinearLayout.LayoutParams(0,-2,1));Ui.Icon icon=new Ui.Icon(a,play?"play":"heart");icon.color=Ui.PURPLE;row.addView(icon,Ui.lp(a,22,22));row.setOnClickListener(v->Ui.openDetails(a,anime));Ui.press(row);col.addView(row,Ui.lp(a,-1,-2));Ui.space(col,7);}
    private static void metric(Activity a,LinearLayout host,String label,String value){LinearLayout row=Ui.row(a);row.setPadding(Ui.dp(a,13),Ui.dp(a,11),Ui.dp(a,13),Ui.dp(a,11));row.setBackground(Ui.stroke(Ui.CARD,13,a));row.addView(Ui.text(a,label,12,Ui.MUTED,false),new LinearLayout.LayoutParams(0,-2,1));row.addView(Ui.text(a,value,15,Ui.PURPLE,true));host.addView(row,Ui.lp(a,-1,-2));Ui.space(host,8);}
}
