package app.yoru.mobile;

import android.app.*;
import android.content.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

final class FeaturePanels {
    private FeaturePanels(){}
    static void queue(Activity a){List<Anime> rows=YoruApp.app().store.watchQueue();ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,430)));if(rows.isEmpty()){col.addView(Ui.text(a,"План пуст. Добавьте тайтл из карточки кнопкой “В план”.",12,Ui.MUTED,false));}else{for(Anime anime:rows){LinearLayout row=Ui.row(a);row.setPadding(Ui.dp(a,12),Ui.dp(a,10),Ui.dp(a,12),Ui.dp(a,10));row.setBackground(Ui.stroke(Ui.CARD,13,a));row.addView(Ui.text(a,anime.title,13,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));TextView open=Ui.text(a,"Открыть",11,Ui.PURPLE,true);open.setPadding(Ui.dp(a,8),Ui.dp(a,6),0,Ui.dp(a,6));open.setOnClickListener(v->Ui.openDetails(a,anime));row.addView(open);col.addView(row,Ui.lp(a,-1,-2));Ui.space(col,8);}}Ui.custom(a,"План просмотра",sc,"Готово",null,rows.isEmpty()?null:"Очистить",()->{YoruApp.app().store.clearWatchQueue();Ui.toast(a,"План очищен");},null);}
    static void stats(Activity a){JSONObject s=YoruApp.app().store.stats();LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);metric(a,col,"Тайтлов в истории",String.valueOf(s.optInt("titles")));metric(a,col,"Серий отмечено",String.valueOf(s.optInt("episodes")));metric(a,col,"Завершено",String.valueOf(s.optInt("finished")));metric(a,col,"В коллекции",String.valueOf(s.optInt("favorites")));metric(a,col,"В плане просмотра",String.valueOf(s.optInt("queue")));long minutes=Math.max(0,s.optLong("seconds")/60);metric(a,col,"Время просмотра",minutes>=60?minutes/60+" ч "+minutes%60+" мин":minutes+" мин");JSONArray genres=s.optJSONArray("genres");StringBuilder g=new StringBuilder();for(int i=0;genres!=null&&i<genres.length();i++){if(g.length()>0)g.append(", ");g.append(genres.optString(i));}Ui.space(col,8);col.addView(Ui.text(a,g.length()>0?"Любимые жанры: "+g:"Любимые жанры появятся после просмотра и добавления в коллекцию.",12,Ui.MUTED,false));Ui.space(col,12);col.addView(Ui.button(a,"Итог года",false,()->year(a)));Ui.custom(a,"Статистика просмотра",col,"Готово",null,null,null,null);}
    static void year(Activity a){JSONObject s=YoruApp.app().store.stats();int episodes=s.optInt("episodes"),titles=s.optInt("titles"),fav=s.optInt("favorites");long hours=Math.max(0,s.optLong("seconds")/3600);String level=episodes>=300?"легендарный марафон":episodes>=120?"сильный сезон":episodes>=40?"уютный темп":"лёгкий старт";String text="Ваш год в YORU: "+level+".\n\nТайтлов: "+titles+"\nСерий: "+episodes+"\nЧасов просмотра: "+hours+"\nВ коллекции: "+fav+"\n\nПродолжайте собирать свою историю — YORU сохранит прогресс, серию и источник.";TextView body=Ui.text(a,text,13,Ui.MUTED,false);body.setLineSpacing(Ui.dp(a,4),1);Ui.custom(a,"Итог года",body,"Красиво",null,"Поделиться",()->{Intent send=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,text);a.startActivity(Intent.createChooser(send,"Поделиться итогом"));},null);}
    static void health(Activity a){LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);TextView state=Ui.text(a,"Проверяем источники…",12,Ui.MUTED,false);col.addView(state);Ui.space(col,12);LinearLayout rows=Ui.column(a);col.addView(rows);YoruApp.app().io.execute(()->{ArrayList<String[]> result=new ArrayList<>();for(String id:new String[]{"yoru","yummy","anilibria","animevost","animelib","animedia","animetka","anidub","kodik"}){String name=ApiRepository.downloadSourceName(id),status="Доступен";try{if("yoru".equals(id))YoruApp.app().api.catalog("yoru","",1,new ApiRepository.Filter());else YoruApp.app().api.catalog(id,"",1,new ApiRepository.Filter());}catch(Exception e){status="Временно нестабилен";}result.add(new String[]{name,status});}YoruApp.app().main.post(()->{rows.removeAllViews();state.setText("Проверка завершена. Если источник нестабилен, YORU Source попробует подобрать запасной вариант.");for(String[] r:result)sourceRow(a,rows,r[0],r[1]);});});Ui.custom(a,"Состояние источников",col,"Готово",null,null,null,null);}
    private static void metric(Activity a,LinearLayout host,String label,String value){LinearLayout row=Ui.row(a);row.setPadding(Ui.dp(a,13),Ui.dp(a,11),Ui.dp(a,13),Ui.dp(a,11));row.setBackground(Ui.stroke(Ui.CARD,13,a));row.addView(Ui.text(a,label,12,Ui.MUTED,false),new LinearLayout.LayoutParams(0,-2,1));row.addView(Ui.text(a,value,15,Ui.PURPLE,true));host.addView(row,Ui.lp(a,-1,-2));Ui.space(host,8);}
    private static void sourceRow(Activity a,LinearLayout host,String name,String status){LinearLayout row=Ui.row(a);row.setPadding(Ui.dp(a,13),Ui.dp(a,11),Ui.dp(a,13),Ui.dp(a,11));row.setBackground(Ui.stroke(Ui.CARD,13,a));row.addView(Ui.text(a,name,13,Ui.TEXT,true),new LinearLayout.LayoutParams(0,-2,1));row.addView(Ui.text(a,status,11,status.startsWith("Доступ")?0xff8ee6a5:0xffffc67a,true));host.addView(row,Ui.lp(a,-1,-2));Ui.space(host,8);}
}
