package app.yoru.mobile;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.media.MediaScannerConnection;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import androidx.core.content.FileProvider;
import androidx.media3.common.*;
import androidx.media3.common.util.*;
import androidx.media3.datasource.*;
import androidx.media3.exoplayer.offline.Download;
import androidx.media3.exoplayer.source.DefaultMediaSourceFactory;
import androidx.media3.transformer.*;
import org.json.*;
import java.io.*;
import java.util.*;

@UnstableApi
final class OfflineExporter {
    private OfflineExporter(){}
    static boolean canExport(Download d){return d!=null&&d.state==Download.STATE_COMPLETED&&(singleFile(d)||converted(d).exists());}
    static boolean canConvert(Download d){return d!=null&&d.state==Download.STATE_COMPLETED&&!singleFile(d);}
    static String format(Download d){if(d==null)return "—";String ext=extension(d);if(ext.equals("mp4"))return "MP4";if(ext.equals("mkv"))return "MKV";if(ext.equals("webm"))return "WEBM";if(ext.equals("m4v"))return "M4V";if(converted(d).exists())return "MP4 экспорт";return "HLS/DASH → MP4";}
    static void openExternal(Activity a,Download d){export(a,d,"Готовим видео для внешнего плеера…",file->{try{Intent intent=new Intent(Intent.ACTION_VIEW);intent.setDataAndType(uri(a,file),mime(file.getName()));intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);a.startActivity(Intent.createChooser(intent,"Открыть в плеере"));}catch(Exception e){Ui.toast(a,"Не найден внешний плеер для этого видео");}});}
    static void share(Activity a,Download d){export(a,d,"Готовим видео для отправки…",file->{try{Intent intent=new Intent(Intent.ACTION_SEND);intent.setType(mime(file.getName()));intent.putExtra(Intent.EXTRA_STREAM,uri(a,file));intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);a.startActivity(Intent.createChooser(intent,"Поделиться серией"));}catch(Exception e){Ui.toast(a,"Не удалось открыть меню отправки");}});}
    static void saveToMovies(Activity a,Download d){if(Build.VERSION.SDK_INT<29&&a.checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED){a.requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},4302);Ui.toast(a,"Разрешите сохранение и нажмите ещё раз");return;}export(a,d,"Готовим MP4 для Видео / YORU…",file->saveFileToMovies(a,file));}
    static void makeMp4(Activity a,Download d){export(a,d,"Собираем HLS/DASH в MP4…",file->Ui.toast(a,"MP4 готов: "+file.getName()));}
    static String details(Download d){JSONObject m=DownloadHub.metadata(d);Anime a=Anime.from(m.optJSONObject("anime")),s=Anime.from(m.optJSONObject("source"));StringBuilder b=new StringBuilder();b.append(a.title).append('\n');b.append("Серия: ").append(Ui.number(m.optDouble("episode",1))).append('\n');b.append("Источник: ").append(ApiRepository.downloadSourceName(s.source)).append('\n');String voice=m.optString("voice","");if(!voice.isEmpty())b.append("Озвучка: ").append(voice).append('\n');int q=m.optInt("quality",0);b.append("Качество: ").append(q>0?q+"p":"Оригинал").append('\n');b.append("Формат: ").append(format(d)).append('\n');b.append("Размер: ").append(Ui.bytes(d.getBytesDownloaded()));if(d.contentLength>0)b.append(" / ").append(Ui.bytes(d.contentLength));b.append('\n').append(singleFile(d)?"Можно открыть во внешнем плеере и сохранить в Видео.":"При открытии во внешнем плеере или сохранении YORU автоматически соберёт MP4.");return b.toString();}
    private interface FileAction {void ready(File file);}
    private static void export(Activity a,Download d,String message,FileAction action){if(d==null||d.state!=Download.STATE_COMPLETED){Ui.toast(a,"Серия ещё не скачана полностью");return;}if(singleFile(d)){copyToCache(a,d,message,action);return;}File ready=converted(d);if(ready.exists()&&ready.length()>0){action.ready(ready);return;}transform(a,d,message,action);}
    private static void copyToCache(Activity a,Download d,String message,FileAction action){ProgressDialog wait=new ProgressDialog(a);wait.setMessage(message);wait.setCancelable(false);wait.show();YoruApp.app().io.execute(()->{try{File file=cacheFile(a,d);YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();action.ready(file);});}catch(Exception e){YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Не удалось подготовить видеофайл");});}});}
    private static void transform(Activity a,Download d,String message,FileAction action){File out=converted(d);File dir=out.getParentFile();if(dir!=null&&!dir.exists())dir.mkdirs();if(out.exists())out.delete();ProgressDialog wait=new ProgressDialog(a);wait.setTitle("MP4 экспорт");wait.setMessage(message);wait.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL);wait.setIndeterminate(true);wait.setCancelable(true);wait.show();Handler h=new Handler(Looper.getMainLooper());ProgressHolder holder=new ProgressHolder();DefaultMediaSourceFactory media=new DefaultMediaSourceFactory(YoruApp.app().mediaCache.offlineFactory());Transformer[] ref=new Transformer[1];Runnable progress=new Runnable(){public void run(){try{Transformer t=ref[0];if(t==null||dead(a)||!wait.isShowing())return;int state=t.getProgress(holder);if(state==Transformer.PROGRESS_STATE_AVAILABLE){wait.setIndeterminate(false);wait.setProgress(Math.max(0,Math.min(100,holder.progress)));}if(state!=Transformer.PROGRESS_STATE_NOT_STARTED)h.postDelayed(this,500);}catch(Exception ignored){}}};Transformer.Listener listener=new Transformer.Listener(){@Override public void onCompleted(Composition composition,ExportResult result){h.removeCallbacksAndMessages(null);YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"MP4 готов");action.ready(out);});}@Override public void onError(Composition composition,ExportResult result,ExportException exception){h.removeCallbacksAndMessages(null);if(out.exists())out.delete();YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Не удалось собрать MP4 для этого потока");});}};try{Transformer transformer=new Transformer.Builder(a).setAssetLoaderFactory(new ExoPlayerAssetLoader.Factory(a,new DefaultDecoderFactory.Builder(a).setEnableDecoderFallback(true).build(),Clock.DEFAULT,media)).setVideoMimeType(MimeTypes.VIDEO_H264).setAudioMimeType(MimeTypes.AUDIO_AAC).addListener(listener).build();ref[0]=transformer;wait.setOnCancelListener(x->{try{transformer.cancel();}catch(Exception ignored){}if(out.exists())out.delete();});transformer.start(new EditedMediaItem.Builder(YoruApp.app().downloads().offlineItem(d)).build(),out.getAbsolutePath());h.postDelayed(progress,500);}catch(Exception e){wait.dismiss();if(out.exists())out.delete();Ui.toast(a,"MP4 экспорт недоступен на этом устройстве");}}
    private static File cacheFile(Context c,Download d)throws Exception{File dir=new File(c.getCacheDir(),"shared-video");if(!dir.exists()&&!dir.mkdirs())throw new IOException();File file=new File(dir,fileName(d));if(file.exists()&&file.length()>0&&(d.contentLength<=0||Math.abs(file.length()-d.contentLength)<1024))return file;try(OutputStream out=new BufferedOutputStream(new FileOutputStream(file))){copy(d,out);}return file;}
    private static void copy(Download d,OutputStream out)throws Exception{DataSpec.Builder builder=new DataSpec.Builder().setUri(d.request.uri);if(d.request.customCacheKey!=null)builder.setKey(d.request.customCacheKey);DataSource source=YoruApp.app().mediaCache.offlineFactory().createDataSource();byte[] buffer=new byte[256*1024];try{source.open(builder.build());int n;while((n=source.read(buffer,0,buffer.length))!=-1)out.write(buffer,0,n);}finally{source.close();}}
    private static void saveFileToMovies(Activity a,File file){ProgressDialog wait=new ProgressDialog(a);wait.setMessage("Сохраняем в Видео / YORU…");wait.setCancelable(false);wait.show();YoruApp.app().io.execute(()->{try{String name=file.getName();if(Build.VERSION.SDK_INT>=29){ContentValues values=new ContentValues();values.put(MediaStore.Video.Media.DISPLAY_NAME,name);values.put(MediaStore.Video.Media.MIME_TYPE,mime(name));values.put(MediaStore.Video.Media.RELATIVE_PATH,Environment.DIRECTORY_MOVIES+"/YORU");values.put(MediaStore.Video.Media.IS_PENDING,1);Uri item=a.getContentResolver().insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,values);if(item==null)throw new IOException();try(OutputStream out=a.getContentResolver().openOutputStream(item);InputStream in=new BufferedInputStream(new FileInputStream(file))){if(out==null)throw new IOException();copyBytes(in,out);}values.clear();values.put(MediaStore.Video.Media.IS_PENDING,0);a.getContentResolver().update(item,values,null,null);YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Сохранено в Видео / YORU");openSaved(a,item,name);});}else{File dir=new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_MOVIES),"YORU");if(!dir.exists()&&!dir.mkdirs())throw new IOException();File target=unique(new File(dir,name));try(OutputStream out=new BufferedOutputStream(new FileOutputStream(target));InputStream in=new BufferedInputStream(new FileInputStream(file))){copyBytes(in,out);}MediaScannerConnection.scanFile(a,new String[]{target.getAbsolutePath()},new String[]{mime(target.getName())},null);YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Сохранено в Видео / YORU");});}}catch(Exception e){YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Не удалось сохранить видео");});}});}
    private static void copyBytes(InputStream in,OutputStream out)throws IOException{byte[] b=new byte[256*1024];int n;while((n=in.read(b))!=-1)out.write(b,0,n);}
    private static Uri uri(Context c,File file){return FileProvider.getUriForFile(c,c.getPackageName()+".files",file);}
    private static void openSaved(Activity a,Uri item,String name){try{Intent intent=new Intent(Intent.ACTION_VIEW);intent.setDataAndType(item,mime(name));intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);a.startActivity(Intent.createChooser(intent,"Открыть сохранённое видео"));}catch(Exception ignored){}}
    private static boolean singleFile(Download d){String e=extension(d);return e.equals("mp4")||e.equals("mkv")||e.equals("webm")||e.equals("m4v");}
    private static String extension(Download d){try{String p=d.request.uri.getPath();if(p==null)return "";int q=p.lastIndexOf('.');if(q<0)return "";String e=p.substring(q+1).toLowerCase(Locale.ROOT);int cut=e.indexOf('?');return cut>=0?e.substring(0,cut):e;}catch(Exception e){return "";}}
    private static String mime(String name){String n=name.toLowerCase(Locale.ROOT);if(n.endsWith(".mp4")||n.endsWith(".m4v"))return "video/mp4";if(n.endsWith(".webm"))return "video/webm";if(n.endsWith(".mkv"))return "video/x-matroska";return "video/mp4";}
    private static File converted(Download d){return new File(YoruApp.app().getCacheDir(),"mp4-export/"+d.request.id+".mp4");}
    private static String fileName(Download d){JSONObject m=DownloadHub.metadata(d);Anime a=Anime.from(m.optJSONObject("anime"));String voice=m.optString("voice","");int q=m.optInt("quality",0);String e=singleFile(d)?extension(d):"mp4";if(e.isEmpty())e="mp4";String name=safe(a.title)+" — серия "+Ui.number(m.optDouble("episode",1));if(!voice.isEmpty())name+=" — "+safe(voice);if(q>0)name+=" — "+q+"p";name+=" — "+d.request.id.substring(0,Math.min(8,d.request.id.length()))+"."+e;return name;}
    private static String safe(String s){s=s==null?"":s.replaceAll("[\\\\/:*?\"<>|]+"," ").replaceAll("\\s+"," ").trim();if(s.length()>90)s=s.substring(0,90).trim();return s.isEmpty()?"YORU":s;}
    private static File unique(File file){if(!file.exists())return file;String name=file.getName();int dot=name.lastIndexOf('.');String base=dot<0?name:name.substring(0,dot),ext=dot<0?"":name.substring(dot);for(int i=2;i<1000;i++){File next=new File(file.getParentFile(),base+" ("+i+")"+ext);if(!next.exists())return next;}return file;}
    private static boolean dead(Activity a){return a.isFinishing()||a.isDestroyed();}
}
