package app.yoru.mobile;

import android.Manifest;
import android.app.*;
import android.content.Context;
import android.content.pm.PackageManager;
import android.os.*;
import android.view.*;
import android.webkit.WebView;
import android.widget.*;
import org.json.*;
import java.text.SimpleDateFormat;
import java.util.*;

public final class ProfileScreen extends ScrollView {
    public interface Actions {void run(String action);}
    private final Activity activity;private final LinearLayout body;private TextView mobile,wifi,other,since,cacheSize,offlineSize,free;private long cacheBytes;private final Handler timer=new Handler(Looper.getMainLooper());private boolean attached,refreshing;
    private final Runnable tick=new Runnable(){public void run(){refresh();timer.postDelayed(this,5000);}};
    public ProfileScreen(Activity a,Actions actions){super(a);activity=a;setFillViewport(true);body=Ui.column(a);body.setPadding(Ui.dp(a,18),Ui.dp(a,14),Ui.dp(a,18),Ui.dp(a,30));addView(body);body.addView(Ui.label(a,"ВАШЕ ЛИЧНОЕ ПРОСТРАНСТВО"));Ui.space(body,11);body.addView(Ui.text(a,"Мой профиль",28,Ui.TEXT,true));Ui.space(body,10);body.addView(Ui.text(a,"Все ваши истории, настройки и загрузки.",12,Ui.MUTED,false));Ui.space(body,24);body.addView(Ui.text(a,"Интернет приложения",20,Ui.TEXT,true));Ui.space(body,12);LinearLayout stats=Ui.row(a);mobile=stat(stats,"Мобильная сеть");wifi=stat(stats,"Wi-Fi / Ethernet");body.addView(stats);Ui.space(body,8);other=Ui.text(a,"",11,Ui.MUTED,false);body.addView(other);Ui.space(body,6);since=Ui.text(a,"",10,Ui.MUTED,false);body.addView(since);Ui.space(body,9);TextView note=Ui.text(a,"≈ Оценка расхода только YORU с момента включения или сброса счётчика. При смене сети и остановке приложения часть трафика может попасть в «другой». Показания оператора могут отличаться.",10,Ui.MUTED,false);body.addView(note);Ui.space(body,10);body.addView(Ui.button(a,"Сбросить счётчики",false,()->Ui.confirm(a,"Сбросить счётчики?","Начать отсчёт трафика заново? Коллекция и загрузки не изменятся.","Сбросить",()->{YoruApp.app().traffic.reset();refresh();},"Отмена")));
        Ui.space(body,25);body.addView(Ui.text(a,"Экономия и загрузки",20,Ui.TEXT,true));Ui.space(body,12);Switch saver=switchRow("Экономия трафика",YoruApp.app().store.dataSaver());body.addView(saver);saver.setOnCheckedChangeListener((b,on)->{YoruApp.app().store.dataSaver(on);YoruApp.app().traffic.preferencesChanged();Ui.toast(a,on?"Экономия включена":"Экономия выключена");});body.addView(Ui.text(a,"На мобильной сети: обложки из кэша, без автоматического перехода к следующей серии и подтверждение открытия внешнего просмотра. Качество онлайн-видео выбирается автоматически. Для скачивания предлагается экономичный вариант.",10,Ui.MUTED,false));Ui.space(body,13);Switch direct=switchRow("Только встроенный просмотр",YoruApp.app().store.directOnly());body.addView(direct);direct.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.directOnly(on);Ui.toast(a,on?"Внешний просмотр будет скрыт, если подходящий вариант не найден":"Внешний просмотр снова разрешён");});body.addView(Ui.text(a,"Если включено, YORU попросит выбрать другой вариант, когда встроенный просмотр недоступен.",10,Ui.MUTED,false));Ui.space(body,13);Switch lite=switchRow("Мини-режим интерфейса",YoruApp.app().store.liteMode());body.addView(lite);lite.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.liteMode(on);Ui.toast(a,on?"Мини-режим включён":"Мини-режим выключен");});body.addView(Ui.text(a,"Меньше анимаций и мягче нагрузка на слабых устройствах.",10,Ui.MUTED,false));Ui.space(body,13);Switch only=switchRow("Только Wi-Fi / безлимитная сеть",YoruApp.app().store.wifiDownloads());body.addView(only);only.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.wifiDownloads(on);YoruApp.app().downloads().applyRequirements();Ui.toast(a,on?"Загрузки будут ожидать безлимитную сеть":"Мобильная сеть разрешена для загрузок");});body.addView(Ui.text(a,"Настройка применяется к скачиванию серий. На платной сети приложение попросит подтвердить загрузку.",10,Ui.MUTED,false));
        Ui.space(body,25);body.addView(Ui.text(a,"Новые серии",20,Ui.TEXT,true));Ui.space(body,12);body.addView(Ui.button(a,"Проверить избранное сейчас",false,()->{if(Build.VERSION.SDK_INT>=33&&a.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)a.requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},4201);EpisodeUpdateReceiver.checkNow(a);Ui.toast(a,"Проверяем новые серии…");}));Ui.space(body,8);body.addView(Ui.text(a,"YORU проверяет аниме из коллекции примерно раз в 6 часов и показывает уведомление, если каталог сообщил больше серий, чем было сохранено раньше.",10,Ui.MUTED,false));Ui.space(body,10);Switch quiet=switchRow("Тихие часы 23:00–08:00",YoruApp.app().store.quietEnabled());body.addView(quiet);quiet.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.quietHours(on,23,8);Ui.toast(a,on?"Ночные уведомления приглушены":"Тихие часы выключены");});

        Ui.space(body,25);body.addView(Ui.text(a,"Приватность и комфорт",20,Ui.TEXT,true));Ui.space(body,12);Switch priv=switchRow("Приватный режим",YoruApp.app().store.privateMode());body.addView(priv);priv.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.smartSetting("privateMode",on);Ui.toast(a,on?"Новая история не будет сохраняться":"История снова сохраняется");});body.addView(Ui.text(a,"Новые просмотры не попадают в историю, когда режим включён.",10,Ui.MUTED,false));Ui.space(body,10);Switch spoiler=switchRow("Без спойлеров",YoruApp.app().store.spoilerSafe());body.addView(spoiler);spoiler.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.smartSetting("spoilerSafe",on);Ui.toast(a,on?"Описания скрываются до нажатия":"Описания снова видны");});Ui.space(body,10);Switch safe=switchRow("Мягкий безопасный режим",YoruApp.app().store.safeMode());body.addView(safe);safe.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.smartSetting("safeMode",on);Ui.toast(a,on?"Чувствительные карточки скрыты":"Фильтр выключен");});Ui.space(body,10);Switch seen=switchRow("Скрывать просмотренное",YoruApp.app().store.hideSeen());body.addView(seen);seen.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.smartSetting("hideSeen",on);Ui.toast(a,on?"Просмотренное скрывается из подборок":"Просмотренное снова видно");});Ui.space(body,10);Switch original=switchRow("Показывать оригинальные названия",YoruApp.app().store.originalTitles());body.addView(original);original.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.smartSetting("originalTitles",on);Ui.toast(a,"Названия обновятся на экранах");});Ui.space(body,10);Switch skip=switchRow("Автопропуск заставки",YoruApp.app().store.autoSkipOpening());body.addView(skip);skip.setOnCheckedChangeListener((button,on)->{YoruApp.app().store.smartSetting("autoSkipOpening",on);Ui.toast(a,on?"YORU будет пропускать заставку, когда знает её границы":"Автопропуск выключен");});
        Ui.space(body,25);body.addView(Ui.text(a,"Память устройства",20,Ui.TEXT,true));Ui.space(body,12);LinearLayout card=Ui.column(a);card.setPadding(Ui.dp(a,16),Ui.dp(a,16),Ui.dp(a,16),Ui.dp(a,16));card.setBackground(Ui.stroke(Ui.CARD,13,a));cacheSize=Ui.text(a,"Кэш: …",17,Ui.TEXT,true);card.addView(cacheSize);Ui.space(card,8);offlineSize=Ui.text(a,"Загрузки: …",12,Ui.PURPLE,false);card.addView(offlineSize);Ui.space(card,7);free=Ui.text(a,"",11,Ui.MUTED,false);card.addView(free);Ui.space(card,14);card.addView(Ui.button(a,"Очистить только кэш",false,this::clearCache));Ui.space(card,9);card.addView(Ui.text(a,"Скачанные серии, коллекция и история останутся. Загрузки удаляются отдельно в своём разделе.",10,Ui.MUTED,false));body.addView(card);
        Ui.space(body,25);body.addView(Ui.text(a,"Ваше приложение",20,Ui.TEXT,true));Ui.space(body,12);for(String[] row:new String[][]{{"center","Центр YORU"},{"playback","Просмотр"},{"appearance","Внешний вид"},{"sources","Каталоги YORU"},{"data","Данные и чистка"},{"about","О проекте"}}){body.addView(Ui.button(a,row[1],false,()->actions.run(row[0])));Ui.space(body,9);}body.addView(Ui.text(a,"YORU "+BuildConfig.VERSION_NAME,10,Ui.MUTED,false));}
    private TextView stat(LinearLayout row,String label){LinearLayout c=Ui.column(activity);c.setPadding(Ui.dp(activity,14),Ui.dp(activity,15),Ui.dp(activity,14),Ui.dp(activity,15));c.setBackground(Ui.stroke(Ui.CARD,12,activity));c.addView(Ui.text(activity,label,10,Ui.MUTED,false));Ui.space(c,10);TextView value=Ui.text(activity,"—",20,Ui.PURPLE,true);c.addView(value);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);if(row.getChildCount()>0)p.leftMargin=Ui.dp(activity,9);row.addView(c,p);return value;}
    private Switch switchRow(String label,boolean checked){Switch s=new Switch(activity);s.setText(label);s.setTextColor(Ui.TEXT);s.setTextSize(13);s.setPadding(0,Ui.dp(activity,5),0,Ui.dp(activity,9));s.setChecked(checked);return s;}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();attached=true;timer.post(tick);}
    @Override protected void onDetachedFromWindow(){attached=false;timer.removeCallbacksAndMessages(null);super.onDetachedFromWindow();}
    private void refresh(){JSONObject t=YoruApp.app().traffic.snapshot();boolean supported=t.optBoolean("supported",true);mobile.setText(supported?"≈ "+Ui.bytes(t.optLong("mobile")):"Нет данных");wifi.setText(supported?"≈ "+Ui.bytes(t.optLong("wifi")):"Нет данных");other.setText("Другой / не определён: "+Ui.bytes(t.optLong("other")));since.setText("С "+new SimpleDateFormat("dd.MM.yyyy HH:mm",new Locale("ru")).format(new Date(t.optLong("since",System.currentTimeMillis()))));if(refreshing)return;refreshing=true;YoruApp.app().io.execute(()->{long tmp=YoruApp.app().mediaCache.temporaryBytes(),download=YoruApp.app().mediaCache.offlineBytes(),remaining=activity.getFilesDir().getUsableSpace();YoruApp.app().main.post(()->{refreshing=false;if(!attached||activity.isFinishing())return;cacheBytes=tmp;cacheSize.setText("Кэш: "+Ui.bytes(tmp));offlineSize.setText("Скачанные серии: "+Ui.bytes(download));free.setText("Свободно: "+Ui.bytes(remaining));});});}
    private void clearCache(){if(YoruApp.app().activePlayers>0){Ui.toast(activity,"Сначала закройте экран просмотра и окно «картинка в картинке»");return;}Ui.confirm(activity,"Очистить "+Ui.bytes(cacheBytes)+" кэша?","Скачанные серии, коллекция и история не будут удалены.","Очистить",()->{try{WebView view=new WebView(activity);view.clearCache(true);view.destroy();}catch(Exception ignored){}YoruApp.app().io.execute(()->{YoruApp.app().mediaCache.clearTemporary();YoruApp.app().images.clear();YoruApp.app().api.clearMemory();YoruApp.app().main.post(()->{if(attached){Ui.toast(activity,"Кэш очищен. Загрузки сохранены.");refresh();}});});},"Отмена");}
}
