package app.yoru.mobile;

import android.content.*;
import android.security.keystore.*;
import android.util.Base64;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import javax.crypto.*;
import javax.crypto.spec.GCMParameterSpec;
import java.util.*;

public final class SecureStore {
    private final SharedPreferences prefs;private final javax.crypto.SecretKey key;
    private JSONObject favorites,history,settings;
    public static final String[] BUCKETS={"planned","watching","completed","onhold","dropped"};
    public static final String[] BUCKET_LABELS={"В планах","Смотрю","Просмотрено","Отложено","Брошено"};
    public SecureStore(Context c){prefs=c.getSharedPreferences("private-library",Context.MODE_PRIVATE);key=getKey();favorites=read("favorites");history=read("history");settings=read("settings");}
    private javax.crypto.SecretKey getKey(){try{KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);String alias="yoru-local-v1";if(!ks.containsAlias(alias)){KeyGenerator gen=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");gen.init(new KeyGenParameterSpec.Builder(alias,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).setRandomizedEncryptionRequired(true).build());gen.generateKey();}return (javax.crypto.SecretKey)ks.getKey(alias,null);}catch(Exception e){return null;}}
    private JSONObject read(String name){String value=prefs.getString(name,"");if(value.isEmpty()||key==null)return new JSONObject();try{byte[] all=Base64.decode(value,Base64.NO_WRAP);int len=all[0]&255;if(len<12||len>16||all.length<=len+1)return new JSONObject();byte[] iv=Arrays.copyOfRange(all,1,1+len);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,key,new GCMParameterSpec(128,iv));return new JSONObject(new String(c.doFinal(all,1+len,all.length-len-1),StandardCharsets.UTF_8));}catch(Exception e){return new JSONObject();}}
    private void write(String name,JSONObject json){if(key==null)return;try{Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key);byte[] iv=c.getIV(),cipher=c.doFinal(json.toString().getBytes(StandardCharsets.UTF_8));byte[] all=new byte[1+iv.length+cipher.length];all[0]=(byte)iv.length;System.arraycopy(iv,0,all,1,iv.length);System.arraycopy(cipher,0,all,1+iv.length,cipher.length);prefs.edit().putString(name,Base64.encodeToString(all,Base64.NO_WRAP)).apply();}catch(Exception ignored){}}
    public boolean persistent(){return key!=null;}
    public synchronized boolean favorite(Anime a){return favorites.has(a.key());}
    public synchronized String bucket(Anime a){JSONObject j=favorites.optJSONObject(a.key());return j==null?"":j.optString("bucket","planned");}
    public synchronized void favorite(Anime a,String bucket){if(!Anime.valid(a))return;try{if(bucket==null||bucket.isEmpty())favorites.remove(a.key());else{JSONObject old=favorites.optJSONObject(a.key());int seen=old==null?Math.max(0,a.episodes):old.optInt("episodesSeen",Math.max(0,a.episodes));favorites.put(a.key(),new JSONObject().put("release",a.json()).put("bucket",bucket).put("added",old==null?System.currentTimeMillis():old.optLong("added",System.currentTimeMillis())).put("episodesSeen",seen));}write("favorites",favorites);}catch(Exception ignored){}}
    public synchronized List<Anime> favorites(){return favorites("","");}
    public synchronized List<Anime> favorites(String bucket,String query){ArrayList<Anime> result=new ArrayList<>();Iterator<String> keys=favorites.keys();String q=query==null?"":query.toLowerCase(Locale.ROOT);while(keys.hasNext()){JSONObject j=favorites.optJSONObject(keys.next());if(j==null)continue;Anime a=Anime.from(j.optJSONObject("release"));if(!Anime.valid(a))continue;if(bucket!=null&&!bucket.isEmpty()&&!bucket.equals(j.optString("bucket","planned")))continue;if(!(a.title+" "+a.original).toLowerCase(Locale.ROOT).contains(q))continue;result.add(a);}result.sort((a,b)->a.title.compareToIgnoreCase(b.title));return result;}
    public synchronized boolean updateFavoriteEpisodes(Anime a,int episodes){if(!Anime.valid(a)||!favorites.has(a.key()))return false;try{JSONObject item=favorites.optJSONObject(a.key());if(item==null)return false;int seen=item.optInt("episodesSeen",0);boolean alert=seen>0&&episodes>seen;if(episodes>seen||seen<=0){Anime copy=Anime.from(a.json());copy.episodes=Math.max(episodes,copy.episodes);item.put("release",copy.json());item.put("episodesSeen",Math.max(episodes,seen));write("favorites",favorites);}return alert;}catch(Exception e){return false;}}
    public synchronized int favoriteCount(){return favorites.length();}
    public synchronized JSONObject progress(Anime a){JSONObject j=history.optJSONObject(a.key());return j==null?new JSONObject():j;}
    public synchronized void progress(Anime a,double episode,int seconds,int duration,String mode,String dubbing,boolean tracked){if(!Anime.valid(a)||episode<0||!Double.isFinite(episode))return;try{if(dubbing!=null&&!dubbing.trim().isEmpty())settings.put("voicePreference",dubbing.trim());JSONObject j=new JSONObject().put("release",a.json()).put("episode",episode).put("time",Math.max(0,seconds)).put("duration",Math.max(0,duration)).put("updated",System.currentTimeMillis()).put("tracked",tracked).put("playerMode",mode==null?"":mode).put("dubbing",dubbing==null?"":dubbing);history.put(a.key(),j);if(a.episodes>0&&episode>=a.episodes&&!"ongoing".equalsIgnoreCase(a.status)){removeWatch(a);JSONObject fav=favorites.optJSONObject(a.key());if(fav!=null)fav.put("bucket","completed");}if(history.length()>100){String oldest=null;long at=Long.MAX_VALUE;Iterator<String> keys=history.keys();while(keys.hasNext()){String k=keys.next();long t=history.optJSONObject(k).optLong("updated");if(t<at){oldest=k;at=t;}}if(oldest!=null)history.remove(oldest);}write("favorites",favorites);write("history",history);write("settings",settings);}catch(Exception ignored){}}
    public synchronized List<Anime> recent(){ArrayList<JSONObject> values=new ArrayList<>();Iterator<String> keys=history.keys();while(keys.hasNext()){JSONObject x=history.optJSONObject(keys.next());if(x!=null)values.add(x);}values.sort((a,b)->Long.compare(b.optLong("updated"),a.optLong("updated")));ArrayList<Anime> out=new ArrayList<>();for(JSONObject j:values){Anime a=Anime.from(j.optJSONObject("release"));if(Anime.valid(a))out.add(a);}return out;}
    public synchronized void clearHistory(){history=new JSONObject();write("history",history);}
    public synchronized int quality(){return settings.optInt("quality",720);}
    public synchronized boolean autoNext(){return settings.optBoolean("autoNext",true);}
    public synchronized void settings(int quality,boolean next){try{settings.put("quality",quality).put("autoNext",next);write("settings",settings);}catch(Exception ignored){}}
    public synchronized int fontScale(){return Math.max(85,Math.min(130,settings.optInt("fontScale",100)));}
    public synchronized boolean customFont(){return settings.optBoolean("customFont",false);}
    public synchronized String fontName(){return settings.optString("fontName","Системный");}
    public synchronized void appearance(int scale,boolean custom,String name){try{settings.put("fontScale",Math.max(85,Math.min(130,scale))).put("customFont",custom).put("fontName",name==null||name.trim().isEmpty()?"Свой шрифт":name.trim());write("settings",settings);}catch(Exception ignored){}}
    public synchronized boolean liteMode(){return settings.optBoolean("liteMode",false);}
    public synchronized void liteMode(boolean enabled){try{settings.put("liteMode",enabled);write("settings",settings);}catch(Exception ignored){}}
    public synchronized boolean directOnly(){return settings.optBoolean("directOnly",false);}
    public synchronized void directOnly(boolean enabled){try{settings.put("directOnly",enabled);write("settings",settings);}catch(Exception ignored){}}
    public synchronized int quietStart(){return Math.max(0,Math.min(23,settings.optInt("quietStart",23)));}
    public synchronized int quietEnd(){return Math.max(0,Math.min(23,settings.optInt("quietEnd",8)));}
    public synchronized boolean quietEnabled(){return settings.optBoolean("quietEnabled",false);}
    public synchronized void quietHours(boolean enabled,int start,int end){try{settings.put("quietEnabled",enabled).put("quietStart",Math.max(0,Math.min(23,start))).put("quietEnd",Math.max(0,Math.min(23,end)));write("settings",settings);}catch(Exception ignored){}}
    public synchronized boolean quietNow(){if(!quietEnabled())return false;int h=Calendar.getInstance().get(Calendar.HOUR_OF_DAY),s=quietStart(),e=quietEnd();return s==e?false:(s<e?h>=s&&h<e:h>=s||h<e);}
    public synchronized String voicePreference(){return settings.optString("voicePreference","");}
    public synchronized String note(Anime a){return Anime.valid(a)?settings.optString("note:"+a.key(),""):"";}
    public synchronized void note(Anime a,String text){if(!Anime.valid(a))return;try{String key="note:"+a.key();String v=text==null?"":text.trim();if(v.isEmpty())settings.remove(key);else settings.put(key,v.length()>800?v.substring(0,800):v);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void enqueueWatch(Anime a){if(!Anime.valid(a))return;try{JSONArray old=settings.optJSONArray("watchQueue"),next=new JSONArray();next.put(a.json());for(int i=0;old!=null&&i<old.length()&&next.length()<30;i++){Anime row=Anime.from(old.optJSONObject(i));if(Anime.valid(row)&&!row.key().equals(a.key()))next.put(row.json());}settings.put("watchQueue",next);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void removeWatch(Anime a){if(!Anime.valid(a))return;try{JSONArray old=settings.optJSONArray("watchQueue"),next=new JSONArray();for(int i=0;old!=null&&i<old.length();i++){Anime row=Anime.from(old.optJSONObject(i));if(Anime.valid(row)&&!row.key().equals(a.key()))next.put(row.json());}settings.put("watchQueue",next);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void clearWatchQueue(){try{settings.remove("watchQueue");write("settings",settings);}catch(Exception ignored){}}
    public synchronized List<Anime> watchQueue(){ArrayList<Anime> out=new ArrayList<>();JSONArray rows=settings.optJSONArray("watchQueue");for(int i=0;rows!=null&&i<rows.length();i++){Anime a=Anime.from(rows.optJSONObject(i));if(Anime.valid(a))out.add(a);}return out;}
    public synchronized JSONObject stats(){try{JSONObject out=new JSONObject();int titles=0,episodes=0,finished=0;long seconds=0;HashMap<String,Integer> genres=new HashMap<>();Iterator<String> keys=history.keys();while(keys.hasNext()){JSONObject h=history.optJSONObject(keys.next());if(h==null)continue;Anime a=Anime.from(h.optJSONObject("release"));if(!Anime.valid(a))continue;titles++;episodes+=Math.max(1,(int)Math.floor(h.optDouble("episode",1)));seconds+=Math.max(0,h.optInt("time",0));if(a.episodes>0&&h.optDouble("episode",0)>=a.episodes)finished++;for(String g:a.genres)if(g!=null&&!g.trim().isEmpty())genres.put(g,genres.getOrDefault(g,0)+1);}ArrayList<Map.Entry<String,Integer>> gs=new ArrayList<>(genres.entrySet());gs.sort((a,b)->b.getValue()-a.getValue());JSONArray top=new JSONArray();for(int i=0;i<Math.min(5,gs.size());i++)top.put(gs.get(i).getKey());return out.put("titles",titles).put("episodes",episodes).put("seconds",seconds).put("finished",finished).put("favorites",favorites.length()).put("queue",watchQueue().size()).put("genres",top);}catch(Exception e){return new JSONObject();}}
    public synchronized ArrayList<Anime> mood(String mood){ArrayList<Anime> source=new ArrayList<>(favorites());source.addAll(recent());LinkedHashMap<String,Anime> out=new LinkedHashMap<>();String m=mood==null?"":mood.toLowerCase(Locale.ROOT);for(Anime a:source){String text=(a.title+" "+a.original+" "+a.type+" "+String.join(" ",a.genres)).toLowerCase(Locale.ROOT);boolean ok=m.contains("уют")&&(text.contains("повсед")||text.contains("роман")||text.contains("комед"))||m.contains("экшен")&&(text.contains("экшен")||text.contains("приключ"))||m.contains("корот")&&(a.episodes>0&&a.episodes<=13||text.contains("фильм"))||m.contains("роман")&&text.contains("роман");if(ok)out.put(a.key(),a);}return new ArrayList<>(out.values());}

    public synchronized String exportData(){try{return new JSONObject().put("format","yoru.android.v3").put("exportedAt",new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.ROOT).format(new Date())).put("favorites",favorites).put("history",history).put("settings",settings).toString(2);}catch(Exception e){return "{}";}}
    public synchronized int importData(String input) throws Exception {if(input.length()>5*1024*1024)throw new Exception("Файл слишком большой");JSONObject root=new JSONObject(input);if(!root.optString("format").matches("yoru(?:\\.v[1-5]|\\.android\\.v[123])"))throw new Exception("Выберите файл коллекции YORU");int count=0;for(String name:new String[]{"favorites","history"}){JSONObject data=root.optJSONObject(name);if(data==null)continue;Iterator<String> keys=data.keys();while(keys.hasNext()){String k=keys.next();JSONObject item=data.optJSONObject(k);if(item==null)continue;Anime a=Anime.from(item.optJSONObject("release"));if(!Anime.valid(a)||!k.equals(a.key()))continue;if(name.equals("favorites")){String bucket=item.optString("bucket","planned");if(!Arrays.asList(BUCKETS).contains(bucket))bucket="planned";favorites.put(k,new JSONObject().put("release",a.json()).put("bucket",bucket).put("added",System.currentTimeMillis()).put("episodesSeen",Math.max(0,item.optInt("episodesSeen",a.episodes))));}else{double ep=item.optDouble("episode",1);if(!Double.isFinite(ep)||ep<0||ep>100000)continue;history.put(k,new JSONObject().put("release",a.json()).put("episode",ep).put("time",Math.min(100000,Math.max(0,item.optInt("time")))).put("duration",Math.min(100000,Math.max(0,item.optInt("duration")))).put("tracked",item.optBoolean("tracked",true)).put("updated",System.currentTimeMillis()).put("playerMode",item.optString("playerMode","")).put("dubbing",item.optString("dubbing","")));}count++;if(count>5000)break;}}JSONObject imported=root.optJSONObject("settings");if(imported!=null){for(String key:new String[]{"fontScale","customFont","fontName","quality","autoNext","dataSaver","wifiDownloads","directOnly","quietEnabled","quietStart","quietEnd","liteMode"})if(imported.has(key))settings.put(key,imported.opt(key));}write("favorites",favorites);write("history",history);write("settings",settings);return count;}
    public synchronized JSONObject traffic(){return read("traffic");}
    public synchronized void traffic(JSONObject value){write("traffic",value);}
    public synchronized boolean dataSaver(){return settings.optBoolean("dataSaver",false);}
    public synchronized boolean wifiDownloads(){return settings.optBoolean("wifiDownloads",true);}
    public synchronized void dataSaver(boolean enabled){try{settings.put("dataSaver",enabled);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void wifiDownloads(boolean enabled){try{settings.put("wifiDownloads",enabled);write("settings",settings);}catch(Exception ignored){}}

    public synchronized List<String> searchHistory(){ArrayList<String> out=new ArrayList<>();JSONArray rows=settings.optJSONArray("searchHistory");for(int i=0;rows!=null&&i<rows.length();i++){String q=rows.optString(i,"").trim();if(!q.isEmpty()&&!out.contains(q))out.add(q);if(out.size()>=14)break;}return out;}
    public synchronized void addSearch(String query){String q=query==null?"":query.trim().replaceAll("\\s+"," ");if(q.length()<2)return;if(q.length()>80)q=q.substring(0,80).trim();try{ArrayList<String> rows=new ArrayList<>();rows.add(q);for(String old:searchHistory())if(!old.equalsIgnoreCase(q))rows.add(old);JSONArray arr=new JSONArray();for(int i=0;i<Math.min(14,rows.size());i++)arr.put(rows.get(i));settings.put("searchHistory",arr);write("settings",settings);}catch(Exception ignored){}}
    public synchronized void clearSearchHistory(){try{settings.remove("searchHistory");write("settings",settings);}catch(Exception ignored){}}

}
