package app.yoru.mobile;

import android.net.Uri;
import android.util.Base64;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.regex.*;

final class VideoResolver {
    private static final int SHIFT=18;
    private VideoResolver(){}
    static TreeMap<Integer,String> resolve(ApiRepository api,String input)throws Exception{
        String url=ApiRepository.embed(input);if(url.isEmpty())url=ApiRepository.safeUrl(input);if(url.isEmpty())throw new IOException("Плеер не передал адрес");
        TreeMap<Integer,String> direct=direct(api,url);if(!direct.isEmpty())return direct;String host=host(url);
        if(has(host,"kodikplayer.com","kodik.info","kodik.cc","kodik.biz"))return kodik(api,url);
        if(has(host,"alloha.yani.tv","alloha.tv"))return alloha(api,url);
        if(has(host,"aksor.tv","aksor.yani.tv"))return aksor(api,url);
        if(has(host,"video.sibnet.ru","sibnet.ru"))return sibnet(api,url);
        if(has(host,"vk.com","vkvideo.ru"))return vk(api,url);
        if(has(host,"aniboom.one"))return aniboom(api,url);
        if(has(host,"sovetromantica.com"))return sovrom(api,url);
        if(has(host,"video1.anilib.me","video2.anilib.me","anilib.me"))return anilib(url);
        return scan(api,url);
    }
    private static boolean has(String host,String...names){for(String n:names)if(host.equals(n)||host.endsWith("."+n))return true;return false;}
    private static String host(String url){try{String h=Uri.parse(url).getHost();return h==null?"":h.toLowerCase(Locale.ROOT);}catch(Exception e){return "";}}
    private static TreeMap<Integer,String> direct(ApiRepository api,String url)throws Exception{TreeMap<Integer,String> out=new TreeMap<>();String path=Uri.parse(url).getPath();String lower=path==null?url.toLowerCase(Locale.ROOT):path.toLowerCase(Locale.ROOT);if(lower.endsWith(".m3u8")){out.putAll(hls(api,url));if(out.isEmpty())out.put(quality(url),url);}else if(lower.endsWith(".mpd")){out.putAll(dash(api,url));if(out.isEmpty())out.put(0,url);}else if(lower.endsWith(".mp4")||lower.endsWith(".mkv")||lower.endsWith(".webm")){out.put(quality(url),url);}return clean(out);}
    private static TreeMap<Integer,String> hls(ApiRepository api,String url)throws Exception{TreeMap<Integer,String> out=new TreeMap<>();String manifest=api.document(url);if(!manifest.trim().startsWith("#EXTM3U"))return out;String[] lines=manifest.split("\\r?\\n");int height=0;for(String line:lines){String l=line.trim();if(l.startsWith("#EXT-X-STREAM-INF")){Matcher m=Pattern.compile("RESOLUTION=\\d+x(\\d+)").matcher(l);height=m.find()?Integer.parseInt(m.group(1)):0;}else if(!l.isEmpty()&&!l.startsWith("#")&&height>0){out.put(height,absolute(url,l));height=0;}}return clean(out);}
    private static TreeMap<Integer,String> dash(ApiRepository api,String url)throws Exception{TreeMap<Integer,String> out=new TreeMap<>();String mpd=api.document(url);Matcher m=Pattern.compile("height=\\\"(\\d+)\\\"").matcher(mpd);while(m.find())out.put(Integer.parseInt(m.group(1)),url);return clean(out);}
    private static TreeMap<Integer,String> kodik(ApiRepository api,String url)throws Exception{String origin=origin(url);HashMap<String,String> headers=new HashMap<>();headers.put("Referer","https://animego.me/");headers.put("Accept-Language","ru-RU,ru;q=0.9");String page=api.request(url,"GET",null,false,headers);LinkedHashMap<String,String> payload=new LinkedHashMap<>();payload.put("d",find(page,"var\\s+domain\\s*=\\s*[\"'](.+?)[\"']"));payload.put("d_sign",find(page,"var\\s+d_sign\\s*=\\s*[\"'](.+?)[\"']"));payload.put("pd",find(page,"var\\s+pd\\s*=\\s*[\"'](.+?)[\"']"));payload.put("pd_sign",find(page,"var\\s+pd_sign\\s*=\\s*[\"'](.+?)[\"']"));payload.put("ref",find(page,"var\\s+ref\\s*=\\s*[\"'](.+?)[\"']"));payload.put("ref_sign",find(page,"var\\s+ref_sign\\s*=\\s*[\"'](.+?)[\"']"));payload.put("type",find(page,"videoInfo\\.type\\s*\\+?=\\s*[\"'](.+?)[\"']"));payload.put("hash",find(page,"videoInfo\\.hash\\s*\\+?=\\s*[\"'](.+?)[\"']"));payload.put("id",find(page,"videoInfo\\.id\\s*\\+?=\\s*[\"'](.+?)[\"']"));StringBuilder body=new StringBuilder();for(Map.Entry<String,String> e:payload.entrySet()){if(e.getValue().isEmpty())throw new IOException("Kodik не передал параметры");if(body.length()>0)body.append('&');body.append(enc(e.getKey())).append('=').append(enc(e.getValue()));}headers.clear();headers.put("Origin",origin);headers.put("Referer",url);headers.put("Accept","application/json, text/javascript, */*; q=0.01");String json=api.request(origin+"/ftor","POST",body.toString(),true,headers);JSONObject root=new JSONObject(json);JSONObject links=root.optJSONObject("links");TreeMap<Integer,String> out=new TreeMap<>();if(links!=null){Iterator<String> keys=links.keys();while(keys.hasNext()){String key=keys.next();JSONArray arr=links.optJSONArray(key);if(arr==null||arr.length()==0)continue;String src=arr.optJSONObject(0)==null?"":arr.optJSONObject(0).optString("src","");String decoded=decode(src);int cut=decoded.indexOf(":hls:manifest");if(cut>=0)decoded=decoded.substring(0,cut);String safe=ApiRepository.safeUrl(decoded);if(!safe.isEmpty())try{out.put(Integer.parseInt(key),safe);}catch(Exception ignored){out.put(quality(safe),safe);}}}if(out.isEmpty())throw new IOException("Kodik не вернул прямой поток");return clean(out);}
    private static TreeMap<Integer,String> alloha(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),"https://animego.me/"));String id=find(page,"const\\s+fileList\\s+=\\s*JSON\\.parse\\('\\{\\\"type\\\":\\s*\\\"serial\\\",\\s*\\\"active\\\":\\s*\\{\\\"id\\\":\\s*(\\d+)");if(id.isEmpty())id=find(page,"\\\"active\\\"\\s*:\\s*\\{\\s*\\\"id\\\"\\s*:\\s*(\\d+)");String token=find(page,"const\\s+userParam\\s*=\\s*\\{[\\s\\S]*?token:\\s*[\"'](.+?)[\"']");String user=find(page,"<meta\\s+name\\s*=\\s*[\"']user[\"']\\s+content\\s*=\\s*[\"'](.+?)[\"']");if(id.isEmpty()||token.isEmpty()||user.isEmpty())throw new IOException("Alloha не передал параметры");HashMap<String,String> h=headers("https://alloha.yani.tv",url);h.put("Accepts-Controls",user);String json=api.request("https://alloha.yani.tv/movie/"+id,"POST","token="+enc(token)+"&av1=true&autoplay=0&audio=&subtitle=",true,h);JSONObject root=new JSONObject(json);JSONArray sources=root.optJSONArray("hlsSource");TreeMap<Integer,String> out=new TreeMap<>();JSONObject first=sources==null||sources.length()==0?null:sources.optJSONObject(0);JSONObject q=first==null?null:first.optJSONObject("quality");if(q!=null){Iterator<String> keys=q.keys();while(keys.hasNext()){String key=keys.next();if(key.equalsIgnoreCase("Object"))continue;String link=q.optString(key,"");int cut=link.indexOf(" or ");if(cut>=0)link=link.substring(0,cut);String safe=ApiRepository.safeUrl(link);if(!safe.isEmpty())try{out.put(Integer.parseInt(key),safe);}catch(Exception ignored){}}}if(out.isEmpty())throw new IOException("Alloha не вернул прямой поток");return clean(out);}
    private static TreeMap<Integer,String> aksor(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),"https://animego.me/"));String link=find(page,"var\\s+videoUrl\\s*=\\s*[\"'](.+?)[\"']");if(link.isEmpty())throw new IOException("Aksor не вернул видео");String safe=absolute(url,link);TreeMap<Integer,String> out=new TreeMap<>();if(!safe.isEmpty())out.put(quality(safe),safe);return clean(out);}
    private static TreeMap<Integer,String> sibnet(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),"https://animego.me/"));String path=find(page,"src:\\s*[\"']/(.+?\\.mp4[^\"']*)[\"']");if(path.isEmpty())throw new IOException("Sibnet не вернул видео");String safe=ApiRepository.safeUrl("https://video.sibnet.ru/"+path);TreeMap<Integer,String> out=new TreeMap<>();if(!safe.isEmpty())out.put(480,safe);return clean(out);}
    private static TreeMap<Integer,String> vk(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),"https://animego.me/"));Matcher m=Pattern.compile("\\\"url(\\d+)\\\"\\s*:\\s*\\\"(.+?)\\\"").matcher(page);TreeMap<Integer,String> out=new TreeMap<>();while(m.find()){String safe=ApiRepository.safeUrl(m.group(2).replace("\\/","/").replace("\\u0026","&"));if(!safe.isEmpty())out.put(Integer.parseInt(m.group(1)),safe);}if(out.isEmpty())throw new IOException("VK не вернул видео");return clean(out);}
    private static TreeMap<Integer,String> aniboom(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),"https://animego.me/"));String dash=find(page,"&quot;dash&quot;:&quot;\\{\\\\&quot;src\\\\&quot;:\\\\&quot;(https[^;]+?\\.mpd)");if(dash.isEmpty())dash=find(page,"\\\"dash\\\"\\s*:\\s*\\\"(https[^\\\"]+?\\.mpd)\\\"");dash=dash.replace("\\\\\\/","/").replace("\\/","/");String safe=ApiRepository.safeUrl(dash);if(safe.isEmpty())throw new IOException("Aniboom не вернул видео");TreeMap<Integer,String> out=dash(api,safe);if(out.isEmpty())out.put(0,safe);return clean(out);}
    private static TreeMap<Integer,String> sovrom(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),"https://animego.me/"));String link=find(page,"var\\s+config\\s*=\\s*\\{[\\s\\S]*?[\"']file[\"']\\s*:\\s*[\"'](.+?)[\"']");String safe=absolute(url,link);TreeMap<Integer,String> out=new TreeMap<>();if(!safe.isEmpty())out.putAll(direct(api,safe));if(out.isEmpty()&&!safe.isEmpty())out.put(1080,safe);return clean(out);}
    private static TreeMap<Integer,String> anilib(String url)throws Exception{String safe=ApiRepository.safeUrl(url);TreeMap<Integer,String> out=new TreeMap<>();if(!safe.isEmpty())out.put(quality(safe),safe);return clean(out);}
    private static TreeMap<Integer,String> scan(ApiRepository api,String url)throws Exception{String page=api.request(url,"GET",null,false,headers(origin(url),"https://animego.me/"));ArrayList<String> found=new ArrayList<>();Matcher f=Pattern.compile("(?:file|src|hls|url)\\s*[:=]\\s*[\"']([^\"']+?\\.(?:m3u8|mpd|mp4)(?:[^\"']*)?)[\"']",Pattern.CASE_INSENSITIVE).matcher(page);while(f.find())found.add(f.group(1));Matcher u=Pattern.compile("https?:\\\\?/\\\\?/[^\"'<>\\s]+?\\.(?:m3u8|mpd|mp4)(?:[^\"'<>\\s]*)?",Pattern.CASE_INSENSITIVE).matcher(page);while(u.find())found.add(u.group());for(String s:found){String safe=absolute(url,s.replace("\\/","/"));if(safe.isEmpty())continue;TreeMap<Integer,String> out=direct(api,safe);if(!out.isEmpty())return out;}throw new IOException("Плеер не дал прямой поток");}
    private static TreeMap<Integer,String> clean(TreeMap<Integer,String> input){TreeMap<Integer,String> out=new TreeMap<>();for(Map.Entry<Integer,String> e:input.entrySet()){String s=ApiRepository.safeUrl(e.getValue());if(!s.isEmpty())out.put(e.getKey()==null?0:e.getKey(),s);}return out;}
    private static HashMap<String,String> headers(String origin,String referer){HashMap<String,String> h=new HashMap<>();h.put("Origin",origin);h.put("Referer",referer);h.put("Accept-Language","ru-RU,ru;q=0.9,en;q=0.5");h.put("User-Agent","Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/126 Mobile Safari/537.36");return h;}
    private static String origin(String url){try{Uri u=Uri.parse(url);return u.getScheme()+"://"+u.getHost();}catch(Exception e){return "https://animego.me";}}
    private static String absolute(String base,String value){try{if(value==null||value.trim().isEmpty())return "";value=value.trim().replace("&amp;","&").replace("\\/","/");if(value.startsWith("//"))value="https:"+value;return ApiRepository.safeUrl(new URL(new URL(base),value).toString());}catch(Exception e){return "";}}
    private static String find(String input,String regex){Matcher m=Pattern.compile(regex,Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(input);return m.find()?m.group(1).replace("&amp;","&"):"";}
    private static int quality(String url){Matcher m=Pattern.compile("(?:^|[^0-9])([1-9][0-9]{2,3})p?(?:[^0-9]|$)").matcher(url);int q=0;while(m.find()){try{int v=Integer.parseInt(m.group(1));if(v>=240&&v<=4320)q=v;}catch(Exception ignored){}}return q;}
    private static String decode(String src)throws Exception{if(src==null||src.isEmpty())return "";if(src.contains("cloud.kodik")||src.startsWith("//")||src.startsWith("http"))return src.startsWith("http")?src:"https:"+src;String caesar=caesar(src);int mod=caesar.length()%4;if(mod!=0)caesar=caesar+"====".substring(mod);return new String(Base64.decode(caesar,Base64.DEFAULT),StandardCharsets.UTF_8);}
    private static String caesar(String input){StringBuilder out=new StringBuilder();for(int i=0;i<input.length();i++){char ch=input.charAt(i);if(ch>='a'&&ch<='z')out.append((char)((ch-'a'+SHIFT)%26+'a'));else if(ch>='A'&&ch<='Z')out.append((char)((ch-'A'+SHIFT)%26+'A'));else out.append(ch);}return out.toString();}
    private static String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){return "";}}
}
