package app.yoru.mobile;

import android.app.*;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;

public final class VpnScreen extends ScrollView {
    private final Activity activity;private final LinearLayout body;private final EditText input;private final Spinner locations,mode;private final TextView status,count,selected;private final Handler handler=new Handler(Looper.getMainLooper());private boolean setup;
    public VpnScreen(Activity a){super(a);activity=a;setFillViewport(true);body=Ui.column(a);body.setPadding(Ui.dp(a,17),Ui.dp(a,14),Ui.dp(a,17),Ui.dp(a,28));addView(body,new ScrollView.LayoutParams(-1,-2));body.addView(Ui.label(a,"ВСТРОЕННЫЙ VPN"));Ui.space(body,11);body.addView(Ui.text(a,"VPN",31,Ui.TEXT,true));Ui.space(body,8);body.addView(Ui.text(a,"Сначала YORU распаковывает подписку через обычную сеть телефона без системного VPN. Потом запускается Xray/VLESS/VLESS Reality.",13,Ui.MUTED,false));Ui.space(body,18);status=Ui.text(a,"",13,Ui.PURPLE,true);body.addView(status);Ui.space(body,16);body.addView(Ui.text(a,"Ссылка подписки",12,Ui.MUTED,true));Ui.space(body,7);input=new EditText(a);input.setTextColor(Ui.TEXT);input.setHintTextColor(Ui.MUTED);input.setTextSize(13);input.setSingleLine(false);input.setMinLines(2);input.setMaxLines(4);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);input.setHint("Вставь VPN subscription URL сюда");input.setText(YoruApp.app().store.vpnSubscriptionUrl());input.setPadding(Ui.dp(a,14),Ui.dp(a,12),Ui.dp(a,14),Ui.dp(a,12));input.setBackground(Ui.stroke(Ui.CARD,12,a));body.addView(input,Ui.lp(a,-1,-2));Ui.space(body,10);body.addView(Ui.button(a,"Обновить локации из подписки",true,()->YoruVpn.refreshInline(activity,input.getText().toString().trim(),this::refreshSafe)));Ui.space(body,20);body.addView(Ui.text(a,"Локация",12,Ui.MUTED,true));Ui.space(body,7);locations=new Spinner(a);body.addView(locations,Ui.lp(a,-1,48));Ui.space(body,7);selected=Ui.text(a,"",11,Ui.MUTED,false);body.addView(selected);Ui.space(body,16);body.addView(Ui.text(a,"Режим работы",12,Ui.MUTED,true));Ui.space(body,7);mode=new Spinner(a);mode.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_item,new String[]{"Только наше приложение YORU","Выбранные приложения","Все приложения телефона"}));body.addView(mode,Ui.lp(a,-1,48));Ui.space(body,10);body.addView(Ui.button(a,"Выбрать приложения для VPN",false,()->YoruVpn.apps(activity)));Ui.space(body,18);LinearLayout buttons=Ui.row(a);buttons.addView(Ui.button(a,"Подключить",true,()->{YoruVpn.connect(activity);handler.postDelayed(this::refreshSafe,1500);}),new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams off=new LinearLayout.LayoutParams(0,-2,1);off.leftMargin=Ui.dp(a,9);buttons.addView(Ui.button(a,"Отключить",false,()->{YoruVpn.disconnect(activity);handler.postDelayed(this::refreshSafe,700);}),off);body.addView(buttons);Ui.space(body,15);body.addView(Ui.button(a,"Показать статус",false,()->YoruVpn.status(activity)));Ui.space(body,20);count=Ui.text(a,"",12,Ui.MUTED,false);body.addView(count);Ui.space(body,11);body.addView(Ui.text(a,"Если подписка открывается только при рабочем VPN, YORU всё равно сначала пробует не-VPN сеть Android, чтобы активный сломанный туннель не блокировал импорт. По умолчанию VPN работает только для YORU.",11,Ui.MUTED,false));bind();refreshSafe();}
    private void bind(){locations.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> p,View v,int pos,long id){if(setup)return;try{JSONArray list=YoruApp.app().store.vpnProfiles();JSONObject row=list.optJSONObject(pos);if(row!=null){YoruApp.app().store.vpnSelected(row.optString("id"));selected.setText("Выбрано: "+YoruVpnProfile.label(row).replace('\n',' '));}}catch(Throwable ignored){}}public void onNothingSelected(AdapterView<?> p){}});mode.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> p,View v,int pos,long id){if(setup)return;try{YoruApp.app().store.vpnMode(new String[]{"self","selected","all"}[pos]);refreshSafe();}catch(Throwable ignored){}}public void onNothingSelected(AdapterView<?> p){}});}
    private void refreshSafe(){try{refresh();}catch(Throwable e){setup=false;status.setText("Статус: экран восстановлен после битых VPN-данных");selected.setText("Обновите подписку ещё раз");count.setText("Локаций найдено: 0");}}
    private void refresh(){setup=true;status.setText(YoruVpnService.active()?"Статус: подключен · "+YoruVpnService.text():"Статус: отключен · "+YoruVpnService.text());JSONArray list=YoruApp.app().store.vpnProfiles();String[] names=new String[Math.max(1,list.length())];String id=YoruApp.app().store.vpnSelected();int sel=0;if(list.length()==0)names[0]="Сначала вставьте подписку и нажмите обновить";else for(int i=0;i<list.length();i++){JSONObject p=list.optJSONObject(i);names[i]=p==null?"VPN":YoruVpnProfile.label(p).replace('\n',' ');if(p!=null&&p.optString("id").equals(id))sel=i;}locations.setAdapter(new ArrayAdapter<>(activity,android.R.layout.simple_spinner_item,names));locations.setSelection(Math.min(sel,names.length-1));JSONObject p=YoruVpnProfile.selected(list,id);selected.setText(p==null?"Локация ещё не выбрана":"Выбрано: "+YoruVpnProfile.label(p).replace('\n',' '));String m=YoruApp.app().store.vpnMode();mode.setSelection("all".equals(m)?2:"selected".equals(m)?1:0);count.setText("Локаций найдено: "+list.length()+" · режим: "+YoruVpn.modeLabel(m)+" · приложений выбрано: "+YoruApp.app().store.vpnApps().length());setup=false;}
    @Override protected void onAttachedToWindow(){super.onAttachedToWindow();refreshSafe();}
    @Override protected void onDetachedFromWindow(){handler.removeCallbacksAndMessages(null);super.onDetachedFromWindow();}
}
