package app.yoru.mobile;

import org.json.*;
import java.util.*;

final class YoruBrain {
    private YoruBrain(){}
    static String title(Anime a){if(a==null)return "Аниме";try{if(YoruApp.app()!=null&&YoruApp.app().store.originalTitles()&&!a.original.isEmpty())return a.original;}catch(Exception ignored){}return a.title;}
    static boolean visible(Anime a){if(!Anime.valid(a))return false;SecureStore s=YoruApp.app().store;if(s.hidden(a))return false;if(s.safeMode()&&(a.age.contains("18")||text(a).contains("эрот")))return false;if(s.hideSeen()&&"completed".equals(s.bucket(a)))return false;return true;}
    static ArrayList<Anime> visible(Collection<Anime> rows){LinkedHashMap<String,Anime> out=new LinkedHashMap<>();if(rows!=null)for(Anime a:rows)if(visible(a))out.put(a.key(),a);return new ArrayList<>(out.values());}
    static ArrayList<Anime> shelf(String kind,int max){SecureStore store=YoruApp.app().store;ArrayList<Anime> base=new ArrayList<>();base.addAll(YoruApp.app().api.seed());base.addAll(store.favorites());base.addAll(store.recent());ArrayList<Anime> out=new ArrayList<>();for(Anime a:visible(base)){String t=text(a);boolean ok=false;if("forYou".equals(kind))ok=taste(a)>0;if("short".equals(kind))ok=a.episodes>0&&a.episodes<=13||a.type.toLowerCase(Locale.ROOT).contains("фильм");if("movies".equals(kind))ok=a.type.toLowerCase(Locale.ROOT).contains("фильм");if("ongoing".equals(kind))ok="ongoing".equals(a.status)||"anons".equals(a.status);if("classics".equals(kind))ok=a.year>0&&a.year<2015&&a.score>=7;if("gems".equals(kind))ok=a.score>=7.5&&!store.favorite(a);if("pinned".equals(kind))ok=store.pinned(a);if("rewatch".equals(kind))ok=store.rewatch(a)>0||"completed".equals(store.bucket(a));if("romance".equals(kind))ok=t.contains("роман");if("action".equals(kind))ok=t.contains("экшен")||t.contains("приключ");if("calm".equals(kind))ok=t.contains("повсед")||t.contains("комед")||t.contains("слайс");if(ok)out.add(a);}out.sort((a,b)->Integer.compare(score(b,kind),score(a,kind)));return limit(unique(out),max);}
    static ArrayList<Anime> similar(Anime source,int max){ArrayList<Anime> out=new ArrayList<>();if(source==null)return out;for(Anime a:visible(YoruApp.app().api.seed())){if(a.key().equals(source.key()))continue;int s=0;if(!source.studio.isEmpty()&&source.studio.equalsIgnoreCase(a.studio))s+=6;if(source.year>0&&Math.abs(source.year-a.year)<=2)s++;for(String g:source.genres)if(a.genres.contains(g))s+=2;if(s>0)out.add(a);}out.sort((a,b)->Integer.compare(simScore(source,b),simScore(source,a)));return limit(unique(out),max);}
    static Anime surprise(){ArrayList<Anime> rows=shelf("forYou",50);if(rows.isEmpty())rows=visible(YoruApp.app().api.seed());if(rows.isEmpty())return null;return rows.get(new Random().nextInt(rows.size()));}
    static String dashboard(){JSONObject s=YoruApp.app().store.stats();int today=s.optInt("today"),goal=s.optInt("goal"),streak=s.optInt("streak"),queue=s.optInt("queue");String pace=today>=goal?"цель дня выполнена":"до цели дня: "+Math.max(0,goal-today);return "Сегодня: "+today+" / "+goal+" · "+pace+"\nСерия дней: "+streak+" · в плане: "+queue+" · в коллекции: "+s.optInt("favorites");}
    static String[] achievements(){JSONObject s=YoruApp.app().store.stats();ArrayList<String> rows=new ArrayList<>();add(rows,s.optInt("titles")>=1,"Первый тайтл","Начните историю просмотра");add(rows,s.optInt("episodes")>=10,"10 серий","Отметьте 10 серий");add(rows,s.optInt("episodes")>=50,"50 серий","Отметьте 50 серий");add(rows,s.optInt("episodes")>=100,"100 серий","Отметьте 100 серий");add(rows,s.optInt("finished")>=1,"Финалист","Завершите первый тайтл");add(rows,s.optInt("favorites")>=5,"Коллекционер","Добавьте 5 тайтлов в коллекцию");add(rows,s.optInt("queue")>=3,"Планировщик","Добавьте 3 тайтла в план");add(rows,s.optInt("streak")>=3,"Серия дней","Смотрите 3 дня подряд");add(rows,s.optInt("today")>=s.optInt("goal",3),"Цель дня","Выполните дневную цель");add(rows,s.optInt("ratings")>=3,"Критик","Поставьте 3 личные оценки");add(rows,s.optInt("pins")>=1,"Закреплено","Закрепите любимый тайтл");add(rows,s.optInt("rewatches")>=1,"Пересмотр","Отметьте пересмотр");return rows.toArray(new String[0]);}
    static String chip(Anime a){SecureStore s=YoruApp.app().store;if(s.pinned(a))return "Закреплено";int r=s.rating(a);if(r>0)return "Ваша оценка "+r+"/10";if(s.rewatch(a)>0)return "Пересмотр · "+s.rewatch(a);JSONObject h=s.progress(a);if(h.length()>0)return "Продолжить · серия "+Ui.number(h.optDouble("episode",1));if(s.favorite(a))return "В коллекции";if("ongoing".equals(a.status))return "Онгоинг";return ApiRepository.sourceNames.get(a.source);}
    static String personalLine(Anime a){SecureStore s=YoruApp.app().store;ArrayList<String> rows=new ArrayList<>();int r=s.rating(a);if(r>0)rows.add("оценка "+r+"/10");String tags=s.tags(a);if(!tags.isEmpty())rows.add(tags);int rw=s.rewatch(a);if(rw>0)rows.add("пересмотров: "+rw);return rows.isEmpty()?"":String.join(" · ",rows);}
    private static void add(ArrayList<String> rows,boolean ok,String title,String hint){rows.add((ok?"✓ ":"○ ")+title+" — "+hint);}
    private static int score(Anime a,String kind){int s=taste(a)*3+(int)Math.round(a.score*10);if(YoruApp.app().store.favorite(a))s+=30;if(YoruApp.app().store.pinned(a))s+=80;if("short".equals(kind)&&a.episodes>0)s+=Math.max(0,20-a.episodes);if("ongoing".equals(kind)&&"ongoing".equals(a.status))s+=50;return s;}
    private static int taste(Anime a){JSONObject st=YoruApp.app().store.stats();JSONArray gs=st.optJSONArray("genres");int score=0;for(int i=0;gs!=null&&i<gs.length();i++)if(a.genres.contains(gs.optString(i)))score+=5-i;String tags=YoruApp.app().store.tags(a);if(!tags.isEmpty())score+=2;return score;}
    private static int simScore(Anime source,Anime a){int s=0;if(!source.studio.isEmpty()&&source.studio.equalsIgnoreCase(a.studio))s+=6;if(source.year>0&&Math.abs(source.year-a.year)<=2)s++;for(String g:source.genres)if(a.genres.contains(g))s+=2;return s;}
    private static String text(Anime a){return (a.title+" "+a.original+" "+a.type+" "+a.status+" "+a.age+" "+a.studio+" "+String.join(" ",a.genres)).toLowerCase(Locale.ROOT);}
    private static ArrayList<Anime> unique(Collection<Anime> in){LinkedHashMap<String,Anime> out=new LinkedHashMap<>();for(Anime a:in)if(Anime.valid(a))out.put(a.key(),a);return new ArrayList<>(out.values());}
    private static ArrayList<Anime> limit(ArrayList<Anime> rows,int max){if(rows.size()<=max)return rows;return new ArrayList<>(rows.subList(0,max));}
}
