package app.yoru.mobile;

import android.util.Base64;
import org.json.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.regex.*;

final class YoruVpnProfile {
    static final String[] SCHEMES={"vless","vmess","trojan","ss","socks"};
    private static final Pattern LINK=Pattern.compile("(?i)(vless|vmess|trojan|ss|socks)://[^\\s\\\"'<>]+",Pattern.CASE_INSENSITIVE);
    private YoruVpnProfile(){}
    static JSONArray parseSubscription(String input)throws Exception{LinkedHashMap<String,JSONObject> out=new LinkedHashMap<>();parseAny(input==null?"":input,out,0);JSONArray arr=new JSONArray();for(JSONObject p:out.values())arr.put(p);return arr;}
    static JSONObject profile(String raw){try{String scheme=scheme(raw);if(!supported(scheme))return null;Parts parts=scheme.equals("vmess")?vmessParts(raw):standard(raw,scheme);if(parts.host==null||parts.host.trim().isEmpty())return null;String name=nameOf(scheme,parts);return new JSONObject().put("id",id(raw)).put("name",name).put("scheme",scheme).put("host",parts.host).put("port",parts.port).put("raw",raw);}catch(Exception e){return null;}}
    static String label(JSONObject p){String name=p.optString("name");String scheme=p.optString("scheme").toUpperCase(Locale.ROOT);String host=p.optString("host");int port=p.optInt("port",0);String tail=host.isEmpty()?scheme:scheme+" · "+host+(port>0?":"+port:"");return name.isEmpty()?tail:name+"\n"+tail;}
    static JSONObject selected(JSONArray list,String id){if(list==null||list.length()==0)return null;for(int i=0;i<list.length();i++){JSONObject p=list.optJSONObject(i);if(p!=null&&p.optString("id").equals(id))return p;}return list.optJSONObject(0);}
    static String decode(String value){try{return URLDecoder.decode(value==null?"":value,"UTF-8");}catch(Exception e){return value==null?"":value;}}
    static String enc(String value){try{return URLEncoder.encode(value==null?"":value,"UTF-8").replace("+","%20");}catch(Exception e){return value==null?"":value;}}
    static Map<String,String> query(String q){LinkedHashMap<String,String> map=new LinkedHashMap<>();if(q==null)return map;for(String token:q.split("&")){if(token.isEmpty())continue;String k=token.contains("=")?token.substring(0,token.indexOf('=')):token;String v=token.contains("=")?token.substring(token.indexOf('=')+1):"";map.put(decode(k).toLowerCase(Locale.ROOT),decode(v));}return map;}
    static Parts standard(String raw,String scheme){String body=raw.substring((scheme+"://").length());String main=body.contains("#")?body.substring(0,body.indexOf('#')):body;String frag=body.contains("#")?body.substring(body.indexOf('#')+1):"";String query="";int qi=main.indexOf('?');if(qi>=0){query=main.substring(qi+1);main=main.substring(0,qi);}String path="";int slash=main.indexOf('/');if(slash>=0){path=main.substring(slash);main=main.substring(0,slash);}String user="";String hostPort=main;int at=main.lastIndexOf('@');if(at>=0){user=main.substring(0,at);hostPort=main.substring(at+1);}String host=hostPort;int port=scheme.equals("socks")?1080:443;if(hostPort.startsWith("[")){int end=hostPort.indexOf(']');if(end>0){host=hostPort.substring(1,end);String rest=hostPort.substring(end+1);if(rest.startsWith(":"))port=parseInt(rest.substring(1),port);}}else{int colon=hostPort.lastIndexOf(':');if(colon>0&&colon<hostPort.length()-1){host=hostPort.substring(0,colon);port=parseInt(hostPort.substring(colon+1),port);}}return new Parts(decode(user),decode(host),port,query,decode(frag),decode(path));}
    static Parts vmessParts(String raw)throws Exception{String tmp=raw.substring("vmess://".length());String payload=(tmp.contains("#")?tmp.substring(0,tmp.indexOf('#')):tmp).trim();String decoded=decodeBase64(payload);if(decoded==null)throw new Exception();JSONObject o=new JSONObject(decoded);String host=o.optString("add");int port=parseInt(o.optString("port"),443);String name=o.optString("ps");return new Parts(o.optString("id"),host,port,"",name,"");}
    static String decodeBase64(String data){String out=decodeBase64Any(data);return out!=null&&(out.contains("://")||out.trim().startsWith("{")||out.trim().startsWith("[")||out.contains("proxies:")||out.contains("outbounds"))?out:null;}
    static String decodeBase64Any(String data){if(data==null)return null;String base=data.replace('\n',' ').replace('\r',' ').trim().replace(" ","");for(int mode=0;mode<2;mode++)try{String s=base;int pad=(4-s.length()%4)%4;for(int i=0;i<pad;i++)s+="=";byte[] b=Base64.decode(s,mode==0?Base64.DEFAULT|Base64.URL_SAFE:Base64.DEFAULT);return new String(b,StandardCharsets.UTF_8);}catch(Exception ignored){}return null;}
    private static void parseAny(String text,LinkedHashMap<String,JSONObject> out,int depth){if(text==null||text.trim().isEmpty()||depth>4)return;String value=text.trim();collectLinks(value,out);String decoded=decodeBase64(value);if(decoded!=null&&!decoded.equals(value))parseAny(decoded,out,depth+1);parseJson(value,out,depth);parseYaml(value,out);}
    private static void collectLinks(String text,LinkedHashMap<String,JSONObject> out){Matcher m=LINK.matcher(text);while(m.find()){String raw=clean(m.group());JSONObject p=profile(raw);if(p!=null)out.put(p.optString("id"),p);}}
    private static void parseJson(String text,LinkedHashMap<String,JSONObject> out,int depth){try{Object root=text.startsWith("[")?new JSONArray(text):text.startsWith("{")?new JSONObject(text):null;if(root!=null)walkJson(root,out,depth);}catch(Exception ignored){}}
    private static void walkJson(Object node,LinkedHashMap<String,JSONObject> out,int depth)throws Exception{if(depth>4||node==null)return;if(node instanceof JSONObject){JSONObject o=(JSONObject)node;JSONArray proxies=o.optJSONArray("proxies");if(proxies!=null)parseObjects(proxies,out);JSONArray outbounds=o.optJSONArray("outbounds");if(outbounds!=null)parseObjects(outbounds,out);JSONArray servers=o.optJSONArray("servers");if(servers!=null)parseObjects(servers,out);JSONObject one=fromObject(o);if(one!=null)out.put(one.optString("id"),one);Iterator<String> it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof String)parseAny((String)v,out,depth+1);else if(v instanceof JSONObject||v instanceof JSONArray)walkJson(v,out,depth+1);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof String)parseAny((String)v,out,depth+1);else walkJson(v,out,depth+1);}}}
    private static void parseObjects(JSONArray a,LinkedHashMap<String,JSONObject> out){for(int i=0;i<a.length();i++){JSONObject p=fromObject(a.optJSONObject(i));if(p!=null)out.put(p.optString("id"),p);}}
    private static JSONObject fromObject(JSONObject o){try{if(o==null)return null;String type=first(o,"type","protocol").toLowerCase(Locale.ROOT);if(type.equals("shadowsocks"))type="ss";if(type.equals("socks5"))type="socks";if(!supported(type))return null;String name=first(o,"name","remark","remarks","tag");String server=first(o,"server","address","add");int port=parseInt(first(o,"port","server_port"),443);if(server.isEmpty()&&o.has("settings"))return fromXray(o,type,name);JSONObject flat=flat(o);String raw=rawFrom(type,name,server,port,flat);return profile(raw);}catch(Exception e){return null;}}
    private static JSONObject flat(JSONObject o)throws Exception{JSONObject f=new JSONObject();Iterator<String> it=o.keys();while(it.hasNext()){String k=it.next();Object v=o.opt(k);if(!(v instanceof JSONObject)&&!(v instanceof JSONArray))f.put(k.replace("-","_"),v);}JSONObject tls=o.optJSONObject("tls");if(tls!=null){if(tls.optBoolean("enabled",false))f.put("security","tls");String s=tls.optString("server_name",tls.optString("servername",tls.optString("sni","")));if(!s.isEmpty())f.put("sni",s);JSONObject utls=tls.optJSONObject("utls");if(utls!=null&&!utls.optString("fingerprint","").isEmpty())f.put("fingerprint",utls.optString("fingerprint"));JSONObject reality=tls.optJSONObject("reality");if(reality!=null&&reality.optBoolean("enabled",false)){f.put("security","reality");f.put("public_key",reality.optString("public_key",reality.optString("publicKey","")));f.put("short_id",reality.optString("short_id",reality.optString("shortId","")));}}JSONObject tr=o.optJSONObject("transport");if(tr!=null){f.put("network",tr.optString("type",tr.optString("network","tcp")));String path=tr.optString("path",tr.optString("service_name",tr.optString("serviceName","")));if(!path.isEmpty())f.put("path",path);JSONObject headers=tr.optJSONObject("headers");if(headers!=null&&!headers.optString("Host",headers.optString("host","")).isEmpty())f.put("host_header",headers.optString("Host",headers.optString("host","")));}JSONObject ws=o.optJSONObject("ws-opts");if(ws==null)ws=o.optJSONObject("ws_opts");if(ws!=null){f.put("network","ws");if(!ws.optString("path","").isEmpty())f.put("path",ws.optString("path"));JSONObject h=ws.optJSONObject("headers");if(h!=null&&!h.optString("Host",h.optString("host","")).isEmpty())f.put("host_header",h.optString("Host",h.optString("host","")));}JSONObject grpc=o.optJSONObject("grpc-opts");if(grpc==null)grpc=o.optJSONObject("grpc_opts");if(grpc!=null){f.put("network","grpc");String g=grpc.optString("grpc-service-name",grpc.optString("grpc_service_name",grpc.optString("serviceName","")));if(!g.isEmpty())f.put("serviceName",g);}JSONObject reality=o.optJSONObject("reality-opts");if(reality==null)reality=o.optJSONObject("reality_opts");if(reality!=null){f.put("security","reality");f.put("public_key",reality.optString("public-key",reality.optString("public_key",reality.optString("publicKey",""))));f.put("short_id",reality.optString("short-id",reality.optString("short_id",reality.optString("shortId",""))));}return f;}
    private static JSONObject fromXray(JSONObject o,String type,String name)throws Exception{JSONObject settings=o.optJSONObject("settings");if(settings==null)return null;if(type.equals("vmess")||type.equals("vless")){JSONArray vnext=settings.optJSONArray("vnext");if(vnext==null||vnext.length()==0)return null;JSONObject host=vnext.optJSONObject(0);JSONArray users=host==null?null:host.optJSONArray("users");JSONObject u=users==null?null:users.optJSONObject(0);if(host==null||u==null)return null;JSONObject flat=new JSONObject().put("type",type).put("name",name).put("server",host.optString("address")).put("port",host.optInt("port",443)).put("uuid",u.optString("id")).put("alterId",u.optInt("alterId",0)).put("cipher",u.optString("security",u.optString("encryption","auto")));return profile(rawFrom(type,name,flat.optString("server"),flat.optInt("port"),flat));}if(type.equals("trojan")||type.equals("ss")||type.equals("socks")){JSONArray arr=settings.optJSONArray(type.equals("ss")?"servers":"servers");JSONObject row=arr==null?null:arr.optJSONObject(0);if(row==null)return null;row.put("type",type);row.put("name",name);row.put("server",row.optString("address",row.optString("server")));row.put("port",row.optInt("port",443));return profile(rawFrom(type,name,row.optString("server"),row.optInt("port"),row));}return null;}
    private static void parseYaml(String text,LinkedHashMap<String,JSONObject> out){if(!text.contains(":"))return;ArrayList<Map<String,String>> blocks=new ArrayList<>();LinkedHashMap<String,String> cur=null;String parent="";for(String raw:text.split("\\r?\\n")){String line=raw.trim();if(line.isEmpty()||line.startsWith("#"))continue;if(line.startsWith("- ")){if(cur!=null)blocks.add(cur);cur=new LinkedHashMap<>();line=line.substring(2).trim();parent="";}if(cur==null)continue;int idx=line.indexOf(':');if(idx<0)continue;String key=line.substring(0,idx).trim().replace("\"","").replace("'","");String val=unquote(line.substring(idx+1).trim());if(val.isEmpty()){parent=key.toLowerCase(Locale.ROOT);continue;}String norm=key.toLowerCase(Locale.ROOT).replace("-","_");if(parent.contains("headers")&&norm.equals("host"))norm="host_header";cur.put(norm,val);}if(cur!=null)blocks.add(cur);for(Map<String,String> b:blocks){JSONObject p=fromMap(b);if(p!=null)out.put(p.optString("id"),p);}}
    private static JSONObject fromMap(Map<String,String> m){try{String type=pick(m,"type","protocol").toLowerCase(Locale.ROOT);if(type.equals("shadowsocks"))type="ss";if(type.equals("socks5"))type="socks";if(!supported(type))return null;String server=pick(m,"server","address","add");int port=parseInt(pick(m,"port","server_port"),443);if(server.isEmpty())return null;JSONObject o=new JSONObject();for(Map.Entry<String,String> e:m.entrySet())o.put(e.getKey(),e.getValue());String raw=rawFrom(type,pick(m,"name","remark","tag"),server,port,o);return profile(raw);}catch(Exception e){return null;}}
    private static String rawFrom(String type,String name,String server,int port,JSONObject o)throws Exception{if(type.equals("vmess")){JSONObject v=new JSONObject();v.put("v","2");v.put("ps",name.isEmpty()?server:name);v.put("add",server);v.put("port",String.valueOf(port));v.put("id",first(o,"uuid","id"));v.put("aid",first(o,"alterId","alterid","aid").isEmpty()?"0":first(o,"alterId","alterid","aid"));v.put("scy",first(o,"cipher","security","method").isEmpty()?"auto":first(o,"cipher","security","method"));v.put("net",network(o));v.put("type",first(o,"headerType","header_type","type"));v.put("host",first(o,"host","host_header","serverName","servername","sni"));v.put("path",path(o));v.put("tls",tls(o));v.put("sni",first(o,"sni","serverName","servername"));v.put("fp",first(o,"fp","fingerprint","client_fingerprint"));return "vmess://"+Base64.encodeToString(v.toString().getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP);}StringBuilder q=new StringBuilder();if(type.equals("vless")){add(q,"encryption",first(o,"encryption","cipher").isEmpty()?"none":first(o,"encryption","cipher"));add(q,"security",tls(o));add(q,"type",network(o));add(q,"sni",first(o,"sni","serverName","servername"));add(q,"host",first(o,"host","host_header"));add(q,"path",path(o));add(q,"flow",first(o,"flow"));add(q,"fp",first(o,"fp","fingerprint","client_fingerprint"));add(q,"pbk",first(o,"pbk","public_key","publicKey"));add(q,"sid",first(o,"sid","short_id","shortId"));add(q,"spx",first(o,"spx","spider_x","spiderX"));return "vless://"+enc(first(o,"uuid","id"))+"@"+server+":"+port+"?"+q+"#"+enc(name.isEmpty()?server:name);}if(type.equals("trojan")){add(q,"security",tls(o).equals("none")?"tls":tls(o));add(q,"type",network(o));add(q,"sni",first(o,"sni","serverName","servername","peer"));add(q,"host",first(o,"host","host_header"));add(q,"path",path(o));add(q,"fp",first(o,"fp","fingerprint","client_fingerprint"));add(q,"pbk",first(o,"pbk","public_key","publicKey"));add(q,"sid",first(o,"sid","short_id","shortId"));return "trojan://"+enc(first(o,"password","passwd"))+"@"+server+":"+port+"?"+q+"#"+enc(name.isEmpty()?server:name);}if(type.equals("ss")){String method=first(o,"cipher","method");String pass=first(o,"password","passwd");String user=Base64.encodeToString((method+":"+pass).getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP);return "ss://"+user+"@"+server+":"+port+"#"+enc(name.isEmpty()?server:name);}if(type.equals("socks"))return "socks://"+server+":"+port+"#"+enc(name.isEmpty()?server:name);throw new Exception();}
    private static void add(StringBuilder q,String k,String v){if(v==null||v.isEmpty())return;if(q.length()>0)q.append('&');q.append(k).append('=').append(enc(v));}
    private static String tls(JSONObject o){String s=first(o,"security","tls","network_security");if(s.equalsIgnoreCase("true"))return "tls";if(s.equalsIgnoreCase("false"))return "none";if(s.isEmpty()&&(!first(o,"sni","serverName","servername","pbk","public_key").isEmpty()))return first(o,"pbk","public_key").isEmpty()?"tls":"reality";return s.isEmpty()?"none":s;}
    private static String network(JSONObject o){String s=first(o,"network","net","type");if(s.equals("vless")||s.equals("vmess")||s.equals("trojan")||s.equals("ss"))s="tcp";return s.isEmpty()?"tcp":s;}
    private static String path(JSONObject o){return first(o,"path","ws_path","grpc_service_name","serviceName","service_name");}
    private static String first(JSONObject o,String... keys){for(String k:keys){String v=o.optString(k,"");if(!v.isEmpty())return String.valueOf(v);}return "";}
    private static String pick(Map<String,String> m,String... keys){for(String k:keys){String v=m.get(k.toLowerCase(Locale.ROOT).replace("-","_"));if(v!=null&&!v.isEmpty())return v;}return "";}
    private static String unquote(String v){if((v.startsWith("\"")&&v.endsWith("\""))||(v.startsWith("'")&&v.endsWith("'")))return v.substring(1,v.length()-1);return v;}
    private static String clean(String s){while(s.endsWith(",")||s.endsWith("]")||s.endsWith("}")||s.endsWith(")"))s=s.substring(0,s.length()-1);return s.trim();}
    private static boolean supported(String s){for(String x:SCHEMES)if(x.equals(s))return true;return false;}
    private static String scheme(String raw){int i=raw.indexOf("://");return i<1?"":raw.substring(0,i).toLowerCase(Locale.ROOT);}
    private static String nameOf(String scheme,Parts parts){if(scheme.equals("vmess"))return parts.fragment.isEmpty()?parts.host+":"+parts.port:parts.fragment;if(!parts.fragment.isEmpty())return parts.fragment;return parts.host+":"+parts.port;}
    private static int parseInt(String s,int def){try{return Integer.parseInt(String.valueOf(s).trim());}catch(Exception e){return def;}}
    private static String id(String raw)throws Exception{MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] b=md.digest(raw.getBytes(StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();for(int i=0;i<8;i++)sb.append(String.format(Locale.ROOT,"%02x",b[i]));return sb.toString();}
    static final class Parts {final String user,host,query,fragment,path;final int port;Parts(String user,String host,int port,String query,String fragment,String path){this.user=user;this.host=host;this.port=port;this.query=query;this.fragment=fragment;this.path=path;}}
}
