package app.yoru.mobile;

import android.util.Base64;
import org.json.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.regex.*;

final class YoruVpnProfile {
    static final String[] SCHEMES={"vless","vmess","trojan","ss","socks"};
    private static final Pattern LINK=Pattern.compile("(?i)(vless|vmess|trojan|ss|socks|socks5)://[^\\s\\\"'<>]+",Pattern.CASE_INSENSITIVE);
    private YoruVpnProfile(){}
    static JSONArray parseSubscription(String input)throws Exception{LinkedHashMap<String,JSONObject> out=new LinkedHashMap<>();parseAny(input==null?"":input,out,0);JSONArray arr=new JSONArray();for(JSONObject p:out.values())arr.put(p);return arr;}
    static JSONObject profile(String raw){try{raw=normalizeRaw(clean(raw));String scheme=scheme(raw);if(!supported(scheme))return null;Parts parts=scheme.equals("vmess")?vmessParts(raw):standard(raw,scheme);if(parts.host==null||parts.host.trim().isEmpty())return null;String name=nameOf(scheme,parts);JSONObject p=new JSONObject().put("id",id(raw)).put("name",name).put("scheme",scheme).put("host",parts.host).put("port",parts.port).put("raw",raw);String flag=flag(name+" "+parts.host);String country=country(name+" "+parts.host);if(!flag.isEmpty())p.put("flag",flag);if(!country.isEmpty())p.put("country",country);return p;}catch(Exception e){return null;}}
    static String label(JSONObject p){String name=p.optString("name");String scheme=p.optString("scheme").toUpperCase(Locale.ROOT);String host=p.optString("host");int port=p.optInt("port",0);String country=p.optString("country");String flag=p.optString("flag");String place=country.isEmpty()?"Страна не указана":(flag.isEmpty()?country:flag+" "+country);String title=name.isEmpty()?place:place+" · "+name;String tail=host.isEmpty()?scheme:scheme+" · "+host+(port>0?":"+port:"");return title+"\n"+tail;}
    static JSONObject selected(JSONArray list,String id){if(list==null||list.length()==0)return null;for(int i=0;i<list.length();i++){JSONObject p=list.optJSONObject(i);if(p!=null&&p.optString("id").equals(id))return p;}return list.optJSONObject(0);}
    static String decode(String value){try{return URLDecoder.decode(value==null?"":value,"UTF-8");}catch(Exception e){return value==null?"":value;}}
    static String enc(String value){try{return URLEncoder.encode(value==null?"":value,"UTF-8").replace("+","%20");}catch(Exception e){return value==null?"":value;}}
    static Map<String,String> query(String q){LinkedHashMap<String,String> map=new LinkedHashMap<>();if(q==null)return map;for(String token:q.split("&")){if(token.isEmpty())continue;String k=token.contains("=")?token.substring(0,token.indexOf('=')):token;String v=token.contains("=")?token.substring(token.indexOf('=')+1):"";String key=decode(k).toLowerCase(Locale.ROOT);String val=decode(v);map.put(key,val);map.put(key.replace("-","").replace("_",""),val);map.put(key.replace("-","_"),val);}return map;}
    static Parts standard(String raw,String scheme){String body=raw.substring((scheme+"://").length());String main=body.contains("#")?body.substring(0,body.indexOf('#')):body;String frag=body.contains("#")?body.substring(body.indexOf('#')+1):"";String query="";int qi=main.indexOf('?');if(qi>=0){query=main.substring(qi+1);main=main.substring(0,qi);}String path="";int slash=main.indexOf('/');if(slash>=0){path=main.substring(slash);main=main.substring(0,slash);}String user="";String hostPort=main;int at=main.lastIndexOf('@');if(at>=0){user=main.substring(0,at);hostPort=main.substring(at+1);}String host=hostPort;int port=scheme.equals("socks")?1080:443;if(hostPort.startsWith("[")){int end=hostPort.indexOf(']');if(end>0){host=hostPort.substring(1,end);String rest=hostPort.substring(end+1);if(rest.startsWith(":"))port=parseInt(rest.substring(1),port);}}else{int colon=hostPort.lastIndexOf(':');if(colon>0&&colon<hostPort.length()-1){host=hostPort.substring(0,colon);port=parseInt(hostPort.substring(colon+1),port);}}return new Parts(decode(user),decode(host),port,query,decode(frag),decode(path));}
    static Parts vmessParts(String raw)throws Exception{String tmp=raw.substring("vmess://".length());String payload=(tmp.contains("#")?tmp.substring(0,tmp.indexOf('#')):tmp).trim();String decoded=decodeBase64(payload);if(decoded==null)throw new Exception();JSONObject o=new JSONObject(decoded);String host=o.optString("add",o.optString("server",o.optString("address")));int port=parseInt(o.optString("port"),443);String name=o.optString("ps",o.optString("name",host));return new Parts(o.optString("id",o.optString("uuid")),host,port,"",name,"");}
    static String decodeBase64(String data){String out=decodeBase64Any(data);return out!=null&&(out.contains("://")||out.trim().startsWith("{")||out.trim().startsWith("[")||out.contains("proxies:")||out.contains("outbounds")||out.contains("server:"))?out:null;}
    static String decodeBase64Any(String data){if(data==null)return null;String base=data.replace('\n',' ').replace('\r',' ').trim().replace(" ","");if(base.isEmpty())return null;for(int mode=0;mode<2;mode++)try{String s=base;int pad=(4-s.length()%4)%4;for(int i=0;i<pad;i++)s+="=";byte[] b=Base64.decode(s,mode==0?Base64.DEFAULT|Base64.URL_SAFE:Base64.DEFAULT);return new String(b,StandardCharsets.UTF_8);}catch(Exception ignored){}return null;}
    private static void parseAny(String text,LinkedHashMap<String,JSONObject> out,int depth){if(text==null||text.trim().isEmpty()||depth>5)return;String value=text.trim();collectLinks(value,out);String decoded=decodeBase64(value);if(decoded!=null&&!decoded.equals(value))parseAny(decoded,out,depth+1);parseJson(value,out,depth);parseYaml(value,out);}
    private static void collectLinks(String text,LinkedHashMap<String,JSONObject> out){Matcher m=LINK.matcher(text);while(m.find()){JSONObject p=profile(m.group());if(p!=null)out.put(p.optString("id"),p);}}
    private static void parseJson(String text,LinkedHashMap<String,JSONObject> out,int depth){try{Object root=text.startsWith("[")?new JSONArray(text):text.startsWith("{")?new JSONObject(text):null;if(root!=null)walkJson(root,out,depth);}catch(Exception ignored){}}
    private static void walkJson(Object node,LinkedHashMap<String,JSONObject> out,int depth)throws Exception{if(depth>5||node==null)return;if(node instanceof JSONObject){JSONObject o=(JSONObject)node;parseObjects(o.optJSONArray("proxies"),out);parseObjects(o.optJSONArray("outbounds"),out);parseObjects(o.optJSONArray("servers"),out);parseObjects(o.optJSONArray("endpoints"),out);JSONObject one=fromObject(o);if(one!=null)out.put(one.optString("id"),one);Iterator<String> it=o.keys();while(it.hasNext()){Object v=o.opt(it.next());if(v instanceof String)parseAny((String)v,out,depth+1);else if(v instanceof JSONObject||v instanceof JSONArray)walkJson(v,out,depth+1);}}else if(node instanceof JSONArray){JSONArray a=(JSONArray)node;for(int i=0;i<a.length();i++){Object v=a.opt(i);if(v instanceof String)parseAny((String)v,out,depth+1);else walkJson(v,out,depth+1);}}}
    private static void parseObjects(JSONArray a,LinkedHashMap<String,JSONObject> out){if(a==null)return;for(int i=0;i<a.length();i++){JSONObject p=fromObject(a.optJSONObject(i));if(p!=null)out.put(p.optString("id"),p);}}
    private static JSONObject fromObject(JSONObject o){try{if(o==null)return null;String type=type(first(o,"type","protocol"));if(!supported(type))return null;String name=first(o,"name","remark","remarks","tag","ps");String server=first(o,"server","address","add","server_address");int port=parseInt(first(o,"port","server_port","serverPort"),443);if((server.isEmpty()||o.has("settings"))&&o.has("settings"))return fromXray(o,type,name);if(server.isEmpty())return null;JSONObject flat=flat(o);String raw=rawFrom(type,name,server,port,flat);return profile(raw);}catch(Exception e){return null;}}
    private static JSONObject flat(JSONObject o)throws Exception{JSONObject f=new JSONObject();Iterator<String> it=o.keys();while(it.hasNext()){String k=it.next();Object v=o.opt(k);if(!(v instanceof JSONObject)&&!(v instanceof JSONArray)){f.put(norm(k),v);f.put(k,v);}}JSONObject tls=o.optJSONObject("tls");if(tls!=null){if(tls.optBoolean("enabled",false)||"tls".equalsIgnoreCase(tls.optString("type")))f.put("security","tls");String s=first(tls,"server_name","servername","serverName","sni");if(!s.isEmpty())f.put("sni",s);JSONObject utls=tls.optJSONObject("utls");if(utls!=null&&!first(utls,"fingerprint","fp").isEmpty())f.put("fingerprint",first(utls,"fingerprint","fp"));JSONObject reality=tls.optJSONObject("reality");if(reality!=null&&reality.optBoolean("enabled",false)){f.put("security","reality");f.put("public_key",first(reality,"public_key","publicKey","pbk"));f.put("short_id",first(reality,"short_id","shortId","sid"));f.put("spider_x",first(reality,"spider_x","spiderX","spx"));}}
        JSONObject tr=o.optJSONObject("transport");if(tr!=null){String n=first(tr,"type","network");if(!n.isEmpty())f.put("network",n);String path=first(tr,"path","service_name","serviceName","grpc_service_name");if(!path.isEmpty())f.put("path",path);JSONObject headers=tr.optJSONObject("headers");if(headers!=null&&!first(headers,"Host","host").isEmpty())f.put("host_header",first(headers,"Host","host"));}
        JSONObject ws=object(o,"ws-opts","ws_opts","wsSettings");if(ws!=null){f.put("network","ws");if(!first(ws,"path").isEmpty())f.put("path",first(ws,"path"));JSONObject h=ws.optJSONObject("headers");if(h!=null&&!first(h,"Host","host").isEmpty())f.put("host_header",first(h,"Host","host"));}
        JSONObject grpc=object(o,"grpc-opts","grpc_opts","grpcSettings");if(grpc!=null){f.put("network","grpc");String g=first(grpc,"grpc-service-name","grpc_service_name","serviceName","service_name");if(!g.isEmpty())f.put("serviceName",g);}
        JSONObject reality=object(o,"reality-opts","reality_opts","realitySettings");if(reality!=null){f.put("security","reality");f.put("public_key",first(reality,"public-key","public_key","publicKey","pbk"));f.put("short_id",first(reality,"short-id","short_id","shortId","sid"));f.put("spider_x",first(reality,"spider-x","spider_x","spiderX","spx"));if(!first(reality,"serverName","server_name","sni").isEmpty())f.put("sni",first(reality,"serverName","server_name","sni"));}
        return f;}
    private static JSONObject fromXray(JSONObject o,String type,String name)throws Exception{JSONObject settings=o.optJSONObject("settings");if(settings==null)return null;JSONObject stream=streamFlat(o.optJSONObject("streamSettings"));if(type.equals("vmess")||type.equals("vless")){JSONArray vnext=settings.optJSONArray("vnext");if(vnext==null||vnext.length()==0)return null;JSONObject host=vnext.optJSONObject(0);JSONArray users=host==null?null:host.optJSONArray("users");JSONObject u=users==null?null:users.optJSONObject(0);if(host==null||u==null)return null;JSONObject flat=new JSONObject().put("type",type).put("name",name).put("server",host.optString("address")).put("port",host.optInt("port",443)).put("uuid",first(u,"id","uuid")).put("alterId",u.optInt("alterId",0)).put("cipher",first(u,"security","encryption"));if(type.equals("vless"))flat.put("encryption",first(u,"encryption").isEmpty()?"none":first(u,"encryption"));else if(!first(u,"encryption").isEmpty())flat.put("encryption",first(u,"encryption"));if(!first(u,"flow").isEmpty())flat.put("flow",first(u,"flow"));merge(stream,flat);return profile(rawFrom(type,name,flat.optString("server"),flat.optInt("port"),flat));}if(type.equals("trojan")||type.equals("ss")||type.equals("socks")){JSONArray arr=settings.optJSONArray("servers");JSONObject row=arr==null?null:arr.optJSONObject(0);if(row==null)return null;row.put("type",type);row.put("name",name);row.put("server",row.optString("address",row.optString("server")));row.put("port",row.optInt("port",443));merge(stream,row);return profile(rawFrom(type,name,row.optString("server"),row.optInt("port"),row));}return null;}
    private static JSONObject streamFlat(JSONObject s)throws Exception{JSONObject f=new JSONObject();if(s==null)return f;String network=first(s,"network");String security=first(s,"security");if(!network.isEmpty())f.put("network",network);if(!security.isEmpty())f.put("security",security);JSONObject tls=s.optJSONObject("tlsSettings");if(tls!=null){f.put("security","tls");if(!first(tls,"serverName","server_name","sni").isEmpty())f.put("sni",first(tls,"serverName","server_name","sni"));if(!first(tls,"fingerprint","fp").isEmpty())f.put("fingerprint",first(tls,"fingerprint","fp"));Object alpn=tls.opt("alpn");if(alpn instanceof JSONArray)f.put("alpn",join((JSONArray)alpn));else if(alpn instanceof String)f.put("alpn",alpn);}JSONObject reality=s.optJSONObject("realitySettings");if(reality!=null){f.put("security","reality");f.put("public_key",first(reality,"publicKey","public_key","pbk"));f.put("short_id",first(reality,"shortId","short_id","sid"));f.put("spider_x",first(reality,"spiderX","spider_x","spx"));if(!first(reality,"serverName","server_name","sni").isEmpty())f.put("sni",first(reality,"serverName","server_name","sni"));if(!first(reality,"fingerprint","fp").isEmpty())f.put("fingerprint",first(reality,"fingerprint","fp"));}JSONObject ws=s.optJSONObject("wsSettings");if(ws!=null){f.put("network","ws");if(!first(ws,"path").isEmpty())f.put("path",first(ws,"path"));JSONObject h=ws.optJSONObject("headers");if(h!=null&&!first(h,"Host","host").isEmpty())f.put("host_header",first(h,"Host","host"));}JSONObject grpc=s.optJSONObject("grpcSettings");if(grpc!=null){f.put("network","grpc");if(!first(grpc,"serviceName","service_name").isEmpty())f.put("serviceName",first(grpc,"serviceName","service_name"));}JSONObject http=s.optJSONObject("httpSettings");if(http!=null){f.put("network","http");Object hosts=http.opt("host");if(hosts instanceof JSONArray&&((JSONArray)hosts).length()>0)f.put("host_header",((JSONArray)hosts).optString(0));else if(hosts instanceof String)f.put("host_header",hosts);Object paths=http.opt("path");if(paths instanceof JSONArray&&((JSONArray)paths).length()>0)f.put("path",((JSONArray)paths).optString(0));else if(paths instanceof String)f.put("path",paths);}JSONObject tcp=s.optJSONObject("tcpSettings");if(tcp!=null){JSONObject header=tcp.optJSONObject("header");if(header!=null&&!first(header,"type").isEmpty())f.put("headerType",first(header,"type"));}return f;}
    private static void parseYaml(String text,LinkedHashMap<String,JSONObject> out){if(!text.contains(":"))return;ArrayList<Map<String,String>> blocks=new ArrayList<>();LinkedHashMap<String,String> cur=null;String parent="";for(String raw:text.split("\\r?\\n")){String line=raw.trim();if(line.isEmpty()||line.startsWith("#"))continue;if(line.startsWith("- ")){if(cur!=null)blocks.add(cur);cur=new LinkedHashMap<>();line=line.substring(2).trim();parent="";if(line.startsWith("{")&&line.endsWith("}")){inline(line,cur);continue;}}if(cur==null)continue;int idx=line.indexOf(':');if(idx<0)continue;String key=line.substring(0,idx).trim().replace("\"","").replace("'","");String val=unquote(line.substring(idx+1).trim());if(val.isEmpty()){parent=key.toLowerCase(Locale.ROOT);continue;}String norm=norm(key);if(parent.contains("headers")&&norm.equals("host"))norm="host_header";cur.put(norm,val);}if(cur!=null)blocks.add(cur);for(Map<String,String> b:blocks){JSONObject p=fromMap(b);if(p!=null)out.put(p.optString("id"),p);}}
    private static void inline(String line,Map<String,String> out){String body=line.substring(1,line.length()-1);for(String part:body.split(",")){int i=part.indexOf(':');if(i<0)i=part.indexOf('=');if(i<0)continue;String k=part.substring(0,i).trim();String v=part.substring(i+1).trim();out.put(norm(k),unquote(v));}}
    private static JSONObject fromMap(Map<String,String> m){try{String type=type(pick(m,"type","protocol"));if(!supported(type))return null;String server=pick(m,"server","address","add","server_address");int port=parseInt(pick(m,"port","server_port"),443);if(server.isEmpty())return null;JSONObject o=new JSONObject();for(Map.Entry<String,String> e:m.entrySet())o.put(e.getKey(),e.getValue());String raw=rawFrom(type,pick(m,"name","remark","remarks","tag","ps"),server,port,o);return profile(raw);}catch(Exception e){return null;}}
    private static String rawFrom(String type,String name,String server,int port,JSONObject o)throws Exception{if(type.equals("vmess")){JSONObject v=new JSONObject();v.put("v","2");v.put("ps",name.isEmpty()?server:name);v.put("add",server);v.put("port",String.valueOf(port));v.put("id",first(o,"uuid","id"));v.put("aid",first(o,"alterId","alterid","aid").isEmpty()?"0":first(o,"alterId","alterid","aid"));v.put("scy",first(o,"cipher","security","method").isEmpty()?"auto":first(o,"cipher","security","method"));v.put("net",network(o));v.put("type",first(o,"headerType","header_type","type"));v.put("host",first(o,"host","host_header","serverName","servername","sni"));v.put("path",path(o));v.put("tls",tls(o));v.put("sni",first(o,"sni","serverName","servername"));v.put("fp",first(o,"fp","fingerprint","client_fingerprint","client-fingerprint"));return "vmess://"+Base64.encodeToString(v.toString().getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP);}StringBuilder q=new StringBuilder();if(type.equals("vless")){add(q,"encryption",first(o,"encryption","cipher").isEmpty()?"none":first(o,"encryption","cipher"));add(q,"security",tls(o));add(q,"type",network(o));add(q,"sni",first(o,"sni","serverName","servername"));add(q,"host",first(o,"host","host_header"));add(q,"path",path(o));add(q,"flow",first(o,"flow"));add(q,"fp",first(o,"fp","fingerprint","client_fingerprint","client-fingerprint"));add(q,"pbk",first(o,"pbk","public_key","publicKey","public-key"));add(q,"sid",first(o,"sid","short_id","shortId","short-id"));add(q,"spx",first(o,"spx","spider_x","spiderX","spider-x"));return "vless://"+enc(first(o,"uuid","id"))+"@"+server+":"+port+"?"+q+"#"+enc(name.isEmpty()?server:name);}if(type.equals("trojan")){add(q,"security",tls(o).equals("none")?"tls":tls(o));add(q,"type",network(o));add(q,"sni",first(o,"sni","serverName","servername","peer"));add(q,"host",first(o,"host","host_header"));add(q,"path",path(o));add(q,"fp",first(o,"fp","fingerprint","client_fingerprint","client-fingerprint"));add(q,"pbk",first(o,"pbk","public_key","publicKey","public-key"));add(q,"sid",first(o,"sid","short_id","shortId","short-id"));return "trojan://"+enc(first(o,"password","passwd"))+"@"+server+":"+port+"?"+q+"#"+enc(name.isEmpty()?server:name);}if(type.equals("ss")){String method=first(o,"cipher","method");String pass=first(o,"password","passwd");String user=Base64.encodeToString((method+":"+pass).getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP);return "ss://"+user+"@"+server+":"+port+"#"+enc(name.isEmpty()?server:name);}if(type.equals("socks"))return "socks://"+server+":"+port+"#"+enc(name.isEmpty()?server:name);throw new Exception();}
    private static void add(StringBuilder q,String k,String v){if(v==null||v.isEmpty())return;if(q.length()>0)q.append('&');q.append(k).append('=').append(enc(v));}
    private static String tls(JSONObject o){String s=first(o,"security","tls","network_security");if(s.equalsIgnoreCase("true"))return "tls";if(s.equalsIgnoreCase("false"))return "none";if(s.isEmpty()&&!first(o,"pbk","public_key","publicKey","public-key").isEmpty())return "reality";if(s.isEmpty()&&!first(o,"sni","serverName","servername").isEmpty())return "tls";return s.isEmpty()?"none":s;}
    private static String network(JSONObject o){String s=first(o,"network","net","type");if(s.equals("vless")||s.equals("vmess")||s.equals("trojan")||s.equals("ss")||s.equals("socks"))s="tcp";return s.isEmpty()?"tcp":s.toLowerCase(Locale.ROOT);}
    private static String path(JSONObject o){return first(o,"path","ws_path","grpc_service_name","grpc-service-name","serviceName","service_name","servicename");}
    private static void merge(JSONObject from,JSONObject to)throws Exception{Iterator<String> it=from.keys();while(it.hasNext()){String k=it.next();Object v=from.opt(k);if(v!=null&&!JSONObject.NULL.equals(v))to.put(k,v);}}
    private static JSONObject object(JSONObject o,String... keys){for(String k:keys){JSONObject x=o.optJSONObject(k);if(x!=null)return x;}return null;}
    private static String first(JSONObject o,String... keys){for(String k:keys){Object raw=o.opt(k);if(raw==null||JSONObject.NULL.equals(raw))continue;String v=String.valueOf(raw);if(!v.isEmpty())return v;}return "";}
    private static String pick(Map<String,String> m,String... keys){for(String k:keys){String n=norm(k);String v=m.get(n);if(v==null)v=m.get(n.replace("_",""));if(v!=null&&!v.isEmpty())return strip(v);}return "";}
    private static String type(String s){s=s==null?"":s.toLowerCase(Locale.ROOT).trim();if(s.equals("shadowsocks"))return "ss";if(s.equals("socks5"))return "socks";return s;}
    private static String norm(String k){return k==null?"":k.trim().replace("\"","").replace("'","").toLowerCase(Locale.ROOT).replace("-","_");}
    private static String strip(String s){s=unquote(s==null?"":s.trim());if(s.startsWith("[")&&s.endsWith("]"))s=s.substring(1,s.length()-1).trim();return s;}
    private static String unquote(String v){v=v==null?"":v.trim();while(v.endsWith(","))v=v.substring(0,v.length()-1).trim();if((v.startsWith("\"")&&v.endsWith("\""))||(v.startsWith("'")&&v.endsWith("'")))return v.substring(1,v.length()-1);return v;}
    private static String clean(String s){s=s==null?"":s.trim();while(s.endsWith(",")||s.endsWith("]")||s.endsWith("}")||s.endsWith(")"))s=s.substring(0,s.length()-1);return s.trim();}
    private static String normalizeRaw(String raw){if(raw.toLowerCase(Locale.ROOT).startsWith("socks5://"))return "socks://"+raw.substring("socks5://".length());return raw;}
    private static boolean supported(String s){for(String x:SCHEMES)if(x.equals(s))return true;return false;}
    private static String scheme(String raw){int i=raw.indexOf("://");return i<1?"":type(raw.substring(0,i));}
    private static String nameOf(String scheme,Parts parts){if(scheme.equals("vmess"))return parts.fragment.isEmpty()?parts.host+":"+parts.port:parts.fragment;if(!parts.fragment.isEmpty())return parts.fragment;return parts.host+":"+parts.port;}
    private static int parseInt(String s,int def){try{return Integer.parseInt(String.valueOf(s).trim());}catch(Exception e){return def;}}
    private static String join(JSONArray a){StringBuilder b=new StringBuilder();for(int i=0;i<a.length();i++){String v=a.optString(i);if(v.isEmpty())continue;if(b.length()>0)b.append(',');b.append(v);}return b.toString();}
    private static String flag(String text){String code=flagCode(text);if(code.isEmpty())return "";int a=0x1F1E6+code.charAt(0)-'A',b=0x1F1E6+code.charAt(1)-'A';return new String(Character.toChars(a))+new String(Character.toChars(b));}
    private static String country(String text){String code=flagCode(text);if(!code.isEmpty())return countryName(code);code=countryCodeToken(text);if(!code.isEmpty())return countryName(code);String l=(text==null?"":text).toLowerCase(Locale.ROOT);String[][] map={{"RU","россия,russia,moscow,москва,spb,питер,санкт"},{"NL","netherlands,нидерланд,amsterdam,амстердам"},{"DE","germany,германия,deutsch,frankfurt,франкфурт"},{"FI","finland,финлянд,helsinki,хельсинки"},{"EE","estonia,эстони,tallinn,таллин"},{"SE","sweden,швеци,stockholm,стокгольм"},{"FR","france,франци,paris,париж"},{"GB","united kingdom,britain,england,london,брит,англи,лондон"},{"US","usa,united states,america,америк,new york,los angeles,miami"},{"TR","turkey,турци,istanbul,стамбул"},{"PL","poland,польш,warsaw,варшава"},{"LV","latvia,латви,riga,рига"},{"LT","lithuania,литв,vilnius,вильнюс"},{"JP","japan,япони,tokyo,токио"},{"SG","singapore,сингапур"},{"AE","uae,emirates,dubai,дубай,эмират"},{"KZ","kazakhstan,казахстан,астана,алматы"},{"UA","ukraine,украин,kyiv,kiev,киев"},{"MD","moldova,молд"},{"AM","armenia,армени,ереван,yerevan"},{"GE","georgia,грузи,tbilisi,тбилиси"},{"CA","canada,канад,toronto,торонто"},{"IT","italy,итали,rome,milan,рим,милан"},{"ES","spain,испан,madrid,мадрид"}};for(String[] row:map)if(has(l,row[1]))return countryName(row[0]);return "";}
    private static String countryCodeToken(String text){if(text==null)return "";HashSet<String> all=new HashSet<>(Arrays.asList(Locale.getISOCountries()));Matcher m=Pattern.compile("(^|[^A-Za-z])([A-Z]{2})([^A-Za-z]|$)").matcher(text);while(m.find()){String c=m.group(2);if(all.contains(c))return c;}return "";}
    private static boolean has(String l,String csv){for(String x:csv.split(","))if(!x.isEmpty()&&l.contains(x))return true;return false;}
    private static String flagCode(String text){if(text==null)return "";int first=-1;for(int i=0;i<text.length();){int cp=text.codePointAt(i);if(cp>=0x1F1E6&&cp<=0x1F1FF){if(first<0)first=cp;else{return ""+(char)('A'+first-0x1F1E6)+(char)('A'+cp-0x1F1E6);}}else first=-1;i+=Character.charCount(cp);}return "";}
    private static String countryName(String code){try{String s=new Locale("",code).getDisplayCountry(new Locale("ru"));return s==null||s.isEmpty()?code:s;}catch(Exception e){return code;}}
    private static String id(String raw)throws Exception{MessageDigest md=MessageDigest.getInstance("SHA-256");byte[] b=md.digest(raw.getBytes(StandardCharsets.UTF_8));StringBuilder sb=new StringBuilder();for(int i=0;i<8;i++)sb.append(String.format(Locale.ROOT,"%02x",b[i]));return sb.toString();}
    static final class Parts {final String user,host,query,fragment,path;final int port;Parts(String user,String host,int port,String query,String fragment,String path){this.user=user;this.host=host;this.port=port;this.query=query;this.fragment=fragment;this.path=path;}}
}
