package app.yoru.mobile;

import org.json.*;
import java.util.*;

final class YoruBrain {
    private YoruBrain(){}
    static String title(Anime a){if(a==null)return "Аниме";try{if(YoruApp.app()!=null&&YoruApp.app().store.originalTitles()&&!a.original.isEmpty())return a.original;}catch(Exception ignored){}return a.title;}
    static boolean visible(Anime a){if(!Anime.valid(a))return false;SecureStore s=YoruApp.app().store;if(s.hidden(a))return false;if(s.safeMode()&&(a.age.contains("18")||text(a).contains("эрот")))return false;if(s.hideSeen()&&"completed".equals(s.bucket(a)))return false;return true;}
    static ArrayList<Anime> visible(Collection<Anime> rows){LinkedHashMap<String,Anime> out=new LinkedHashMap<>();if(rows!=null)for(Anime a:rows)if(visible(a))out.put(a.key(),a);return new ArrayList<>(out.values());}
    static ArrayList<Anime> shelf(String kind,int max){SecureStore store=YoruApp.app().store;ArrayList<Anime> base=new ArrayList<>();base.addAll(YoruApp.app().api.seed());base.addAll(store.favorites());base.addAll(store.recent());ArrayList<Anime> out=new ArrayList<>();for(Anime a:visible(base)){String t=text(a);boolean ok=false;if("forYou".equals(kind))ok=taste(a)>0;if("short".equals(kind))ok=a.episodes>0&&a.episodes<=13||a.type.toLowerCase(Locale.ROOT).contains("фильм");if("movies".equals(kind))ok=a.type.toLowerCase(Locale.ROOT).contains("фильм");if("ongoing".equals(kind))ok="ongoing".equals(a.status)||"anons".equals(a.status);if("classics".equals(kind))ok=a.year>0&&a.year<2015&&a.score>=7;if("gems".equals(kind))ok=a.score>=7.5&&!store.favorite(a);if("pinned".equals(kind))ok=store.pinned(a);if("rewatch".equals(kind))ok=store.rewatch(a)>0||"completed".equals(store.bucket(a));if("romance".equals(kind))ok=t.contains("роман");if("action".equals(kind))ok=t.contains("экшен")||t.contains("приключ");if("calm".equals(kind))ok=t.contains("повсед")||t.contains("комед")||t.contains("слайс");if(ok)out.add(a);}out.sort((a,b)->Integer.compare(score(b,kind),score(a,kind)));return limit(unique(out),max);}
    static ArrayList<Anime> similar(Anime source,int max){ArrayList<Anime> out=new ArrayList<>();if(source==null)return out;for(Anime a:visible(YoruApp.app().api.seed())){if(a.key().equals(source.key()))continue;int s=0;if(!source.studio.isEmpty()&&source.studio.equalsIgnoreCase(a.studio))s+=6;if(source.year>0&&Math.abs(source.year-a.year)<=2)s++;for(String g:source.genres)if(a.genres.contains(g))s+=2;if(s>0)out.add(a);}out.sort((a,b)->Integer.compare(simScore(source,b),simScore(source,a)));return limit(unique(out),max);}
    static Anime surprise(){ArrayList<Anime> rows=shelf("forYou",50);if(rows.isEmpty())rows=visible(YoruApp.app().api.seed());if(rows.isEmpty())return null;return rows.get(new Random().nextInt(rows.size()));}
    static String dashboard(){JSONObject s=YoruApp.app().store.stats();int today=s.optInt("today"),goal=s.optInt("goal"),streak=s.optInt("streak"),queue=s.optInt("queue");String pace=today>=goal?"цель дня выполнена":"до цели дня: "+Math.max(0,goal-today);return "Сегодня: "+today+" / "+goal+" · "+pace+"\nСерия дней: "+streak+" · в плане: "+queue+" · в коллекции: "+s.optInt("favorites");}
    static String[] achievements(){JSONObject s=YoruApp.app().store.stats();ArrayList<String> rows=new ArrayList<>();add(rows,s.optInt("titles")>=1,"Первый тайтл","Начните историю просмотра");add(rows,s.optInt("episodes")>=10,"10 серий","Отметьте 10 серий");add(rows,s.optInt("episodes")>=50,"50 серий","Отметьте 50 серий");add(rows,s.optInt("episodes")>=100,"100 серий","Отметьте 100 серий");add(rows,s.optInt("finished")>=1,"Финалист","Завершите первый тайтл");add(rows,s.optInt("favorites")>=5,"Коллекционер","Добавьте 5 тайтлов в коллекцию");add(rows,s.optInt("queue")>=3,"Планировщик","Добавьте 3 тайтла в план");add(rows,s.optInt("streak")>=3,"Серия дней","Смотрите 3 дня подряд");add(rows,s.optInt("today")>=s.optInt("goal",3),"Цель дня","Выполните дневную цель");add(rows,s.optInt("ratings")>=3,"Критик","Поставьте 3 личные оценки");add(rows,s.optInt("pins")>=1,"Закреплено","Закрепите любимый тайтл");add(rows,s.optInt("rewatches")>=1,"Пересмотр","Отметьте пересмотр");return rows.toArray(new String[0]);}
    static String chip(Anime a){SecureStore s=YoruApp.app().store;if(s.pinned(a))return "Закреплено";int r=s.rating(a);if(r>0)return "Ваша оценка "+r+"/10";if(s.rewatch(a)>0)return "Пересмотр · "+s.rewatch(a);JSONObject h=s.progress(a);if(h.length()>0)return "Продолжить · серия "+Ui.number(h.optDouble("episode",1));if(s.favorite(a))return "В коллекции";if("ongoing".equals(a.status))return "Онгоинг";return ApiRepository.sourceNames.get(a.source);}
    static String personalLine(Anime a){SecureStore s=YoruApp.app().store;ArrayList<String> rows=new ArrayList<>();int r=s.rating(a);if(r>0)rows.add("оценка "+r+"/10");String tags=s.tags(a);if(!tags.isEmpty())rows.add(tags);int rw=s.rewatch(a);if(rw>0)rows.add("пересмотров: "+rw);return rows.isEmpty()?"":String.join(" · ",rows);}
    static String commandCenter(){JSONObject s=YoruApp.app().store.stats();int goal=Math.max(1,s.optInt("goal",3)),today=s.optInt("today"),queue=s.optInt("queue"),hidden=s.optInt("hidden"),pins=s.optInt("pins");String focus=today>=goal?"можно выбирать без спешки":"лучше продолжить короткий эпизод";return "Фокус дня: "+focus+".\nЦель: "+today+" / "+goal+" · план: "+queue+" · закреплено: "+pins+(hidden>0?" · скрыто: "+hidden:"");}
    static ArrayList<Anime> priorities(int max){LinkedHashMap<String,Anime> rows=new LinkedHashMap<>();for(Anime a:YoruApp.app().store.watchQueue())if(visible(a))rows.put(a.key(),a);for(Anime a:YoruApp.app().store.recent())if(visible(a))rows.put(a.key(),a);for(Anime a:YoruApp.app().store.favorites())if(visible(a))rows.put(a.key(),a);ArrayList<Anime> out=new ArrayList<>(rows.values());out.sort((a,b)->Integer.compare(priorityScore(b),priorityScore(a)));return limit(out,max);}
    static ArrayList<Anime> marathon(int max){ArrayList<Anime> out=new ArrayList<>();for(Anime a:visible(YoruApp.app().store.watchQueue()))if(a.episodes==0||a.episodes<=24||YoruApp.app().store.progress(a).length()>0)out.add(a);for(Anime a:shelf("short",40))if(!out.contains(a))out.add(a);out.sort((a,b)->Integer.compare(marathonScore(b),marathonScore(a)));return limit(unique(out),max);}
    static String tasteMap(){JSONObject s=YoruApp.app().store.stats();JSONArray gs=s.optJSONArray("genres");ArrayList<String> lines=new ArrayList<>();for(int i=0;gs!=null&&i<Math.min(5,gs.length());i++)lines.add((i+1)+". "+gs.optString(i));String mood=s.optInt("episodes")>=80?"уверенный марафон":s.optInt("favorites")>=8?"собранная коллекция":s.optInt("queue")>=3?"плановое настроение":"поиск вкуса";return "Профиль: "+mood+"\n"+(lines.isEmpty()?"Любимые жанры появятся после просмотра, оценок и тегов.":"Любимые жанры:\n"+String.join("\n",lines));}
    static String[] libraryDoctor(){SecureStore store=YoruApp.app().store;JSONObject s=store.stats();ArrayList<String> rows=new ArrayList<>();int queue=s.optInt("queue"),hidden=s.optInt("hidden"),ratings=s.optInt("ratings"),pins=s.optInt("pins"),today=s.optInt("today"),goal=s.optInt("goal",3);rows.add((queue==0?"○":"✓")+" План просмотра — "+(queue==0?"добавьте 2–3 тайтла, чтобы YORU строил вечер":"в плане "+queue+" тайтлов"));rows.add((ratings<3?"○":"✓")+" Оценки — "+(ratings<3?"поставьте ещё "+(3-ratings)+", чтобы рекомендации стали точнее":"личный вкус уже обучается"));rows.add((pins==0?"○":"✓")+" Закрепления — "+(pins==0?"закрепите любимое, и оно будет выше в коллекции":"главные тайтлы закреплены"));rows.add((today>=goal?"✓":"○")+" Цель дня — "+today+" / "+goal);rows.add((hidden>0?"✓":"○")+" Чистота подборок — "+(hidden>0?"скрыто "+hidden+" тайтлов":"лишнее можно скрывать из карточки"));int duplicates=duplicateCount();rows.add((duplicates==0?"✓":"○")+" Дубли — "+(duplicates==0?"явных повторов не найдено":"найдено похожих карточек: "+duplicates));int stale=staleCount();rows.add((stale==0?"✓":"○")+" Долгие паузы — "+(stale==0?"активных пауз нет":"можно вернуться к "+stale+" тайтлам"));return rows.toArray(new String[0]);}
    static ArrayList<Anime> restartList(int max){ArrayList<Anime> out=new ArrayList<>();long edge=System.currentTimeMillis()-21L*24*60*60*1000;for(Anime a:YoruApp.app().store.recent()){JSONObject h=YoruApp.app().store.progress(a);if(h.optLong("updated")>0&&h.optLong("updated")<edge&&visible(a))out.add(a);}out.sort((a,b)->Long.compare(YoruApp.app().store.progress(a).optLong("updated"),YoruApp.app().store.progress(b).optLong("updated")));return limit(unique(out),max);}
    static ArrayList<Anime> watchOrder(Anime source){ArrayList<Anime> rows=new ArrayList<>();if(source==null)return rows;rows.add(source);rows.addAll(source.related);for(Anime a:similar(source,12))if(a.year>0&&source.year>0&&Math.abs(a.year-source.year)<=8)rows.add(a);ArrayList<Anime> out=unique(rows);out.sort((a,b)->{int y=Integer.compare(a.year==0?9999:a.year,b.year==0?9999:b.year);if(y!=0)return y;return YoruBrain.title(a).compareToIgnoreCase(YoruBrain.title(b));});return limit(out,24);}
    static String nextHint(Anime a){if(a==null)return "Откройте карточку и выберите просмотр.";JSONObject h=YoruApp.app().store.progress(a);if(h.length()==0)return "Начать с первой серии";double ep=h.optDouble("episode",1);int time=h.optInt("time",0);String seen=a.episodes>0&&ep>=a.episodes?"финал отмечен":"продолжить серию "+Ui.number(ep);return seen+" · "+Ui.time(time);}
    private static int priorityScore(Anime a){SecureStore store=YoruApp.app().store;int s=score(a,"forYou");if(store.pinned(a))s+=120;if(store.watchQueue().contains(a))s+=60;JSONObject h=store.progress(a);if(h.length()>0)s+=40;if("watching".equals(store.bucket(a)))s+=35;if("ongoing".equals(a.status))s+=20;if(a.episodes>0&&a.episodes<=13)s+=12;return s;}
    private static int marathonScore(Anime a){int s=priorityScore(a);if(a.episodes>0)s+=Math.max(0,30-a.episodes);if(a.type.toLowerCase(Locale.ROOT).contains("фильм"))s+=35;return s;}
    private static int duplicateCount(){HashMap<String,Integer> seen=new HashMap<>();int dup=0;ArrayList<Anime> all=new ArrayList<>();all.addAll(YoruApp.app().store.favorites());all.addAll(YoruApp.app().store.recent());for(Anime a:all){String key=a.malId>0?"mal:"+a.malId:plainName(a.title);if(key.isEmpty())continue;int n=seen.getOrDefault(key,0)+1;seen.put(key,n);if(n==2)dup++;}return dup;}
    private static int staleCount(){long edge=System.currentTimeMillis()-21L*24*60*60*1000;int n=0;for(Anime a:YoruApp.app().store.recent()){JSONObject h=YoruApp.app().store.progress(a);if(h.optLong("updated")>0&&h.optLong("updated")<edge&&visible(a))n++;}return n;}
    private static void add(ArrayList<String> rows,boolean ok,String title,String hint){rows.add((ok?"✓ ":"○ ")+title+" — "+hint);}
    private static int score(Anime a,String kind){int s=taste(a)*3+(int)Math.round(a.score*10);if(YoruApp.app().store.favorite(a))s+=30;if(YoruApp.app().store.pinned(a))s+=80;if("short".equals(kind)&&a.episodes>0)s+=Math.max(0,20-a.episodes);if("ongoing".equals(kind)&&"ongoing".equals(a.status))s+=50;return s;}
    private static int taste(Anime a){JSONObject st=YoruApp.app().store.stats();JSONArray gs=st.optJSONArray("genres");int score=0;for(int i=0;gs!=null&&i<gs.length();i++)if(a.genres.contains(gs.optString(i)))score+=5-i;String tags=YoruApp.app().store.tags(a);if(!tags.isEmpty())score+=2;return score;}
    private static int simScore(Anime source,Anime a){int s=0;if(!source.studio.isEmpty()&&source.studio.equalsIgnoreCase(a.studio))s+=6;if(source.year>0&&Math.abs(source.year-a.year)<=2)s++;for(String g:source.genres)if(a.genres.contains(g))s+=2;return s;}
    private static String text(Anime a){return (a.title+" "+a.original+" "+a.type+" "+a.status+" "+a.age+" "+a.studio+" "+String.join(" ",a.genres)).toLowerCase(Locale.ROOT);}
    private static ArrayList<Anime> unique(Collection<Anime> in){LinkedHashMap<String,Anime> out=new LinkedHashMap<>();for(Anime a:in)if(Anime.valid(a))out.put(a.key(),a);return new ArrayList<>(out.values());}
    private static ArrayList<Anime> limit(ArrayList<Anime> rows,int max){if(rows.size()<=max)return rows;return new ArrayList<>(rows.subList(0,max));}
}
