package app.yoru.mobile;

import android.util.Base64;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

final class YoruVpnConfig {
    private YoruVpnConfig(){}
    static String build(JSONObject profile)throws Exception{String raw=profile.optString("raw");String scheme=profile.optString("scheme");JSONObject root=new JSONObject();root.put("log",new JSONObject().put("loglevel","warning"));root.put("stats",new JSONObject());root.put("policy",new JSONObject().put("system",new JSONObject().put("statsOutboundUplink",true).put("statsOutboundDownlink",true)));root.put("dns",new JSONObject().put("servers",new JSONArray().put("1.1.1.1").put("8.8.8.8")).put("queryStrategy","UseIPv4"));root.put("inbounds",inbounds());JSONArray out=new JSONArray();out.put(outbound(raw,scheme));out.put(new JSONObject().put("tag","direct").put("protocol","freedom").put("settings",new JSONObject().put("domainStrategy","UseIP")));out.put(new JSONObject().put("tag","block").put("protocol","blackhole"));out.put(new JSONObject().put("tag","dns-out").put("protocol","dns"));root.put("outbounds",out);root.put("routing",new JSONObject().put("domainStrategy","IPIfNonMatch").put("rules",new JSONArray().put(new JSONObject().put("type","field").put("port","53").put("outboundTag","dns-out"))));return root.toString();}
    private static JSONArray inbounds()throws Exception{JSONObject tun=new JSONObject();tun.put("tag","tun-in");tun.put("protocol","tun");tun.put("port",0);tun.put("settings",new JSONObject().put("name","xray0").put("mtu",1400).put("stack","gvisor"));tun.put("sniffing",new JSONObject().put("enabled",true).put("destOverride",new JSONArray().put("http").put("tls").put("quic")));return new JSONArray().put(tun);}
    private static JSONObject outbound(String raw,String scheme)throws Exception{if(scheme.equals("vmess"))return vmess(raw);if(scheme.equals("vless"))return vless(raw);if(scheme.equals("trojan"))return trojan(raw);if(scheme.equals("ss"))return shadowsocks(raw);if(scheme.equals("socks"))return socks(raw);throw new Exception("unsupported");}
    private static JSONObject vmess(String raw)throws Exception{String tmp=raw.substring("vmess://".length());String payload=(tmp.contains("#")?tmp.substring(0,tmp.indexOf('#')):tmp).trim();String decoded=YoruVpnProfile.decodeBase64(payload);if(decoded==null)throw new Exception("bad vmess");JSONObject src=new JSONObject(decoded);String host=src.optString("add");int port=intValue(src.optString("port"),443);String network=src.optString("net","tcp");String security=src.optString("tls","none");JSONObject user=new JSONObject().put("id",src.optString("id")).put("alterId",intValue(src.optString("aid"),0)).put("security",src.optString("scy","auto"));JSONObject vnext=new JSONObject().put("address",host).put("port",port).put("users",new JSONArray().put(user));JSONObject o=new JSONObject().put("tag","proxy").put("protocol","vmess").put("settings",new JSONObject().put("vnext",new JSONArray().put(vnext)));o.put("streamSettings",stream(network,security,host,src.optString("sni"),src.optString("host"),src.optString("path"),src.optString("type"),src.optString("alpn"),src.optString("fp"),"","","",false));return o;}
    private static JSONObject vless(String raw)throws Exception{YoruVpnProfile.Parts p=YoruVpnProfile.standard(raw,"vless");Map<String,String> q=YoruVpnProfile.query(p.query);String network=value(q,"type","tcp");String security=value(q,"security","none");String method=value(q,"encryption","none");JSONObject user=new JSONObject().put("id",p.user).put("encryption",method);String flow=value(q,"flow","");if(!flow.isEmpty())user.put("flow",flow);JSONObject vnext=new JSONObject().put("address",p.host).put("port",p.port).put("users",new JSONArray().put(user));JSONObject o=new JSONObject().put("tag","proxy").put("protocol","vless").put("settings",new JSONObject().put("vnext",new JSONArray().put(vnext)));o.put("streamSettings",stream(network,security,p.host,value(q,"sni",value(q,"host",p.host)),value(q,"host",""),value(q,"path",value(q,"servicename",p.path)),value(q,"headertype","none"),value(q,"alpn",""),value(q,"fp",""),value(q,"pbk",""),value(q,"sid",""),value(q,"spx",""),truth(value(q,"allowinsecure","false"))));return o;}
    private static JSONObject trojan(String raw)throws Exception{YoruVpnProfile.Parts p=YoruVpnProfile.standard(raw,"trojan");Map<String,String> q=YoruVpnProfile.query(p.query);String network=value(q,"type","tcp");String security=value(q,"security","tls");JSONObject server=new JSONObject().put("address",p.host).put("port",p.port).put("password",p.user);String flow=value(q,"flow","");if(!flow.isEmpty())server.put("flow",flow);JSONObject o=new JSONObject().put("tag","proxy").put("protocol","trojan").put("settings",new JSONObject().put("servers",new JSONArray().put(server)));o.put("streamSettings",stream(network,security,p.host,value(q,"sni",value(q,"peer",p.host)),value(q,"host",""),value(q,"path",value(q,"servicename",p.path)),"none",value(q,"alpn",""),value(q,"fp",""),value(q,"pbk",""),value(q,"sid",""),value(q,"spx",""),truth(value(q,"allowinsecure","false"))));return o;}
    private static JSONObject shadowsocks(String raw)throws Exception{String body=raw.substring("ss://".length());String main=body.contains("#")?body.substring(0,body.indexOf('#')):body;String query="";int qi=main.indexOf('?');if(qi>=0){query=main.substring(qi+1);main=main.substring(0,qi);}String method,password,host;int port;if(main.contains("@")){String user=main.substring(0,main.lastIndexOf('@'));String hostPort=main.substring(main.lastIndexOf('@')+1);String creds=YoruVpnProfile.decodeBase64Any(user);if(creds==null)creds=YoruVpnProfile.decode(user);method=before(creds,':');password=creds.contains(":")?creds.substring(creds.indexOf(':')+1):"";HostPort hp=hostPort(hostPort,8388);host=hp.host;port=hp.port;}else{String decoded=YoruVpnProfile.decodeBase64Any(main);if(decoded==null)throw new Exception("bad ss");method=before(decoded,':');String rest=decoded.contains(":")?decoded.substring(decoded.indexOf(':')+1):"";password=before(rest,'@');HostPort hp=hostPort(rest.contains("@")?rest.substring(rest.lastIndexOf('@')+1):"",8388);host=hp.host;port=hp.port;}JSONObject server=new JSONObject().put("address",host).put("port",port).put("method",method).put("password",password);return new JSONObject().put("tag","proxy").put("protocol","shadowsocks").put("settings",new JSONObject().put("servers",new JSONArray().put(server))).put("streamSettings",new JSONObject().put("network","tcp"));}
    private static JSONObject socks(String raw)throws Exception{YoruVpnProfile.Parts p=YoruVpnProfile.standard(raw,"socks");String user="",pass="";if(p.user.contains(":")){user=p.user.substring(0,p.user.indexOf(':'));pass=p.user.substring(p.user.indexOf(':')+1);}JSONObject s=new JSONObject().put("address",p.host).put("port",p.port);if(!user.isEmpty())s.put("users",new JSONArray().put(new JSONObject().put("user",user).put("pass",pass)));return new JSONObject().put("tag","proxy").put("protocol","socks").put("settings",new JSONObject().put("servers",new JSONArray().put(s))).put("streamSettings",new JSONObject().put("network","tcp"));}
    private static JSONObject stream(String network,String security,String host,String sni,String requestHost,String path,String header,String alpn,String fp,String pbk,String sid,String spx,boolean insecure)throws Exception{network=network==null||network.isEmpty()?"tcp":network.toLowerCase(Locale.ROOT);security=security==null||security.isEmpty()?"none":security.toLowerCase(Locale.ROOT);JSONObject st=new JSONObject().put("network",network);if(!security.equals("none")){st.put("security",security);if(security.equals("reality")){JSONObject r=new JSONObject().put("serverName",empty(sni)?host:sni).put("publicKey",pbk);if(!fp.isEmpty())r.put("fingerprint",fp);if(!sid.isEmpty())r.put("shortId",sid);if(!spx.isEmpty())r.put("spiderX",spx);st.put("realitySettings",r);}else{JSONObject t=new JSONObject().put("serverName",empty(sni)?host:sni).put("allowInsecure",insecure);if(!fp.isEmpty())t.put("fingerprint",fp);JSONArray a=alpn(alpn);if(a.length()>0)t.put("alpn",a);st.put("tlsSettings",t);}}if(network.equals("ws")){JSONObject ws=new JSONObject();ws.put("path",empty(path)?"/":path);if(!requestHost.isEmpty())ws.put("headers",new JSONObject().put("Host",requestHost));st.put("wsSettings",ws);}else if(network.equals("grpc")){st.put("grpcSettings",new JSONObject().put("serviceName",empty(path)?"":path));}else if(network.equals("h2")||network.equals("http")){JSONObject h=new JSONObject();if(!requestHost.isEmpty())h.put("host",new JSONArray().put(requestHost));if(!path.isEmpty())h.put("path",path);st.put("httpSettings",h);}else if(network.equals("xhttp")||network.equals("httpupgrade")){JSONObject x=new JSONObject();if(!path.isEmpty())x.put("path",path);if(!requestHost.isEmpty())x.put("host",requestHost);st.put(network.equals("xhttp")?"xhttpSettings":"httpupgradeSettings",x);}else if(network.equals("tcp")&&!header.equals("none")){st.put("tcpSettings",new JSONObject().put("header",new JSONObject().put("type",header)));}return st;}
    private static JSONArray alpn(String s){JSONArray a=new JSONArray();if(s==null)return a;for(String p:s.split(",")){String v=p.trim();if(!v.isEmpty())a.put(v);}return a;}
    private static boolean truth(String s){return "1".equals(s)||"true".equalsIgnoreCase(s)||"yes".equalsIgnoreCase(s);}
    private static String value(Map<String,String> m,String key,String def){String v=m.get(key.toLowerCase(Locale.ROOT));return v==null||v.isEmpty()?def:v;}
    private static int intValue(String s,int def){try{return Integer.parseInt(s.trim());}catch(Exception e){return def;}}
    private static boolean empty(String s){return s==null||s.isEmpty();}
    private static String before(String s,char c){int i=s.indexOf(c);return i<0?s:s.substring(0,i);}
    private static HostPort hostPort(String value,int def){String h=value;int p=def;if(value.startsWith("[")){int end=value.indexOf(']');if(end>0){h=value.substring(1,end);String rest=value.substring(end+1);if(rest.startsWith(":"))p=intValue(rest.substring(1),def);}}else{int colon=value.lastIndexOf(':');if(colon>0){h=value.substring(0,colon);p=intValue(value.substring(colon+1),def);}}return new HostPort(YoruVpnProfile.decode(h),p);}
    private static final class HostPort {final String host;final int port;HostPort(String h,int p){host=h;port=p;}}
}
