package app.yoru.mobile;

import android.app.*;
import android.widget.*;
import org.json.*;
import java.util.*;

final class YoruNexus {
    private static final String[] PLAY={"yoru","yummy","anilibria","animevost","animelib","animelib4k","animedia","animetka","anidub","anijoy","kodik"};
    private static final String[] DISCOVER={"anilibria","animevost","animelib","animelib4k","animedia","animetka","anidub","anijoy","kodik"};
    private static final HashMap<String,Integer> BASE=new HashMap<>();
    static {BASE.put("yoru",105);BASE.put("yummy",100);BASE.put("anilibria",92);BASE.put("animevost",86);BASE.put("animelib4k",82);BASE.put("animelib",78);BASE.put("animedia",70);BASE.put("animetka",66);BASE.put("anidub",62);BASE.put("anijoy",64);BASE.put("kodik",58);}
    private static boolean playable(String s){return s!=null&&Arrays.asList(PLAY).contains(s);}
    private static JSONObject snapshot(){YoruApp app=YoruApp.app();return app==null||app.store==null?new JSONObject():app.store.nexusSnapshot();}
    static ArrayList<String> playbackOrder(Anime input){LinkedHashSet<String> set=new LinkedHashSet<>();if(input!=null&&playable(input.source)&&!input.metadataOnly())set.add(input.source);ArrayList<String> pool=new ArrayList<>(Arrays.asList(PLAY));pool.sort((a,b)->score(b,input)-score(a,input));for(String s:pool)if(!set.contains(s))set.add(s);return new ArrayList<>(set);}
    static ArrayList<String> discoveryOrder(Anime original,Anime shell){ArrayList<String> pool=new ArrayList<>(Arrays.asList(DISCOVER));Anime base=shell==null?original:shell;pool.sort((a,b)->score(b,base)-score(a,base));if(pool.size()>9)return new ArrayList<>(pool.subList(0,9));return pool;}
    static int score(String source,Anime input){String s=sourceId(source);int v=BASE.containsKey(s)?BASE.get(s):45;JSONObject row=snapshot().optJSONObject(s);if(row!=null){int ok=row.optInt("ok"),fail=row.optInt("fail"),total=ok+fail;if(total>0)v+=(ok*44/Math.max(1,total))-Math.min(36,fail*7);long avg=row.optLong("avg",0);if(avg>0)v-=Math.min(28,(int)(avg/850));if(row.optLong("lastBad",0)>System.currentTimeMillis()-20*60*1000)v-=22;int streak=row.optInt("streak",0);if(streak>=2)v-=Math.min(70,streak*18);if(total>=5&&fail>ok)v-=Math.min(48,(fail-ok)*9);v+=Math.min(16,row.optInt("quality",0)/120);v+=Math.min(14,row.optInt("variants",0));}if(input!=null){if(s.equals(input.source))v+=20;if(input.libriaAlias!=null&&!input.libriaAlias.isEmpty()&&s.equals("anilibria"))v+=18;if(input.malId>0&&(s.equals("yummy")||s.equals("kodik")||s.equals("yoru")))v+=12;if(input.kpId>0&&s.equals("kodik"))v+=10;if(input.episodes>0&&input.episodes<=2&&(s.equals("kodik")||s.equals("animelib")||s.equals("anijoy")))v+=5;}YoruApp app=YoruApp.app();if(app!=null&&app.savingMobile()&&(s.equals("kodik")||s.equals("animetka")||s.equals("anidub")||s.equals("anijoy")))v-=8;return v;}
    static void record(String source,boolean ok,long ms,int episodes,int variants,int quality){YoruApp app=YoruApp.app();if(app!=null&&app.store!=null)app.store.nexusEvent(sourceId(source),ok,Math.max(0,ms),Math.max(0,episodes),Math.max(0,variants),Math.max(0,quality));}
    static void recordVariant(Anime.Variant v,boolean ok,long ms,int quality){record(variantSource(v),ok,ms,0,ok?1:0,quality);}
    static int optionCount(Anime a){int n=0;if(a!=null)for(Anime.Episode e:a.episodeList)n+=Math.min(40,e.streams.size()+e.variants.size());return n;}
    static int maxQuality(Anime a){int q=0;if(a!=null)for(Anime.Episode e:a.episodeList)for(Integer k:e.streams.keySet())if(k!=null)q=Math.max(q,k);return q;}
    static ArrayList<Anime.Variant> sortVariants(Collection<Anime.Variant> rows){ArrayList<Anime.Variant> out=new ArrayList<>();if(rows!=null)for(Anime.Variant v:rows)if(v!=null)out.add(v);out.sort((a,b)->variantRank(a)-variantRank(b));return out;}
    static int variantRank(Anime.Variant v){String src=variantSource(v);int rank=1000-score(src,null);String text=((v==null?"":v.name)+" "+(v==null?"":v.player)+" "+(v==null?"":v.displayName)).toLowerCase(Locale.ROOT);String pref="";try{pref=YoruApp.app().store.voicePreference().toLowerCase(Locale.ROOT);}catch(Exception ignored){}if(!pref.isEmpty()&&(text.contains(pref)||pref.contains(text.trim())))rank-=60;if(text.contains("1080"))rank-=14;else if(text.contains("720"))rank-=10;else if(text.contains("480"))rank-=3;if(text.contains("субтит")||text.contains("sub"))rank+=8;if(text.contains("трейлер")||text.contains("анонс"))rank+=30;return rank;}
    static ArrayList<Anime> mergeCatalog(Collection<Anime> rows,int limit){LinkedHashMap<String,Anime> map=new LinkedHashMap<>();if(rows!=null)for(Anime a:rows){if(!Anime.valid(a))continue;String key=identity(a);Anime old=map.get(key);if(old==null){for(Map.Entry<String,Anime> e:map.entrySet())if(sameTitle(e.getValue(),a)){key=e.getKey();old=e.getValue();break;}}if(old==null)map.put(key,a);else{Anime chosen=best(old,a),extra=chosen==old?a:old;absorb(chosen,extra);map.put(key,chosen);}}ArrayList<Anime> out=new ArrayList<>(map.values());out.sort((a,b)->{int p=score(b.source,b)-score(a.source,a);if(p!=0)return p;return Double.compare(b.score,a.score);});if(limit>0&&out.size()>limit)return new ArrayList<>(out.subList(0,limit));return out;}
    private static Anime best(Anime a,Anime b){int as=score(a.source,a)+(a.poster.isEmpty()?0:8)+(a.description.isEmpty()?0:6)+(a.episodeList.isEmpty()?0:10);int bs=score(b.source,b)+(b.poster.isEmpty()?0:8)+(b.description.isEmpty()?0:6)+(b.episodeList.isEmpty()?0:10);return bs>as?b:a;}
    private static boolean sameTitle(Anime a,Anime b){if(a==null||b==null)return false;if(a.malId>0&&b.malId>0&&a.malId==b.malId)return true;if(a.anilistId>0&&b.anilistId>0&&a.anilistId==b.anilistId)return true;if(a.kpId>0&&b.kpId>0&&a.kpId==b.kpId)return true;String at=ApiRepository.plainName(a.title),ao=ApiRepository.plainName(a.original),bt=ApiRepository.plainName(b.title),bo=ApiRepository.plainName(b.original);boolean name=(!at.isEmpty()&&(at.equals(bt)||at.equals(bo)))||(!ao.isEmpty()&&(ao.equals(bt)||ao.equals(bo)));boolean year=a.year==0||b.year==0||Math.abs(a.year-b.year)<=1;return name&&year;}
    static void absorb(Anime target,Anime source){if(target==null||source==null)return;if(target.title.isEmpty())target.title=source.title;if(target.original.isEmpty())target.original=source.original;if(target.alias.isEmpty())target.alias=source.alias;if(target.poster.isEmpty())target.poster=source.poster;if(target.description.isEmpty())target.description=source.description;if(target.year==0)target.year=source.year;if(target.type.isEmpty()||"Аниме".equals(target.type))target.type=source.type;if(target.status.isEmpty())target.status=source.status;if(target.age.isEmpty())target.age=source.age;if(target.studio.isEmpty())target.studio=source.studio;if(target.episodes==0)target.episodes=source.episodes;if(target.malId==0)target.malId=source.malId;if(target.anilistId==0)target.anilistId=source.anilistId;if(target.kpId==0)target.kpId=source.kpId;if(target.libriaAlias.isEmpty())target.libriaAlias=source.libriaAlias;if(target.score==0)target.score=source.score;if(target.blocked&& !source.blocked)target.blocked=false;for(String g:source.genres)if(g!=null&&!g.isEmpty()&&!target.genres.contains(g)&&target.genres.size()<30)target.genres.add(g);for(Anime r:source.related)if(Anime.valid(r)&&target.related.size()<24)target.related.add(r);}
    static String identity(Anime a){if(a==null)return "";if(a.malId>0)return "mal:"+a.malId;if(a.anilistId>0)return "ani:"+a.anilistId;if(a.kpId>0)return "kp:"+a.kpId;String n=ApiRepository.plainName((a.original.isEmpty()?a.title:a.original));if(n.isEmpty())n=ApiRepository.plainName(a.title);return n+":"+(a.year>0?a.year:0);}
    static String variantSource(Anime.Variant v){String text=((v==null?"":v.name)+" "+(v==null?"":v.player)+" "+(v==null?"":v.displayName)).toLowerCase(Locale.ROOT);return sourceId(text);}
    static String sourceId(String value){String v=value==null?"":value.trim().toLowerCase(Locale.ROOT);if(v.isEmpty())return "yoru";if(v.contains("yoru max")||v.contains("yummy")||v.contains("yani")||v.contains("cvh")||v.contains("cdnvideohub"))return "yummy";if(v.contains("yoru prime")||v.contains("kodik")||v.contains("aniqit"))return "kodik";if(v.contains("anilibria")||v.contains("aniliberty"))return "anilibria";if(v.contains("animevost"))return "animevost";if(v.contains("animelib ultra")||v.contains("animelib4k"))return "animelib4k";if(v.contains("animelib")||v.contains("anilib"))return "animelib";if(v.contains("animedia"))return "animedia";if(v.contains("animetka"))return "animetka";if(v.contains("anidub"))return "anidub";if(v.contains("anijoy"))return "anijoy";if(v.contains("yoru"))return "yoru";return v.replaceAll("[^a-z0-9_]+","");}
    static String homeLine(){JSONObject s=snapshot();int ok=0,fail=0,best=0;String leader="YORU";Iterator<String> it=s.keys();while(it.hasNext()){String k=it.next();JSONObject r=s.optJSONObject(k);if(r==null)continue;ok+=r.optInt("ok");fail+=r.optInt("fail");int score=score(k,null);if(score>best){best=score;leader=label(k);}}if(ok+fail==0)return "Nexus готовит единую связку каталогов, серий, озвучек и качества. Чем больше вы смотрите, тем точнее автоподбор.";return "Nexus обучился на "+(ok+fail)+" запусках: сейчас выше всего доверие к «"+leader+"», неудачные варианты отодвигаются сами.";}
    static String cardLine(Anime a){String src=label(a==null?"yoru":a.source);int variants=optionCount(a);String line="Nexus объединяет карточку, серии и варианты просмотра в один запуск.";if(variants>0)line+=" Уже собрано вариантов: "+variants+".";else line+=" Если текущая карточка пустая, YORU попробует собрать её через другие каталоги.";return line+" Текущий вход: "+src+".";}
    static ArrayList<Anime> airQueue(int limit){LinkedHashMap<String,Anime> map=new LinkedHashMap<>();YoruApp app=YoruApp.app();if(app==null||app.store==null||app.api==null)return new ArrayList<>();add(map,app.store.watchQueue());add(map,YoruBrain.priorities(24));add(map,app.store.recent());add(map,app.store.favorites());add(map,YoruBrain.shelf("forYou",24));add(map,YoruBrain.shelf("gems",16));add(map,YoruBrain.shelf("classics",16));add(map,app.api.seed());ArrayList<Anime> out=new ArrayList<>();for(Anime a:map.values())if(YoruBrain.visible(a))out.add(a);out.sort((a,b)->airScore(b)-airScore(a));if(limit>0&&out.size()>limit)return new ArrayList<>(out.subList(0,limit));return out;}
    private static void add(LinkedHashMap<String,Anime> map,Collection<Anime> rows){if(rows==null)return;for(Anime a:rows)if(Anime.valid(a)&&!map.containsKey(identity(a)))map.put(identity(a),a);}
    private static int airScore(Anime a){YoruApp app=YoruApp.app();int v=(int)Math.round(a.score*12)+score(a.source,a);JSONObject h=app.store.progress(a);if(h.length()>0){v+=70;double ep=h.optDouble("episode",1);if(a.episodes>0)v+=Math.max(0,45-(int)Math.abs(a.episodes-ep)*3);long age=System.currentTimeMillis()-h.optLong("updated",0);v-=Math.min(28,(int)(age/(1000L*60*60*24*14)));}if(app.store.pinned(a))v+=40;if(app.store.favorite(a))v+=28;if(a.episodes>0&&a.episodes<=13)v+=8;if("ongoing".equalsIgnoreCase(a.status))v+=10;if(app.store.hidden(a))v-=200;return v;}
    static void startAir(Activity a,ArrayList<Anime> queue){if(queue==null||queue.isEmpty()){Ui.toast(a,"Nexus пока не собрал эфир");return;}YoruApp.app().store.replaceWatchQueue(queue);Anime first=queue.get(0);JSONObject h=YoruApp.app().store.progress(first);Ui.toast(a,"Эфир YORU запущен");Ui.openPlayer(a,first,"yoru",h.optDouble("episode",1));}
    static void showAir(Activity a){ArrayList<Anime> rows=airQueue(18);ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,470)));col.addView(Ui.text(a,"Эфир строит непрерывный маршрут: начатое, любимое, закреплённое, короткое и сильные рекомендации. После финальной серии YORU сам перейдёт к следующей истории из плана.",12,Ui.MUTED,false));Ui.space(col,12);if(rows.isEmpty())col.addView(Ui.text(a,"Откройте несколько карточек или добавьте тайтлы в коллекцию — Nexus соберёт эфир автоматически.",12,Ui.MUTED,false));else for(Anime anime:rows.subList(0,Math.min(12,rows.size())))line(a,col,anime,YoruBrain.nextHint(anime));Ui.custom(a,"Эфир YORU",sc,"Запустить",()->startAir(a,rows),"Nexus",()->showPanel(a),"Отмена");}
    static void showPanel(Activity a){ScrollView sc=new ScrollView(a);LinearLayout col=Ui.column(a);col.setPadding(Ui.dp(a,2),0,Ui.dp(a,2),0);sc.addView(col);sc.setLayoutParams(new LinearLayout.LayoutParams(-1,Ui.dp(a,470)));TextView intro=Ui.text(a,homeLine(),13,Ui.MUTED,false);intro.setLineSpacing(Ui.dp(a,5),1);col.addView(intro);Ui.space(col,14);ArrayList<String> order=playbackOrder(null);for(int i=0;i<Math.min(6,order.size());i++){String s=order.get(i);metric(a,col,(i+1)+". "+label(s),qualityLine(s));}Ui.space(col,8);col.addView(Ui.text(a,"Nexus работает локально: запоминает удачные запуски, отодвигает слабые варианты, собирает единые карточки и строит непрерывный эфир без лишних действий.",11,Ui.MUTED,false));Ui.custom(a,"YORU Nexus",sc,"Эфир",()->showAir(a),"Сбросить обучение",()->{YoruApp.app().store.nexusClear();Ui.toast(a,"Nexus начнёт обучение заново");},"Готово");}
    private static String qualityLine(String s){JSONObject r=snapshot().optJSONObject(s);if(r==null)return "Готов к проверке";int ok=r.optInt("ok"),fail=r.optInt("fail"),q=r.optInt("quality"),variants=r.optInt("variants");String line=ok+" удачно"+(fail>0?", "+fail+" заменено":"");if(r.optInt("streak",0)>=3)line+=" · ждёт восстановления";if(q>0)line+=" · до "+q+"p";if(variants>0)line+=" · вариантов: "+variants;return line;}
    private static String label(String source){String id=sourceId(source),name=ApiRepository.downloadSourceName(id);return name.equals(id)?"YORU Link":name;}
    private static void metric(Activity a,LinearLayout host,String label,String value){LinearLayout row=Ui.row(a);row.setPadding(Ui.dp(a,13),Ui.dp(a,11),Ui.dp(a,13),Ui.dp(a,11));row.setBackground(Ui.stroke(Ui.CARD,13,a));LinearLayout words=Ui.column(a);words.addView(Ui.text(a,label,12,Ui.TEXT,true));Ui.space(words,5);words.addView(Ui.text(a,value,10,Ui.MUTED,false));row.addView(words,new LinearLayout.LayoutParams(0,-2,1));host.addView(row,Ui.lp(a,-1,-2));Ui.space(host,8);}
    private static void line(Activity a,LinearLayout col,Anime anime,String subtitle){LinearLayout row=Ui.row(a);row.setPadding(Ui.dp(a,12),Ui.dp(a,10),Ui.dp(a,12),Ui.dp(a,10));row.setBackground(Ui.stroke(Ui.CARD,13,a));LinearLayout words=Ui.column(a);words.addView(Ui.text(a,YoruBrain.title(anime),13,Ui.TEXT,true));Ui.space(words,5);words.addView(Ui.text(a,subtitle==null||subtitle.isEmpty()?anime.meta():subtitle,10,Ui.MUTED,false));row.addView(words,new LinearLayout.LayoutParams(0,-2,1));Ui.Icon icon=new Ui.Icon(a,"play");icon.color=Ui.PURPLE;row.addView(icon,Ui.lp(a,22,22));Ui.press(row);row.setOnClickListener(v->Ui.openDetails(a,anime));col.addView(row,Ui.lp(a,-1,-2));Ui.space(col,7);}
}
