package app.yoru.mobile;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.*;
import android.net.VpnService;
import android.os.*;
import android.text.InputType;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.util.*;

final class YoruVpn {
    static final int REQ_VPN=5401;
    private static String pending;
    private YoruVpn(){}
    static void open(Activity a){ArrayList<String> items=new ArrayList<>();items.add("Вставить подписку и обновить локации");items.add("Выбрать локацию");items.add("Режим: "+modeLabel(YoruApp.app().store.vpnMode()));items.add("Приложения через VPN");items.add(YoruVpnService.active()?"Отключить":"Подключить");items.add("Статус VPN");new AlertDialog.Builder(a).setTitle("YORU · встроенный VPN").setItems(items.toArray(new String[0]),(d,i)->{String x=items.get(i);if(x.startsWith("Вставить"))subscription(a);else if(x.startsWith("Выбрать"))locations(a);else if(x.startsWith("Режим"))mode(a);else if(x.startsWith("Приложения"))apps(a);else if(x.equals("Подключить"))connect(a);else if(x.equals("Отключить"))disconnect(a);else status(a);}).setMessage("Подписка распаковывается на локации прямо на устройстве. По умолчанию выбран режим только для YORU.").setNegativeButton("Закрыть",null).show();}

    static void refreshInline(Activity a,String url,Runnable done){if(url.isEmpty()){Ui.toast(a,"Вставьте ссылку подписки");return;}ProgressDialog wait=new ProgressDialog(a);wait.setMessage("Загружаем VPN подписку…");wait.setCancelable(false);wait.show();YoruApp.app().io.execute(()->{try{String body=download(url);JSONArray list=YoruVpnProfile.parseSubscription(body);if(list.length()==0)throw new IOException("empty");YoruApp.app().store.vpnSubscriptionUrl(url);YoruApp.app().store.vpnProfiles(list);JSONObject first=list.optJSONObject(0);if(first!=null&&YoruApp.app().store.vpnSelected().isEmpty())YoruApp.app().store.vpnSelected(first.optString("id"));YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Локаций найдено: "+list.length());if(done!=null)done.run();});}catch(Exception e){YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Не удалось распаковать VPN подписку");if(done!=null)done.run();});}});}
    static void afterPermission(Activity a,int code){if(code==Activity.RESULT_OK&&pending!=null)start(a,pending);else Ui.toast(a,"VPN-разрешение не выдано");pending=null;}
    private static void subscription(Activity a){EditText input=new EditText(a);input.setSingleLine(false);input.setMinLines(2);input.setTextColor(Ui.TEXT);input.setHintTextColor(Ui.MUTED);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);input.setText(YoruApp.app().store.vpnSubscriptionUrl());input.setHint("https://...");input.setPadding(Ui.dp(a,16),Ui.dp(a,12),Ui.dp(a,16),Ui.dp(a,12));input.setBackground(Ui.stroke(Ui.CARD,12,a));new AlertDialog.Builder(a).setTitle("VPN подписка").setMessage("Вставьте ссылку подписки. Она хранится только на устройстве в зашифрованном хранилище приложения.").setView(input).setPositiveButton("Обновить",(d,w)->refresh(a,input.getText().toString().trim())).setNegativeButton("Отмена",null).show();}
    static void refresh(Activity a,String url){if(url.isEmpty()){Ui.toast(a,"Вставьте ссылку подписки");return;}ProgressDialog wait=new ProgressDialog(a);wait.setMessage("Загружаем VPN подписку…");wait.setCancelable(false);wait.show();YoruApp.app().io.execute(()->{try{String body=download(url);JSONArray list=YoruVpnProfile.parseSubscription(body);if(list.length()==0)throw new IOException("empty");YoruApp.app().store.vpnSubscriptionUrl(url);YoruApp.app().store.vpnProfiles(list);JSONObject first=list.optJSONObject(0);if(first!=null&&YoruApp.app().store.vpnSelected().isEmpty())YoruApp.app().store.vpnSelected(first.optString("id"));YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Локаций найдено: "+list.length());locations(a);});}catch(Exception e){YoruApp.app().main.post(()->{if(dead(a))return;wait.dismiss();Ui.toast(a,"Не удалось распаковать VPN подписку");});}});}
    static void locations(Activity a){JSONArray list=YoruApp.app().store.vpnProfiles();if(list.length()==0){Ui.toast(a,"Сначала обновите подписку");return;}String[] names=new String[list.length()];int selected=0;String id=YoruApp.app().store.vpnSelected();for(int i=0;i<list.length();i++){JSONObject p=list.optJSONObject(i);names[i]=p==null?"VPN":YoruVpnProfile.label(p);if(p!=null&&p.optString("id").equals(id))selected=i;}new AlertDialog.Builder(a).setTitle("VPN локация").setSingleChoiceItems(names,selected,(d,which)->{JSONObject p=list.optJSONObject(which);if(p!=null){YoruApp.app().store.vpnSelected(p.optString("id"));Ui.toast(a,"Выбрано: "+p.optString("name"));}d.dismiss();}).setNegativeButton("Закрыть",null).show();}
    static void mode(Activity a){String[] labels={"Только YORU","Выбранные приложения","Все приложения"};String[] values={"self","selected","all"};String cur=YoruApp.app().store.vpnMode();int checked=0;for(int i=0;i<values.length;i++)if(values[i].equals(cur))checked=i;new AlertDialog.Builder(a).setTitle("Режим VPN").setSingleChoiceItems(labels,checked,(d,which)->{YoruApp.app().store.vpnMode(values[which]);Ui.toast(a,"VPN: "+labels[which]);d.dismiss();}).setNegativeButton("Закрыть",null).show();}
    static void apps(Activity a){List<ApplicationInfo> all=a.getPackageManager().getInstalledApplications(0);ArrayList<ApplicationInfo> launch=new ArrayList<>();for(ApplicationInfo app:all)if(a.getPackageManager().getLaunchIntentForPackage(app.packageName)!=null)launch.add(app);launch.sort((x,y)->label(a,x).compareToIgnoreCase(label(a,y)));String[] names=new String[launch.size()];boolean[] checked=new boolean[launch.size()];HashSet<String> saved=new HashSet<>();JSONArray arr=YoruApp.app().store.vpnApps();for(int i=0;i<arr.length();i++)saved.add(arr.optString(i));for(int i=0;i<launch.size();i++){ApplicationInfo info=launch.get(i);names[i]=label(a,info);checked[i]=saved.contains(info.packageName);}new AlertDialog.Builder(a).setTitle("Приложения через VPN").setMultiChoiceItems(names,checked,(d,which,on)->checked[which]=on).setPositiveButton("Сохранить",(d,w)->{JSONArray out=new JSONArray();for(int i=0;i<checked.length;i++)if(checked[i])out.put(launch.get(i).packageName);YoruApp.app().store.vpnApps(out);Ui.toast(a,"Список VPN-приложений сохранён");}).setNegativeButton("Отмена",null).show();}
    static void connect(Activity a){JSONObject p=YoruVpnProfile.selected(YoruApp.app().store.vpnProfiles(),YoruApp.app().store.vpnSelected());if(p==null){Ui.toast(a,"Сначала добавьте VPN подписку");return;}try{pending=p.toString();if(Build.VERSION.SDK_INT>=33&&a.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)a.requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},5402);Intent prepare=VpnService.prepare(a);if(prepare!=null)a.startActivityForResult(prepare,REQ_VPN);else afterPermission(a,Activity.RESULT_OK);}catch(Exception e){Ui.toast(a,"Не удалось запросить VPN-разрешение");}}
    private static void start(Activity a,String profile){Intent i=new Intent(a,YoruVpnService.class).setAction(YoruVpnService.ACTION_CONNECT).putExtra(YoruVpnService.EXTRA_PROFILE,profile).putExtra(YoruVpnService.EXTRA_MODE,YoruApp.app().store.vpnMode());ArrayList<String> apps=new ArrayList<>();JSONArray arr=YoruApp.app().store.vpnApps();for(int n=0;n<arr.length();n++){String p=arr.optString(n);if(!p.isEmpty())apps.add(p);}i.putStringArrayListExtra(YoruVpnService.EXTRA_APPS,apps);if(Build.VERSION.SDK_INT>=26)a.startForegroundService(i);else a.startService(i);Ui.toast(a,"VPN подключается…");}
    static void disconnect(Activity a){a.startService(new Intent(a,YoruVpnService.class).setAction(YoruVpnService.ACTION_DISCONNECT));Ui.toast(a,"VPN отключается");}
    static void status(Activity a){new AlertDialog.Builder(a).setTitle("VPN статус").setMessage(YoruVpnService.text()+"\n\nЛокаций: "+YoruApp.app().store.vpnProfiles().length()+"\nРежим: "+modeLabel(YoruApp.app().store.vpnMode())).setPositiveButton("Понятно",null).show();}
    private static String download(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setInstanceFollowRedirects(true);c.setConnectTimeout(12000);c.setReadTimeout(18000);c.setRequestProperty("User-Agent","YORU Android");int code=c.getResponseCode();if(code<200||code>=300)throw new IOException(String.valueOf(code));try(InputStream in=c.getInputStream()){return ApiRepository.readStream(in,8*1024*1024);}}
    static String modeLabel(String m){if("all".equals(m))return "все приложения";if("selected".equals(m))return "выбранные приложения";return "только YORU";}
    private static String label(Context c,ApplicationInfo i){try{return String.valueOf(c.getPackageManager().getApplicationLabel(i));}catch(Exception e){return i.packageName;}}
    private static boolean dead(Activity a){return a.isFinishing()||a.isDestroyed();}
}
