package app.yoru.mobile;

import android.util.JsonReader;
import android.util.JsonToken;
import java.io.*;
import java.net.*;
import java.util.*;

final class YummyParser {
    static ArrayList<Anime.Episode> episodes(String id)throws Exception{
        HttpURLConnection c=(HttpURLConnection)new URL("https://api.yani.tv/anime/"+id+"/videos").openConnection();c.setConnectTimeout(15000);c.setReadTimeout(25000);c.setRequestProperty("User-Agent","YORU-Android/2.1");c.setRequestProperty("Accept","application/json");c.setRequestProperty("Accept-Language","ru");TreeMap<Double,Anime.Episode> groups=new TreeMap<>();HashMap<Double,HashSet<String>> seen=new HashMap<>();
        try{if(c.getResponseCode()!=200)throw new IOException("Каталог временно не ответил");try(JsonReader r=new JsonReader(new InputStreamReader(c.getInputStream(),java.nio.charset.StandardCharsets.UTF_8))){r.beginObject();boolean response=false;int records=0;while(r.hasNext()){String name=r.nextName();if(!name.equals("response")){if(name.equals("error")){String error=text(r);if(!error.isEmpty()&&!error.equals("0")&&!error.equals("false"))throw new IOException("Каталог не вернул серии");}else r.skipValue();continue;}response=true;if(r.peek()!=JsonToken.BEGIN_ARRAY)throw new IOException("Не удалось получить серии");r.beginArray();while(r.hasNext()){if(Thread.currentThread().isInterrupted())throw new InterruptedIOException();if(++records>300000)throw new IOException("Список серий слишком большой");String num="",url="",voice="Озвучка",player="";int duration=0,opening=0,end=0;r.beginObject();while(r.hasNext()){String key=r.nextName();if(key.equals("number"))num=text(r);else if(key.equals("iframe_url"))url=text(r);else if(key.equals("duration"))duration=integer(r);else if(key.equals("data")&&r.peek()==JsonToken.BEGIN_OBJECT){r.beginObject();while(r.hasNext()){String k=r.nextName();if(k.equals("dubbing"))voice=text(r);else if(k.equals("player"))player=text(r);else r.skipValue();}r.endObject();}else if(key.equals("skips")&&r.peek()==JsonToken.BEGIN_OBJECT){r.beginObject();while(r.hasNext()){String skip=r.nextName();if(skip.equals("opening")&&r.peek()==JsonToken.BEGIN_OBJECT){int length=0;r.beginObject();while(r.hasNext()){String k=r.nextName();if(k.equals("time"))opening=integer(r);else if(k.equals("length"))length=integer(r);else r.skipValue();}r.endObject();end=opening+length;}else r.skipValue();}r.endObject();}else r.skipValue();}r.endObject();double ordinal;try{ordinal=Double.parseDouble(num);}catch(Exception e){continue;}String safe=ApiRepository.embed(url);if(!Double.isFinite(ordinal)||ordinal<0||ordinal>100000||safe.isEmpty())continue;Anime.Episode ep=groups.get(ordinal);if(ep==null){ep=new Anime.Episode();ep.id=id+"-"+ordinal;ep.number=ordinal;groups.put(ordinal,ep);seen.put(ordinal,new HashSet<>());}if(!seen.get(ordinal).add(voice+"|"+safe))continue;Anime.Variant v=new Anime.Variant(ApiRepository.cleanLabel(voice),ApiRepository.cleanLabel(player),safe);v.duration=duration;v.openingStart=opening;v.openingEnd=end;ep.variants.add(v);ep.duration=Math.max(ep.duration,duration);}
            r.endArray();}r.endObject();if(!response)throw new IOException("YORU Max не вернул список серий");}
        }finally{c.disconnect();}
        ArrayList<Anime.Episode> result=new ArrayList<>(groups.values());for(Anime.Episode ep:result){ep.variants.sort(Comparator.comparingInt(v->voicePriority(v.name)*100+playerPriority(v.player)));HashMap<String,Integer> versions=new HashMap<>();for(Anime.Variant v:ep.variants){String player=cleanPlayer(v.player);String key=v.name+"|"+player;int n=versions.getOrDefault(key,0)+1;versions.put(key,n);v.displayName=v.name+(player.isEmpty()?"":" · "+player)+(n>1?" · вариант "+n:"");}}return result;
    }
    private static int voicePriority(String name){String v=(name==null?"":name).toLowerCase(Locale.ROOT);return v.contains("animevost")?0:v.contains("anilibria")?1:v.contains("studio band")?2:5;}
    private static int playerPriority(String name){String v=(name==null?"":name).toLowerCase(Locale.ROOT);if(v.contains("cvh")||v.contains("cdnvideohub"))return 0;if(v.contains("kodik"))return 1;if(v.contains("aksor"))return 2;if(v.contains("vk")||v.contains("вконт"))return 3;if(v.contains("rutube"))return 4;if(v.contains("zedfilm")||v.contains("hlamer"))return 5;if(v.contains("alloha"))return 6;if(v.contains("sibnet"))return 7;return 20;}
    private static String cleanPlayer(String name){String v=name==null?"":name.trim();return v.equalsIgnoreCase("null")?"":v;}
    private static String text(JsonReader r)throws IOException{if(r.peek()==JsonToken.NULL){r.nextNull();return "";}if(r.peek()==JsonToken.BOOLEAN)return String.valueOf(r.nextBoolean());return r.nextString();}
    private static int integer(JsonReader r)throws IOException{try{return (int)Math.max(0,Double.parseDouble(text(r)));}catch(NumberFormatException e){return 0;}}
}
