package app.yoru.vk;

import android.app.*;
import android.content.*;
import android.net.Uri;
import android.net.http.SslError;
import android.os.*;
import android.view.*;
import android.webkit.*;
import android.widget.*;

public final class WebActivity extends Activity {
    private LinearLayout root;
    private FrameLayout area;
    private WebView web;
    private TextView host,status;
    private ProgressBar progress;
    private String home,query="",lastPublic="";
    private boolean desktop,failed,stopped;
    private View full;
    private WebChromeClient.CustomViewCallback fullCallback;
    @Override public void onCreate(Bundle saved){super.onCreate(saved);desktop=getIntent().getBooleanExtra("desktop",false);home=getIntent().getStringExtra("url");String q=getIntent().getStringExtra("query");query=q==null?"":q;if(!WebRoutes.allowedPage(home)){finish();return;}lastPublic=home;root=Ui.column(this);Ui.base(this,root);LinearLayout top=Ui.row(this);top.setPadding(Ui.dp(this,8),Ui.dp(this,6),Ui.dp(this,8),Ui.dp(this,6));TextView back=Ui.button(this,"‹",false,this::onBackPressed);back.setContentDescription("Назад по странице");top.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));host=Ui.text(this,"",12,Ui.TEXT,true);host.setMaxLines(2);host.setPadding(Ui.dp(this,8),0,Ui.dp(this,6),0);top.addView(host,new LinearLayout.LayoutParams(0,-2,1));top.addView(Ui.button(this,"Браузер",false,this::external));top.addView(Ui.button(this,"⋮",false,this::menu),new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));root.addView(top);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);root.addView(progress,new LinearLayout.LayoutParams(-1,Ui.dp(this,3)));status=Ui.text(this,"Страница сайта. Вход и доступ к ролику определяет ВК.",11,Ui.MUTED,false);status.setPadding(Ui.dp(this,12),Ui.dp(this,5),Ui.dp(this,12),Ui.dp(this,5));root.addView(status);area=new FrameLayout(this);root.addView(area,new LinearLayout.LayoutParams(-1,0,1));}
    @Override protected void onStart(){super.onStart();stopped=false;if(web==null)createWeb();}
    @SuppressWarnings("deprecation") private void createWeb(){try{web=new WebView(this);}catch(Exception e){status.setText("Android System WebView недоступен. Нажмите «Браузер».");return;}WebView.setWebContentsDebuggingEnabled(false);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setAllowFileAccessFromFileURLs(false);s.setAllowUniversalAccessFromFileURLs(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setSafeBrowsingEnabled(true);s.setSaveFormData(false);s.setSupportMultipleWindows(false);s.setJavaScriptCanOpenWindowsAutomatically(false);s.setMediaPlaybackRequiresUserGesture(true);s.setUseWideViewPort(true);s.setLoadWithOverviewMode(true);s.setBuiltInZoomControls(true);s.setDisplayZoomControls(false);s.setTextZoom(100);if(desktop)s.setUserAgentString("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36");CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,false);web.setSaveEnabled(false);web.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);web.setWebViewClient(new WebViewClient(){
        @Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){if(!request.isForMainFrame())return false;String url=request.getUrl().toString();if(WebRoutes.allowedPage(url))return false;status.setText("Переход на другой сайт или запуск приложения заблокирован. Можно открыть текущую страницу кнопкой «Браузер».");return true;}
        @Override public void onPageStarted(WebView view,String url,android.graphics.Bitmap icon){failed=false;host.setText(WebRoutes.origin(url));progress.setVisibility(View.VISIBLE);status.setText("Загрузка страницы сайта…");}
        @Override public void onPageFinished(WebView view,String url){progress.setVisibility(View.GONE);host.setText(WebRoutes.origin(url));if(!failed)status.setText("Сайт открыт. CAPTCHA или вход выполняются только самим пользователем. Если не работает — «Браузер» или другой способ.");if(isPublic(url))lastPublic=url;}
        @Override public void onReceivedError(WebView view,WebResourceRequest request,WebResourceError error){if(request.isForMainFrame()){failed=true;progress.setVisibility(View.GONE);status.setText("Страница не загрузилась. Проверьте сеть, обновите Android System WebView или выберите другой способ / браузер.");}}
        @Override public void onReceivedHttpError(WebView view,WebResourceRequest request,WebResourceResponse error){if(request.isForMainFrame()){failed=true;status.setText("Сайт ответил HTTP "+error.getStatusCode()+". Другой способ доступен после возврата назад; можно открыть в браузере.");}}
        @Override public void onReceivedSslError(WebView view,SslErrorHandler handler,SslError error){handler.cancel();failed=true;status.setText("Ошибка сертификата сайта. Соединение остановлено, обход проверки TLS запрещён.");}
        @Override public boolean onRenderProcessGone(WebView view,RenderProcessGoneDetail detail){area.removeView(view);view.destroy();if(web==view)web=null;status.setText("WebView завершил работу. Выберите «Обновить» в меню или внешний браузер.");return true;}
    });web.setWebChromeClient(new WebChromeClient(){
        @Override public void onProgressChanged(WebView view,int value){progress.setProgress(value);}
        @Override public void onPermissionRequest(PermissionRequest request){request.deny();}
        @Override public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback callback){callback.invoke(origin,false,false);}
        @Override public void onShowCustomView(View view,CustomViewCallback callback){if(full!=null){callback.onCustomViewHidden();return;}full=view;fullCallback=callback;area.addView(view,new FrameLayout.LayoutParams(-1,-1));for(int i=0;i<root.getChildCount();i++)if(root.getChildAt(i)!=area)root.getChildAt(i).setVisibility(View.GONE);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}
        @Override public void onHideCustomView(){hideFull();}
    });area.addView(web,new FrameLayout.LayoutParams(-1,-1));host.setText(WebRoutes.origin(lastPublic));web.loadUrl(lastPublic);}
    private boolean isPublic(String url){if(!WebRoutes.allowedPage(url))return false;try{Uri u=Uri.parse(url);String h=u.getHost(),p=u.getPath(),lower=url.toLowerCase(java.util.Locale.ROOT);if(lower.contains("access_token")||lower.contains("oauth")||lower.contains("login")||lower.contains("authorize")||lower.contains("code="))return false;return !(h!=null&&(h.startsWith("id.")||h.startsWith("connect.")))&&(p==null||!p.contains("auth"));}catch(Exception e){return false;}}
    private void hideFull(){if(full==null)return;area.removeView(full);full=null;if(fullCallback!=null){WebChromeClient.CustomViewCallback c=fullCallback;fullCallback=null;c.onCustomViewHidden();}for(int i=0;i<root.getChildCount();i++)if(root.getChildAt(i)!=area)root.getChildAt(i).setVisibility(View.VISIBLE);progress.setVisibility(View.GONE);getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);}
    private void external(){String url=isPublic(web==null?"":web.getUrl())?web.getUrl():lastPublic;try{Intent open=new Intent(Intent.ACTION_VIEW,Uri.parse(WebRoutes.modeUrl(url,false)));open.addCategory(Intent.CATEGORY_BROWSABLE);startActivity(Intent.createChooser(open,"Открыть в браузере или приложении ВК"));}catch(Exception e){Ui.message(this,"Браузер","Не найдено приложение для открытия HTTPS-ссылки.");}}
    private void menu(){String[] choices={"Обновить страницу","К началу поиска",desktop?"Мобильная версия":"Версия для компьютера","Другой способ поиска","Скопировать запрос","Вставить ссылку на видео","Удалить веб-сессию этого приложения"};new AlertDialog.Builder(this).setTitle("VK Web · без ручного токена").setItems(choices,(d,which)->{if(which==0){if(web==null)createWeb();else web.reload();}else if(which==1){lastPublic=home;if(web==null)createWeb();else web.loadUrl(home);}else if(which==2){desktop=!desktop;lastPublic=WebRoutes.modeUrl(lastPublic,desktop);destroyWeb();createWeb();}else if(which==3)finish();else if(which==4){((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Поиск аниме",query));Toast.makeText(this,"Запрос скопирован",Toast.LENGTH_SHORT).show();}else if(which==5)pasteLink();else confirmLogout();}).show();}
    private void pasteLink(){EditText input=Ui.input(this,"https://vkvideo.ru/video…",false);input.setSaveEnabled(false);input.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);input.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(8192)});AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Ссылка на ролик, не токен").setView(input).setPositiveButton("Открыть",null).setNegativeButton("Отмена",null).create();dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{String url=WebRoutes.videoLink(input.getText().toString());input.setText("");lastPublic=url;dialog.dismiss();if(web==null)createWeb();else web.loadUrl(url);}catch(Exception e){input.setError(e.getMessage());}}));dialog.show();}
    private void confirmLogout(){new AlertDialog.Builder(this).setTitle("Удалить веб-сессию?").setMessage("Удалятся cookies и данные сайтов только внутри YORU VK Web. Основная YORU, отдельный браузер и приложение ВК не затрагиваются. Для полного отзыва сессий используйте настройки безопасности ВК.").setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->{destroyWeb();CookieManager.getInstance().removeAllCookies(ok->{CookieManager.getInstance().flush();WebStorage.getInstance().deleteAllData();lastPublic=home;if(!isFinishing()&&!stopped)createWeb();});}).show();}
    private void destroyWeb(){hideFull();if(web!=null){WebView old=web;web=null;old.stopLoading();old.onPause();area.removeView(old);old.destroy();}}
    @Override public void onBackPressed(){if(full!=null){hideFull();return;}if(web!=null&&web.canGoBack()){web.goBack();return;}super.onBackPressed();}
    @Override protected void onResume(){super.onResume();if(web!=null)web.onResume();}
    @Override protected void onPause(){if(web!=null)web.onPause();CookieManager.getInstance().flush();super.onPause();}
    @Override protected void onStop(){stopped=true;destroyWeb();super.onStop();}
    @Override protected void onDestroy(){destroyWeb();super.onDestroy();}
}
