package app.yoru.forge;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.provider.DocumentsContract;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.zip.*;

public final class ForgeActivity extends Activity {
    private static final int REQ_TREE=7101,REQ_EXPORT=7102;
    private static final int BG=0xff120d18,TEXT=0xfff3eafd,MUTED=0xffa99ab8,CARD=0xff20172a,SURFACE=0xff2a2035,PURPLE=0xffb889ff;
    private static final String WORKFLOW_YORU="https://github.com/KamiSakyy/Animmmemmemwm/actions/workflows/build-apk.yml";
    private static final String WORKFLOW_FORGE="https://github.com/KamiSakyy/Animmmemmemwm/actions/workflows/build-forge-apk.yml";
    private static final String APK_DIR="https://github.com/KamiSakyy/Animmmemmemwm/tree/arena/01a07147-animmmemmemwm/apk-output";
    private SharedPreferences prefs;private Uri treeUri,currentUri;private LinearLayout root,body,fileBox;private TextView status,fileTitle,saveButton;private EditText editor;private final ArrayList<Row> rows=new ArrayList<>();private boolean dirty,loading;
    private static final class Row {String id,name,path,mime;long size;Row(String i,String n,String p,String m,long s){id=i;name=n;path=p;mime=m;size=s;}}
    @Override public void onCreate(Bundle state){super.onCreate(state);prefs=getSharedPreferences("forge",MODE_PRIVATE);String saved=prefs.getString("tree","");if(!saved.isEmpty())treeUri=Uri.parse(saved);build();render();}
    private void build(){getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);root=col();root.setBackgroundColor(BG);setContentView(root);LinearLayout top=row();top.setPadding(dp(18),dp(12),dp(18),dp(10));TextView logo=text("YORU Forge",26,PURPLE,true);top.addView(logo,new LinearLayout.LayoutParams(0,-2,1));TextView help=smallButton("Как работает",this::showHelp);top.addView(help);root.addView(top);ScrollView scroll=new ScrollView(this);body=col();body.setPadding(dp(18),dp(8),dp(18),dp(26));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));}
    private void render(){body.removeAllViews();TextView lead=text("Редактор исходников и APK-сборка YORU с телефона",14,TEXT,true);body.addView(lead);space(body,8);body.addView(text("Версия 0.1.0: безопасный старт без токенов в коде. Правки можно сохранить в выбранной папке, экспортировать zip и собрать release APK через GitHub Actions.",12,MUTED,false));space(body,16);projectCard();space(body,14);actionsCard();space(body,14);editorCard();space(body,14);filesCard();}
    private void projectCard(){LinearLayout card=card();String name=treeUri==null?"папка не выбрана":displayName(treeUri);card.addView(text("Проект",18,TEXT,true));space(card,8);status=text(treeUri==null?"Выберите папку с исходниками YORU или распакованный handoff zip.":"Открыто: "+name,12,treeUri==null?MUTED:TEXT,false);card.addView(status);space(card,12);LinearLayout r=row();r.addView(button("Выбрать папку",true,this::pickTree),new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.leftMargin=dp(8);r.addView(button("Обновить",false,this::reloadFiles),p);card.addView(r);body.addView(card);}
    private void actionsCard(){LinearLayout card=card();card.addView(text("Сборка APK",18,TEXT,true));space(card,8);card.addView(text("GitHub Actions для публичного репозитория обычно хватает бесплатно. Forge открывает нужный workflow и папку с готовыми APK. Позже добавлю вход через GitHub внутри приложения, если нужен запуск в один тап.",12,MUTED,false));space(card,12);LinearLayout r1=row();r1.addView(button("Собрать YORU",true,()->openUrl(WORKFLOW_YORU)),new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.leftMargin=dp(8);r1.addView(button("Собрать Forge",false,()->openUrl(WORKFLOW_FORGE)),p);card.addView(r1);space(card,8);LinearLayout r2=row();r2.addView(button("Готовые APK",false,()->openUrl(APK_DIR)),new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams p2=new LinearLayout.LayoutParams(0,-2,1);p2.leftMargin=dp(8);r2.addView(button("Экспорт zip",false,this::exportZip),p2);card.addView(r2);body.addView(card);}
    private void editorCard(){LinearLayout card=card();fileTitle=text("Файл не открыт",16,TEXT,true);card.addView(fileTitle);space(card,10);editor=new EditText(this);editor.setTextColor(TEXT);editor.setHintTextColor(MUTED);editor.setTextSize(13);editor.setTypeface(Typeface.MONOSPACE);editor.setGravity(Gravity.TOP|Gravity.START);editor.setMinLines(12);editor.setMaxLines(24);editor.setSingleLine(false);editor.setHorizontallyScrolling(true);editor.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);editor.setBackground(stroke(SURFACE,14));editor.setPadding(dp(12),dp(12),dp(12),dp(12));editor.setHint("Выберите .java, .gradle, .xml, .md, .json или другой текстовый файл ниже");editor.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){if(!loading&&currentUri!=null){dirty=true;updateSave();}}public void afterTextChanged(Editable e){}});card.addView(editor,new LinearLayout.LayoutParams(-1,dp(300)));space(card,10);LinearLayout r=row();saveButton=button("Сохранить",true,this::saveFile);saveButton.setEnabled(false);saveButton.setAlpha(.55f);r.addView(saveButton,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.leftMargin=dp(8);r.addView(button("Скрыть клавиатуру",false,this::hideKeyboard),p);card.addView(r);body.addView(card);}
    private void filesCard(){LinearLayout card=card();LinearLayout head=row();head.addView(text("Файлы",18,TEXT,true),new LinearLayout.LayoutParams(0,-2,1));TextView count=text(String.valueOf(rows.size()),12,PURPLE,true);head.addView(count);card.addView(head);space(card,8);fileBox=col();card.addView(fileBox);body.addView(card);renderFiles();if(treeUri!=null&&rows.isEmpty())reloadFiles();}
    private void renderFiles(){if(fileBox==null)return;fileBox.removeAllViews();if(treeUri==null){fileBox.addView(text("Сначала выберите папку проекта.",12,MUTED,false));return;}if(rows.isEmpty()){fileBox.addView(text("Нажмите «Обновить», чтобы прочитать дерево проекта.",12,MUTED,false));return;}int limit=Math.min(120,rows.size());for(int i=0;i<limit;i++){Row rr=rows.get(i);TextView item=text(rr.path,12,TEXT,false);item.setSingleLine(true);item.setEllipsize(TextUtils.TruncateAt.START);item.setPadding(dp(12),dp(11),dp(12),dp(11));item.setBackground(stroke(SURFACE,12));item.setOnClickListener(v->openFile(rr));fileBox.addView(item,new LinearLayout.LayoutParams(-1,-2));space(fileBox,7);}if(rows.size()>limit){fileBox.addView(text("Показано "+limit+" из "+rows.size()+" текстовых файлов. Уточните папку проекта или используйте поиск в следующей версии.",11,MUTED,false));}}
    private void pickTree(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);startActivityForResult(i,REQ_TREE);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();if(request==REQ_TREE){int flags=data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);try{getContentResolver().takePersistableUriPermission(uri,flags);}catch(Exception ignored){}treeUri=uri;prefs.edit().putString("tree",uri.toString()).apply();rows.clear();currentUri=null;dirty=false;render();reloadFiles();}else if(request==REQ_EXPORT){writeZip(uri);}}
    private void reloadFiles(){if(treeUri==null){toast("Сначала выберите папку");return;}if(dirty){confirm("Есть несохранённый файл","Сначала сохраните или продолжите без сохранения.","Продолжить",this::loadRows,"Отмена",null);return;}loadRows();}
    private void loadRows(){if(treeUri==null||loading)return;loading=true;if(status!=null)status.setText("Читаю дерево проекта…");new Thread(()->{ArrayList<Row> found=new ArrayList<>();try{walk(DocumentsContract.getTreeDocumentId(treeUri),"",found,0);}catch(Exception ignored){}runOnUiThread(()->{loading=false;rows.clear();rows.addAll(found);if(status!=null)status.setText("Найдено текстовых файлов: "+rows.size());renderFiles();});}).start();}
    private void walk(String id,String path,ArrayList<Row> out,int depth){if(out.size()>700||depth>18)return;Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(treeUri,id);String[] cols={DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME,DocumentsContract.Document.COLUMN_MIME_TYPE,DocumentsContract.Document.COLUMN_SIZE};try(Cursor c=getContentResolver().query(children,cols,null,null,null)){if(c==null)return;ArrayList<Row> dirs=new ArrayList<>(),files=new ArrayList<>();while(c.moveToNext()){String child=c.getString(0),name=c.getString(1),mime=c.getString(2);long size=c.isNull(3)?0:c.getLong(3);if(name==null)name="";String next=path.isEmpty()?name:path+"/"+name;if(skipName(name,next))continue;if(DocumentsContract.Document.MIME_TYPE_DIR.equals(mime))dirs.add(new Row(child,name,next,mime,size));else if(textFile(name,size))files.add(new Row(child,name,next,mime,size));}files.sort(Comparator.comparing(a->a.path.toLowerCase(Locale.ROOT)));dirs.sort(Comparator.comparing(a->a.path.toLowerCase(Locale.ROOT)));out.addAll(files);for(Row d:dirs)walk(d.id,d.path,out,depth+1);}}
    private void openFile(Row r){if(dirty){confirm("Есть несохранённый файл","Сохранить текущие изменения перед открытием другого файла?","Сохранить",()->{saveFile();openFileNow(r);},"Не сохранять",()->{dirty=false;openFileNow(r);});return;}openFileNow(r);}
    private void openFileNow(Row r){try{Uri uri=DocumentsContract.buildDocumentUriUsingTree(treeUri,r.id);String text=read(uri,900000);currentUri=uri;loading=true;editor.setText(text);loading=false;dirty=false;fileTitle.setText(r.path);updateSave();editor.requestFocus();}catch(Exception e){toast("Не удалось открыть файл");}}
    private String read(Uri uri,int max)throws IOException{try(InputStream in=getContentResolver().openInputStream(uri);ByteArrayOutputStream out=new ByteArrayOutputStream()){if(in==null)throw new IOException();byte[] b=new byte[8192];int n,total=0;while((n=in.read(b))!=-1){total+=n;if(total>max)throw new IOException("big");out.write(b,0,n);}return out.toString("UTF-8");}}
    private void saveFile(){if(currentUri==null){toast("Файл не открыт");return;}try(OutputStream out=getContentResolver().openOutputStream(currentUri,"wt")){if(out==null)throw new IOException();out.write(editor.getText().toString().getBytes(StandardCharsets.UTF_8));dirty=false;updateSave();toast("Сохранено");}catch(Exception e){toast("Не удалось сохранить");}}
    private void updateSave(){if(saveButton==null)return;saveButton.setEnabled(currentUri!=null&&dirty);saveButton.setAlpha(currentUri!=null&&dirty?1f:.55f);}
    private void exportZip(){if(treeUri==null){toast("Сначала выберите папку проекта");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/zip");i.putExtra(Intent.EXTRA_TITLE,"YORU-source-from-forge-"+new SimpleDateFormat("yyyyMMdd-HHmm",Locale.ROOT).format(new Date())+".zip");startActivityForResult(i,REQ_EXPORT);}
    private void writeZip(Uri target){if(status!=null)status.setText("Создаю zip…");new Thread(()->{boolean ok=false;int[] count={0};try(OutputStream raw=getContentResolver().openOutputStream(target,"wt");ZipOutputStream zip=new ZipOutputStream(new BufferedOutputStream(raw))){zip.setLevel(Deflater.BEST_SPEED);zip.putNextEntry(new ZipEntry("YORU_FORGE_BUILD_README.ru.md"));zip.write(forgeGuide().getBytes(StandardCharsets.UTF_8));zip.closeEntry();zipWalk(DocumentsContract.getTreeDocumentId(treeUri),"",zip,count,0);ok=true;}catch(Exception ignored){}boolean done=ok;runOnUiThread(()->{if(status!=null)status.setText(done?"Zip готов. Файлов: "+count[0]:"Zip не создан");toast(done?"Zip экспортирован":"Не удалось создать zip");});}).start();}
    private void zipWalk(String id,String path,ZipOutputStream zip,int[] count,int depth)throws IOException{if(depth>24||count[0]>5000)return;Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(treeUri,id);String[] cols={DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME,DocumentsContract.Document.COLUMN_MIME_TYPE,DocumentsContract.Document.COLUMN_SIZE};try(Cursor c=getContentResolver().query(children,cols,null,null,null)){if(c==null)return;while(c.moveToNext()){String child=c.getString(0),name=c.getString(1),mime=c.getString(2);long size=c.isNull(3)?0:c.getLong(3);if(name==null)continue;String next=path.isEmpty()?name:path+"/"+name;if(skipExport(name,next,size))continue;if(DocumentsContract.Document.MIME_TYPE_DIR.equals(mime)){zipWalk(child,next,zip,count,depth+1);}else{Uri file=DocumentsContract.buildDocumentUriUsingTree(treeUri,child);try(InputStream in=getContentResolver().openInputStream(file)){if(in==null)continue;zip.putNextEntry(new ZipEntry(next));byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)zip.write(b,0,n);zip.closeEntry();count[0]++;}}}}}
    private boolean skipName(String name,String path){String n=name.toLowerCase(Locale.ROOT);String p=path.toLowerCase(Locale.ROOT);return n.equals(".git")||n.equals(".gradle")||n.equals(".idea")||n.equals("build")||n.equals("node_modules")||n.equals("apk-output")||n.equals("dist")||n.equals("out")||p.contains("/build/")||p.contains("/.git/")||p.contains("/apk-output/");}
    private boolean skipExport(String name,String path,long size){String n=name.toLowerCase(Locale.ROOT);String p=path.toLowerCase(Locale.ROOT);if(skipName(name,path)||p.contains("owner-signing")||p.endsWith(".jks")||p.endsWith(".keystore")||p.endsWith(".apk")||p.endsWith(".aab")||p.endsWith(".zip"))return true;return size>25L*1024L*1024L;}
    private boolean textFile(String name,long size){if(size>1200000)return false;String n=name.toLowerCase(Locale.ROOT);return n.endsWith(".java")||n.endsWith(".kt")||n.endsWith(".gradle")||n.equals("settings.gradle")||n.endsWith(".xml")||n.endsWith(".json")||n.endsWith(".md")||n.endsWith(".txt")||n.endsWith(".properties")||n.endsWith(".pro")||n.endsWith(".yml")||n.endsWith(".yaml")||n.endsWith(".html")||n.endsWith(".css")||n.endsWith(".js");}
    private String displayName(Uri uri){if(uri==null)return "";try{String id=DocumentsContract.getTreeDocumentId(uri);int slash=id.lastIndexOf(':');String raw=slash>=0?id.substring(slash+1):id;return raw.isEmpty()?"корень проекта":raw;}catch(Exception e){return uri.toString();}}
    private String forgeGuide(){return "# YORU Forge\n\nЭкспорт создан с телефона.\n\n1. Распакуйте zip.\n2. Проверьте изменения.\n3. Соберите release APK через GitHub Actions или локально.\n\nКоманда локальной сборки YORU:\n\n```bash\ncd yoru-android\n./gradlew --no-daemon :app:assembleRelease\n```\n\nКоманда локальной сборки Forge:\n\n```bash\ncd yoru-android\n./gradlew --no-daemon :forge:assembleRelease\n```\n\nНе храните приватные ключи и токены внутри архива.\n";}
    private void showHelp(){LinearLayout c=col();c.setPadding(dp(2),0,dp(2),0);c.addView(text("YORU Forge 0.1.0",19,TEXT,true));space(c,10);c.addView(text("1. Распакуйте handoff zip или исходники YORU в папку телефона.\n2. Нажмите «Выбрать папку».\n3. Откройте файл, исправьте код и нажмите «Сохранить».\n4. Экспортируйте zip или откройте GitHub Actions для release-сборки.\n\nВ этой версии токены не запрашиваются и не сохраняются. Поэтому Forge не пушит изменения сам. Это сделаю отдельным безопасным режимом позже.",13,MUTED,false));custom("Помощь",c,"Понятно",null,"GitHub",()->openUrl(WORKFLOW_YORU));}
    private void openUrl(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){toast("Не удалось открыть ссылку");}}
    private void hideKeyboard(){try{((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(editor.getWindowToken(),0);}catch(Exception ignored){}}
    private LinearLayout col(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}
    private LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.HORIZONTAL);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    private TextView text(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);t.setLineSpacing(dp(3),1);t.setIncludeFontPadding(false);return t;}
    private TextView button(String s,boolean primary,Runnable run){TextView t=text(s,13,primary?0xff21152f:TEXT,true);t.setGravity(Gravity.CENTER);t.setMinHeight(dp(44));t.setPadding(dp(12),dp(11),dp(12),dp(11));t.setBackground(primary?fill(PURPLE,14):stroke(SURFACE,14));t.setOnClickListener(v->{if(run!=null)run.run();});return t;}
    private TextView smallButton(String s,Runnable run){TextView t=button(s,false,run);t.setTextSize(11);t.setMinHeight(dp(36));return t;}
    private LinearLayout card(){LinearLayout c=col();c.setPadding(dp(14),dp(14),dp(14),dp(14));c.setBackground(stroke(CARD,18));return c;}
    private GradientDrawable fill(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private GradientDrawable stroke(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));g.setStroke(dp(1),0x26ffffff);return g;}
    private void space(LinearLayout v,int h){View x=new View(this);v.addView(x,new LinearLayout.LayoutParams(1,dp(h)));}
    private int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private void confirm(String title,String message,String positive,Runnable yes,String negative,Runnable no){LinearLayout c=col();c.addView(text(message,13,MUTED,false));custom(title,c,positive,yes,negative,no);}
    private Dialog custom(String title,View content,String positive,Runnable yes,String negative,Runnable no){Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout box=col();box.setPadding(dp(18),dp(18),dp(18),dp(16));box.setBackground(stroke(CARD,22));box.addView(text(title,20,TEXT,true));space(box,14);box.addView(content);space(box,16);LinearLayout actions=row();actions.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);if(negative!=null){actions.addView(button(negative,false,()->{d.dismiss();if(no!=null)no.run();}),new LinearLayout.LayoutParams(0,-2,1));}if(positive!=null){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.leftMargin=dp(8);actions.addView(button(positive,true,()->{d.dismiss();if(yes!=null)yes.run();}),p);}box.addView(actions);d.setContentView(box);d.setOnShowListener(x->{Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);WindowManager.LayoutParams lp=w.getAttributes();lp.dimAmount=.64f;w.setAttributes(lp);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);w.setLayout(Math.min(getResources().getDisplayMetrics().widthPixels-dp(30),dp(560)),WindowManager.LayoutParams.WRAP_CONTENT);}});d.show();return d;}
}
